/*
	IrCOMM 0x20 Indication (DTE)
*/

#define	IRCOMM_DLT_DTR	0x01
#define	IRCOMM_DLT_RTS	0x02
#define	IRCOMM_DTR		0x04
#define	IRCOMM_RTS		0x08

/*
	IrCOMM 0x21 Indication (DCE)
*/

#define	IRCOMM_DLT_CTS	0x01
#define	IRCOMM_DLT_DSR	0x02
#define	IRCOMM_DLT_RI	0x04
#define	IRCOMM_DLT_CD	0x08
#define	IRCOMM_CTS		0x10
#define	IRCOMM_DSR		0x20
#define	IRCOMM_RI		0x40
#define	IRCOMM_CD		0x80

#define	IRCOMM_DEF_XON	0x11
#define	IRCOMM_DEF_XOFF	0x13
#define	IRCOMM_DEF_ENQ	0x05
#define	IRCOMM_DEF_ACK	0x06

