/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_PushPackage_H
#define XX_PushPackage_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

extern void yInit_PushPackage XPP((void));

/*****
* SIGNAL ChangeStatus
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(EnvironmentSignals),509(25,40),4)
******/
#define z_PUSHPackage_0_ChangeStatus 139
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_PUSHPackage_0_ChangeStatus;

/*****
* SIGNAL LoadSI
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(EnvironmentSignals),509(25,40),6)
******/
#define z_PUSHPackage_1_LoadSI 140
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_PUSHPackage_1_LoadSI;

/*****
* SIGNAL LoadSL
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(EnvironmentSignals),509(25,40),8)
******/
#define z_PUSHPackage_2_LoadSL 141
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_PUSHPackage_2_LoadSL;

/*****
* SIGNAL GetSIinfo
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(EnvironmentSignals),509(25,40),10)
******/
#define z_PUSHPackage_3_GetSIinfo 142
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_PUSHPackage_3_GetSIinfo;

/*****
* SIGNAL GetSLinfo
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(EnvironmentSignals),509(25,40),12)
******/
#define z_PUSHPackage_4_GetSLinfo 143
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_PUSHPackage_4_GetSLinfo;

/*****
* SIGNAL DeleteSI
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(EnvironmentSignals),509(25,40),14)
******/
#define z_PUSHPackage_5_DeleteSI 144
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_PUSHPackage_5_DeleteSI;

/*****
* SIGNAL DeleteSL
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(EnvironmentSignals),509(25,40),16)
******/
#define z_PUSHPackage_6_DeleteSL 145
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_PUSHPackage_6_DeleteSL;

/*****
* SIGNAL PushReqConnectionDone
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(EnvironmentSignals),509(25,40),18)
******/
#define z_PUSHPackage_7_PushReqConnectionDone 146
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Boolean  Param3;
} yPDef_z_PUSHPackage_7_PushReqConnectionDone;

/*****
* SIGNAL StartPush
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(InitSignals),470(30,45),8)
******/
#define z_PUSHPackage_8_StartPush 147
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z_PUSHPackage_8_StartPush;

/*****
* SIGNAL TerminatePush
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(InitSignals),470(30,45),10)
******/
#define z_PUSHPackage_9_TerminatePush 148

/*****
* SIGNAL StartPushDone
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(InitSignals),470(30,45),19)
******/
#define z_PUSHPackage_A_StartPushDone 149

/*****
* SIGNAL TerminatePushDone
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(InitSignals),470(30,45),20)
******/
#define z_PUSHPackage_B_TerminatePushDone 150

/*****
* SIGNAL WSPNewSession
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(WSPIFSignals),512(25,45),10)
******/
#define z_PUSHPackage_C_WSPNewSession 151
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_PUSHPackage_C_WSPNewSession;

/*****
* SIGNAL WSPTerminateSession
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(WSPIFSignals),512(25,45),12)
******/
#define z_PUSHPackage_D_WSPTerminateSession 152
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_PUSHPackage_D_WSPTerminateSession;

/*****
* SIGNAL PushIndicationResp
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(WSPIFSignals),512(25,45),14)
******/
#define z_PUSHPackage_E_PushIndicationResp 153
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_Integer  Param4;
} yPDef_z_PUSHPackage_E_PushIndicationResp;

/*****
* SIGNAL PushIndication
* <<PACKAGE PushPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\pushpackage.sun(WSPIFSignals),512(25,45),24)
******/
#define z_PUSHPackage_F_PushIndication 154
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_Boolean  Param4;
    z_ctypes_4_VoidStar  Param5;
    SDL_Integer  Param6;
    z_ctypes_4_VoidStar  Param7;
    SDL_Integer  Param8;
} yPDef_z_PUSHPackage_F_PushIndication;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
