/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_StackMgr_H
#define XX_StackMgr_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SIGNAL StartWAPStack
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),2)
******/
#define z_StackMgr_0_StartWAPStack 155

/*****
* SIGNAL StartResult
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),3)
******/
#define z_StackMgr_1_StartResult 156
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_StackMgr_1_StartResult;

/*****
* SIGNAL StartWAE
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),4)
******/
#define z_StackMgr_2_StartWAE 157

/*****
* SIGNAL StartWSP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),5)
******/
#define z_StackMgr_3_StartWSP 158

/*****
* SIGNAL StartWTP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),6)
******/
#define z_StackMgr_4_StartWTP 159

/*****
* SIGNAL StartWTLS
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),7)
******/
#define z_StackMgr_5_StartWTLS 160

/*****
* SIGNAL StartWDP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),8)
******/
#define z_StackMgr_6_StartWDP 161

/*****
* SIGNAL StartUDCP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),9)
******/
#define z_StackMgr_7_StartUDCP 162

/*****
* SIGNAL Ready
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),10)
******/
#define z_StackMgr_8_Ready 163
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_StackMgr_8_Ready;

/*****
* SIGNAL TerminateWAPStack
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),11)
******/
#define z_StackMgr_9_TerminateWAPStack 164

/*****
* SIGNAL TerminateWAE
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),12)
******/
#define z_StackMgr_A_TerminateWAE 165

/*****
* SIGNAL TerminateWSP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),13)
******/
#define z_StackMgr_B_TerminateWSP 166

/*****
* SIGNAL TerminateWTP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),14)
******/
#define z_StackMgr_C_TerminateWTP 167

/*****
* SIGNAL TerminateWTLS
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),15)
******/
#define z_StackMgr_D_TerminateWTLS 168

/*****
* SIGNAL TerminateWDP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),16)
******/
#define z_StackMgr_E_TerminateWDP 169

/*****
* SIGNAL TerminateUDCP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),17)
******/
#define z_StackMgr_F_TerminateUDCP 170

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
