/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif


/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* NEWTYPE DisplayInfoType  (TYPE section)
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2288(20,170),1)
******/
typedef struct z00012H_DisplayInfoType_s {
    z_ctypes_4_VoidStar  CardURL;
    z_ctypes_4_VoidStar  Card;
    SDL_Integer  Refresh;
    SDL_Octet  Options;
    SDL_Integer  ImagesEnabled;
    SDL_Integer  CompleteImagesDynamically;
    z_ctypes_4_VoidStar  Network;
    SDL_Integer  NewContext;
} z00012H_DisplayInfoType;

/*****
* NEWTYPE DisplayInfoType  (HEADING section)
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2288(20,170),1)
******/

#define yAssF_z00012H_DisplayInfoType(V,E,A)  V = E
extern void yDef_z00012H_DisplayInfoType XPP(( z00012H_DisplayInfoType * ));
extern SDL_Boolean yEq_z00012H_DisplayInfoType XPP(( z00012H_DisplayInfoType,
  z00012H_DisplayInfoType ));
#define yEqF_z00012H_DisplayInfoType(Expr1,Expr2)  yEq_z00012H_DisplayInfoType(Expr1,Expr2)
#define yNEqF_z00012H_DisplayInfoType(Expr1,Expr2)  ( ! yEq_z00012H_DisplayInfoType(Expr1,Expr2) )
extern z00012H_DisplayInfoType yMake_z00012H_DisplayInfoType
  XPP(( z_ctypes_4_VoidStar, z_ctypes_4_VoidStar, SDL_Integer, SDL_Octet,
  SDL_Integer, SDL_Integer, z_ctypes_4_VoidStar, SDL_Integer ));
#ifndef ANY_z00012H_DisplayInfoType
#define ANY_z00012H_DisplayInfoType  yMake_z00012H_DisplayInfoType(ANY_z_ctypes_4_VoidStar, \
  ANY_z_ctypes_4_VoidStar, ANY_SDL_Integer, ANY_SDL_Octet, ANY_SDL_Integer, \
  ANY_SDL_Integer, ANY_z_ctypes_4_VoidStar, ANY_SDL_Integer)
#endif
#define z00012H3_copy(P)  P

/*****
* PROCESS UA_ME
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z00010F_UA_ME)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),2) */
    z_ctypes_4_VoidStar  z00010F0H_CurrentUA;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),3) */
    z_ctypes_4_VoidStar  z00010F0I_ActiveAgentsList;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),4) */
    SDL_Integer  z00010F0J_NbrOfActiveAgents;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),5) */
    SDL_Integer  z00010F0K_TempIdx;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),6) */
    SDL_Integer  z00010F0L_TempInt;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),7) */
    z_ctypes_4_VoidStar  z00010F0M_WAEManagementObject;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),8) */
    SDL_PId  z00010F0N_DestinationUA;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),9) */
    SDL_PId  z00010F0O_ThePid;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),10) */
    SDL_Integer  z00010F0P_ViewID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),11) */
    SDL_Integer  z00010F0Q_InputID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),12) */
    z_ctypes_4_VoidStar  z00010F0R_RequestURL;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),13) */
    SDL_Boolean  z00010F0S_Reload;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),14) */
    z_ctypes_4_VoidStar  z00010F0T_TheArgument;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),15) */
    SDL_Integer  z00010F0U_UAMode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\ua_me.spr(InitVar),263(5,25),16) */
    SDL_Integer  z00010F0V_WTAViewID;
    z_ctypes_4_VoidStar  yDcn_z_ctypes_4_VoidStar;
} yVDef_z00010F_UA_ME;

/*****
* PROCEDURE WML_GetA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS UA_ME>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_geta.spd,1,1)
******/
extern SDL_Boolean z00010F0A_WML_GetA XPP((SDL_Boolean z00010F0A0_fPrintError));

/*****
* PROCEDURE WML_UnRA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS UA_ME>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_unra.spd,1,1)
******/
extern void z00010F0B_WML_UnRA XPP((SDL_PId z00010F0B0_UnregPid));
#define z00010F0C_WaitForStart  1
#define z00010F0D_Idle  2
#define z00010F0F_TerminatingUserAgents  3
#define z00010F0G_TerminatingContentHandler  4

/*****
* PROCESS MMI_DISP
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_disp.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z00010G_MMI_DISP)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_disp.spr(VariableDecl),152(55,25),2) */
    z_ctypes_4_VoidStar  z00010G4_ActiveMMIAgents;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_disp.spr(VariableDecl),152(55,25),3) */
    SDL_Integer  z00010G5_TempInt;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_disp.spr(VariableDecl),152(55,25),4) */
    SDL_Integer  z00010G6_ViewID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_disp.spr(VariableDecl),152(55,25),5) */
    SDL_Integer  z00010G7_WidgetID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_disp.spr(VariableDecl),152(55,25),6) */
    SDL_PId  z00010G8_ThePid;
} yVDef_z00010G_MMI_DISP;

/*****
* PROCEDURE MMI_GetA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_DISP>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_geta.spd,1,1)
******/
extern SDL_PId z00010G1_MMI_GetA XPP((SDL_Integer z00010G10_Dummy));
#define z00010G2_WaitForStart  1
#define z00010G3_Idle  2

/*****
* SYNONYM CLR_NOTHING
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),5798(130,25),2)
******/
extern SDL_Octet  z00010H1R_CLR_NOTHING;

/*****
* SYNONYM CLR_RESPONSE
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),5798(130,25),3)
******/
extern SDL_Octet  z00010H1S_CLR_RESPONSE;

/*****
* SYNONYM CLR_MMI_LISTS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),5798(130,25),4)
******/
extern SDL_Octet  z00010H1T_CLR_MMI_LISTS;

/*****
* SYNONYM CLR_REQUESTS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),5798(130,25),5)
******/
extern SDL_Octet  z00010H1U_CLR_REQUESTS;

/*****
* PROCESS MMI_AGNT
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr,1,1)
******/
YPAD_PROTOTYPE(yPAD_z00010H_MMI_AGNT)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),2) */
    SDL_Integer  z00010H1V_ViewID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),3) */
    z_ctypes_4_VoidStar  z00010H1W_WAEObject;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),4) */
    z_ctypes_4_VoidStar  z00010H1X_UA;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),7) */
    SDL_Integer  z00010H1Y_iTotalNonCnfRequests;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),8) */
    SDL_Integer  z00010H1Z_TID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),9) */
    z_WAEPackage_2X_RequestType  z00010H20_RequestData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),10) */
    z_ctypes_4_VoidStar  z00010H21_RequestStruct;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),11) */
    z_ctypes_4_VoidStar  z00010H22_RequestURL;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),14) */
    z_WAEPackage_2Y_ResponseType  z00010H23_ResponseData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),15) */
    z_ctypes_4_VoidStar  z00010H24_ResponseURL;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),16) */
    z_ctypes_4_VoidStar  z00010H25_ResponseInfo;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),17) */
    SDL_Integer  z00010H26_ResponseTID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),18) */
    SDL_Integer  z00010H27_ErrorCode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),20) */
    z_ctypes_4_VoidStar  z00010H28_CurrentElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),21) */
    z_ctypes_4_VoidStar  z00010H29_ContainerElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),22) */
    z_ctypes_4_VoidStar  z00010H2A_UATimerElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),23) */
    z_ctypes_4_VoidStar  z00010H2B_TaskElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),24) */
    z_ctypes_4_VoidStar  z00010H2C_RequestImageElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),25) */
    z00012H_DisplayInfoType  z00010H2D_DisplayData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),27) */
    z_ctypes_4_VoidStar  z00010H2E_ListElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),28) */
    z_ctypes_4_VoidStar  z00010H2F_InputElementList;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),29) */
    z_ctypes_4_VoidStar  z00010H2G_ATextElementList;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),30) */
    z_ctypes_4_VoidStar  z00010H2H_AImageElementList;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),31) */
    z_ctypes_4_VoidStar  z00010H2I_OptionElementList;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),32) */
    z_ctypes_4_VoidStar  z00010H2J_DoElementList;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),33) */
    z_ctypes_4_VoidStar  z00010H2K_LanguageStack;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),34) */
    z_ctypes_4_VoidStar  z00010H2L_ImageRequestQueue;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),36) */
    z_ctypes_4_VoidStar  z00010H2M_ElementStack;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),38) */
    z_ctypes_4_VoidStar  z00010H2N_LinkTitle;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),39) */
    SDL_Boolean  z00010H2O_InTableElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),40) */
    z_ctypes_6_ShortInt  z00010H2P_WhiteSpace;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),41) */
    z_ctypes_6_ShortInt  z00010H2Q_TableWhiteSpace;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),42) */
    SDL_Integer  z00010H2R_TableColumns;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),43) */
    SDL_Integer  z00010H2S_TempInt;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),44) */
    SDL_Integer  z00010H2T_EmphMode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),45) */
    z_ctypes_4_VoidStar  z00010H2U_EmphModeBytes;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),46) */
    SDL_Integer  z00010H2V_ImageNr;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),47) */
    SDL_Integer  z00010H2W_InputNr;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),48) */
    SDL_Integer  z00010H2X_TextNr;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),49) */
    SDL_Integer  z00010H2Y_OptionNr;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),50) */
    SDL_Integer  z00010H2Z_DoElementNr;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),51) */
    SDL_Integer  z00010H30_WidgetID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),52) */
    z_ctypes_6_ShortInt  z00010H31_Preformatted;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),737(5,25),53) */
    z_ctypes_6_ShortInt  z00010H32_TextInAnchor;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),5669(80,85),2) */
    z_ctypes_4_VoidStar  z00010H33_TempText;
    z_ctypes_4_VoidStar  yDcn_z_ctypes_4_VoidStar;
} yVDef_z00010H_MMI_AGNT;

/*****
* PROCEDURE MMI_CLR
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_clr.spd,1,1)
******/
extern void z00010H1J_MMI_CLR XPP((SDL_Octet z00010H1J0_ClearFlags));

/*****
* PROCEDURE MMI_SRQ
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_srq.spd,1,1)
******/
extern SDL_Integer z00010H1K_MMI_SRQ XPP((
    z_ctypes_4_VoidStar z00010H1K0_SendURL,
    z_ctypes_4_VoidStar z00010H1K1_SendAccept));

/*****
* SIGNAL ScheduleElement
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\mmi_agnt.spr(VariableDecl),5663(80,70),2)
******/
#define z00010H1L_ScheduleElement 256
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z00010H1L_ScheduleElement;
#define z00010H1M_WaitForID  1
#define z00010H1O_ShuttingDown  2
#define z00010H1P_Idle  3
#define z00010H1Q_ProcessingCard  4

/*****
* SYNONYM CLR_NOTHING
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),2)
******/
extern SDL_Octet  z00010I21_CLR_NOTHING;

/*****
* SYNONYM CLR_RESPONSE
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),3)
******/
extern SDL_Octet  z00010I22_CLR_RESPONSE;

/*****
* SYNONYM CLR_ACTIONS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),4)
******/
extern SDL_Octet  z00010I23_CLR_ACTIONS;

/*****
* SYNONYM CLR_REQUESTS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),5)
******/
extern SDL_Octet  z00010I24_CLR_REQUESTS;

/*****
* SYNONYM CLR_CONTEXT
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),6)
******/
extern SDL_Octet  z00010I25_CLR_CONTEXT;

/*****
* SYNONYM WTA_ERROR_CLR
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),7)
******/
extern SDL_Octet  z00010I26_WTA_ERROR_CLR;

/*****
* SYNONYM CLR_ALL
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),8)
******/
extern SDL_Octet  z00010I27_CLR_ALL;

/*****
* SYNONYM NoCache
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),10)
******/
extern SDL_Octet  z00010I28_NoCache;

/*****
* SYNONYM NoStore
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),11)
******/
extern SDL_Octet  z00010I29_NoStore;

/*****
* SYNONYM Private
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20903(105,115),12)
******/
extern SDL_Octet  z00010I2A_Private;

/*****
* PROCESS WML_UA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr,1,1)
******/
YPAD_PROTOTYPE(yPAD_z00010I_WML_UA)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),2) */
    z_ctypes_4_VoidStar  z00010I2C_WAEObject;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),3) */
    SDL_PId  z00010I2D_PidMMI_Agent;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),4) */
    SDL_Integer  z00010I2E_ViewID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),5) */
    z_ctypes_6_ShortInt  z00010I2F_UA_Mode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),9) */
    SDL_Integer  z00010I2G_iTotalNonCnfRequests;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),10) */
    SDL_Integer  z00010I2H_RequestTID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),11) */
    z_WAEPackage_2X_RequestType  z00010I2I_RequestData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),12) */
    z_ctypes_4_VoidStar  z00010I2J_RequestStruct;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),13) */
    z_ctypes_4_VoidStar  z00010I2K_LoadRequestURL;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),14) */
    z_ctypes_4_VoidStar  z00010I2L_RequestURL;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),15) */
    z_ctypes_6_ShortInt  z00010I2M_Reload;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),16) */
    z_ctypes_6_ShortInt  z00010I2N_GoBackNav;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),17) */
    SDL_Octet  z00010I2O_Options;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),18) */
    z_ctypes_6_ShortInt  z00010I2P_RefreshSignal;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),21) */
    z_WAEPackage_2Y_ResponseType  z00010I2Q_ResponseData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),22) */
    z_ctypes_4_VoidStar  z00010I2R_ResponseURL;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),23) */
    SDL_Integer  z00010I2S_ContentTypeAsInt;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),24) */
    SDL_Integer  z00010I2T_IANACharID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),26) */
    z_ctypes_4_VoidStar  z00010I2U_RequestedAccept;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),27) */
    z_ctypes_4_VoidStar  z00010I2V_ResponseInfo;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),28) */
    SDL_Integer  z00010I2W_ResponseTID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),29) */
    SDL_Integer  z00010I2X_ErrorCode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),30) */
    z_ctypes_7_LongInt  z00010I2Y_TimerStartValue;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),33) */
    SDL_Boolean  z00010I2Z_IsRefreshed;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),34) */
    z_ctypes_6_ShortInt  z00010I30_CacheControl;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),35) */
    z_ctypes_4_VoidStar  z00010I31_CurrentCard;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),36) */
    z_ctypes_4_VoidStar  z00010I32_HistoryItem;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),37) */
    z_ctypes_4_VoidStar  z00010I33_TaskElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),38) */
    z_ctypes_4_VoidStar  z00010I34_TimerElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),39) */
    z_ctypes_4_VoidStar  z00010I35_UA;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),40) */
    z_ctypes_4_VoidStar  z00010I36_InputElementList;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),41) */
    SDL_Integer  z00010I37_NbrOfInputElements;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),42) */
    SDL_Integer  z00010I38_ActiveScriptId;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),43) */
    SDL_Integer  z00010I39_NewContext;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),44) */
    SDL_Boolean  z00010I3A_MMICleared;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),45) */
    z_ctypes_6_ShortInt  z00010I3B_Reparsing;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),47) */
    z00012H_DisplayInfoType  z00010I3C_DisplayData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),48) */
    SDL_Integer  z00010I3D_EventType;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),50) */
    z_ctypes_6_ShortInt  z00010I3E_cmicro;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3941(30,40),51) */
    SDL_Integer  z00010I3F_TimerElementValue;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),13160(180,40),4) */
    z_ctypes_4_VoidStar  z00010I3G_VoidStarDummy;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),13160(180,40),5) */
    SDL_Integer  z00010I3H_IntegerDummy;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),13160(180,40),6) */
    SDL_Integer  z00010I3I_TempInt;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),15752(105,55),2) */
    SDL_Integer  z00010I3J_ScriptErrorCode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),15752(105,55),3) */
    z_ctypes_4_VoidStar  z00010I3K_ScriptResultString;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),15752(105,55),4) */
    SDL_Integer  z00010I3L_ScriptGoPrev;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),15752(105,55),5) */
    z_ctypes_4_VoidStar  z00010I3M_ScriptRequestURL;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),15752(105,55),6) */
    SDL_Integer  z00010I3N_iScriptID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),15752(105,55),7) */
    SDL_Boolean  z00010I3O_LoadBPMode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),25337(205,70),2) */
    z_ctypes_4_VoidStar  z00010I3P_WTAEventType;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),25337(205,70),3) */
    SDL_Integer  z00010I3Q_WTAILibId;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),25337(205,70),4) */
    SDL_Integer  z00010I3R_WTAIFuncId;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),25337(205,70),5) */
    z_ctypes_4_VoidStar  z00010I3S_vsWTAIParam;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),25337(205,70),6) */
    z_ctypes_4_VoidStar  z00010I3T_WTACtrl;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3704(105,85),2) */
    SDL_Boolean  z00010I3U_ScriptActive;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3704(105,85),3) */
    SDL_Integer  z00010I3V_GoRef;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3704(105,85),4) */
    SDL_Boolean  z00010I3W_bIsWTA_URI;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),20828(105,100),2) */
    z_ctypes_4_VoidStar  z00010I3X_TheInputString;
    z_ctypes_4_VoidStar  yDcn_z_ctypes_4_VoidStar;
    SDL_Octet  yDcn_SDL_Octet;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3701(30,25),2) */
    DEF_TIMER_VAR(yTim_TimerEvent)
} yVDef_z00010I_WML_UA;

/*****
* PROCEDURE WML_SRQ
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_srq.spd,1,1)
******/
extern SDL_Integer z00010I1M_WML_SRQ XPP((
    z_ctypes_4_VoidStar z00010I1M0_SendURL,
    z_ctypes_4_VoidStar z00010I1M1_SendAccept,
    z_ctypes_4_VoidStar z00010I1M2_SendElement));

/*****
* SYNONYM CLR_RESPONSE
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA
*     /PROCEDURE WML_CLR>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_clr.spd(1),251(180,10),2)
******/
extern SDL_Octet  z00010I1N1_CLR_RESPONSE;

/*****
* SYNONYM CLR_ACTIONS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA
*     /PROCEDURE WML_CLR>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_clr.spd(1),251(180,10),3)
******/
extern SDL_Octet  z00010I1N2_CLR_ACTIONS;

/*****
* SYNONYM CLR_REQUESTS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA
*     /PROCEDURE WML_CLR>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_clr.spd(1),251(180,10),4)
******/
extern SDL_Octet  z00010I1N3_CLR_REQUESTS;

/*****
* PROCEDURE WML_CLR
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_clr.spd,1,1)
******/
extern void z00010I1N_WML_CLR XPP((SDL_Octet z00010I1N0_ClearFlags));

/*****
* SIGNAL ParsingSignal
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),4721(80,25),2)
******/
#define z00010I1O_ParsingSignal 257

/*****
* SIGNAL IntrinsicEventSignal
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),4721(80,25),3)
******/
#define z00010I1P_IntrinsicEventSignal 258
#define z00010I1Q_WaitForInit  1
#define z00010I1R_WaitForMMIAgentCnf  2
#define z00010I1S_ShuttingDown  3
#define z00010I1T_WTAIWaitFunctionResult  4
#define z00010I1U_Idle  5
#define z00010I1W_ScriptRunning  6
#define z00010I1X_WaitForScriptCnf  7
#define z00010I1Y_Parsing  8
#define z00010I1Z_WaitDisplayMMI  9
#define z00010I20_WaitForVariableInputResponse  10

/*****
* TIMER TimerEvent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr(InitVars),3701(30,25),2)
******/
#define z00010I2B_TimerEvent 1

/*****
* PROCESS WTA_IF
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z00010J_WTA_IF)

/*****
* PROCESS CONT_UA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z00010K_CONT_UA)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),2) */
    z_ctypes_4_VoidStar  z00010K0A_WAEObject;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),5) */
    SDL_Integer  z00010K0B_TID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),6) */
    z_WAEPackage_2X_RequestType  z00010K0C_RequestData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),7) */
    z_ctypes_4_VoidStar  z00010K0D_RequestStruct;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),8) */
    z_ctypes_4_VoidStar  z00010K0E_RequestURL;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),11) */
    z_WAEPackage_2Y_ResponseType  z00010K0F_ResponseData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),12) */
    z_ctypes_4_VoidStar  z00010K0G_ResponseURL;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),13) */
    z_ctypes_4_VoidStar  z00010K0H_TempText;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),14) */
    SDL_Integer  z00010K0I_ResponseTID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),15) */
    z_ctypes_4_VoidStar  z00010K0J_ResponseInfo;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),16) */
    SDL_Integer  z00010K0K_ErrorCode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),17) */
    z_ctypes_4_VoidStar  z00010K0L_RequestElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),18) */
    SDL_Integer  z00010K0M_TempInt;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),19) */
    SDL_Integer  z00010K0N_UrlID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),20) */
    SDL_Boolean  z00010K0O_IsOTAAllowed;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),21) */
    z_ctypes_4_VoidStar  z00010K0P_ListElement;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(InitVars),707(30,25),22) */
    z_ctypes_4_VoidStar  z00010K0Q_ContentRequestList;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),2) */
    SDL_Integer  z00010K0R_Reload;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),3) */
    z_ctypes_4_VoidStar  z00010K0S_AcceptHeader;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),4) */
    z_ctypes_4_VoidStar  z00010K0T_PostData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),5) */
    SDL_Integer  z00010K0U_PostDataLen;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),6) */
    SDL_Boolean  z00010K0V_MoreData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),7) */
    z_ctypes_4_VoidStar  z00010K0W_ContentType;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),8) */
    SDL_Integer  z00010K0X_SendMode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),9) */
    SDL_Integer  z00010K0Y_Method;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),10) */
    z_ctypes_4_VoidStar  z00010K0Z_ContentDisposition;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Request),1706(280,40),11) */
    SDL_Natural  z00010K10_TotalSize;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cont_ua.spr(Send),422(130,25),2) */
    SDL_Integer  z00010K11_RequestScheme;
    z_ctypes_4_VoidStar  yDcn_z_ctypes_4_VoidStar;
    SDL_Octet  yDcn_SDL_Octet;
} yVDef_z00010K_CONT_UA;
#define z00010K07_StandBy  1
#define z00010K09_Idle  2

/*****
* SIGNAL DisplayCardCnf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),8)
******/
#define z00010L_DisplayCardCnf 259
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z00010L_DisplayCardCnf;

/*****
* SIGNAL RegisterUAWithMMICnf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),9)
******/
#define z00010M_RegisterUAWithMMICnf 260

/*****
* SIGNAL TerminateMMIAgentCnf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),10)
******/
#define z00010N_TerminateMMIAgentCnf 261

/*****
* SIGNAL HandleMMIEvent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),11)
******/
#define z00010O_HandleMMIEvent 262
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z00010O_HandleMMIEvent;

/*****
* SIGNAL DisplayAbout
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),24)
******/
#define z00010P_DisplayAbout 263
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z00010P_DisplayAbout;

/*****
* SIGNAL RegisterUAWithMMI
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),25)
******/
#define z00010Q_RegisterUAWithMMI 264
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z00010Q_RegisterUAWithMMI;

/*****
* SIGNAL ClearMMI
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),26)
******/
#define z00010R_ClearMMI 265

/*****
* SIGNAL StopDisplay
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),27)
******/
#define z00010S_StopDisplay 266

/*****
* SIGNAL CloseMMIAgent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),28)
******/
#define z00010T_CloseMMIAgent 267

/*****
* SIGNAL TerminateMMIAgent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),29)
******/
#define z00010U_TerminateMMIAgent 268

/*****
* SIGNAL DisplayCard
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),1937(95,25),30)
******/
#define z00010V_DisplayCard 269
typedef struct {
    SIGNAL_VARS
    z00012H_DisplayInfoType  Param1;
} yPDef_z00010V_DisplayCard;

/*****
* SIGNAL TerminateWMLUACnf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),4)
******/
#define z00010W_TerminateWMLUACnf 270

/*****
* SIGNAL StartWMLUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),18)
******/
#define z00010X_StartWMLUA 271
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z00010X_StartWMLUA;

/*****
* SIGNAL TerminateWMLUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),19)
******/
#define z00010Y_TerminateWMLUA 272

/*****
* SIGNAL DiscardContext
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),20)
******/
#define z00010Z_DiscardContext 273

/*****
* SIGNAL CloseWMLUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),21)
******/
#define z000110_CloseWMLUA 274

/*****
* SIGNAL LoadNewDeck
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),22)
******/
#define z000111_LoadNewDeck 275
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    z_ctypes_6_ShortInt  Param2;
    z_ctypes_6_ShortInt  Param3;
} yPDef_z000111_LoadNewDeck;

/*****
* SIGNAL StopAction
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),23)
******/
#define z000112_StopAction 276

/*****
* SIGNAL GoBackAction
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),24)
******/
#define z000113_GoBackAction 277

/*****
* SIGNAL SetExternalInputField
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),25)
******/
#define z000114_SetExternalInputField 278
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z000114_SetExternalInputField;

/*****
* SIGNAL WTAResponseUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),26)
******/
#define z000115_WTAResponseUA 279
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z000115_WTAResponseUA;

/*****
* SIGNAL StartContentHandler
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),29)
******/
#define z000116_StartContentHandler 280
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z000116_StartContentHandler;

/*****
* SIGNAL TerminateContentHandler
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),30)
******/
#define z000117_TerminateContentHandler 281

/*****
* SIGNAL TerminateContentHandlerDone
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),31)
******/
#define z000118_TerminateContentHandlerDone 282

/*****
* SIGNAL StartMMIDisp
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),32)
******/
#define z000119_StartMMIDisp 283

/*****
* SIGNAL TerminateMMIDisp
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),227(25,40),33)
******/
#define z00011A_TerminateMMIDisp 284

/*****
* SIGNAL MMIKeySelect
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2177(95,135),9)
******/
#define z00011B_MMIKeySelect 285
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z00011B_MMIKeySelect;

/*****
* SIGNAL MMILinkSelectText
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2177(95,135),10)
******/
#define z00011C_MMILinkSelectText 286
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z00011C_MMILinkSelectText;

/*****
* SIGNAL MMILinkSelectImage
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2177(95,135),11)
******/
#define z00011D_MMILinkSelectImage 287
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z00011D_MMILinkSelectImage;

/*****
* SIGNAL MMIChangeOption
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2177(95,135),12)
******/
#define z00011E_MMIChangeOption 288
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z00011E_MMIChangeOption;

/*****
* SIGNAL MMILinkInfo
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2177(95,135),13)
******/
#define z00011F_MMILinkInfo 289
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z00011F_MMILinkInfo;

/*****
* SIGNAL RegisterMMIAgent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2177(95,135),21)
******/
#define z00011G_RegisterMMIAgent 290
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z00011G_RegisterMMIAgent;

/*****
* SIGNAL UnregisterMMIAgent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2177(95,135),22)
******/
#define z00011H_UnregisterMMIAgent 291

/*****
* SIGNAL ControlOfTempBind
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(WTASignals),5204(60,40),8)
******/
#define z00011I_ControlOfTempBind 292
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z00011I_ControlOfTempBind;

/*****
* SIGNAL ProcessContent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(WTASignals),5204(60,40),9)
******/
#define z00011J_ProcessContent 293
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2Y_ResponseType  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_6_ShortInt  Param3;
} yPDef_z00011J_ProcessContent;

/*****
* SIGNAL UnregisterWTADone
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(WTASignals),5204(60,40),10)
******/
#define z00011K_UnregisterWTADone 294

/*****
* SIGNAL RegisterWTA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(WTASignals),5204(60,40),22)
******/
#define z00011L_RegisterWTA 295
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z00011L_RegisterWTA;

/*****
* SIGNAL UnregisterWTA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(WTASignals),5204(60,40),23)
******/
#define z00011M_UnregisterWTA 296

/*****
* SIGNAL ControlOfTempBindResult
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(WTASignals),5204(60,40),24)
******/
#define z00011N_ControlOfTempBindResult 297
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z00011N_ControlOfTempBindResult;

/*****
* SIGNAL HandleChannelContent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(WTASignals),5204(60,40),25)
******/
#define z00011O_HandleChannelContent 298
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2Y_ResponseType  Param1;
} yPDef_z00011O_HandleChannelContent;

/*****
* SIGNAL ServiceTerminatedFromUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(WTASignals),5204(60,40),26)
******/
#define z00011P_ServiceTerminatedFromUA 299

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\cnf_push_wta__ua.sbk(2),2288(20,170),10) */
#include "wmldef.h"
#include "wml_uafn.h"
#include "wml_mmi.h"
#include "wmlif.h"
#include "wmltoken.h"

                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wml_ua.spr,1,1) */
#include "wmlelm.h"
#include "history.h"
#include "wbxmldec.h"
#include "wtai_if.h"
#include "dbfunct.h"

#ifdef CONFIG_WTA
#include "wta_ua.h"
#endif

