/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#define C_MICRO_1_3
#include "ml_typw.h"
#include "ctypes.h"
#include "waepckg.h"


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* SYNONYM Get
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),287(30,55),13)
******/
SDL_Octet  z_WAEPackage_2Z_Get;

/*****
* SYNONYM Post
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),287(30,55),14)
******/
SDL_Octet  z_WAEPackage_30_Post;

/*****
* SYNONYM application_vnd_wap.wmlc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),23)
******/
SDL_Octet  z_WAEPackage_31_application_vnd_wapwmlc;

/*****
* SYNONYM application_vnd_wap.wbxml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),24)
******/
SDL_Octet  z_WAEPackage_32_application_vnd_wapwbxml;

/*****
* SYNONYM application_vnd_wap.wmlscriptc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),25)
******/
SDL_Octet  z_WAEPackage_33_application_vnd_wapwmlscriptc;

/*****
* SYNONYM application_vnd_wap.channelc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),26)
******/
SDL_Octet  z_WAEPackage_34_application_vnd_wapchannelc;

/*****
* SYNONYM Continued
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),3)
******/
SDL_Octet  z_WAEPackage_35_Continued;

/*****
* SYNONYM SwitchingProtocols
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),4)
******/
SDL_Octet  z_WAEPackage_36_SwitchingProtocols;

/*****
* SYNONYM RequestOK
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),6)
******/
SDL_Octet  z_WAEPackage_37_RequestOK;

/*****
* SYNONYM Created
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),9)
******/
SDL_Octet  z_WAEPackage_38_Created;

/*****
* SYNONYM MultipleChoices
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),18)
******/
SDL_Octet  z_WAEPackage_39_MultipleChoices;

/*****
* SYNONYM MovedPermanently
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),19)
******/
SDL_Octet  z_WAEPackage_3A_MovedPermanently;

/*****
* SYNONYM MovedTemporarily
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),20)
******/
SDL_Octet  z_WAEPackage_3B_MovedTemporarily;

/*****
* SYNONYM SeeOther
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),21)
******/
SDL_Octet  z_WAEPackage_3C_SeeOther;

/*****
* SYNONYM NotModified
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),22)
******/
SDL_Octet  z_WAEPackage_3D_NotModified;

/*****
* SYNONYM UseProxy
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),23)
******/
SDL_Octet  z_WAEPackage_3E_UseProxy;

/*****
* SYNONYM Unauthorized
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),29)
******/
SDL_Octet  z_WAEPackage_3F_Unauthorized;

/*****
* SYNONYM NotFound
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),34)
******/
SDL_Octet  z_WAEPackage_3G_NotFound;

/*****
* SYNONYM ProxyAuthenticationRequired
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),40)
******/
SDL_Octet  z_WAEPackage_3H_ProxyAuthenticationRequired;

/*****
* NEWTYPE RequestType  (BODY section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),1)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAEPackage_2X_RequestType(
   z_WAEPackage_2X_RequestType *yVar )
#else
extern void yDef_z_WAEPackage_2X_RequestType( yVar )
  z_WAEPackage_2X_RequestType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).ViewID));
  xDef_SDL_Integer(&((*yVar).UA_Type));
  xDef_SDL_Integer(&((*yVar).Scheme));
  xDef_SDL_Integer(&((*yVar).TID));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RequestStruct));
  xDef_SDL_Octet(&((*yVar).Options));
  xDef_SDL_Integer(&((*yVar).Prio));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAEPackage_2X_RequestType(
  z_WAEPackage_2X_RequestType yExpr1,
  z_WAEPackage_2X_RequestType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAEPackage_2X_RequestType( yExpr1, yExpr2 )
  z_WAEPackage_2X_RequestType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.ViewID, yExpr2.ViewID) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.UA_Type, yExpr2.UA_Type) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.Scheme, yExpr2.Scheme) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.TID, yExpr2.TID) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RequestStruct, yExpr2.RequestStruct) )
  return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.Options, yExpr2.Options) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.Prio, yExpr2.Prio) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAEPackage_2X_RequestType yMake_z_WAEPackage_2X_RequestType(
  SDL_Integer yViewID,
  SDL_Integer yUA_Type,
  SDL_Integer yScheme,
  SDL_Integer yTID,
  z_ctypes_4_VoidStar yRequestStruct,
  SDL_Octet yOptions,
  SDL_Integer yPrio )
#else
extern z_WAEPackage_2X_RequestType  yMake_z_WAEPackage_2X_RequestType( yViewID,
  yUA_Type, yScheme, yTID, yRequestStruct, yOptions, yPrio )
  SDL_Integer yViewID;
  SDL_Integer yUA_Type;
  SDL_Integer yScheme;
  SDL_Integer yTID;
  z_ctypes_4_VoidStar yRequestStruct;
  SDL_Octet yOptions;
  SDL_Integer yPrio;
#endif
{
  z_WAEPackage_2X_RequestType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAEPackage_2X_RequestType));
  yAssF_SDL_Integer(yVar.ViewID, yViewID, XASSMAKE);
  yAssF_SDL_Integer(yVar.UA_Type, yUA_Type, XASSMAKE);
  yAssF_SDL_Integer(yVar.Scheme, yScheme, XASSMAKE);
  yAssF_SDL_Integer(yVar.TID, yTID, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RequestStruct, yRequestStruct, XASSMAKE);
  yAssF_SDL_Octet(yVar.Options, yOptions, XASSMAKE);
  yAssF_SDL_Integer(yVar.Prio, yPrio, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE ResponseType  (BODY section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),11)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAEPackage_2Y_ResponseType(
   z_WAEPackage_2Y_ResponseType *yVar )
#else
extern void yDef_z_WAEPackage_2Y_ResponseType( yVar )
  z_WAEPackage_2Y_ResponseType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).Scheme));
  xDef_SDL_Integer(&((*yVar).TID));
  yDef_z_ctypes_4_VoidStar(&((*yVar).HeaderHandle));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ContentType));
  yDef_z_ctypes_4_VoidStar(&((*yVar).BodyData));
  xDef_SDL_Integer(&((*yVar).BodyDataLength));
  xDef_SDL_Octet(&((*yVar).Status));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ExtParameters));
  xDef_SDL_Boolean(&((*yVar).MoreData));
  xDef_SDL_Natural(&((*yVar).TotalSize));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAEPackage_2Y_ResponseType(
  z_WAEPackage_2Y_ResponseType yExpr1,
  z_WAEPackage_2Y_ResponseType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAEPackage_2Y_ResponseType( yExpr1, yExpr2 )
  z_WAEPackage_2Y_ResponseType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.Scheme, yExpr2.Scheme) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.TID, yExpr2.TID) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.HeaderHandle, yExpr2.HeaderHandle) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ContentType, yExpr2.ContentType) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.BodyData, yExpr2.BodyData) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyDataLength, yExpr2.BodyDataLength) )
  return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.Status, yExpr2.Status) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ExtParameters, yExpr2.ExtParameters) )
  return SDL_False;
  if ( yNEqF_SDL_Boolean(yExpr1.MoreData, yExpr2.MoreData) ) return SDL_False;
  if ( yNEqF_SDL_Natural(yExpr1.TotalSize, yExpr2.TotalSize) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAEPackage_2Y_ResponseType yMake_z_WAEPackage_2Y_ResponseType(
  SDL_Integer yScheme,
  SDL_Integer yTID,
  z_ctypes_4_VoidStar yHeaderHandle,
  z_ctypes_4_VoidStar yContentType,
  z_ctypes_4_VoidStar yBodyData,
  SDL_Integer yBodyDataLength,
  SDL_Octet yStatus,
  z_ctypes_4_VoidStar yExtParameters,
  SDL_Boolean yMoreData,
  SDL_Natural yTotalSize )
#else
extern z_WAEPackage_2Y_ResponseType  yMake_z_WAEPackage_2Y_ResponseType
  ( yScheme, yTID, yHeaderHandle, yContentType, yBodyData, yBodyDataLength,
  yStatus, yExtParameters, yMoreData, yTotalSize )
  SDL_Integer yScheme;
  SDL_Integer yTID;
  z_ctypes_4_VoidStar yHeaderHandle;
  z_ctypes_4_VoidStar yContentType;
  z_ctypes_4_VoidStar yBodyData;
  SDL_Integer yBodyDataLength;
  SDL_Octet yStatus;
  z_ctypes_4_VoidStar yExtParameters;
  SDL_Boolean yMoreData;
  SDL_Natural yTotalSize;
#endif
{
  z_WAEPackage_2Y_ResponseType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAEPackage_2Y_ResponseType));
  yAssF_SDL_Integer(yVar.Scheme, yScheme, XASSMAKE);
  yAssF_SDL_Integer(yVar.TID, yTID, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.HeaderHandle, yHeaderHandle, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ContentType, yContentType, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.BodyData, yBodyData, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyDataLength, yBodyDataLength, XASSMAKE);
  yAssF_SDL_Octet(yVar.Status, yStatus, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ExtParameters, yExtParameters, XASSMAKE);
  yAssF_SDL_Boolean(yVar.MoreData, yMoreData, XASSMAKE);
  yAssF_SDL_Natural(yVar.TotalSize, yTotalSize, XASSMAKE);
  return yVar;
}

extern void yInit_WAEPackage XPP((void))
{
  static int IsCalled = 0;
  if (IsCalled) return;
  IsCalled = 1;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),287(30,55),13) */
  yAssF_SDL_Octet(z_WAEPackage_2Z_Get, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L40", "40")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),287(30,55),14) */
  yAssF_SDL_Octet(z_WAEPackage_30_Post, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L60", "60")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),23) */
  yAssF_SDL_Octet(z_WAEPackage_31_application_vnd_wapwmlc, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L14", "14")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),24) */
  yAssF_SDL_Octet(z_WAEPackage_32_application_vnd_wapwbxml, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L29", "29")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),25) */
  yAssF_SDL_Octet(z_WAEPackage_33_application_vnd_wapwmlscriptc,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L15", "15")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),26) */
  yAssF_SDL_Octet(z_WAEPackage_34_application_vnd_wapchannelc,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L16", "16")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),3) */
  yAssF_SDL_Octet(z_WAEPackage_35_Continued, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L10", "10")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),4) */
  yAssF_SDL_Octet(z_WAEPackage_36_SwitchingProtocols, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L11", "11")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),6) */
  yAssF_SDL_Octet(z_WAEPackage_37_RequestOK, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L20", "20")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),9) */
  yAssF_SDL_Octet(z_WAEPackage_38_Created, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L21", "21")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),18) */
  yAssF_SDL_Octet(z_WAEPackage_39_MultipleChoices, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L30", "30")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),19) */
  yAssF_SDL_Octet(z_WAEPackage_3A_MovedPermanently, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L31", "31")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),20) */
  yAssF_SDL_Octet(z_WAEPackage_3B_MovedTemporarily, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L32", "32")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),21) */
  yAssF_SDL_Octet(z_WAEPackage_3C_SeeOther, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L33", "33")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),22) */
  yAssF_SDL_Octet(z_WAEPackage_3D_NotModified, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L34", "34")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),23) */
  yAssF_SDL_Octet(z_WAEPackage_3E_UseProxy, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L35", "35")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),29) */
  yAssF_SDL_Octet(z_WAEPackage_3F_Unauthorized, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L41", "41")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),34) */
  yAssF_SDL_Octet(z_WAEPackage_3G_NotFound, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L44", "44")), XASS);
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),40) */
  yAssF_SDL_Octet(z_WAEPackage_3H_ProxyAuthenticationRequired,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L47", "47")), XASS);
}
