/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_WAEPackage_H
#define XX_WAEPackage_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

extern void yInit_WAEPackage XPP((void));

/*****
* SYNONYM MAXNUMBEROFWMLUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),302(30,90),3)
******/
#define z_WAEPackage_3I_MAXNUMBEROFWMLUA SDL_INTEGER_LIT(5)

/*****
* NEWTYPE RequestType  (TYPE section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),1)
******/
typedef struct z_WAEPackage_2X_RequestType_s {
    SDL_Integer  ViewID;
    SDL_Integer  UA_Type;
    SDL_Integer  Scheme;
    SDL_Integer  TID;
    z_ctypes_4_VoidStar  RequestStruct;
    SDL_Octet  Options;
    SDL_Integer  Prio;
} z_WAEPackage_2X_RequestType;

/*****
* NEWTYPE ResponseType  (TYPE section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),11)
******/
typedef struct z_WAEPackage_2Y_ResponseType_s {
    SDL_Integer  Scheme;
    SDL_Integer  TID;
    z_ctypes_4_VoidStar  HeaderHandle;
    z_ctypes_4_VoidStar  ContentType;
    z_ctypes_4_VoidStar  BodyData;
    SDL_Integer  BodyDataLength;
    SDL_Octet  Status;
    z_ctypes_4_VoidStar  ExtParameters;
    SDL_Boolean  MoreData;
    SDL_Natural  TotalSize;
} z_WAEPackage_2Y_ResponseType;

/*****
* NEWTYPE RequestType  (HEADING section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),1)
******/

#define yAssF_z_WAEPackage_2X_RequestType(V,E,A)  V = E
extern void yDef_z_WAEPackage_2X_RequestType
  XPP(( z_WAEPackage_2X_RequestType * ));
extern SDL_Boolean yEq_z_WAEPackage_2X_RequestType
  XPP(( z_WAEPackage_2X_RequestType, z_WAEPackage_2X_RequestType ));
#define yEqF_z_WAEPackage_2X_RequestType(Expr1,Expr2)  yEq_z_WAEPackage_2X_RequestType(Expr1,Expr2)
#define yNEqF_z_WAEPackage_2X_RequestType(Expr1,Expr2)  ( ! yEq_z_WAEPackage_2X_RequestType(Expr1,Expr2) )
extern z_WAEPackage_2X_RequestType yMake_z_WAEPackage_2X_RequestType
  XPP(( SDL_Integer, SDL_Integer, SDL_Integer, SDL_Integer,
  z_ctypes_4_VoidStar, SDL_Octet, SDL_Integer ));
#ifndef ANY_z_WAEPackage_2X_RequestType
#define ANY_z_WAEPackage_2X_RequestType  yMake_z_WAEPackage_2X_RequestType(ANY_SDL_Integer, \
  ANY_SDL_Integer, ANY_SDL_Integer, ANY_SDL_Integer, ANY_z_ctypes_4_VoidStar, \
  ANY_SDL_Octet, ANY_SDL_Integer)
#endif
#define z_WAEPackage_2X3_copy(P)  P

/*****
* NEWTYPE ResponseType  (HEADING section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),11)
******/

#define yAssF_z_WAEPackage_2Y_ResponseType(V,E,A)  V = E
extern void yDef_z_WAEPackage_2Y_ResponseType
  XPP(( z_WAEPackage_2Y_ResponseType * ));
extern SDL_Boolean yEq_z_WAEPackage_2Y_ResponseType
  XPP(( z_WAEPackage_2Y_ResponseType, z_WAEPackage_2Y_ResponseType ));
#define yEqF_z_WAEPackage_2Y_ResponseType(Expr1,Expr2)  yEq_z_WAEPackage_2Y_ResponseType(Expr1,Expr2)
#define yNEqF_z_WAEPackage_2Y_ResponseType(Expr1,Expr2)  ( ! yEq_z_WAEPackage_2Y_ResponseType(Expr1,Expr2) )
extern z_WAEPackage_2Y_ResponseType yMake_z_WAEPackage_2Y_ResponseType
  XPP(( SDL_Integer, SDL_Integer, z_ctypes_4_VoidStar, z_ctypes_4_VoidStar,
  z_ctypes_4_VoidStar, SDL_Integer, SDL_Octet, z_ctypes_4_VoidStar,
  SDL_Boolean, SDL_Natural ));
#ifndef ANY_z_WAEPackage_2Y_ResponseType
#define ANY_z_WAEPackage_2Y_ResponseType  yMake_z_WAEPackage_2Y_ResponseType(ANY_SDL_Integer, \
  ANY_SDL_Integer, ANY_z_ctypes_4_VoidStar, ANY_z_ctypes_4_VoidStar, \
  ANY_z_ctypes_4_VoidStar, ANY_SDL_Integer, ANY_SDL_Octet, \
  ANY_z_ctypes_4_VoidStar, ANY_SDL_Boolean, ANY_SDL_Natural)
#endif
#define z_WAEPackage_2Y3_copy(P)  P

/*****
* SYNONYM Get
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),287(30,55),13)
******/
extern SDL_Octet  z_WAEPackage_2Z_Get;

/*****
* SYNONYM Post
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),287(30,55),14)
******/
extern SDL_Octet  z_WAEPackage_30_Post;

/*****
* SYNONYM application_vnd_wap.wmlc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),23)
******/
extern SDL_Octet  z_WAEPackage_31_application_vnd_wapwmlc;

/*****
* SYNONYM application_vnd_wap.wbxml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),24)
******/
extern SDL_Octet  z_WAEPackage_32_application_vnd_wapwbxml;

/*****
* SYNONYM application_vnd_wap.wmlscriptc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),25)
******/
extern SDL_Octet  z_WAEPackage_33_application_vnd_wapwmlscriptc;

/*****
* SYNONYM application_vnd_wap.channelc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),26)
******/
extern SDL_Octet  z_WAEPackage_34_application_vnd_wapchannelc;

/*****
* SYNONYM Continued
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),3)
******/
extern SDL_Octet  z_WAEPackage_35_Continued;

/*****
* SYNONYM SwitchingProtocols
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),4)
******/
extern SDL_Octet  z_WAEPackage_36_SwitchingProtocols;

/*****
* SYNONYM RequestOK
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),6)
******/
extern SDL_Octet  z_WAEPackage_37_RequestOK;

/*****
* SYNONYM Created
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),9)
******/
extern SDL_Octet  z_WAEPackage_38_Created;

/*****
* SYNONYM MultipleChoices
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),18)
******/
extern SDL_Octet  z_WAEPackage_39_MultipleChoices;

/*****
* SYNONYM MovedPermanently
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),19)
******/
extern SDL_Octet  z_WAEPackage_3A_MovedPermanently;

/*****
* SYNONYM MovedTemporarily
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),20)
******/
extern SDL_Octet  z_WAEPackage_3B_MovedTemporarily;

/*****
* SYNONYM SeeOther
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),21)
******/
extern SDL_Octet  z_WAEPackage_3C_SeeOther;

/*****
* SYNONYM NotModified
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),22)
******/
extern SDL_Octet  z_WAEPackage_3D_NotModified;

/*****
* SYNONYM UseProxy
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),23)
******/
extern SDL_Octet  z_WAEPackage_3E_UseProxy;

/*****
* SYNONYM Unauthorized
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),29)
******/
extern SDL_Octet  z_WAEPackage_3F_Unauthorized;

/*****
* SYNONYM NotFound
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),34)
******/
extern SDL_Octet  z_WAEPackage_3G_NotFound;

/*****
* SYNONYM ProxyAuthenticationRequired
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),40)
******/
extern SDL_Octet  z_WAEPackage_3H_ProxyAuthenticationRequired;

/*****
* SIGNAL GetContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(110,30),8)
******/
#define z_WAEPackage_00_GetContent 33
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_00_GetContent;

/*****
* SIGNAL PostContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(110,30),9)
******/
#define z_WAEPackage_01_PostContent 34
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
    SDL_Integer  Param6;
    SDL_Boolean  Param7;
    z_ctypes_4_VoidStar  Param8;
    SDL_Integer  Param9;
    z_ctypes_4_VoidStar  Param10;
    SDL_Natural  Param11;
} yPDef_z_WAEPackage_01_PostContent;

/*****
* SIGNAL AcknowledgeContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(110,30),11)
******/
#define z_WAEPackage_02_AcknowledgeContent 35
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_02_AcknowledgeContent;

/*****
* SIGNAL CancelContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(110,30),12)
******/
#define z_WAEPackage_03_CancelContent 36
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_03_CancelContent;

/*****
* SIGNAL PostMoreContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(110,30),13)
******/
#define z_WAEPackage_04_PostMoreContent 37
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    SDL_Boolean  Param4;
} yPDef_z_WAEPackage_04_PostMoreContent;

/*****
* SIGNAL InputString
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(20,40),3)
******/
#define z_WAEPackage_05_InputString 38
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_05_InputString;

/*****
* SIGNAL LoadURL
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(20,40),4)
******/
#define z_WAEPackage_06_LoadURL 39
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Boolean  Param3;
    SDL_Integer  Param4;
} yPDef_z_WAEPackage_06_LoadURL;

/*****
* SIGNAL ReloadCard
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(20,40),5)
******/
#define z_WAEPackage_07_ReloadCard 40
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_07_ReloadCard;

/*****
* SIGNAL OpenView
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(20,40),6)
******/
#define z_WAEPackage_08_OpenView 41
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_08_OpenView;

/*****
* SIGNAL CloseView
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(20,40),7)
******/
#define z_WAEPackage_09_CloseView 42
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_09_CloseView;

/*****
* SIGNAL DiscardAllContext
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(20,40),8)
******/
#define z_WAEPackage_0A_DiscardAllContext 43

/*****
* SIGNAL Abort
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(20,40),9)
******/
#define z_WAEPackage_0B_Abort 44
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_0B_Abort;

/*****
* SIGNAL GoBack
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(20,40),10)
******/
#define z_WAEPackage_0C_GoBack 45
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_0C_GoBack;

/*****
* SIGNAL WTAResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(20,40),11)
******/
#define z_WAEPackage_0D_WTAResponse 46
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_0D_WTAResponse;

/*****
* SIGNAL InitCache
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(110,45),10)
******/
#define z_WAEPackage_0E_InitCache 47
typedef struct {
    SIGNAL_VARS
    z_ctypes_7_LongInt  Param1;
    z_ctypes_7_LongInt  Param2;
} yPDef_z_WAEPackage_0E_InitCache;

/*****
* SIGNAL PrepareCache
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(110,45),11)
******/
#define z_WAEPackage_0F_PrepareCache 48
typedef struct {
    SIGNAL_VARS
    z_ctypes_7_LongInt  Param1;
} yPDef_z_WAEPackage_0F_PrepareCache;

/*****
* SIGNAL PasswordDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(110,45),12)
******/
#define z_WAEPackage_0G_PasswordDialogResponse 49
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_0G_PasswordDialogResponse;

/*****
* SIGNAL SetupConnectionDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(110,45),14)
******/
#define z_WAEPackage_0H_SetupConnectionDone 50
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Boolean  Param3;
} yPDef_z_WAEPackage_0H_SetupConnectionDone;

/*****
* SIGNAL CloseConnection
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(110,45),15)
******/
#define z_WAEPackage_0I_CloseConnection 51
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Boolean  Param3;
} yPDef_z_WAEPackage_0I_CloseConnection;

/*****
* SIGNAL RequestConnectionDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(110,45),16)
******/
#define z_WAEPackage_0J_RequestConnectionDone 52
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Boolean  Param2;
} yPDef_z_WAEPackage_0J_RequestConnectionDone;

/*****
* SIGNAL KeySelected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(110,115),3)
******/
#define z_WAEPackage_0K_KeySelected 53
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0K_KeySelected;

/*****
* SIGNAL TextSelected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(110,115),4)
******/
#define z_WAEPackage_0L_TextSelected 54
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0L_TextSelected;

/*****
* SIGNAL ImageSelected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(110,115),5)
******/
#define z_WAEPackage_0M_ImageSelected 55
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0M_ImageSelected;

/*****
* SIGNAL ChangeOptionState
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(110,115),6)
******/
#define z_WAEPackage_0N_ChangeOptionState 56
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0N_ChangeOptionState;

/*****
* SIGNAL LinkInfo
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(110,115),7)
******/
#define z_WAEPackage_0O_LinkInfo 57
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_0O_LinkInfo;

/*****
* SIGNAL PromptDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(20,165),3)
******/
#define z_WAEPackage_0P_PromptDialogResponse 58
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_0P_PromptDialogResponse;

/*****
* SIGNAL ConfirmDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(20,165),4)
******/
#define z_WAEPackage_0Q_ConfirmDialogResponse 59
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_0Q_ConfirmDialogResponse;

/*****
* SIGNAL AlertDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(20,165),5)
******/
#define z_WAEPackage_0R_AlertDialogResponse 60
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0R_AlertDialogResponse;

/*****
* SIGNAL TextSigned
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(20,165),6)
******/
#define z_WAEPackage_0S_TextSigned 61
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_Integer  Param4;
    z_ctypes_4_VoidStar  Param5;
    z_ctypes_4_VoidStar  Param6;
    SDL_Integer  Param7;
    z_ctypes_4_VoidStar  Param8;
    SDL_Integer  Param9;
    SDL_Integer  Param10;
    SDL_Integer  Param11;
} yPDef_z_WAEPackage_0S_TextSigned;

/*****
* SIGNAL WMLSLibFuncResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(20,165),7)
******/
#define z_WAEPackage_0T_WMLSLibFuncResponse 62
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z_WAEPackage_0T_WMLSLibFuncResponse;

/*****
* SIGNAL StartUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),5)
******/
#define z_WAEPackage_0U_StartUA 63
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z_WAEPackage_0U_StartUA;

/*****
* SIGNAL TerminateUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),6)
******/
#define z_WAEPackage_0V_TerminateUA 64

/*****
* SIGNAL TerminateUACnf
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),11)
******/
#define z_WAEPackage_0W_TerminateUACnf 65

/*****
* SIGNAL StartWMLS
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),17)
******/
#define z_WAEPackage_0X_StartWMLS 66

/*****
* SIGNAL TerminateWMLS
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),18)
******/
#define z_WAEPackage_0Y_TerminateWMLS 67

/*****
* SIGNAL TerminateWMLSCnf
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),23)
******/
#define z_WAEPackage_0Z_TerminateWMLSCnf 68

/*****
* SIGNAL AbortScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),13)
******/
#define z_WAEPackage_10_AbortScript 69
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_10_AbortScript;

/*****
* SIGNAL InvokeScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),14)
******/
#define z_WAEPackage_11_InvokeScript 70
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
    SDL_Integer  Param6;
} yPDef_z_WAEPackage_11_InvokeScript;

/*****
* SIGNAL LoadDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),17)
******/
#define z_WAEPackage_12_LoadDone 71
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    SDL_Integer  Param4;
} yPDef_z_WAEPackage_12_LoadDone;

/*****
* SIGNAL LoadStringDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),20)
******/
#define z_WAEPackage_13_LoadStringDone 72
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    z_ctypes_9_UnsignedInt  Param4;
} yPDef_z_WAEPackage_13_LoadStringDone;

/*****
* SIGNAL LoadStringError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),23)
******/
#define z_WAEPackage_14_LoadStringError 73
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_14_LoadStringError;

/*****
* SIGNAL LoadError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),24)
******/
#define z_WAEPackage_15_LoadError 74
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_15_LoadError;

/*****
* SIGNAL InvokeWTAIFromScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),25)
******/
#define z_WAEPackage_16_InvokeWTAIFromScript 75
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_16_InvokeWTAIFromScript;

/*****
* SIGNAL WTAIResultInfoScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),26)
******/
#define z_WAEPackage_17_WTAIResultInfoScript 76
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_17_WTAIResultInfoScript;

/*****
* SIGNAL RefreshDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),27)
******/
#define z_WAEPackage_18_RefreshDone 77
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_18_RefreshDone;

/*****
* SIGNAL InvokeDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),40)
******/
#define z_WAEPackage_19_InvokeDone 78
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    SDL_Integer  Param4;
    z_ctypes_4_VoidStar  Param5;
} yPDef_z_WAEPackage_19_InvokeDone;

/*****
* SIGNAL InvokeStatus
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),41)
******/
#define z_WAEPackage_1A_InvokeStatus 79
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1A_InvokeStatus;

/*****
* SIGNAL LoadBP
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),42)
******/
#define z_WAEPackage_1B_LoadBP 80
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z_WAEPackage_1B_LoadBP;

/*****
* SIGNAL LoadString
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),43)
******/
#define z_WAEPackage_1C_LoadString 81
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_1C_LoadString;

/*****
* SIGNAL RefreshReqFromWmls
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),44)
******/
#define z_WAEPackage_1D_RefreshReqFromWmls 82
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1D_RefreshReqFromWmls;

/*****
* SIGNAL GetFileResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(FILESignals),338(60,50),4)
******/
#define z_WAEPackage_1E_GetFileResponse 83
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_1E_GetFileResponse;

/*****
* SIGNAL CallFunctionResult
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(FILESignals),338(60,50),5)
******/
#define z_WAEPackage_1F_CallFunctionResult 84
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
} yPDef_z_WAEPackage_1F_CallFunctionResult;

/*****
* SIGNAL FileFunctionTimer
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(FILESignals),338(60,50),6)
******/
#define z_WAEPackage_1G_FileFunctionTimer 85
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_WAEPackage_1G_FileFunctionTimer;

/*****
* SIGNAL WSPRequest
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),4)
******/
#define z_WAEPackage_1H_WSPRequest 86
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2X_RequestType  Param1;
} yPDef_z_WAEPackage_1H_WSPRequest;

/*****
* SIGNAL WSPAbortRequest
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),5)
******/
#define z_WAEPackage_1I_WSPAbortRequest 87
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1I_WSPAbortRequest;

/*****
* SIGNAL WSPAckGetContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),7)
******/
#define z_WAEPackage_1J_WSPAckGetContent 88
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1J_WSPAckGetContent;

/*****
* SIGNAL StartWSPIFDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),20)
******/
#define z_WAEPackage_1K_StartWSPIFDone 89

/*****
* SIGNAL TerminateWSPIFDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),21)
******/
#define z_WAEPackage_1L_TerminateWSPIFDone 90

/*****
* SIGNAL StartWSPIF
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),29)
******/
#define z_WAEPackage_1M_StartWSPIF 91
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z_WAEPackage_1M_StartWSPIF;

/*****
* SIGNAL TerminateWSPIF
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),30)
******/
#define z_WAEPackage_1N_TerminateWSPIF 92

/*****
* SIGNAL WSPResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),536(20,130),4)
******/
#define z_WAEPackage_1O_WSPResponse 93
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2Y_ResponseType  Param1;
} yPDef_z_WAEPackage_1O_WSPResponse;

/*****
* SIGNAL WSPError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),536(20,130),5)
******/
#define z_WAEPackage_1P_WSPError 94
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_1P_WSPError;

/*****
* SIGNAL WSPAckPostContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),536(20,130),7)
******/
#define z_WAEPackage_1Q_WSPAckPostContent 95
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1Q_WSPAckPostContent;

/*****
* SIGNAL StartDI
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),18)
******/
#define z_WAEPackage_1R_StartDI 96

/*****
* SIGNAL TerminateDI
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),19)
******/
#define z_WAEPackage_1S_TerminateDI 97

/*****
* SIGNAL SMNewSession
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),20)
******/
#define z_WAEPackage_1T_SMNewSession 98
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
    SDL_PId  Param6;
} yPDef_z_WAEPackage_1T_SMNewSession;

/*****
* SIGNAL SMTerminateSession
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),21)
******/
#define z_WAEPackage_1U_SMTerminateSession 99

/*****
* SIGNAL SMNewTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),22)
******/
#define z_WAEPackage_1V_SMNewTransaction 100
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2X_RequestType  Param1;
    SDL_PId  Param2;
} yPDef_z_WAEPackage_1V_SMNewTransaction;

/*****
* SIGNAL SMAbortTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),23)
******/
#define z_WAEPackage_1W_SMAbortTransaction 101
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1W_SMAbortTransaction;

/*****
* SIGNAL SMBasicAuth
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),25)
******/
#define z_WAEPackage_1X_SMBasicAuth 102
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_1X_SMBasicAuth;

/*****
* SIGNAL SMReConnect
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),27)
******/
#define z_WAEPackage_1Y_SMReConnect 103

/*****
* SIGNAL SMTerminateBearer
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),28)
******/
#define z_WAEPackage_1Z_SMTerminateBearer 104
typedef struct {
    SIGNAL_VARS
    SDL_Octet  Param1;
} yPDef_z_WAEPackage_1Z_SMTerminateBearer;

/*****
* SIGNAL SMPushIndicationResp
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),30)
******/
#define z_WAEPackage_20_SMPushIndicationResp 105
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_20_SMPushIndicationResp;

/*****
* SIGNAL SMSetupConnectionDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),32)
******/
#define z_WAEPackage_21_SMSetupConnectionDone 106
typedef struct {
    SIGNAL_VARS
    SDL_Boolean  Param1;
} yPDef_z_WAEPackage_21_SMSetupConnectionDone;

/*****
* SIGNAL SMCloseConnection
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),34)
******/
#define z_WAEPackage_22_SMCloseConnection 107
typedef struct {
    SIGNAL_VARS
    SDL_Boolean  Param1;
} yPDef_z_WAEPackage_22_SMCloseConnection;

/*****
* SIGNAL WSPIFAckRes
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),36)
******/
#define z_WAEPackage_23_WSPIFAckRes 108
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_23_WSPIFAckRes;

/*****
* SIGNAL SessionProcInstalled
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),53)
******/
#define z_WAEPackage_24_SessionProcInstalled 109
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_PId  Param3;
} yPDef_z_WAEPackage_24_SessionProcInstalled;

/*****
* SIGNAL StartDIDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),54)
******/
#define z_WAEPackage_25_StartDIDone 110

/*****
* SIGNAL TerminateDIDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),55)
******/
#define z_WAEPackage_26_TerminateDIDone 111

/*****
* SIGNAL SMTerminateSessionDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),56)
******/
#define z_WAEPackage_27_SMTerminateSessionDone 112

/*****
* SIGNAL GetNextTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),57)
******/
#define z_WAEPackage_28_GetNextTransaction 113

/*****
* SIGNAL Connected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),58)
******/
#define z_WAEPackage_29_Connected 114
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_29_Connected;

/*****
* SIGNAL StoreTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),60)
******/
#define z_WAEPackage_2A_StoreTransaction 115
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2X_RequestType  Param1;
    SDL_PId  Param2;
} yPDef_z_WAEPackage_2A_StoreTransaction;

/*****
* SIGNAL WSPIFResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),61)
******/
#define z_WAEPackage_2B_WSPIFResponse 116
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2Y_ResponseType  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    SDL_PId  Param4;
    SDL_Integer  Param5;
    SDL_Integer  Param6;
    z_WAEPackage_2X_RequestType  Param7;
    SDL_Integer  Param8;
} yPDef_z_WAEPackage_2B_WSPIFResponse;

/*****
* SIGNAL WSPIFError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),63)
******/
#define z_WAEPackage_2C_WSPIFError 117
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_PId  Param3;
} yPDef_z_WAEPackage_2C_WSPIFError;

/*****
* SIGNAL WSPIFPushIndication
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),65)
******/
#define z_WAEPackage_2D_WSPIFPushIndication 118
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_Boolean  Param4;
    SDL_Integer  Param5;
    SDL_Integer  Param6;
    z_ctypes_4_VoidStar  Param7;
    z_ctypes_4_VoidStar  Param8;
} yPDef_z_WAEPackage_2D_WSPIFPushIndication;

/*****
* SIGNAL WSPIFAckCnf
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),67)
******/
#define z_WAEPackage_2E_WSPIFAckCnf 119
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_PId  Param2;
} yPDef_z_WAEPackage_2E_WSPIFAckCnf;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
