/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#define C_MICRO_1_3
#include "ml_typw.h"
#include "ctypes.h"
#include "buffmgt.h"
#include "glbldecl.h"
#include "wdp_ul.h"
#include "wtlspckg.h"
#include "wtls_wdp.h"
#include "wdppckg.h"
#include "wdp_udp.h"
#include "wspcmwtp.h"
#include "wtppckg.h"
#include "wtp_wdp.h"
#include "sptp_tls.h"
#include "wspclwdp.h"
#include "waepckg.h"
#include "wtapckg.h"
#include "pushpckg.h"
#include "wae_wsp.h"
#include "stackmgr.h"
#include "wap.h"
#include "wae.h"
#include "wae_ua.h"

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PROCESS WTA_IF
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr,4,1)
******/
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),2) */
    SDL_PId  z00010J9_WTAUAPid;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),3) */
    z_ctypes_4_VoidStar  z00010JA_WTA_Control;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),4) */
    z_ctypes_4_VoidStar  z00010JB_EventID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),5) */
    z_ctypes_4_VoidStar  z00010JC_EventParameters;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),6) */
    z_WAEPackage_2Y_ResponseType  z00010JD_ResponseData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),7) */
    z_ctypes_4_VoidStar  z00010JE_WTAIParam;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),8) */
    z_ctypes_4_VoidStar  z00010JF_URIParameters;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),9) */
    SDL_Integer  z00010JG_ScriptID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),10) */
    SDL_Integer  z00010JH_FuncID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),11) */
    SDL_Integer  z00010JI_TempInt;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),12) */
    SDL_Boolean  z00010JJ_ServiceActive;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),13) */
    z_ctypes_6_ShortInt  z00010JK_StartServiceAttempt;
} yVDef_z00010J_WTA_IF;
#define z00010J4_StandBy  1
#define z00010J6_Idle  2
#define z00010J7_ServiceExecuting  3
#define z00010J8_CheckBinding  4

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(InitVars),116(30,25),13) */
#include "wta_ua.h"
#include "wtai_if.h"
#include "aapiwta.h"


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PROCESS WTA_IF
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr,4,1)
******/

/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
** Tables for process WTA_IF
** #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr,4,1)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

/*--------------Instance Data---------------*/
#define X_MAX_INST_z00010J_WTA_IF 1
static yVDef_z00010J_WTA_IF *yINSTD_z00010J_WTA_IF[X_MAX_INST_z00010J_WTA_IF];

/*--------------Process State---------------*/
static xSTATE yPSTATETBL_z00010J_WTA_IF[X_MAX_INST_z00010J_WTA_IF] = {
  XSTARTUP
};

/*---------------State Index----------------*/
static XCONST xSITBL xSTATE_INDEX_z00010J_WTA_IF[5] = {0, 5, 13, 22, 29};

/*---------------Transition-----------------*/
#define XMAX_TRANS_z00010J_WTA_IF 29
static XCONST xTR_TABLE_ENTRY yTRTBL_z00010J_WTA_IF[XMAX_TRANS_z00010J_WTA_IF] = {

    /* StandBy */
  XMK_B z00011L_RegisterWTA, 1 XMK_E,
  XMK_B z00011M_UnregisterWTA, 2 XMK_E,
  XMK_B z00011N_ControlOfTempBindResult, 16 XMK_E,
  XMK_B z_WTAPackage_I_GlobalBindingResult, 17 XMK_E,
  XMK_B XASTERISK, XSAVEID XMK_E

    /* Idle */,
  XMK_B z00011M_UnregisterWTA, 2 XMK_E,
  XMK_B z00011N_ControlOfTempBindResult, 16 XMK_E,
  XMK_B z00011O_HandleChannelContent, 6 XMK_E,
  XMK_B z_WTAPackage_2_WTAEvent, 4 XMK_E,
  XMK_B z_WTAPackage_1_WTAExecuteService, 7 XMK_E,
  XMK_B z_WTAPackage_0_TerminateWTAService, 3 XMK_E,
  XMK_B z_WTAPackage_H_InstallationResult, 5 XMK_E,
  XMK_B z_WTAPackage_I_GlobalBindingResult, 17 XMK_E

    /* ServiceExecuting */,
  XMK_B z00011M_UnregisterWTA, 2 XMK_E,
  XMK_B z00011N_ControlOfTempBindResult, 16 XMK_E,
  XMK_B z00011O_HandleChannelContent, 12 XMK_E,
  XMK_B z00011P_ServiceTerminatedFromUA, 9 XMK_E,
  XMK_B z_WTAPackage_2_WTAEvent, 10 XMK_E,
  XMK_B z_WTAPackage_1_WTAExecuteService, 8 XMK_E,
  XMK_B z_WTAPackage_0_TerminateWTAService, 3 XMK_E,
  XMK_B z_WTAPackage_H_InstallationResult, 11 XMK_E,
  XMK_B z_WTAPackage_I_GlobalBindingResult, 17 XMK_E

    /* CheckBinding */,
  XMK_B z00011M_UnregisterWTA, 2 XMK_E,
  XMK_B z00011N_ControlOfTempBindResult, 13 XMK_E,
  XMK_B z00011P_ServiceTerminatedFromUA, 15 XMK_E,
  XMK_B z_WTAPackage_2_WTAEvent, XSAVEID XMK_E,
  XMK_B z_WTAPackage_1_WTAExecuteService, XSAVEID XMK_E,
  XMK_B z_WTAPackage_0_TerminateWTAService, 3 XMK_E,
  XMK_B z_WTAPackage_I_GlobalBindingResult, 14 XMK_E
};

/*-----------Process-PID-Values-------------*/
#ifdef XMK_USE_PID_ADDRESSING
static xPIDTable yPID_TBL_z00010J_WTA_IF[X_MAX_INST_z00010J_WTA_IF];
#endif

/*-----------Process Description------------*/
#define X_PRIO_z00010J_WTA_IF  xDefaultPrioProcess
XCONST XPDTBL yPDTBL_z00010J_WTA_IF = {
#ifdef XMK_USE_PID_ADDRESSING
  yPID_TBL_z00010J_WTA_IF,
#endif
  (xINSTD *)yINSTD_z00010J_WTA_IF,
  sizeof(yVDef_z00010J_WTA_IF),
  X_MAX_INST_z00010J_WTA_IF,
#ifdef XMK_USE_TIMESLICE
  X_TIMESLICE_z00010J_WTA_IF,
#endif
#ifdef XMK_USE_PREEMPTIVE
  X_PRIO_z00010J_WTA_IF,
#endif
  (xmk_T_TRANS_ADDRESS) yPAD_z00010J_WTA_IF,
  yTRTBL_z00010J_WTA_IF,
  xSTATE_INDEX_z00010J_WTA_IF,
  yPSTATETBL_z00010J_WTA_IF
};

/*+++++
* Function for process WTA_IF
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr,4,1)
++++++*/
YPAD_FUNCTION(yPAD_z00010J_WTA_IF)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z00010J_WTA_IF)
  YPAD_TEMP_VARS
  SDL_Integer  yDcn_SDL_Integer;
  /* INTEGRATION: commented out statement */
  /* SDL_Boolean  yDcn_SDL_Boolean; */
  /* INTEGRATION: commented out statement */
  /* SDL_PId  yDcn_SDL_PId; */
  YPRSNAME_VAR("WTA_IF")

  BEGIN_PAD
  switch (XSYMBOLNUMBER) {

/*-----
* START
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1685(30,40),1)
------*/
  case 0:
    BEGIN_START_TRANSITION
    XAT_FIRST_SYMBOL(0, 1612)
    yAssF_SDL_PId(yVarP->z00010J9_WTAUAPid, SDL_NULL, XASS);
    yAssF_z_ctypes_4_VoidStar(yVarP->z00010JA_WTA_Control, z_ctypes_40_Null(),
      XASS);
    yDef_z_ctypes_4_VoidStar(&yVarP->z00010JB_EventID);
    yDef_z_ctypes_4_VoidStar(&yVarP->z00010JC_EventParameters);
    yDef_z_WAEPackage_2Y_ResponseType(&yVarP->z00010JD_ResponseData);
    yDef_z_ctypes_4_VoidStar(&yVarP->z00010JE_WTAIParam);
    yAssF_z_ctypes_4_VoidStar(yVarP->z00010JF_URIParameters,
      z_ctypes_40_Null(), XASS);
    xDef_SDL_Integer(&yVarP->z00010JG_ScriptID);
    xDef_SDL_Integer(&yVarP->z00010JH_FuncID);
    xDef_SDL_Integer(&yVarP->z00010JI_TempInt);
    xDef_SDL_Boolean(&yVarP->z00010JJ_ServiceActive);
    yAssF_z_ctypes_6_ShortInt(yVarP->z00010JK_StartServiceAttempt,
      SDL_INTEGER_LIT(0), XASS);
    XBETWEEN_SYMBOLS(18, 1630, 220)

/*-----
* NEXTSTATE StandBy
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1688(30,55),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(StandBy, z00010J4_StandBy, "StandBy")

/*-----
* INPUT RegisterWTA
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1694(80,55),1)
------*/
  case 1:
    XDEBUG_LABEL(StandBy_RegisterWTA)
    XAT_FIRST_SYMBOL(1, 1613)
    XOS_TRACE_INPUT("RegisterWTA")
    yAssF_z_ctypes_4_VoidStar(yVarP->z00010JA_WTA_Control,
      ((yPDef_z00011L_RegisterWTA *)ySVarP)->Param1, XASS);
    XBETWEEN_SYMBOLS(19, 1631, 239)
    {

/*-----
* ASSIGNMENT WTAUAPid := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1697(80,70),1)
------*/
      yAssF_SDL_PId(yVarP->z00010J9_WTAUAPid, SDL_SENDER, XASS);
#ifdef XTRACE
      xTraceAssign("WTAUAPid := ");
#endif
      XBETWEEN_STMTS(20, 1632, 250)

/*-----
* ASSIGNMENT ServiceActive := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1697(80,70),2)
------*/
      yAssF_SDL_Boolean(yVarP->z00010JJ_ServiceActive, SDL_False, XASS);
#ifdef XTRACE
      xTraceAssign("ServiceActive := ");
#endif
      XBETWEEN_STMTS(21, 1633, 260)

/*-----
* ASSIGNMENT StartServiceAttempt := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1697(80,70),3)
------*/
      yAssF_z_ctypes_6_ShortInt(yVarP->z00010JK_StartServiceAttempt,
        SDL_INTEGER_LIT(0), XASS);
#ifdef XTRACE
      xTraceAssign("StartServiceAttempt := ");
#endif
    }
    XBETWEEN_SYMBOLS(22, 1634, 272)

/*-----
* NEXTSTATE Idle
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1703(80,85),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(Idle, z00010J6_Idle, "Idle")

/*-----
* INPUT UnregisterWTA
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1895(130,130),1)
------*/
  case 2:
    XDEBUG_LABEL(ASTERISK_UnregisterWTA)
    XAT_FIRST_SYMBOL(2, 1614)
    XOS_TRACE_INPUT("UnregisterWTA")
    XBETWEEN_SYMBOLS(23, 1635, 289)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),2012(130,160),1)
------*/
#ifdef XTRACE
    yAssF_SDL_PId(yDcn_SDL_PId, yVarP->z00010J9_WTAUAPid, XASS);
    if (yEqF_SDL_PId(yDcn_SDL_PId, SDL_NULL)) {
#else
    if (yEqF_SDL_PId(yVarP->z00010J9_WTAUAPid, SDL_NULL)) {
#endif
#ifdef XTRACE
    xTraceDecision("PATH: PId");
#endif
      XBETWEEN_SYMBOLS(24, 1636, 304)

/*-----
* ASSIGNMENT WTAUAPid := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),2018(105,175),1)
------*/
      yAssF_SDL_PId(yVarP->z00010J9_WTAUAPid, SDL_SENDER, XASS);
#ifdef XTRACE
      xTraceAssign("WTAUAPid := ");
#endif
    } else {
#ifdef XTRACE
    xTraceDecision("ELSE");
#endif
        /* Null transition */
    }
    XBETWEEN_SYMBOLS(25, 1637, 320)

/*-----
* OUTPUT UnregisterWTADone
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1916(130,190),1)
------*/
    ALLOC_SIGNAL_NPAR(UnregisterWTADone, z00011K_UnregisterWTADone,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, UnregisterWTADone,
      z00011K_UnregisterWTADone, yVarP->z00010J9_WTAUAPid, 0,
      "UnregisterWTADone")
    XBETWEEN_SYMBOLS(26, 1638, 331)

/*-----
* NEXTSTATE StandBy
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1901(130,205),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(StandBy, z00010J4_StandBy, "StandBy")

/*-----
* INPUT TerminateWTAService
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1709(30,145),1)
------*/
  case 3:
    XDEBUG_LABEL(ASTERISK_TerminateWTAService)
    XAT_FIRST_SYMBOL(3, 1615)
    XOS_TRACE_INPUT("TerminateWTAService")
    XBETWEEN_SYMBOLS(27, 1639, 348)

/*-----
* OUTPUT DiscardContext
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1712(30,160),1)
------*/
    ALLOC_SIGNAL_NPAR(DiscardContext, z00010Z_DiscardContext, XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, DiscardContext, z00010Z_DiscardContext,
      yVarP->z00010J9_WTAUAPid, 0, "DiscardContext")

/*-----
* JOIN ServiceTermination
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(StartUp),1715(35,190),1)
------*/
    goto L_ServiceTermination;

/*-----
* INPUT WTAEvent
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1772(30,70),1)
------*/
  case 4:
    XDEBUG_LABEL(Idle_WTAEvent)
    XAT_FIRST_SYMBOL(4, 1616)
    XOS_TRACE_INPUT("WTAEvent")
    yAssF_z_ctypes_4_VoidStar(yVarP->z00010JB_EventID,
      ((yPDef_z_WTAPackage_2_WTAEvent *)ySVarP)->Param1, XASS);
    yAssF_z_ctypes_4_VoidStar(yVarP->z00010JC_EventParameters,
      ((yPDef_z_WTAPackage_2_WTAEvent *)ySVarP)->Param2, XASS);
    XBETWEEN_SYMBOLS(28, 1640, 376)

/*-----
* OUTPUT ControlOfGlobalBinding
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1778(30,85),1)
------*/
    ALLOC_SIGNAL_PAR(ControlOfGlobalBinding,
      z_WTAPackage_G_ControlOfGlobalBinding,
      yPDef_z_WTAPackage_G_ControlOfGlobalBinding)
    yAssF_z_ctypes_4_VoidStar(((yPDef_z_WTAPackage_G_ControlOfGlobalBinding *)OUTSIGNAL_DATA_PTR)->Param1,
      yVarP->z00010JB_EventID, XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, ControlOfGlobalBinding,
      z_WTAPackage_G_ControlOfGlobalBinding, TO_PROCESS(RepH_ME,
      z000407_RepH_ME), yPDef_z_WTAPackage_G_ControlOfGlobalBinding,
      "ControlOfGlobalBinding")
    XBETWEEN_SYMBOLS(29, 1641, 391)

/*-----
* NEXTSTATE CheckBinding
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1781(30,115),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(CheckBinding, z00010J8_CheckBinding, "CheckBinding")

/*-----
* INPUT InstallationResult
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1784(105,70),1)
------*/
  case 5:
    XDEBUG_LABEL(Idle_InstallationResult)
    XAT_FIRST_SYMBOL(5, 1617)
    XOS_TRACE_INPUT("InstallationResult")
    yAssF_z_WAEPackage_2Y_ResponseType(yVarP->z00010JD_ResponseData,
      ((yPDef_z_WTAPackage_H_InstallationResult *)ySVarP)->Param1, XASS);
    XBETWEEN_SYMBOLS(30, 1642, 410)

/*-----
* OUTPUT ProcessContent
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1787(105,85),1)
------*/
    ALLOC_SIGNAL_PAR(ProcessContent, z00011J_ProcessContent,
      yPDef_z00011J_ProcessContent)
    yAssF_z_WAEPackage_2Y_ResponseType(((yPDef_z00011J_ProcessContent *)OUTSIGNAL_DATA_PTR)->Param1,
      yVarP->z00010JD_ResponseData, XASSPARA);
    yAssF_z_ctypes_4_VoidStar(((yPDef_z00011J_ProcessContent *)OUTSIGNAL_DATA_PTR)->Param2,
      z_ctypes_40_Null(), XASSPARA);
    yAssF_z_ctypes_6_ShortInt(((yPDef_z00011J_ProcessContent *)OUTSIGNAL_DATA_PTR)->Param3,
      TRUE, XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, ProcessContent, z00011J_ProcessContent,
      yVarP->z00010J9_WTAUAPid, yPDef_z00011J_ProcessContent, "ProcessContent")
    XBETWEEN_SYMBOLS(31, 1643, 426)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1790(105,115),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT HandleChannelContent
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1793(155,70),1)
------*/
  case 6:
    XDEBUG_LABEL(Idle_HandleChannelContent)
    XAT_FIRST_SYMBOL(6, 1618)
    XOS_TRACE_INPUT("HandleChannelContent")
    yAssF_z_WAEPackage_2Y_ResponseType(yVarP->z00010JD_ResponseData,
      ((yPDef_z00011O_HandleChannelContent *)ySVarP)->Param1, XASS);
    XBETWEEN_SYMBOLS(32, 1644, 445)

/*-----
* OUTPUT ReqInstallation
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1796(155,100),1)
------*/
    ALLOC_SIGNAL_PAR(ReqInstallation, z_WTAPackage_F_ReqInstallation,
      yPDef_z_WTAPackage_F_ReqInstallation)
    yAssF_z_WAEPackage_2Y_ResponseType(((yPDef_z_WTAPackage_F_ReqInstallation *)OUTSIGNAL_DATA_PTR)->Param1,
      yVarP->z00010JD_ResponseData, XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, ReqInstallation,
      z_WTAPackage_F_ReqInstallation, TO_PROCESS(RepH_ME, z000407_RepH_ME),
      yPDef_z_WTAPackage_F_ReqInstallation, "ReqInstallation")
    XBETWEEN_SYMBOLS(33, 1645, 458)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1799(155,115),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT WTAExecuteService
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1958(205,70),1)
------*/
  case 7:
    XDEBUG_LABEL(Idle_WTAExecuteService)
    XAT_FIRST_SYMBOL(7, 1619)
    XOS_TRACE_INPUT("WTAExecuteService")
    yAssF_z_ctypes_4_VoidStar(yVarP->z00010JB_EventID,
      ((yPDef_z_WTAPackage_1_WTAExecuteService *)ySVarP)->Param1, XASS);
    XBETWEEN_SYMBOLS(34, 1646, 477)

/*-----
* OUTPUT ControlOfGlobalBinding
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1964(205,85),1)
------*/
    ALLOC_SIGNAL_PAR(ControlOfGlobalBinding,
      z_WTAPackage_G_ControlOfGlobalBinding,
      yPDef_z_WTAPackage_G_ControlOfGlobalBinding)
    yAssF_z_ctypes_4_VoidStar(((yPDef_z_WTAPackage_G_ControlOfGlobalBinding *)OUTSIGNAL_DATA_PTR)->Param1,
      yVarP->z00010JB_EventID, XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, ControlOfGlobalBinding,
      z_WTAPackage_G_ControlOfGlobalBinding, TO_PROCESS(RepH_ME,
      z000407_RepH_ME), yPDef_z_WTAPackage_G_ControlOfGlobalBinding,
      "ControlOfGlobalBinding")
    XBETWEEN_SYMBOLS(35, 1647, 492)
    {

/*-----
* ASSIGNMENT EventParameters := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1976(205,100),1)
------*/
      yAssF_z_ctypes_4_VoidStar(yVarP->z00010JC_EventParameters,
        z_ctypes_40_Null(), XASS);
#ifdef XTRACE
      xTraceAssign("EventParameters := ");
#endif
      XBETWEEN_STMTS(36, 1648, 504)

/*-----
* ASSIGNMENT StartServiceAttempt := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1976(205,100),2)
------*/
      yAssF_z_ctypes_6_ShortInt(yVarP->z00010JK_StartServiceAttempt,
        SDL_INTEGER_LIT(1), XASS);
#ifdef XTRACE
      xTraceAssign("StartServiceAttempt := ");
#endif
    }
    XBETWEEN_SYMBOLS(37, 1649, 516)

/*-----
* NEXTSTATE CheckBinding
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(Idle),1970(205,115),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(CheckBinding, z00010J8_CheckBinding, "CheckBinding")

/*-----
* INPUT WTAExecuteService
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1982(30,70),1)
------*/
  case 8:
    XDEBUG_LABEL(ServiceExecuting_WTAExecuteService)
    XAT_FIRST_SYMBOL(8, 1620)
    XOS_TRACE_INPUT("WTAExecuteService")
    yAssF_z_ctypes_4_VoidStar(yVarP->z00010JB_EventID,
      ((yPDef_z_WTAPackage_1_WTAExecuteService *)ySVarP)->Param1, XASS);
    XBETWEEN_SYMBOLS(38, 1650, 535)

/*-----
* OUTPUT ControlOfGlobalBinding
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1985(30,85),1)
------*/
    ALLOC_SIGNAL_PAR(ControlOfGlobalBinding,
      z_WTAPackage_G_ControlOfGlobalBinding,
      yPDef_z_WTAPackage_G_ControlOfGlobalBinding)
    yAssF_z_ctypes_4_VoidStar(((yPDef_z_WTAPackage_G_ControlOfGlobalBinding *)OUTSIGNAL_DATA_PTR)->Param1,
      yVarP->z00010JB_EventID, XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, ControlOfGlobalBinding,
      z_WTAPackage_G_ControlOfGlobalBinding, TO_PROCESS(RepH_ME,
      z000407_RepH_ME), yPDef_z_WTAPackage_G_ControlOfGlobalBinding,
      "ControlOfGlobalBinding")
    XBETWEEN_SYMBOLS(39, 1651, 550)
    {

/*-----
* ASSIGNMENT EventParameters := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1991(30,100),1)
------*/
      yAssF_z_ctypes_4_VoidStar(yVarP->z00010JC_EventParameters,
        z_ctypes_40_Null(), XASS);
#ifdef XTRACE
      xTraceAssign("EventParameters := ");
#endif
      XBETWEEN_STMTS(40, 1652, 562)

/*-----
* ASSIGNMENT StartServiceAttempt := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1991(30,100),2)
------*/
      yAssF_z_ctypes_6_ShortInt(yVarP->z00010JK_StartServiceAttempt,
        SDL_INTEGER_LIT(1), XASS);
#ifdef XTRACE
      xTraceAssign("StartServiceAttempt := ");
#endif
    }
    XBETWEEN_SYMBOLS(41, 1653, 574)

/*-----
* NEXTSTATE CheckBinding
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1988(30,160),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(CheckBinding, z00010J8_CheckBinding, "CheckBinding")

/*-----
* INPUT ServiceTerminatedFromUA
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),887(80,70),1)
------*/
  case 9:
    XDEBUG_LABEL(ServiceExecuting_ServiceTerminatedFromUA)
    XAT_FIRST_SYMBOL(9, 1621)
    XOS_TRACE_INPUT("ServiceTerminatedFromUA")

/*-----
* JOIN ServiceTermination
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1043(85,160),1)
------*/
    goto L_ServiceTermination;

/*-----
* INPUT WTAEvent
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),302(130,70),1)
------*/
  case 10:
    XDEBUG_LABEL(ServiceExecuting_WTAEvent)
    XAT_FIRST_SYMBOL(10, 1622)
    XOS_TRACE_INPUT("WTAEvent")
    yAssF_z_ctypes_4_VoidStar(yVarP->z00010JB_EventID,
      ((yPDef_z_WTAPackage_2_WTAEvent *)ySVarP)->Param1, XASS);
    yAssF_z_ctypes_4_VoidStar(yVarP->z00010JC_EventParameters,
      ((yPDef_z_WTAPackage_2_WTAEvent *)ySVarP)->Param2, XASS);
    XBETWEEN_SYMBOLS(42, 1654, 610)

/*-----
* OUTPUT ControlOfTempBind
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),308(130,85),1)
------*/
    ALLOC_SIGNAL_PAR(ControlOfTempBind, z00011I_ControlOfTempBind,
      yPDef_z00011I_ControlOfTempBind)
    yAssF_z_ctypes_4_VoidStar(((yPDef_z00011I_ControlOfTempBind *)OUTSIGNAL_DATA_PTR)->Param1,
      yVarP->z00010JB_EventID, XASSPARA);
    yAssF_z_ctypes_4_VoidStar(((yPDef_z00011I_ControlOfTempBind *)OUTSIGNAL_DATA_PTR)->Param2,
      yVarP->z00010JC_EventParameters, XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, ControlOfTempBind,
      z00011I_ControlOfTempBind, yVarP->z00010J9_WTAUAPid,
      yPDef_z00011I_ControlOfTempBind, "ControlOfTempBind")
    XBETWEEN_SYMBOLS(43, 1655, 625)

/*-----
* NEXTSTATE CheckBinding
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),305(130,160),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(CheckBinding, z00010J8_CheckBinding, "CheckBinding")

/*-----
* INPUT InstallationResult
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1313(355,70),1)
------*/
  case 11:
    XDEBUG_LABEL(ServiceExecuting_InstallationResult)
    XAT_FIRST_SYMBOL(11, 1623)
    XOS_TRACE_INPUT("InstallationResult")
    yAssF_z_WAEPackage_2Y_ResponseType(yVarP->z00010JD_ResponseData,
      ((yPDef_z_WTAPackage_H_InstallationResult *)ySVarP)->Param1, XASS);
    XBETWEEN_SYMBOLS(44, 1656, 644)

/*-----
* OUTPUT ProcessContent
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1316(355,85),1)
------*/
    ALLOC_SIGNAL_PAR(ProcessContent, z00011J_ProcessContent,
      yPDef_z00011J_ProcessContent)
    yAssF_z_WAEPackage_2Y_ResponseType(((yPDef_z00011J_ProcessContent *)OUTSIGNAL_DATA_PTR)->Param1,
      yVarP->z00010JD_ResponseData, XASSPARA);
    yAssF_z_ctypes_4_VoidStar(((yPDef_z00011J_ProcessContent *)OUTSIGNAL_DATA_PTR)->Param2,
      z_ctypes_40_Null(), XASSPARA);
    yAssF_z_ctypes_6_ShortInt(((yPDef_z00011J_ProcessContent *)OUTSIGNAL_DATA_PTR)->Param3,
      TRUE, XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, ProcessContent, z00011J_ProcessContent,
      yVarP->z00010J9_WTAUAPid, yPDef_z00011J_ProcessContent, "ProcessContent")

/*-----
* JOIN ServiceInitiation
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1514(360,160),1)
------*/
    goto L_ServiceInitiation;

/*-----
* INPUT HandleChannelContent
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1322(405,70),1)
------*/
  case 12:
    XDEBUG_LABEL(ServiceExecuting_HandleChannelContent)
    XAT_FIRST_SYMBOL(12, 1624)
    XOS_TRACE_INPUT("HandleChannelContent")
    yAssF_z_WAEPackage_2Y_ResponseType(yVarP->z00010JD_ResponseData,
      ((yPDef_z00011O_HandleChannelContent *)ySVarP)->Param1, XASS);
    XBETWEEN_SYMBOLS(45, 1657, 677)

/*-----
* OUTPUT ReqInstallation
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1325(405,85),1)
------*/
    ALLOC_SIGNAL_PAR(ReqInstallation, z_WTAPackage_F_ReqInstallation,
      yPDef_z_WTAPackage_F_ReqInstallation)
    yAssF_z_WAEPackage_2Y_ResponseType(((yPDef_z_WTAPackage_F_ReqInstallation *)OUTSIGNAL_DATA_PTR)->Param1,
      yVarP->z00010JD_ResponseData, XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, ReqInstallation,
      z_WTAPackage_F_ReqInstallation, TO_PROCESS(RepH_ME, z000407_RepH_ME),
      yPDef_z_WTAPackage_F_ReqInstallation, "ReqInstallation")
    XBETWEEN_SYMBOLS(46, 1658, 690)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceExecuting),1328(405,160),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT ControlOfTempBindResult
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),458(55,55),1)
------*/
  case 13:
    XDEBUG_LABEL(CheckBinding_ControlOfTempBindResult)
    XAT_FIRST_SYMBOL(13, 1625)
    XOS_TRACE_INPUT("ControlOfTempBindResult")
    yAssF_SDL_Integer(yVarP->z00010JI_TempInt,
      ((yPDef_z00011N_ControlOfTempBindResult *)ySVarP)->Param1, XASS);
    XBETWEEN_SYMBOLS(59, 1671, 709)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),461(55,70),1)
------*/
    yAssF_SDL_Integer(yDcn_SDL_Integer, yVarP->z00010JI_TempInt, XASS);
    if (yEqF_SDL_Integer(yDcn_SDL_Integer, TRUE)) {
#ifdef XTRACE
    xTraceDecision("PATH: #CODE");
#endif
      XBETWEEN_SYMBOLS(60, 1672, 720)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),470(30,85),1)
------*/
#ifdef XTRACE
      xTraceTask(" ");
#endif
WTAa_processedByAService(TRUE);
SDL_Free(& yVarP->z00010JB_EventID);
yVarP->z00010JC_EventParameters = NULL;

      XBETWEEN_SYMBOLS(61, 1673, 733)

/*-----
* NEXTSTATE ServiceExecuting
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),464(30,145),1)
------*/
      XAT_LAST_SYMBOL
      SDL_NEXTSTATE(ServiceExecuting, z00010J7_ServiceExecuting,
        "ServiceExecuting")
    } else if (yEqF_SDL_Integer(yDcn_SDL_Integer, FALSE)) {
#ifdef XTRACE
    xTraceDecision("PATH: #CODE");
#endif
      XBETWEEN_SYMBOLS(62, 1674, 746)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),1091(105,85),1)
------*/
#ifdef XTRACE
      xTraceTask(" ");
#endif
yVarP->z00010JI_TempInt=TRUE;
if (yVarP->z00010JA_WTA_Control)
{
  yVarP->z00010JI_TempInt = ( (WTACONTROL*)(yVarP->
  z00010JA_WTA_Control) )->fContextProtected;
}

      XBETWEEN_SYMBOLS(63, 1675, 762)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),917(105,100),1)
------*/
      yAssF_SDL_Integer(yDcn_SDL_Integer, yVarP->z00010JI_TempInt, XASS);
      if (yEqF_SDL_Integer(yDcn_SDL_Integer, TRUE)) {
#ifdef XTRACE
      xTraceDecision("PATH: #CODE");
#endif
        XBETWEEN_SYMBOLS(64, 1676, 773)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),929(80,115),1)
------*/
#ifdef XTRACE
        xTraceTask(" ");
#endif
WTAa_processedByAService(FALSE);
SDL_Free(& yVarP->z00010JB_EventID);
SDL_DeleteParameters(& yVarP->z00010JC_EventParameters);


/*-----
* JOIN MMIFallback
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),1640(85,145),1)
------*/
        goto L_MMIFallback;
      } else if (yEqF_SDL_Integer(yDcn_SDL_Integer, FALSE)) {
#ifdef XTRACE
      xTraceDecision("PATH: #CODE");
#endif
        XBETWEEN_SYMBOLS(65, 1677, 796)

/*-----
* OUTPUT ControlOfGlobalBinding
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),467(130,115),1)
------*/
        ALLOC_SIGNAL_PAR(ControlOfGlobalBinding,
          z_WTAPackage_G_ControlOfGlobalBinding,
          yPDef_z_WTAPackage_G_ControlOfGlobalBinding)
        yAssF_z_ctypes_4_VoidStar(((yPDef_z_WTAPackage_G_ControlOfGlobalBinding *)OUTSIGNAL_DATA_PTR)->Param1,
          yVarP->z00010JB_EventID, XASSPARA);
        SDL_OUTP_PAR(xDefaultPrioSignal, ControlOfGlobalBinding,
          z_WTAPackage_G_ControlOfGlobalBinding, TO_PROCESS(RepH_ME,
          z000407_RepH_ME), yPDef_z_WTAPackage_G_ControlOfGlobalBinding,
          "ControlOfGlobalBinding")
        XBETWEEN_SYMBOLS(66, 1678, 811)
        {

/*-----
* ASSIGNMENT EventID := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),791(130,130),1)
------*/
          yAssF_z_ctypes_4_VoidStar(yVarP->z00010JB_EventID,
            z_ctypes_40_Null(), XASS);
#ifdef XTRACE
          xTraceAssign("EventID := ");
#endif
          XBETWEEN_STMTS(67, 1679, 823)

/*-----
* ASSIGNMENT ServiceActive := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),791(130,130),2)
------*/
          yAssF_SDL_Boolean(yVarP->z00010JJ_ServiceActive, SDL_True, XASS);
#ifdef XTRACE
          xTraceAssign("ServiceActive := ");
#endif
        }
        XBETWEEN_SYMBOLS(68, 1680, 834)

/*-----
* NEXTSTATE CheckBinding
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),473(130,145),1)
------*/
        XAT_LAST_SYMBOL
        SDL_NEXTSTATE(CheckBinding, z00010J8_CheckBinding, "CheckBinding")
      }
#ifdef XEDECISION
      else {
        XDECISION_ERROR
      }
#endif
    }
#ifdef XEDECISION
    else {
      XDECISION_ERROR
    }
#endif

/*-----
* INPUT GlobalBindingResult
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),482(205,55),1)
------*/
  case 14:
    XDEBUG_LABEL(CheckBinding_GlobalBindingResult)
    XAT_FIRST_SYMBOL(14, 1626)
    XOS_TRACE_INPUT("GlobalBindingResult")
    yAssF_SDL_Integer(yVarP->z00010JI_TempInt,
      ((yPDef_z_WTAPackage_I_GlobalBindingResult *)ySVarP)->Param1, XASS);
    yAssF_z_WAEPackage_2Y_ResponseType(yVarP->z00010JD_ResponseData,
      ((yPDef_z_WTAPackage_I_GlobalBindingResult *)ySVarP)->Param2, XASS);
    XBETWEEN_SYMBOLS(69, 1681, 867)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),491(205,70),1)
------*/
    yAssF_SDL_Integer(yDcn_SDL_Integer, yVarP->z00010JI_TempInt, XASS);
    if (yEqF_SDL_Integer(yDcn_SDL_Integer, FALSE)) {
#ifdef XTRACE
    xTraceDecision("PATH: #CODE");
#endif
      XBETWEEN_SYMBOLS(70, 1682, 878)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),497(180,85),1)
------*/
#ifdef XTRACE
      xTraceTask(" ");
#endif
if (!yVarP->z00010JK_StartServiceAttempt)
  WTAa_processedByAService(FALSE);
yVarP->z00010JK_StartServiceAttempt = 0;
SDL_DeleteParameters(& yVarP->z00010JC_EventParameters);


/*-----
* JOIN MMIFallback
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),1616(185,145),1)
------*/
      goto L_MMIFallback;
    } else if (yEqF_SDL_Integer(yDcn_SDL_Integer, TRUE)) {
#ifdef XTRACE
    xTraceDecision("PATH: #CODE");
#endif
      XBETWEEN_SYMBOLS(71, 1683, 902)

/*-----
* OUTPUT ProcessContent
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),485(230,85),1)
------*/
      ALLOC_SIGNAL_PAR(ProcessContent, z00011J_ProcessContent,
        yPDef_z00011J_ProcessContent)
      yAssF_z_WAEPackage_2Y_ResponseType(((yPDef_z00011J_ProcessContent *)OUTSIGNAL_DATA_PTR)->Param1,
        yVarP->z00010JD_ResponseData, XASSPARA);
      yAssF_z_ctypes_4_VoidStar(((yPDef_z00011J_ProcessContent *)OUTSIGNAL_DATA_PTR)->Param2,
        yVarP->z00010JC_EventParameters, XASSPARA);
      yAssF_z_ctypes_6_ShortInt(((yPDef_z00011J_ProcessContent *)OUTSIGNAL_DATA_PTR)->Param3,
        TRUE, XASSPARA);
      SDL_OUTP_PAR(xDefaultPrioSignal, ProcessContent, z00011J_ProcessContent,
        yVarP->z00010J9_WTAUAPid, yPDef_z00011J_ProcessContent,
        "ProcessContent")
      XBETWEEN_SYMBOLS(72, 1684, 919)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),488(230,100),1)
------*/
#ifdef XTRACE
      xTraceTask(" ");
#endif
if (!yVarP->z00010JK_StartServiceAttempt)
  WTAa_processedByAService(TRUE);
yVarP->z00010JK_StartServiceAttempt = 0;
yVarP->z00010JC_EventParameters = NULL;


/*-----
* JOIN ServiceInitiation
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),1511(235,145),1)
------*/
      goto L_ServiceInitiation;
    }
#ifdef XEDECISION
    else {
      XDECISION_ERROR
    }
#endif

/*-----
* INPUT ServiceTerminatedFromUA
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),869(280,55),1)
------*/
  case 15:
    XDEBUG_LABEL(CheckBinding_ServiceTerminatedFromUA)
    XAT_FIRST_SYMBOL(15, 1627)
    XOS_TRACE_INPUT("ServiceTerminatedFromUA")

/*-----
* JOIN ServiceTermination
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),998(285,145),1)
------*/
    goto L_ServiceTermination;

/*-----
* INPUT ControlOfTempBindResult
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),950(130,190),1)
------*/
  case 16:
    XDEBUG_LABEL(ASTERISK_ControlOfTempBindResult)
    XAT_FIRST_SYMBOL(16, 1628)
    XOS_TRACE_INPUT("ControlOfTempBindResult")
    yAssF_SDL_Integer(yVarP->z00010JI_TempInt,
      ((yPDef_z00011N_ControlOfTempBindResult *)ySVarP)->Param1, XASS);

  L_grst332:
    XBETWEEN_SYMBOLS(73, 1685, 973)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),968(155,205),1)
------*/
#ifdef XTRACE
    xTraceTask(" ");
#endif
SDL_Free(& yVarP->z00010JB_EventID);
SDL_DeleteParameters(& yVarP->z00010JC_EventParameters);

    XBETWEEN_SYMBOLS(74, 1686, 985)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),980(155,220),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT GlobalBindingResult
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),953(180,190),1)
------*/
  case 17:
    XDEBUG_LABEL(ASTERISK_GlobalBindingResult)
    XAT_FIRST_SYMBOL(17, 1629)
    XOS_TRACE_INPUT("GlobalBindingResult")
    yAssF_SDL_Integer(yVarP->z00010JI_TempInt,
      ((yPDef_z_WTAPackage_I_GlobalBindingResult *)ySVarP)->Param1, XASS);
    yAssF_z_WAEPackage_2Y_ResponseType(yVarP->z00010JD_ResponseData,
      ((yPDef_z_WTAPackage_I_GlobalBindingResult *)ySVarP)->Param2, XASS);

/*-----
* JOIN grst332
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(CheckBinding),968(155,205),1)
------*/
    goto L_grst332;

  L_ServiceTermination:
    XBETWEEN_SYMBOLS(47, 1659, 1014)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1538(30,85),1)
------*/
#ifdef XTRACE
    xTraceTask(" ");
#endif
SDL_TerminateService(yVarP->z00010JA_WTA_Control);

    XBETWEEN_SYMBOLS(48, 1660, 1025)
    {

/*-----
* ASSIGNMENT ServiceActive := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1649(30,100),1)
------*/
      yAssF_SDL_Boolean(yVarP->z00010JJ_ServiceActive, SDL_False, XASS);
#ifdef XTRACE
      xTraceAssign("ServiceActive := ");
#endif
      XBETWEEN_STMTS(49, 1661, 1036)

/*-----
* ASSIGNMENT StartServiceAttempt := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1649(30,100),2)
------*/
      yAssF_z_ctypes_6_ShortInt(yVarP->z00010JK_StartServiceAttempt,
        SDL_INTEGER_LIT(0), XASS);
#ifdef XTRACE
      xTraceAssign("StartServiceAttempt := ");
#endif
    }
    XBETWEEN_SYMBOLS(50, 1662, 1048)

/*-----
* NEXTSTATE Idle
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1544(30,130),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(Idle, z00010J6_Idle, "Idle")

  L_ServiceInitiation:
    XBETWEEN_SYMBOLS(51, 1663, 1058)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1568(105,70),1)
------*/
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z00010JJ_ServiceActive, XASS);
    if (yDcn_SDL_Boolean) {
#else
    if (yVarP->z00010JJ_ServiceActive) {
#endif
#ifdef XTRACE
    xTraceDecision("TRUE");
#endif
      XBETWEEN_SYMBOLS(52, 1664, 1073)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1589(130,85),1)
------*/
#ifdef XTRACE
      xTraceTask(" ");
#endif
SDL_TerminateService( yVarP->z00010JA_WTA_Control );

    } else {
#ifdef XTRACE
    xTraceDecision("FALSE");
#endif
        /* Null transition */
    }
    XBETWEEN_SYMBOLS(53, 1665, 1090)
    {

/*-----
* ASSIGNMENT ServiceActive := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1604(105,100),1)
------*/
      yAssF_SDL_Boolean(yVarP->z00010JJ_ServiceActive, SDL_True, XASS);
#ifdef XTRACE
      xTraceAssign("ServiceActive := ");
#endif
    }
    XBETWEEN_SYMBOLS(54, 1666, 1102)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1655(105,115),1)
------*/
#ifdef XTRACE
    xTraceTask(" ");
#endif
if (yVarP->z00010JA_WTA_Control)
  yVarP->z00010JI_TempInt = ( (WTACONTROL*)(yVarP->
  z00010JA_WTA_Control) )->iViewID;

MMIa_status( (UINT8)yVarP->z00010JI_TempInt, WTAServiceStarted, NULL );


    XBETWEEN_SYMBOLS(55, 1667, 1118)

/*-----
* NEXTSTATE ServiceExecuting
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1583(105,130),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(ServiceExecuting, z00010J7_ServiceExecuting,
      "ServiceExecuting")

  L_MMIFallback:
    XBETWEEN_SYMBOLS(56, 1668, 1129)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1619(80,175),1)
------*/
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z00010JJ_ServiceActive, XASS);
    if (yDcn_SDL_Boolean) {
#else
    if (yVarP->z00010JJ_ServiceActive) {
#endif
#ifdef XTRACE
    xTraceDecision("TRUE");
#endif
      XBETWEEN_SYMBOLS(58, 1670, 1144)

/*-----
* NEXTSTATE ServiceExecuting
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1625(105,190),1)
------*/
      XAT_LAST_SYMBOL
      SDL_NEXTSTATE(ServiceExecuting, z00010J7_ServiceExecuting,
        "ServiceExecuting")
    } else {
#ifdef XTRACE
    xTraceDecision("FALSE");
#endif
      XBETWEEN_SYMBOLS(57, 1669, 1157)

/*-----
* NEXTSTATE Idle
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wae\wml\wta_if.spr(ServiceToggle),1622(55,190),1)
------*/
      XAT_LAST_SYMBOL
      SDL_NEXTSTATE(Idle, z00010J6_Idle, "Idle")
    }
  }
  END_PAD(yPAD_z00010J_WTA_IF)
}
