/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#define C_MICRO_1_3
#include "ml_typw.h"
#include "ctypes.h"
#include "buffmgt.h"
#include "glbldecl.h"
#include "wdp_ul.h"
#include "wtlspckg.h"
#include "wtls_wdp.h"
#include "wdppckg.h"
#include "wdp_udp.h"
#include "wspcmwtp.h"
#include "wtppckg.h"
#include "wtp_wdp.h"
#include "sptp_tls.h"
#include "wspclwdp.h"
#include "waepckg.h"
#include "wtapckg.h"
#include "pushpckg.h"
#include "wae_wsp.h"
#include "stackmgr.h"
#include "wap.h"

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PROCESS WDPhandler
* <<SYSTEM WAP/BLOCK WDP>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z59_WDPhandler)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),872(30,20),2) */
    z_ctypes_4_VoidStar  z598_UDPData;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),872(30,20),3) */
    DeviceAddress  z599_dstAddr;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),872(30,20),3) */
    DeviceAddress  z59A_srcAddr;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),872(30,20),4) */
    pdubuf_ptr  z59B_tmpBuf;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),2) */
    SDL_Integer  z59C_srcPort;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),2) */
    SDL_Integer  z59D_dstPort;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),3) */
    SDL_Natural  z59E_DataLen;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),3) */
    SDL_Natural  z59F_FaultCode;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),4) */
    SDL_Boolean  z59G_ok;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),239(30,65),2) */
    TDUnitdataReqType  z59H_dataReq;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),239(30,65),3) */
    TDUnitdataIndType  z59I_dataInd;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),2) */
    SDL_Integer  z59J_port;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),3) */
    SDL_PId  z59K_upperlayerPId;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),4) */
    SDL_Natural  z59L_stackconfig;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),5) */
    SDL_Octet  z59M_bearer;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),6) */
    SDL_Octet  z59N_viewID;
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),7) */
    SDL_Octet  z59O_channelID;
    SDL_Octet  yDcn_SDL_Octet;
} yVDef_z59_WDPhandler;
#define z596_AwaitStart  1
#define z597_IDLE  2

/*****
* PROCESS WDPmanagement
* <<SYSTEM WAP/BLOCK WDP>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z5A_WDPmanagement)
typedef struct {
    PROCESS_VARS
} yVDef_z5A_WDPmanagement;
#define z5A0_AwaitStartWDP  1
#define z5A1_AwaitReady  2
#define z5A2_AwaitWDPhReady  3
#define z5A3_AwaitReassembleReady  4
#define z5A4_idle  5
#define z5A5_AwaitTerminated  6
#define z5A6_AwaitWDPhTerminated  7
#define z5A7_AwaitReassembleTerminated  8

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
                /* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),4) */
#include "wdpsuppt.h"
#include "capiclnt.h"
#include "dbfunct.h"
#include "wipdb.h"


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PROCESS WDPhandler
* <<SYSTEM WAP/BLOCK WDP>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr,4,1)
******/

/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
** Tables for process WDPhandler
** #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr,4,1)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

/*--------------Instance Data---------------*/
#define X_MAX_INST_z59_WDPhandler 1
static yVDef_z59_WDPhandler *yINSTD_z59_WDPhandler[X_MAX_INST_z59_WDPhandler];

/*--------------Process State---------------*/
static xSTATE yPSTATETBL_z59_WDPhandler[X_MAX_INST_z59_WDPhandler] = {
  XSTARTUP
};

/*---------------State Index----------------*/
static XCONST xSITBL xSTATE_INDEX_z59_WDPhandler[3] = {0, 3, 9};

/*---------------Transition-----------------*/
#define XMAX_TRANS_z59_WDPhandler 9
static XCONST xTR_TABLE_ENTRY yTRTBL_z59_WDPhandler[XMAX_TRANS_z59_WDPhandler] = {

    /* AwaitStart */
  XMK_B z_WDP_UpperLayer_1_OpenPort, XSAVEID XMK_E,
  XMK_B z_WDPPckg_0_StartWDPh, 1 XMK_E,
  XMK_B z_WDPPckg_3_TerminateWDPh, 2 XMK_E

    /* IDLE */,
  XMK_B z_WDP_UpperLayer_0_TDUnitdataReq, 3 XMK_E,
  XMK_B z_Global_Declarations_0_ClosePort, 4 XMK_E,
  XMK_B z_WDP_UpperLayer_1_OpenPort, 5 XMK_E,
  XMK_B z_WDPPckg_3_TerminateWDPh, 6 XMK_E,
  XMK_B z_WDP_UDP_1_RecUDPDatagram, 8 XMK_E,
  XMK_B z_WDP_UDP_2_UDPErrorInd, 7 XMK_E
};

/*-----------Process-PID-Values-------------*/
#ifdef XMK_USE_PID_ADDRESSING
static xPIDTable yPID_TBL_z59_WDPhandler[X_MAX_INST_z59_WDPhandler];
#endif

/*-----------Process Description------------*/
#define X_PRIO_z59_WDPhandler  xDefaultPrioProcess
XCONST XPDTBL yPDTBL_z59_WDPhandler = {
#ifdef XMK_USE_PID_ADDRESSING
  yPID_TBL_z59_WDPhandler,
#endif
  (xINSTD *)yINSTD_z59_WDPhandler,
  sizeof(yVDef_z59_WDPhandler),
  X_MAX_INST_z59_WDPhandler,
#ifdef XMK_USE_TIMESLICE
  X_TIMESLICE_z59_WDPhandler,
#endif
#ifdef XMK_USE_PREEMPTIVE
  X_PRIO_z59_WDPhandler,
#endif
  (xmk_T_TRANS_ADDRESS) yPAD_z59_WDPhandler,
  yTRTBL_z59_WDPhandler,
  xSTATE_INDEX_z59_WDPhandler,
  yPSTATETBL_z59_WDPhandler
};

/*+++++
* Function for process WDPhandler
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr,4,1)
++++++*/
YPAD_FUNCTION(yPAD_z59_WDPhandler)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z59_WDPhandler)
  YPAD_TEMP_VARS
  /* INTEGRATION: commented out statement */
  /* SDL_Integer  yDcn_SDL_Integer; */
  /* INTEGRATION: commented out statement */
  /* SDL_Boolean  yDcn_SDL_Boolean; */
  YPRSNAME_VAR("WDPhandler")

  BEGIN_PAD
  switch (XSYMBOLNUMBER) {

/*-----
* START
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1763(55,25),1)
------*/
  case 0:
    BEGIN_START_TRANSITION
    XAT_FIRST_SYMBOL(0, 7706)
    yDef_z_ctypes_4_VoidStar(&yVarP->z598_UDPData);
    yDef_DeviceAddress(&yVarP->z599_dstAddr);
    yDef_DeviceAddress(&yVarP->z59A_srcAddr);
    yDef_pdubuf_ptr(&yVarP->z59B_tmpBuf);
    xDef_SDL_Integer(&yVarP->z59C_srcPort);
    xDef_SDL_Integer(&yVarP->z59D_dstPort);
    xDef_SDL_Natural(&yVarP->z59E_DataLen);
    xDef_SDL_Natural(&yVarP->z59F_FaultCode);
    xDef_SDL_Boolean(&yVarP->z59G_ok);
    yDef_TDUnitdataReqType(&yVarP->z59H_dataReq);
    yDef_TDUnitdataIndType(&yVarP->z59I_dataInd);
    xDef_SDL_Integer(&yVarP->z59J_port);
    xDef_SDL_PId(&yVarP->z59K_upperlayerPId);
    xDef_SDL_Natural(&yVarP->z59L_stackconfig);
    xDef_SDL_Octet(&yVarP->z59M_bearer);
    xDef_SDL_Octet(&yVarP->z59N_viewID);
    xDef_SDL_Octet(&yVarP->z59O_channelID);
    XBETWEEN_SYMBOLS(9, 7715, 224)

/*-----
* NEXTSTATE AwaitStart
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1766(55,40),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitStart, z596_AwaitStart, "AwaitStart")

/*-----
* INPUT StartWDPh
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1772(55,80),1)
------*/
  case 1:
    XDEBUG_LABEL(AwaitStart_StartWDPh)
    XAT_FIRST_SYMBOL(1, 7707)
    XOS_TRACE_INPUT("StartWDPh")
    XBETWEEN_SYMBOLS(10, 7716, 241)
    {

/*-----
* CALL wdp_porttbl_init
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),3815(55,95),1)
------*/
#ifdef XTRACE
      xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_init");
#endif
#ifdef XMSCE
      xMSCETask("CALL EXTERNAL wdp_porttbl_init");
#endif
      wdp_porttbl_init();
    }
    XBETWEEN_SYMBOLS(11, 7717, 256)
    {

/*-----
* CALL wdp_address_init
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),4010(55,110),1)
------*/
#ifdef XTRACE
      xTraceAlg("CALL EXTERNAL PROCEDURE wdp_address_init");
#endif
#ifdef XMSCE
      xMSCETask("CALL EXTERNAL wdp_address_init");
#endif
      wdp_address_init();
    }
    XBETWEEN_SYMBOLS(12, 7718, 271)

/*-----
* OUTPUT WDPhReady
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\startanswer.smc(1),281(80,40),1)
------*/
    ALLOC_SIGNAL_NPAR(WDPhReady, z_WDPPckg_9_WDPhReady, XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, WDPhReady, z_WDPPckg_9_WDPhReady,
      TO_PROCESS(WDPmanagement, z5A_WDPmanagement), 0, "WDPhReady")
    XBETWEEN_SYMBOLS(13, 7719, 280)

/*-----
* OUTPUT SegmentationReady
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\startanswer.smc(1),287(80,55),1)
------*/
    ALLOC_SIGNAL_NPAR(SegmentationReady, z_WDPPckg_A_SegmentationReady,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, SegmentationReady,
      z_WDPPckg_A_SegmentationReady, TO_PROCESS(WDPmanagement,
      z5A_WDPmanagement), 0, "SegmentationReady")
    XBETWEEN_SYMBOLS(14, 7720, 291)

/*-----
* OUTPUT ReassembleReady
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\startanswer.smc(1),293(80,70),1)
------*/
    ALLOC_SIGNAL_NPAR(ReassembleReady, z_WDPPckg_B_ReassembleReady,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, ReassembleReady,
      z_WDPPckg_B_ReassembleReady, TO_PROCESS(WDPmanagement,
      z5A_WDPmanagement), 0, "ReassembleReady")
    XBETWEEN_SYMBOLS(15, 7721, 302)

/*-----
* NEXTSTATE IDLE
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1793(55,140),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(IDLE, z597_IDLE, "IDLE")

/*-----
* INPUT TerminateWDPh
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1796(95,80),1)
------*/
  case 2:
    XDEBUG_LABEL(AwaitStart_TerminateWDPh)
    XAT_FIRST_SYMBOL(2, 7708)
    XOS_TRACE_INPUT("TerminateWDPh")
    XBETWEEN_SYMBOLS(16, 7722, 319)
    {

/*-----
* CALL wdp_porttbl_clear
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),3821(95,95),1)
------*/
#ifdef XTRACE
      xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_clear");
#endif
#ifdef XMSCE
      xMSCETask("CALL EXTERNAL wdp_porttbl_clear");
#endif
      wdp_porttbl_clear();
    }
    XBETWEEN_SYMBOLS(17, 7723, 334)

/*-----
* OUTPUT WDPhTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),305(80,40),1)
------*/
    ALLOC_SIGNAL_NPAR(WDPhTerminated, z_WDPPckg_6_WDPhTerminated,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, WDPhTerminated,
      z_WDPPckg_6_WDPhTerminated, TO_PROCESS(WDPmanagement, z5A_WDPmanagement),
      0, "WDPhTerminated")
    XBETWEEN_SYMBOLS(18, 7724, 345)

/*-----
* OUTPUT SegmentationTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),287(80,55),1)
------*/
    ALLOC_SIGNAL_NPAR(SegmentationTerminated,
      z_WDPPckg_8_SegmentationTerminated, XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, SegmentationTerminated,
      z_WDPPckg_8_SegmentationTerminated, TO_PROCESS(WDPmanagement,
      z5A_WDPmanagement), 0, "SegmentationTerminated")
    XBETWEEN_SYMBOLS(19, 7725, 356)

/*-----
* OUTPUT ReassembleTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),293(80,70),1)
------*/
    ALLOC_SIGNAL_NPAR(ReassembleTerminated, z_WDPPckg_7_ReassembleTerminated,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, ReassembleTerminated,
      z_WDPPckg_7_ReassembleTerminated, TO_PROCESS(WDPmanagement,
      z5A_WDPmanagement), 0, "ReassembleTerminated")
    XBETWEEN_SYMBOLS(20, 7726, 367)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1799(95,130),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT TDUnitdataReq
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),128(75,60),1)
------*/
  case 3:
    XDEBUG_LABEL(IDLE_TDUnitdataReq)
    XAT_FIRST_SYMBOL(3, 7709)
    XOS_TRACE_INPUT("TDUnitdataReq")
    yAssF_TDUnitdataReqType(yVarP->z59H_dataReq,
      ((yPDef_z_WDP_UpperLayer_0_TDUnitdataReq *)ySVarP)->Param1, XASS);
    yAssF_SDL_PId(yVarP->z59K_upperlayerPId,
      ((yPDef_z_WDP_UpperLayer_0_TDUnitdataReq *)ySVarP)->Param2, XASS);
    yAssF_SDL_Natural(yVarP->z59L_stackconfig, yTstA_SDL_Natural(
      ((yPDef_z_WDP_UpperLayer_0_TDUnitdataReq *)ySVarP)->Param3), XASS);
    XBETWEEN_SYMBOLS(21, 7727, 390)

/*-----
* TASK log internal
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),3191(75,75),1)
------*/
#ifdef XTRACE
    xTraceTask("log internal");
#endif
#if defined LOG_INTERNAL
{
char *logstr;
char *strPDU;
char *strparam1;

logstr = OctetString2HexString(yVarP->
  z59H_dataReq.SourceAddress.Address.data, yVarP->
  z59H_dataReq.SourceAddress.Address.length);
CLNTa_log(0, 0, "WDP Receive TDUnitDataReq: Source Address = %s\n", logstr);
OSConnectorFree(logstr);

logstr = OctetString2HexString(yVarP->
  z59H_dataReq.SourceAddress.SecondAddress.data, yVarP->
  z59H_dataReq.SourceAddress.SecondAddress.length);
CLNTa_log(0, 0, "WDP Receive TDUnitDataReq: Source SecondAddress = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: Source Bearer = %d\n", yVarP->
  z59H_dataReq.SourceAddress.Bearer);

CLNTa_log(0, 0, "WDP: Source SecondAddressFormat= %d\n", yVarP->
  z59H_dataReq.SourceAddress.SecondAddressFormat);

CLNTa_log(0, 0, "WDP: Source PortNumber = %d\n", yVarP->
  z59H_dataReq.SourceAddress.PortNumber);

logstr = OctetString2HexString(yVarP->
  z59H_dataReq. DestinationAddress.Address.data, yVarP->
  z59H_dataReq. DestinationAddress.Address.length);
CLNTa_log(0, 0, "WDP Receive TDUnitDataReq: Destination Address = %s\n", logstr);
OSConnectorFree(logstr);

logstr = OctetString2HexString(yVarP->
  z59H_dataReq. DestinationAddress.SecondAddress.data, yVarP->
  z59H_dataReq. DestinationAddress.SecondAddress.length);
CLNTa_log(0, 0, "WDP Receive TDUnitDataReq: Destination SecondAddress = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: DesinationBearer = %d\n", yVarP->
  z59H_dataReq.DestinationAddress.Bearer);

CLNTa_log(0, 0, "WDP: DesinationSecondAddressFormat= %d\n", yVarP->
  z59H_dataReq.DestinationAddress.SecondAddressFormat);

CLNTa_log(0, 0, "WDP: DesinationPortNumber = %d\n", yVarP->
  z59H_dataReq.DestinationAddress.PortNumber);

CLNTa_log(0, 0, "WDP: StackConfig = %d\n", yVarP->z59L_stackconfig);

strPDU = pdubuf_getStart( yVarP->z59H_dataReq.UserData );
strparam1 = OctetString2HexString((CHAR*)strPDU,pdubuf_getLength(yVarP->
  z59H_dataReq.UserData));

CLNTa_log(0,0, "WDP data %s\n", strparam1?strparam1:"");
DEALLOC(&strparam1);
}
#endif

    XBETWEEN_SYMBOLS(22, 7728, 458)

/*-----
* ASSIGNMENT srcAddr := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),2525(75,90),1)
------*/
    yAssF_DeviceAddress(yVarP->z59A_srcAddr, yVarP->z59H_dataReq.SourceAddress.
      Address, XASS);
#ifdef XTRACE
    xTraceAssign("srcAddr := ");
#endif
    XBETWEEN_SYMBOLS(23, 7729, 469)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),599(75,105),1)
------*/
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean,
      xAnd_SDL_Boolean((xLT_SDL_Integer(z_WDPPckg_N_MinDestPortNo, yVarP->
      z59H_dataReq.DestinationAddress.PortNumber)), (xLT_SDL_Integer(yVarP->
      z59H_dataReq.DestinationAddress.PortNumber, z_WDPPckg_O_MaxDestPortNo))),
      XASS);
    if (yDcn_SDL_Boolean) {
#else
    if (xAnd_SDL_Boolean((xLT_SDL_Integer(z_WDPPckg_N_MinDestPortNo, yVarP->
      z59H_dataReq.DestinationAddress.PortNumber)), (xLT_SDL_Integer(yVarP->
      z59H_dataReq.DestinationAddress.PortNumber,
      z_WDPPckg_O_MaxDestPortNo)))) {
#endif
#ifdef XTRACE
    xTraceDecision("TRUE");
#endif
      XBETWEEN_SYMBOLS(24, 7730, 491)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),617(75,125),1)
------*/
#ifdef XTRACE
      yAssF_SDL_Boolean(yDcn_SDL_Boolean,
        xAnd_SDL_Boolean((xLE_SDL_Integer(z_WDPPckg_L_MinSourcePortNo, yVarP->
        z59H_dataReq.SourceAddress.PortNumber)), (xLT_SDL_Integer(yVarP->
        z59H_dataReq.SourceAddress.PortNumber, z_WDPPckg_M_MaxSourcePortNo))),
        XASS);
      if (yDcn_SDL_Boolean) {
#else
      if (xAnd_SDL_Boolean((xLE_SDL_Integer(z_WDPPckg_L_MinSourcePortNo, yVarP->
        z59H_dataReq.SourceAddress.PortNumber)), (xLT_SDL_Integer(yVarP->
        z59H_dataReq.SourceAddress.PortNumber, z_WDPPckg_M_MaxSourcePortNo)))) {
#endif
#ifdef XTRACE
      xTraceDecision("TRUE");
#endif
        XBETWEEN_SYMBOLS(25, 7731, 512)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),635(75,145),1)
------*/
#ifdef XTRACE
        yAssF_SDL_Integer(yDcn_SDL_Integer, devaddr_getlen(&(yVarP->
          z59H_dataReq.DestinationAddress.Address)), XASS);
        if (yEqF_SDL_Integer(yDcn_SDL_Integer, SDL_INTEGER_LIT(0))) {
#else
        if (yEqF_SDL_Integer(devaddr_getlen(&(yVarP->z59H_dataReq.
          DestinationAddress.Address)), SDL_INTEGER_LIT(0))) {
#endif
#ifdef XTRACE
        xTraceDecision("PATH: Integer");
#endif
            /* Null transition */
        } else {
#ifdef XTRACE
        xTraceDecision("ELSE");
#endif
          XBETWEEN_SYMBOLS(26, 7732, 534)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),788(75,165),1)
------*/
#ifdef XTRACE
          yAssF_SDL_Integer(yDcn_SDL_Integer, PDU_getLen(yVarP->z59H_dataReq.
            UserData), XASS);
          if (yEqF_SDL_Integer(yDcn_SDL_Integer, SDL_INTEGER_LIT(0))) {
#else
          if (yEqF_SDL_Integer(PDU_getLen(yVarP->z59H_dataReq.UserData),
            SDL_INTEGER_LIT(0))) {
#endif
#ifdef XTRACE
          xTraceDecision("PATH: Integer");
#endif
              /* Null transition */
          } else {
#ifdef XTRACE
          xTraceDecision("ELSE");
#endif
            XBETWEEN_SYMBOLS(27, 7733, 556)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),137(75,185),1)
------*/
            yAssF_SDL_Octet(yVarP->yDcn_SDL_Octet, yVarP->z59H_dataReq.
              DestinationAddress.Bearer, XASS);
            if (yEqF_SDL_Octet(yVarP->yDcn_SDL_Octet, xI2O_SDL_Octet(
                  BEARER_ANY_UDP)) ||
                yEqF_SDL_Octet(yVarP->yDcn_SDL_Octet, xI2O_SDL_Octet(
                  BEARER_GSM_CSD)) ||
                yEqF_SDL_Octet(yVarP->yDcn_SDL_Octet, xI2O_SDL_Octet(
                  BEARER_GSM_GPRS)) ||
                yEqF_SDL_Octet(yVarP->yDcn_SDL_Octet, xI2O_SDL_Octet(
              BEARER_BT))) {
#ifdef XTRACE
            xTraceDecision("PATH: I2O");
#endif
              XBETWEEN_SYMBOLS(28, 7734, 575)

/*-----
* ASSIGNMENT srcPort := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),2)
------*/
              yAssF_SDL_Integer(yVarP->z59C_srcPort, yVarP->z59H_dataReq.
                SourceAddress.PortNumber, XASS);
#ifdef XTRACE
              xTraceAssign("srcPort := ");
#endif
              XBETWEEN_STMTS(29, 7735, 586)

/*-----
* ASSIGNMENT dstPort := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),3)
------*/
              yAssF_SDL_Integer(yVarP->z59D_dstPort, yVarP->z59H_dataReq.
                DestinationAddress.PortNumber, XASS);
#ifdef XTRACE
              xTraceAssign("dstPort := ");
#endif
              XBETWEEN_STMTS(30, 7736, 597)

/*-----
* ASSIGNMENT dstAddr := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),4)
------*/
              yAssF_DeviceAddress(yVarP->z599_dstAddr, yVarP->z59H_dataReq.
                DestinationAddress.Address, XASS);
#ifdef XTRACE
              xTraceAssign("dstAddr := ");
#endif
              XBETWEEN_STMTS(31, 7737, 608)

/*-----
* ASSIGNMENT viewID := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),5)
------*/
              yAssF_SDL_Octet(yVarP->z59N_viewID, yVarP->z59H_dataReq.
                DestinationAddress.ViewID, XASS);
#ifdef XTRACE
              xTraceAssign("viewID := ");
#endif
              XBETWEEN_STMTS(32, 7738, 619)

/*-----
* ASSIGNMENT channelID := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),6)
------*/
              yAssF_SDL_Octet(yVarP->z59O_channelID, yVarP->z59H_dataReq.
                DestinationAddress.ChannelID, XASS);
#ifdef XTRACE
              xTraceAssign("channelID := ");
#endif
              XBETWEEN_SYMBOLS(33, 7739, 630)
              {

/*-----
* CALL wdp_porttbl_update
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),3254(75,240),1)
------*/
#ifdef XTRACE
                xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_update");
#endif
#ifdef XMSCE
                xMSCETask("CALL EXTERNAL wdp_porttbl_update");
#endif
                wdp_porttbl_update(yVarP->z59C_srcPort, yVarP->
                  z59K_upperlayerPId, yTstA_SDL_Natural(yVarP->
                  z59L_stackconfig), yVarP->z59H_dataReq.DestinationAddress.
                  Bearer, yVarP->z59N_viewID, yVarP->z59O_channelID);
              }
              XBETWEEN_SYMBOLS(34, 7740, 648)

/*-----
* TASK sendRequest
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1463(75,255),1)
------*/
#ifdef XTRACE
              xTraceTask("sendRequest");
#endif
#ifdef FEATURE_WAP
  UDPa_sendRequest ((const CHAR *)pdubuf_getStart (yVarP->z59H_dataReq.UserData),
                    pdubuf_getLength (yVarP->z59H_dataReq.UserData),
                    (const CHAR *)yVarP->z599_dstAddr.data, (INT8)yVarP->z599_dstAddr.length,
                    (const CHAR *)yVarP->z59A_srcAddr.data, (INT8)yVarP->z59A_srcAddr.length,
                    (UINT16)yVarP->z59D_dstPort, (UINT16)yVarP->z59C_srcPort,
                    yVarP->z59N_viewID, yVarP->z59O_channelID);
#else
  UDPa_sendRequest (pdubuf_getStart (yVarP->z59H_dataReq.UserData),
                    pdubuf_getLength (yVarP->z59H_dataReq.UserData),
                    yVarP->z599_dstAddr.data, (INT8)yVarP->z599_dstAddr.length,
                    yVarP->z59A_srcAddr.data, (INT8)yVarP->z59A_srcAddr.length,
                    (UINT16)yVarP->z59D_dstPort, (UINT16)yVarP->z59C_srcPort,
                    yVarP->z59N_viewID, yVarP->z59O_channelID);
#endif //FEATURE_WAP



              XBETWEEN_SYMBOLS(35, 7741, 665)

/*-----
* TASK log external
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),2180(75,270),1)
------*/
#ifdef XTRACE
              xTraceTask("log external");
#endif
#if defined LOG_EXTERNAL
  CLNTa_log (0, log_wdp_sendUDP, "UDPa_sendRequest");
#endif

              XBETWEEN_SYMBOLS(36, 7742, 678)

/*-----
* TASK log internal
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),3233(75,285),1)
------*/
#ifdef XTRACE
              xTraceTask("log internal");
#endif
#if defined LOG_INTERNAL
{
char *logstr;

logstr = OctetString2HexString(yVarP->z59A_srcAddr.data, yVarP->
  z59A_srcAddr.length);
CLNTa_log(0, 0, "WDP UDPsendReq Source Address = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: Source PortNumber = %d\n", yVarP->z59C_srcPort);

logstr = OctetString2HexString(yVarP->z599_dstAddr.data, yVarP->
  z599_dstAddr.length);
CLNTa_log(0, 0, "WDP: Destination Address = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: DesinationPortNumber = %d\n", yVarP->z59D_dstPort);

logstr = OctetString2HexString (pdubuf_getStart (yVarP->z59H_dataReq.UserData),
                                pdubuf_getLength (yVarP->
  z59H_dataReq.UserData));
CLNTa_log(0,0, "WDP data %s\n", logstr);
OSConnectorFree(logstr);
}
#endif

              XBETWEEN_SYMBOLS(37, 7743, 713)

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1157(75,300),1)
------*/
              yAssF_SDL_Boolean(yVarP->z59G_ok, PDU_rel(&(yVarP->z59H_dataReq.
                UserData)), XASS);
#ifdef XTRACE
              xTraceAssign("ok := ");
#endif
              XBETWEEN_SYMBOLS(38, 7744, 724)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1184(75,315),1)
------*/
              XAT_LAST_SYMBOL
              SDL_DASH_NEXTSTATE
            } else {
#ifdef XTRACE
            xTraceDecision("ELSE");
#endif
              XBETWEEN_SYMBOLS(39, 7745, 736)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\bearerchoice.smc(1),158(80,55),1)
------*/
#ifdef XTRACE
              xTraceTask(" ");
#endif
  CLNTa_error (0, ERR_WDP_ErrorBearerNotSupported, ERRTYPE_INFORMATION);

              XBETWEEN_SYMBOLS(40, 7746, 747)

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\bearerchoice.smc(1),176(80,100),1)
------*/
              yAssF_SDL_Boolean(yVarP->z59G_ok, PDU_rel(&(yVarP->z59H_dataReq.
                UserData)), XASS);
#ifdef XTRACE
              xTraceAssign("ok := ");
#endif
              XBETWEEN_SYMBOLS(41, 7747, 758)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\bearerchoice.smc(1),179(80,145),1)
------*/
              XAT_LAST_SYMBOL
              SDL_DASH_NEXTSTATE
            }
          }
        }
      } else {
#ifdef XTRACE
      xTraceDecision("FALSE");
#endif
          /* Null transition */
      }
    } else {
#ifdef XTRACE
    xTraceDecision("FALSE");
#endif
        /* Null transition */
    }
    XBETWEEN_SYMBOLS(42, 7748, 781)

/*-----
* TASK error
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),2699(10,190),1)
------*/
#ifdef XTRACE
    xTraceTask("error");
#endif
  CLNTa_error (0, ERR_WDP_ErrorInDatafromWSP, ERRTYPE_INFORMATION);

    XBETWEEN_SYMBOLS(43, 7749, 792)

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1430(10,205),1)
------*/
    yAssF_SDL_Boolean(yVarP->z59G_ok, PDU_rel(&(yVarP->z59H_dataReq.UserData)),
      XASS);
#ifdef XTRACE
    xTraceAssign("ok := ");
#endif
    XBETWEEN_SYMBOLS(44, 7750, 803)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1277(10,220),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT ClosePort
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3443(35,45),1)
------*/
  case 4:
    XDEBUG_LABEL(IDLE_ClosePort)
    XAT_FIRST_SYMBOL(4, 7710)
    XOS_TRACE_INPUT("ClosePort")
    yAssF_SDL_Integer(yVarP->z59J_port,
      ((yPDef_z_Global_Declarations_0_ClosePort *)ySVarP)->Param1, XASS);
    yAssF_SDL_Natural(yVarP->z59L_stackconfig, yTstA_SDL_Natural(
      ((yPDef_z_Global_Declarations_0_ClosePort *)ySVarP)->Param2), XASS);
    XBETWEEN_SYMBOLS(45, 7751, 824)
    {

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3797(35,80),1)
------*/
      yAssF_SDL_Boolean(yVarP->z59G_ok, wdp_porttbl_lookup(yVarP->z59J_port,
        &(yVarP->z59K_upperlayerPId), &(yVarP->z59L_stackconfig), &(yVarP->
        z59M_bearer), &(yVarP->z59N_viewID), &(yVarP->z59O_channelID)), XASS);
#ifdef XTRACE
      xTraceAssign("ok := ");
#endif
    }
    XBETWEEN_SYMBOLS(46, 7752, 838)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3800(35,95),1)
------*/
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z59G_ok, XASS);
    if (yDcn_SDL_Boolean) {
#else
    if (yVarP->z59G_ok) {
#endif
#ifdef XTRACE
    xTraceDecision("TRUE");
#endif
      XBETWEEN_SYMBOLS(47, 7753, 853)
      {

/*-----
* CALL wdp_porttbl_delete
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3791(35,110),1)
------*/
#ifdef XTRACE
        xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_delete");
#endif
#ifdef XMSCE
        xMSCETask("CALL EXTERNAL wdp_porttbl_delete");
#endif
        wdp_porttbl_delete(yVarP->z59J_port);
      }
      XBETWEEN_SYMBOLS(48, 7754, 868)

/*-----
* TASK close connection
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3779(35,125),1)
------*/
#ifdef XTRACE
      xTraceTask("close connection");
#endif
  {
    UINT8  errorCode;
    DB_ref ref;
    INT32  online;

    if ((yVarP->z59M_bearer == BEARER_ANY_UDP) ||
        (yVarP->z59M_bearer == BEARER_GSM_CSD) ||
        (yVarP->z59M_bearer == BEARER_GSM_GPRS) ||
        (yVarP->z59M_bearer == BEARER_BT)) {
      do {
        ref = getChannelRef (yVarP->z59N_viewID, yVarP->z59O_channelID);
        if (ref != DB_null) {
#ifdef FEATURE_WAP
          online = getInt (ref, (const BYTE *)"onln", FALSE, &errorCode);
#else
          online = getInt (ref, "onln", FALSE, &errorCode);
#endif //FEATURE_WAP
          if ((errorCode == DB_err_success) && online)
            break;
        }
        CLNTa_closeConnection (yVarP->z59N_viewID, yVarP->z59O_channelID);
      } while (0);
    }
  }

    } else {
#ifdef XTRACE
    xTraceDecision("FALSE");
#endif
        /* Null transition */
    }
    XBETWEEN_SYMBOLS(49, 7755, 904)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3449(35,145),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT OpenPort
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3482(115,45),1)
------*/
  case 5:
    XDEBUG_LABEL(IDLE_OpenPort)
    XAT_FIRST_SYMBOL(5, 7711)
    XOS_TRACE_INPUT("OpenPort")
    yAssF_SDL_Integer(yVarP->z59J_port, ((yPDef_z_WDP_UpperLayer_1_OpenPort *)
      ySVarP)->Param1, XASS);
    yAssF_SDL_PId(yVarP->z59K_upperlayerPId,
      ((yPDef_z_WDP_UpperLayer_1_OpenPort *)ySVarP)->Param2, XASS);
    yAssF_SDL_Natural(yVarP->z59L_stackconfig, yTstA_SDL_Natural(
      ((yPDef_z_WDP_UpperLayer_1_OpenPort *)ySVarP)->Param3), XASS);
    XBETWEEN_SYMBOLS(50, 7756, 927)
    {

/*-----
* CALL wdp_porttbl_update
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3488(115,65),1)
------*/
#ifdef XTRACE
      xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_update");
#endif
#ifdef XMSCE
      xMSCETask("CALL EXTERNAL wdp_porttbl_update");
#endif
      wdp_porttbl_update(yVarP->z59J_port, yVarP->z59K_upperlayerPId,
        yTstA_SDL_Natural(yVarP->z59L_stackconfig), xI2O_SDL_Octet(
        SDL_INTEGER_LIT(0)), xI2O_SDL_Octet(SDL_INTEGER_LIT(0)), xI2O_SDL_Octet(
        SDL_INTEGER_LIT(0)));
    }
    XBETWEEN_SYMBOLS(51, 7757, 945)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3491(115,85),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT TerminateWDPh
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3884(40,55),1)
------*/
  case 6:
    XDEBUG_LABEL(IDLE_TerminateWDPh)
    XAT_FIRST_SYMBOL(6, 7712)
    XOS_TRACE_INPUT("TerminateWDPh")
    XBETWEEN_SYMBOLS(52, 7758, 962)
    {

/*-----
* CALL wdp_porttbl_clear
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3887(40,70),1)
------*/
#ifdef XTRACE
      xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_clear");
#endif
#ifdef XMSCE
      xMSCETask("CALL EXTERNAL wdp_porttbl_clear");
#endif
      wdp_porttbl_clear();
    }
    XBETWEEN_SYMBOLS(53, 7759, 977)

/*-----
* OUTPUT WDPhTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),305(80,40),1)
------*/
    ALLOC_SIGNAL_NPAR(WDPhTerminated, z_WDPPckg_6_WDPhTerminated,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, WDPhTerminated,
      z_WDPPckg_6_WDPhTerminated, TO_PROCESS(WDPmanagement, z5A_WDPmanagement),
      0, "WDPhTerminated")
    XBETWEEN_SYMBOLS(54, 7760, 988)

/*-----
* OUTPUT SegmentationTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),287(80,55),1)
------*/
    ALLOC_SIGNAL_NPAR(SegmentationTerminated,
      z_WDPPckg_8_SegmentationTerminated, XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, SegmentationTerminated,
      z_WDPPckg_8_SegmentationTerminated, TO_PROCESS(WDPmanagement,
      z5A_WDPmanagement), 0, "SegmentationTerminated")
    XBETWEEN_SYMBOLS(55, 7761, 999)

/*-----
* OUTPUT ReassembleTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),293(80,70),1)
------*/
    ALLOC_SIGNAL_NPAR(ReassembleTerminated, z_WDPPckg_7_ReassembleTerminated,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, ReassembleTerminated,
      z_WDPPckg_7_ReassembleTerminated, TO_PROCESS(WDPmanagement,
      z5A_WDPmanagement), 0, "ReassembleTerminated")
    XBETWEEN_SYMBOLS(56, 7762, 1010)

/*-----
* NEXTSTATE AwaitStart
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3893(40,105),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitStart, z596_AwaitStart, "AwaitStart")

/*-----
* INPUT UDPErrorInd
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3908(110,55),1)
------*/
  case 7:
    XDEBUG_LABEL(IDLE_UDPErrorInd)
    XAT_FIRST_SYMBOL(7, 7713)
    XOS_TRACE_INPUT("UDPErrorInd")
    yAssF_SDL_Integer(yVarP->z59D_dstPort, ((yPDef_z_WDP_UDP_2_UDPErrorInd *)
      ySVarP)->Param1, XASS);
    yAssF_SDL_Natural(yVarP->z59F_FaultCode, yTstA_SDL_Natural(
      ((yPDef_z_WDP_UDP_2_UDPErrorInd *)ySVarP)->Param2), XASS);
    XBETWEEN_SYMBOLS(57, 7763, 1031)

/*-----
* TASK log external
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3914(110,75),1)
------*/
#ifdef XTRACE
    xTraceTask("log external");
#endif
#if defined LOG_EXTERNAL
  CLNTa_log (0, log_wdp_UDPErrorInd, "\n");
#endif

    XBETWEEN_SYMBOLS(58, 7764, 1044)

/*-----
* TASK error
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3920(110,90),1)
------*/
#ifdef XTRACE
    xTraceTask("error");
#endif
  CLNTa_error (0, (INT16)yVarP->z59F_FaultCode, ERRTYPE_BEARER);

    XBETWEEN_SYMBOLS(59, 7765, 1055)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3926(110,105),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT RecUDPDatagram
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3347(55,45),1)
------*/
  case 8:
    XDEBUG_LABEL(IDLE_RecUDPDatagram)
    XAT_FIRST_SYMBOL(8, 7714)
    XOS_TRACE_INPUT("RecUDPDatagram")
    yAssF_z_ctypes_4_VoidStar(yVarP->z598_UDPData,
      ((yPDef_z_WDP_UDP_1_RecUDPDatagram *)ySVarP)->Param1, XASS);
    yAssF_SDL_Natural(yVarP->z59E_DataLen, yTstA_SDL_Natural(
      ((yPDef_z_WDP_UDP_1_RecUDPDatagram *)ySVarP)->Param2), XASS);
    yAssF_DeviceAddress(yVarP->z599_dstAddr,
      ((yPDef_z_WDP_UDP_1_RecUDPDatagram *)ySVarP)->Param3, XASS);
    yAssF_DeviceAddress(yVarP->z59A_srcAddr,
      ((yPDef_z_WDP_UDP_1_RecUDPDatagram *)ySVarP)->Param4, XASS);
    yAssF_SDL_Integer(yVarP->z59D_dstPort, ((yPDef_z_WDP_UDP_1_RecUDPDatagram *)
      ySVarP)->Param5, XASS);
    yAssF_SDL_Integer(yVarP->z59C_srcPort, ((yPDef_z_WDP_UDP_1_RecUDPDatagram *)
      ySVarP)->Param6, XASS);
    XBETWEEN_SYMBOLS(60, 7766, 1084)

/*-----
* TASK log external
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3353(55,60),1)
------*/
#ifdef XTRACE
    xTraceTask("log external");
#endif
#if defined LOG_EXTERNAL
  CLNTa_log (0, log_wdp_RecUDPDatagram, "\n");
#endif

    XBETWEEN_SYMBOLS(61, 7767, 1097)

/*-----
* TASK log internal
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3359(55,75),1)
------*/
#ifdef XTRACE
    xTraceTask("log internal");
#endif
#if defined LOG_INTERNAL
{
char *logstr;
char *strparam1;
logstr = OctetString2HexString(yVarP->z59A_srcAddr.data, yVarP->
  z59A_srcAddr.length);
CLNTa_log(0, 0, "WDP Source Address = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: Source PortNumber = %d\n", yVarP->z59C_srcPort);

logstr = OctetString2HexString(yVarP->z599_dstAddr.data, yVarP->
  z599_dstAddr.length);
CLNTa_log(0, 0, "WDP: Destination Address = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: DesinationPortNumber = %d\n", yVarP->z59D_dstPort);

strparam1=OctetString2HexString(yVarP->z598_UDPData,yVarP->z59E_DataLen);
CLNTa_log(0,0, "WDP data %s\n", strparam1?strparam1:"");
DEALLOC(&strparam1);
}
#endif

    XBETWEEN_SYMBOLS(62, 7768, 1130)
    {

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3389(55,90),1)
------*/
      yAssF_SDL_Boolean(yVarP->z59G_ok, wdp_porttbl_lookup(yVarP->z59D_dstPort,
        &(yVarP->z59K_upperlayerPId), &(yVarP->z59L_stackconfig), &(yVarP->
        z59M_bearer), &(yVarP->z59N_viewID), &(yVarP->z59O_channelID)), XASS);
#ifdef XTRACE
      xTraceAssign("ok := ");
#endif
    }
    XBETWEEN_SYMBOLS(63, 7769, 1144)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3398(55,105),1)
------*/
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z59G_ok, XASS);
    if (yDcn_SDL_Boolean) {
#else
    if (yVarP->z59G_ok) {
#endif
#ifdef XTRACE
    xTraceDecision("TRUE");
#endif
      XBETWEEN_SYMBOLS(66, 7772, 1159)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2537(55,125),1)
------*/
#ifdef XTRACE
      yAssF_SDL_Boolean(yDcn_SDL_Boolean, xLE_SDL_Integer(yVarP->z59E_DataLen,
        MaxPDUsize), XASS);
      if (yDcn_SDL_Boolean) {
#else
      if (xLE_SDL_Integer(yVarP->z59E_DataLen, MaxPDUsize)) {
#endif
#ifdef XTRACE
      xTraceDecision("TRUE");
#endif
        XBETWEEN_SYMBOLS(67, 7773, 1175)

/*-----
* ASSIGNMENT tmpBuf := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2498(55,140),1)
------*/
        yAssF_pdubuf_ptr(yVarP->z59B_tmpBuf, PDU_getFromData(yVarP->
          z598_UDPData, yTstA_SDL_Natural(yVarP->z59E_DataLen)), XASS);
#ifdef XTRACE
        xTraceAssign("tmpBuf := ");
#endif
        XBETWEEN_SYMBOLS(68, 7774, 1186)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2504(55,155),1)
------*/
#ifdef XTRACE
        yAssF_SDL_Boolean(yDcn_SDL_Boolean, PDU_isNull(yVarP->z59B_tmpBuf),
          XASS);
        if (yDcn_SDL_Boolean) {
#else
        if (PDU_isNull(yVarP->z59B_tmpBuf)) {
#endif
#ifdef XTRACE
        xTraceDecision("TRUE");
#endif
            /* Null transition */
        } else {
#ifdef XTRACE
        xTraceDecision("FALSE");
#endif
          XBETWEEN_SYMBOLS(69, 7775, 1207)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),923(55,175),1)
------*/
          yAssF_pdubuf_ptr(yVarP->z59I_dataInd.UserData, yVarP->z59B_tmpBuf,
            XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_SYMBOLS(70, 7776, 1218)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2264(55,195),1)
------*/
          yAssF_SDL_Integer(yVarP->z59I_dataInd.SourceAddress.PortNumber,
            yVarP->z59C_srcPort, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(71, 7777, 1229)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2264(55,195),2)
------*/
          yAssF_SDL_Integer(yVarP->z59I_dataInd.DestinationAddress.PortNumber,
            yVarP->z59D_dstPort, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_SYMBOLS(72, 7778, 1240)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2267(55,225),1)
------*/
          yAssF_DeviceAddress(yVarP->z59I_dataInd.SourceAddress.Address, yVarP->
            z59A_srcAddr, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(73, 7779, 1251)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2267(55,225),2)
------*/
          yAssF_SDL_Octet(yVarP->z59I_dataInd.SourceAddress.
            SecondAddressFormat, xI2O_SDL_Octet(SDL_INTEGER_LIT(255)), XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(74, 7780, 1262)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2267(55,225),3)
------*/
          yAssF_DeviceAddress(yVarP->z59I_dataInd.DestinationAddress.Address,
            yVarP->z599_dstAddr, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(75, 7781, 1273)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2267(55,225),4)
------*/
          yAssF_SDL_Octet(yVarP->z59I_dataInd.DestinationAddress.
            SecondAddressFormat, xI2O_SDL_Octet(SDL_INTEGER_LIT(255)), XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_SYMBOLS(76, 7782, 1284)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),1)
------*/
          yAssF_SDL_Octet(yVarP->z59I_dataInd.SourceAddress.Bearer, yVarP->
            z59M_bearer, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(77, 7783, 1295)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),2)
------*/
          yAssF_SDL_Octet(yVarP->z59I_dataInd.DestinationAddress.Bearer, yVarP->
            z59M_bearer, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(78, 7784, 1306)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),3)
------*/
          yAssF_SDL_Octet(yVarP->z59I_dataInd.SourceAddress.ViewID, yVarP->
            z59N_viewID, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(79, 7785, 1317)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),4)
------*/
          yAssF_SDL_Octet(yVarP->z59I_dataInd.DestinationAddress.ViewID, yVarP->
            z59N_viewID, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(80, 7786, 1328)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),5)
------*/
          yAssF_SDL_Octet(yVarP->z59I_dataInd.SourceAddress.ChannelID, yVarP->
            z59O_channelID, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(81, 7787, 1339)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),6)
------*/
          yAssF_SDL_Octet(yVarP->z59I_dataInd.DestinationAddress.ChannelID,
            yVarP->z59O_channelID, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_SYMBOLS(82, 7788, 1350)

/*-----
* TASK log internal
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3170(55,275),1)
------*/
#ifdef XTRACE
          xTraceTask("log internal");
#endif
#if defined LOG_INTERNAL
{
char *logstr;
char *strPDU;
char *strparam1;
logstr = OctetString2HexString(yVarP->
  z59I_dataInd.SourceAddress.Address.data, yVarP->
  z59I_dataInd.SourceAddress.Address.length);
CLNTa_log(0, 0, "WDP Send TDUnitDataInd: Source Address = %s\n", logstr);
OSConnectorFree(logstr);

logstr = OctetString2HexString(yVarP->
  z59I_dataInd.SourceAddress. SecondAddress.data, yVarP->
  z59I_dataInd.SourceAddress. SecondAddress.length);
CLNTa_log(0, 0, "WDP Send TDUnitDataInd: Source SecondAddress = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: Source Bearer = %d\n", yVarP->
  z59I_dataInd.SourceAddress.Bearer);

CLNTa_log(0, 0, "WDP: Source SecondAddressFormat= %d\n", yVarP->
  z59I_dataInd.SourceAddress.SecondAddressFormat);

CLNTa_log(0, 0, "WDP: Source PortNumber = %d\n", yVarP->
  z59I_dataInd.SourceAddress.PortNumber);

logstr = OctetString2HexString(yVarP->
  z59I_dataInd.DestinationAddress.Address.data, yVarP->
  z59I_dataInd.DestinationAddress.Address.length);
CLNTa_log(0, 0, "WDP Send TDUnitDataInd: Destination Address = %s\n", logstr);
OSConnectorFree(logstr);

logstr = OctetString2HexString(yVarP->
  z59I_dataInd. DestinationAddress.SecondAddress.data, yVarP->
  z59I_dataInd.DestinationAddress.SecondAddress.length);
CLNTa_log(0, 0, "WDP Send TDUnitDataInd: Destination SecondAddress = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: DesinationBearer = %d\n", yVarP->
  z59I_dataInd.DestinationAddress.Bearer);

CLNTa_log(0, 0, "WDP: DesinationSecondAddressFormat= %d\n", yVarP->
  z59I_dataInd.DestinationAddress.SecondAddressFormat);

CLNTa_log(0, 0, "WDP: DesinationPortNumber = %d\n", yVarP->
  z59I_dataInd.DestinationAddress.PortNumber);

CLNTa_log(0, 0, "WDP: StackConfig = %d\n", yVarP->z59L_stackconfig);

strPDU = pdubuf_getStart( yVarP->z59I_dataInd.UserData );
strparam1=OctetString2HexString((CHAR*)strPDU,pdubuf_getLength(yVarP->
  z59I_dataInd.UserData));

CLNTa_log(0,0, "WDP data %s\n", strparam1?strparam1:"");
DEALLOC(&strparam1);
}
#endif

          XBETWEEN_SYMBOLS(83, 7789, 1417)

/*-----
* OUTPUT TDUnitDataInd
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2285(55,290),1)
------*/
          ALLOC_SIGNAL_PAR(TDUnitDataInd, z_WDP_UpperLayer_2_TDUnitDataInd,
            yPDef_z_WDP_UpperLayer_2_TDUnitDataInd)
          yAssF_TDUnitdataIndType(((yPDef_z_WDP_UpperLayer_2_TDUnitDataInd *)OUTSIGNAL_DATA_PTR)->Param1,
            yVarP->z59I_dataInd, XASSPARA);
          yAssF_SDL_Natural(((yPDef_z_WDP_UpperLayer_2_TDUnitDataInd *)OUTSIGNAL_DATA_PTR)->Param2,
            yTstA_SDL_Natural(yVarP->z59L_stackconfig), XASSPARA);
          SDL_OUTP_PAR(xDefaultPrioSignal, TDUnitDataInd,
            z_WDP_UpperLayer_2_TDUnitDataInd, yVarP->z59K_upperlayerPId,
            yPDef_z_WDP_UpperLayer_2_TDUnitDataInd, "TDUnitDataInd")
          XBETWEEN_SYMBOLS(84, 7790, 1432)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2288(55,305),1)
------*/
          XAT_LAST_SYMBOL
          SDL_DASH_NEXTSTATE
        }
      } else {
#ifdef XTRACE
      xTraceDecision("FALSE");
#endif
          /* Null transition */
      }
      XBETWEEN_SYMBOLS(85, 7791, 1447)

/*-----
* TASK error
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2780(115,175),1)
------*/
#ifdef XTRACE
      xTraceTask("error");
#endif
  CLNTa_error (0, ERR_WDP_UDPBigBuffer, ERRTYPE_INFORMATION);

      XBETWEEN_SYMBOLS(86, 7792, 1458)

/*-----
* TASK Free buffer
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2408(115,190),1)
------*/
#ifdef XTRACE
      xTraceTask("Free buffer");
#endif
  OSConnectorFree (yVarP->z598_UDPData);

      XBETWEEN_SYMBOLS(87, 7793, 1469)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),1358(115,210),1)
------*/
      XAT_LAST_SYMBOL
      SDL_DASH_NEXTSTATE
    } else {
#ifdef XTRACE
    xTraceDecision("FALSE");
#endif
      XBETWEEN_SYMBOLS(64, 7770, 1481)

/*-----
* TASK Free buffer
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3404(135,120),1)
------*/
#ifdef XTRACE
      xTraceTask("Free buffer");
#endif
  OSConnectorFree (yVarP->z598_UDPData);

      XBETWEEN_SYMBOLS(65, 7771, 1492)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3416(135,135),1)
------*/
      XAT_LAST_SYMBOL
      SDL_DASH_NEXTSTATE
    }
  }
  END_PAD(yPAD_z59_WDPhandler)
}

/*****
* PROCESS WDPmanagement
* <<SYSTEM WAP/BLOCK WDP>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr,4,1)
******/

/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
** Tables for process WDPmanagement
** #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr,4,1)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

/*--------------Instance Data---------------*/
#define X_MAX_INST_z5A_WDPmanagement 1
static yVDef_z5A_WDPmanagement *yINSTD_z5A_WDPmanagement[X_MAX_INST_z5A_WDPmanagement];

/*--------------Process State---------------*/
static xSTATE yPSTATETBL_z5A_WDPmanagement[X_MAX_INST_z5A_WDPmanagement] = {
  XSTARTUP
};

/*---------------State Index----------------*/
static XCONST xSITBL xSTATE_INDEX_z5A_WDPmanagement[9] = {0, 2, 5, 7, 8, 9, 12,
    14, 15};

/*---------------Transition-----------------*/
#define XMAX_TRANS_z5A_WDPmanagement 15
static XCONST xTR_TABLE_ENTRY yTRTBL_z5A_WDPmanagement[XMAX_TRANS_z5A_WDPmanagement] = {

    /* AwaitStartWDP */
  XMK_B z_StackMgr_6_StartWDP, 2 XMK_E,
  XMK_B z_StackMgr_E_TerminateWDP, 1 XMK_E

    /* AwaitReady */,
  XMK_B z_WDPPckg_9_WDPhReady, XSAVEID XMK_E,
  XMK_B z_WDPPckg_A_SegmentationReady, 3 XMK_E,
  XMK_B z_WDPPckg_B_ReassembleReady, XSAVEID XMK_E

    /* AwaitWDPhReady */,
  XMK_B z_WDPPckg_9_WDPhReady, 4 XMK_E,
  XMK_B z_WDPPckg_B_ReassembleReady, XSAVEID XMK_E

    /* AwaitReassembleReady */,
  XMK_B z_WDPPckg_B_ReassembleReady, 5 XMK_E

    /* idle */,
  XMK_B z_StackMgr_E_TerminateWDP, 6 XMK_E

    /* AwaitTerminated */,
  XMK_B z_WDPPckg_6_WDPhTerminated, XSAVEID XMK_E,
  XMK_B z_WDPPckg_7_ReassembleTerminated, XSAVEID XMK_E,
  XMK_B z_WDPPckg_8_SegmentationTerminated, 7 XMK_E

    /* AwaitWDPhTerminated */,
  XMK_B z_WDPPckg_6_WDPhTerminated, 8 XMK_E,
  XMK_B z_WDPPckg_7_ReassembleTerminated, XSAVEID XMK_E

    /* AwaitReassembleTerminated */,
  XMK_B z_WDPPckg_7_ReassembleTerminated, 9 XMK_E
};

/*-----------Process-PID-Values-------------*/
#ifdef XMK_USE_PID_ADDRESSING
static xPIDTable yPID_TBL_z5A_WDPmanagement[X_MAX_INST_z5A_WDPmanagement];
#endif

/*-----------Process Description------------*/
#define X_PRIO_z5A_WDPmanagement  xDefaultPrioProcess
XCONST XPDTBL yPDTBL_z5A_WDPmanagement = {
#ifdef XMK_USE_PID_ADDRESSING
  yPID_TBL_z5A_WDPmanagement,
#endif
  (xINSTD *)yINSTD_z5A_WDPmanagement,
  sizeof(yVDef_z5A_WDPmanagement),
  X_MAX_INST_z5A_WDPmanagement,
#ifdef XMK_USE_TIMESLICE
  X_TIMESLICE_z5A_WDPmanagement,
#endif
#ifdef XMK_USE_PREEMPTIVE
  X_PRIO_z5A_WDPmanagement,
#endif
  (xmk_T_TRANS_ADDRESS) yPAD_z5A_WDPmanagement,
  yTRTBL_z5A_WDPmanagement,
  xSTATE_INDEX_z5A_WDPmanagement,
  yPSTATETBL_z5A_WDPmanagement
};

/*+++++
* Function for process WDPmanagement
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr,4,1)
++++++*/
YPAD_FUNCTION(yPAD_z5A_WDPmanagement)
{
  YPAD_YSVARP
  /* INTEGRATION: commented out statement */
  /* YPAD_YVARP(yVDef_z5A_WDPmanagement) */
  YPAD_TEMP_VARS
  YPRSNAME_VAR("WDPmanagement")

  BEGIN_PAD
  switch (XSYMBOLNUMBER) {

/*-----
* START
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),197(30,25),1)
------*/
  case 0:
    BEGIN_START_TRANSITION
    XAT_FIRST_SYMBOL(0, 7794)
    XBETWEEN_SYMBOLS(10, 7804, 1612)

/*-----
* NEXTSTATE AwaitStartWDP
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),611(30,40),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitStartWDP, z5A0_AwaitStartWDP, "AwaitStartWDP")

/*-----
* INPUT TerminateWDP
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1652(105,40),1)
------*/
  case 1:
    XDEBUG_LABEL(AwaitStartWDP_TerminateWDP)
    XAT_FIRST_SYMBOL(1, 7795)
    XOS_TRACE_INPUT("TerminateWDP")
    XBETWEEN_SYMBOLS(11, 7805, 1629)

/*-----
* OUTPUT Ready
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1655(105,55),1)
------*/
    ALLOC_SIGNAL_PAR(Ready, z_StackMgr_8_Ready, yPDef_z_StackMgr_8_Ready)
    yAssF_SDL_Natural(((yPDef_z_StackMgr_8_Ready *)OUTSIGNAL_DATA_PTR)->Param1,
      yTstA_SDL_Natural(SDL_INTEGER_LIT(5)), XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, Ready, z_StackMgr_8_Ready,
      TO_PROCESS(StackCtrl, z17_StackCtrl), yPDef_z_StackMgr_8_Ready, "Ready")
    XBETWEEN_SYMBOLS(12, 7806, 1640)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1658(105,70),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT StartWDP
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\managementstart.smc(1),251(80,25),1)
------*/
  case 2:
    XDEBUG_LABEL(AwaitStartWDP_StartWDP)
    XAT_FIRST_SYMBOL(2, 7796)
    XOS_TRACE_INPUT("StartWDP")
    XBETWEEN_SYMBOLS(13, 7807, 1657)

/*-----
* OUTPUT StartWDPh
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\managementstart.smc(1),254(80,40),1)
------*/
    ALLOC_SIGNAL_NPAR(StartWDPh, z_WDPPckg_0_StartWDPh, XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, StartWDPh, z_WDPPckg_0_StartWDPh,
      TO_PROCESS(WDPhandler, z59_WDPhandler), 0, "StartWDPh")
    XBETWEEN_SYMBOLS(14, 7808, 1666)

/*-----
* NEXTSTATE AwaitReady
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\managementstart.smc(1),263(80,85),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitReady, z5A1_AwaitReady, "AwaitReady")

/*-----
* INPUT SegmentationReady
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1859(30,100),1)
------*/
  case 3:
    XDEBUG_LABEL(AwaitReady_SegmentationReady)
    XAT_FIRST_SYMBOL(3, 7797)
    XOS_TRACE_INPUT("SegmentationReady")
    XBETWEEN_SYMBOLS(15, 7809, 1683)

/*-----
* NEXTSTATE AwaitWDPhReady
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1865(30,115),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitWDPhReady, z5A2_AwaitWDPhReady, "AwaitWDPhReady")

/*-----
* INPUT WDPhReady
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1691(130,100),1)
------*/
  case 4:
    XDEBUG_LABEL(AwaitWDPhReady_WDPhReady)
    XAT_FIRST_SYMBOL(4, 7798)
    XOS_TRACE_INPUT("WDPhReady")
    XBETWEEN_SYMBOLS(16, 7810, 1700)

/*-----
* NEXTSTATE AwaitReassembleReady
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1694(130,115),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitReassembleReady, z5A3_AwaitReassembleReady,
      "AwaitReassembleReady")

/*-----
* INPUT ReassembleReady
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1715(30,145),1)
------*/
  case 5:
    XDEBUG_LABEL(AwaitReassembleReady_ReassembleReady)
    XAT_FIRST_SYMBOL(5, 7799)
    XOS_TRACE_INPUT("ReassembleReady")
    XBETWEEN_SYMBOLS(17, 7811, 1718)

/*-----
* OUTPUT Ready
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1724(30,160),1)
------*/
    ALLOC_SIGNAL_PAR(Ready, z_StackMgr_8_Ready, yPDef_z_StackMgr_8_Ready)
    yAssF_SDL_Natural(((yPDef_z_StackMgr_8_Ready *)OUTSIGNAL_DATA_PTR)->Param1,
      yTstA_SDL_Natural(SDL_INTEGER_LIT(5)), XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, Ready, z_StackMgr_8_Ready,
      TO_PROCESS(StackCtrl, z17_StackCtrl), yPDef_z_StackMgr_8_Ready, "Ready")
    XBETWEEN_SYMBOLS(18, 7812, 1729)

/*-----
* NEXTSTATE idle
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1727(30,175),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(idle, z5A4_idle, "idle")

/*-----
* INPUT TerminateWDP
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),818(30,40),1)
------*/
  case 6:
    XDEBUG_LABEL(idle_TerminateWDP)
    XAT_FIRST_SYMBOL(6, 7800)
    XOS_TRACE_INPUT("TerminateWDP")
    XBETWEEN_SYMBOLS(19, 7813, 1746)

/*-----
* OUTPUT TerminateWDPh
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\managementterminate.smc(1),302(80,55),1)
------*/
    ALLOC_SIGNAL_NPAR(TerminateWDPh, z_WDPPckg_3_TerminateWDPh,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, TerminateWDPh, z_WDPPckg_3_TerminateWDPh,
      TO_PROCESS(WDPhandler, z59_WDPhandler), 0, "TerminateWDPh")
    XBETWEEN_SYMBOLS(20, 7814, 1756)

/*-----
* NEXTSTATE AwaitTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),830(30,70),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitTerminated, z5A5_AwaitTerminated, "AwaitTerminated")

/*-----
* INPUT SegmentationTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2006(80,40),1)
------*/
  case 7:
    XDEBUG_LABEL(AwaitTerminated_SegmentationTerminated)
    XAT_FIRST_SYMBOL(7, 7801)
    XOS_TRACE_INPUT("SegmentationTerminated")
    XBETWEEN_SYMBOLS(21, 7815, 1773)

/*-----
* NEXTSTATE AwaitWDPhTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2009(80,55),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitWDPhTerminated, z5A6_AwaitWDPhTerminated,
      "AwaitWDPhTerminated")

/*-----
* INPUT WDPhTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2018(30,115),1)
------*/
  case 8:
    XDEBUG_LABEL(AwaitWDPhTerminated_WDPhTerminated)
    XAT_FIRST_SYMBOL(8, 7802)
    XOS_TRACE_INPUT("WDPhTerminated")
    XBETWEEN_SYMBOLS(22, 7816, 1791)

/*-----
* NEXTSTATE AwaitReassembleTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2021(30,130),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitReassembleTerminated, z5A7_AwaitReassembleTerminated,
      "AwaitReassembleTerminated")

/*-----
* INPUT ReassembleTerminated
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2030(130,115),1)
------*/
  case 9:
    XDEBUG_LABEL(AwaitReassembleTerminated_ReassembleTerminated)
    XAT_FIRST_SYMBOL(9, 7803)
    XOS_TRACE_INPUT("ReassembleTerminated")
    XBETWEEN_SYMBOLS(23, 7817, 1809)

/*-----
* OUTPUT Ready
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2039(130,130),1)
------*/
    ALLOC_SIGNAL_PAR(Ready, z_StackMgr_8_Ready, yPDef_z_StackMgr_8_Ready)
    yAssF_SDL_Natural(((yPDef_z_StackMgr_8_Ready *)OUTSIGNAL_DATA_PTR)->Param1,
      yTstA_SDL_Natural(SDL_INTEGER_LIT(5)), XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, Ready, z_StackMgr_8_Ready,
      TO_PROCESS(StackCtrl, z17_StackCtrl), yPDef_z_StackMgr_8_Ready, "Ready")
    XBETWEEN_SYMBOLS(24, 7818, 1820)

/*-----
* NEXTSTATE AwaitStartWDP
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2042(130,145),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitStartWDP, z5A0_AwaitStartWDP, "AwaitStartWDP")
  }
  END_PAD(yPAD_z5A_WDPmanagement)
}
