/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_WDP_UDP_H
#define XX_WDP_UDP_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SIGNAL UDPsendReq
* <<PACKAGE WDP_UDP>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdp_udp.sun(1),122(25,40),5)
******/
#define z_WDP_UDP_0_UDPsendReq 197
typedef struct {
    SIGNAL_VARS
    SDL_Octet_String  Param1;
    DeviceAddress  Param2;
    DeviceAddress  Param3;
    SDL_Natural  Param4;
    SDL_Natural  Param5;
} yPDef_z_WDP_UDP_0_UDPsendReq;

/*****
* SIGNAL RecUDPDatagram
* <<PACKAGE WDP_UDP>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdp_udp.sun(1),125(25,85),3)
******/
#define z_WDP_UDP_1_RecUDPDatagram 198
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Natural  Param2;
    DeviceAddress  Param3;
    DeviceAddress  Param4;
    SDL_Natural  Param5;
    SDL_Natural  Param6;
} yPDef_z_WDP_UDP_1_RecUDPDatagram;

/*****
* SIGNAL UDPErrorInd
* <<PACKAGE WDP_UDP>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdp_udp.sun(1),125(25,85),6)
******/
#define z_WDP_UDP_2_UDPErrorInd 199
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Natural  Param2;
} yPDef_z_WDP_UDP_2_UDPErrorInd;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
