/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_WDPpckg_H
#define XX_WDPpckg_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SYNONYM MinSourcePortNo
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(2),143(30,40),2)
******/
#define z_WDPPckg_L_MinSourcePortNo SDL_INTEGER_LIT(0)

/*****
* SYNONYM MaxSourcePortNo
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(2),143(30,40),4)
******/
#define z_WDPPckg_M_MaxSourcePortNo SDL_INTEGER_LIT(90000)

/*****
* SYNONYM MinDestPortNo
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(2),146(30,75),2)
******/
#define z_WDPPckg_N_MinDestPortNo SDL_INTEGER_LIT(0)

/*****
* SYNONYM MaxDestPortNo
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(2),146(30,75),4)
******/
#define z_WDPPckg_O_MaxDestPortNo SDL_INTEGER_LIT(90000)

/*****
* SYNONYM MaxLengthUNSegSMSMessage
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(2),152(30,135),4)
******/
#define z_WDPPckg_P_MaxLengthUNSegSMSMessage SDL_INTEGER_LIT(133)

/*****
* SYNONYM MaxLengthSegSMSMessage
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(2),152(30,135),6)
******/
#define z_WDPPckg_Q_MaxLengthSegSMSMessage SDL_INTEGER_LIT(128)

/*****
* SIGNAL StartWDPh
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),4)
******/
#define z_WDPPckg_0_StartWDPh 17

/*****
* SIGNAL StartReassemble
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),5)
******/
#define z_WDPPckg_1_StartReassemble 18

/*****
* SIGNAL StartSegmentation
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),6)
******/
#define z_WDPPckg_2_StartSegmentation 19

/*****
* SIGNAL TerminateWDPh
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),7)
******/
#define z_WDPPckg_3_TerminateWDPh 20

/*****
* SIGNAL TerminateReassemble
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),8)
******/
#define z_WDPPckg_4_TerminateReassemble 21

/*****
* SIGNAL TerminateSegmentation
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),9)
******/
#define z_WDPPckg_5_TerminateSegmentation 22

/*****
* SIGNAL WDPhTerminated
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),10)
******/
#define z_WDPPckg_6_WDPhTerminated 23

/*****
* SIGNAL ReassembleTerminated
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),11)
******/
#define z_WDPPckg_7_ReassembleTerminated 24

/*****
* SIGNAL SegmentationTerminated
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),12)
******/
#define z_WDPPckg_8_SegmentationTerminated 25

/*****
* SIGNAL WDPhReady
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),13)
******/
#define z_WDPPckg_9_WDPhReady 26

/*****
* SIGNAL SegmentationReady
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),14)
******/
#define z_WDPPckg_A_SegmentationReady 27

/*****
* SIGNAL ReassembleReady
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),119(30,40),15)
******/
#define z_WDPPckg_B_ReassembleReady 28

/*****
* SIGNAL ReassemblyExpired
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),155(95,140),3)
******/
#define z_WDPPckg_C_ReassemblyExpired 29
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WDPPckg_C_ReassemblyExpired;

/*****
* SIGNAL SMS_USSDToSend
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(1),125(30,185),2)
******/
#define z_WDPPckg_D_SMS_USSDToSend 30
typedef struct {
    SIGNAL_VARS
    TDUnitdataReqType  Param1;
} yPDef_z_WDPPckg_D_SMS_USSDToSend;

/*****
* SIGNAL ReassAbortReq
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(2),149(30,115),2)
******/
#define z_WDPPckg_E_ReassAbortReq 31
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_WDPPckg_E_ReassAbortReq;

/*****
* SIGNAL UDCPSegSent
* <<PACKAGE WDPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wdppckg.sun(2),149(30,115),3)
******/
#define z_WDPPckg_F_UDCPSegSent 32

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
