/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_WTPpckg_H
#define XX_WTPpckg_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* NEWTYPE TransactionType  (TYPE section)
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(1),119(40,55),1)
******/
typedef struct TransactionType_s {
    SDL_Natural  dir;
    SDL_Natural  tid;
    SDL_Integer  handle;
    SDL_PId  pid;
    AddressType  clientAddress;
    AddressType  serverAddress;
} TransactionType;

/*****
* NEWTYPE TransactionType  (HEADING section)
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(1),119(40,55),1)
******/

#define yAssF_TransactionType(V,E,A)  V = E
extern void yDef_TransactionType XPP(( TransactionType * ));
#define yEqF_TransactionType(Expr1,Expr2)  (Expr1) == (Expr2)
#define yNEqF_TransactionType(Expr1,Expr2)  (Expr1) != (Expr2)
extern TransactionType yMake_TransactionType XPP(( SDL_Natural, SDL_Natural,
  SDL_Integer, SDL_PId, AddressType, AddressType ));
#ifndef ANY_TransactionType
#define ANY_TransactionType  yMake_TransactionType(ANY_SDL_Natural, \
  ANY_SDL_Natural, ANY_SDL_Integer, ANY_SDL_PId, ANY_AddressType, \
  ANY_AddressType)
#endif
#define z_WTPpckg_L3_copy(P)  P

/*****
* SIGNAL SendInvoke
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),2)
******/
#define z_WTPpckg_0_SendInvoke 242
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
    SDL_Boolean  Param2;
    TRInvokeReqType  Param3;
    SDL_Natural  Param4;
} yPDef_z_WTPpckg_0_SendInvoke;

/*****
* SIGNAL SegmInvoke
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),3)
******/
#define z_WTPpckg_1_SegmInvoke 243
typedef struct {
    SIGNAL_VARS
    TRInvokeReqType  Param1;
} yPDef_z_WTPpckg_1_SegmInvoke;

/*****
* SIGNAL ReceiveInvoke
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),4)
******/
#define z_WTPpckg_2_ReceiveInvoke 244
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    TDUnitdataIndType  Param4;
    SDL_Natural  Param5;
} yPDef_z_WTPpckg_2_ReceiveInvoke;

/*****
* SIGNAL ResultResp
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),5)
******/
#define z_WTPpckg_3_ResultResp 245
typedef struct {
    SIGNAL_VARS
    pdubuf_ptr  Param1;
} yPDef_z_WTPpckg_3_ResultResp;

/*****
* SIGNAL InvokeResp
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),6)
******/
#define z_WTPpckg_4_InvokeResp 246
typedef struct {
    SIGNAL_VARS
    pdubuf_ptr  Param1;
} yPDef_z_WTPpckg_4_InvokeResp;

/*****
* SIGNAL AbortReq
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),7)
******/
#define z_WTPpckg_5_AbortReq 247
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_WTPpckg_5_AbortReq;

/*****
* SIGNAL ReceiveResult
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),8)
******/
#define z_WTPpckg_6_ReceiveResult 248
typedef struct {
    SIGNAL_VARS
    TDUnitdataIndType  Param1;
} yPDef_z_WTPpckg_6_ReceiveResult;

/*****
* SIGNAL ReceiveAck
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),9)
******/
#define z_WTPpckg_7_ReceiveAck 249
typedef struct {
    SIGNAL_VARS
    TDUnitdataIndType  Param1;
} yPDef_z_WTPpckg_7_ReceiveAck;

/*****
* SIGNAL ReceiveNack
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),10)
******/
#define z_WTPpckg_8_ReceiveNack 250
typedef struct {
    SIGNAL_VARS
    TDUnitdataIndType  Param1;
} yPDef_z_WTPpckg_8_ReceiveNack;

/*****
* SIGNAL ReceiveAbort
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),11)
******/
#define z_WTPpckg_9_ReceiveAbort 251
typedef struct {
    SIGNAL_VARS
    TDUnitdataIndType  Param1;
} yPDef_z_WTPpckg_9_ReceiveAbort;

/*****
* SIGNAL ReceiveErrorPDU
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),12)
******/
#define z_WTPpckg_A_ReceiveErrorPDU 252

/*****
* SIGNAL Done
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),13)
******/
#define z_WTPpckg_B_Done 253
typedef struct {
    SIGNAL_VARS
    SDL_Boolean  Param1;
    SDL_Duration  Param2;
    SDL_Integer  Param3;
} yPDef_z_WTPpckg_B_Done;

/*****
* SIGNAL StopTrans
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),140(30,40),14)
******/
#define z_WTPpckg_C_StopTrans 254

/*****
* SIGNAL WTPWaitTimeout
* <<PACKAGE WTPpckg>>
* #SDTREF(SDL,D:\WIP\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wtppckg.sun(2),164(30,185),2)
******/
#define z_WTPpckg_D_WTPWaitTimeout 255
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WTPpckg_D_WTPWaitTimeout;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
