extern void SKY_wait (unsigned char viewId, char isWait);
extern void SKY_status (unsigned char viewId, unsigned char status, const char *URL);
extern void SKY_unknownContent (unsigned char viewId, const char *data, unsigned short length, const char *contentType, const char *URL);
extern void SKY_passwordDialog (unsigned char viewId, unsigned char dialogId, const char *realm, signed char type);
extern void SKY_promptDialog (unsigned char viewId, unsigned char dialogId, const unsigned short *message, const unsigned short *defaultMessage);
extern void SKY_confirmDialog (unsigned char viewId, unsigned char dialogId, const unsigned short *message, const unsigned short *ok, const unsigned short *cancel);
extern void SKY_alertDialog (unsigned char viewId, unsigned char dialogId, const unsigned short *message);
extern void SKY_newCard (unsigned char viewId, const unsigned short *title, char isList, char isRefresh, const char *URL, char isBookmarkable, const unsigned short * const *history);
extern void SKY_showCard (unsigned char viewId);
extern void SKY_cancelCard (unsigned char viewId);
extern void SKY_newKey (unsigned char viewId, unsigned char keyId, const unsigned short *eventType, const unsigned short *label, char isOptional);
extern void SKY_newText (unsigned char viewId, unsigned char textId, const unsigned short *text, char isLink, const unsigned short *linkTitle, signed char format);
extern void SKY_newImage (unsigned char viewId, unsigned char imageId, const char *imageData, unsigned short imageSize, const char *imageType, const unsigned short *altText, const unsigned short *localSrc, char isLink, const unsigned short *linkTitle, signed char vSpace, signed char hSpace, signed short width, signed short height, signed char isPercent, signed char align);
extern void SKY_completeImage (unsigned char viewId, unsigned char imageId, const char *imageData, unsigned short imageSize, const char *imageType);
extern void SKY_newParagraph (unsigned char viewId, signed char align, char wrap);
extern void SKY_closeParagraph (unsigned char viewId);
extern void SKY_newBreak (unsigned char viewId);
extern void SKY_newTable (unsigned char viewId, const unsigned short *title, signed char noOfColumns, const char *align);
extern void SKY_newTableData (unsigned char viewId);
extern void SKY_closeTable (unsigned char viewId);
extern void SKY_newFieldSet (unsigned char viewId, const unsigned short *title);
extern void SKY_closeFieldSet (unsigned char viewId);
extern void SKY_newSelect (unsigned char viewId, const unsigned short *title, char multiSelect, signed char tabIndex);
extern void SKY_closeSelect (unsigned char viewId);
extern void SKY_newOption (unsigned char viewId, unsigned char optionId, const unsigned short *label, const unsigned short *title, char isSelected);
extern void SKY_newOptionGroup (unsigned char viewId, const unsigned short *label);
extern void SKY_closeOptionGroup (unsigned char viewId);
extern void SKY_newInput (unsigned char viewId, unsigned char inputId, const unsigned short *title, const unsigned short *text, char isPassword, char emptyOk, const unsigned short *format, signed char size, signed char nchars, signed char tabIndex);
extern void SKY_getInputString (unsigned char viewId, unsigned char inputId);
extern void SKY_linkInfo (unsigned char viewId, unsigned char widgetType , unsigned char widgetId, const char *URL);
