


#if !defined(__dcoldnm_h__)
#define	__dcoldnm_h__


#define	QUEUE			MISCQUEUE


#define	InitRandomize		MiscInitRandomize
#define	Random8				MiscRandom8
#define	Random16			MiscRandom16
#define	Random32			MiscRandom32
#define	InitQueue			MiscInitQueue
#define	FlushQueue			MiscFlushQueue
#define	GetUsedQueueSize	MiscGetUsedQueueSize
#define	GetFreeQueueSize	MiscGetFreeQueueSize
#define	GetReadableQueue	MiscGetReadableQueue
#define	GetWritableQueue	MiscGetWritableQueue
#define	SkipReadQueue		MiscSkipReadQueue
#define	SkipWriteQueue		MiscSkipWriteQueue
#define	GetQueue			MiscGetQueue
#define	SenseQueue			MiscSenseQueue
#define	SetQueue			MiscSetQueue
#define	CopyQueue			MiscCopyQueue
#define	SetBigEndian16		MiscSetBigEndian16
#define	GetBigEndian16		MiscGetBigEndian16
#define	SetBigEndian32		MiscSetBigEndian32
#define	GetBigEndian32		MiscGetBigEndian32


#endif	