/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */
/*
 * ConTypes.h
 *
 * Generated by CreatePrefixTree.
 * DO NOT EDIT!!!
 * To add or modify the list of supported content types,
 * edit the file ContentTypes.txt and then run CreatePrefixTree.
 */

#ifndef _ConTypes_h
#define _ConTypes_h

#define WAP_USE_CHARACTERBELL 

#ifdef WAP_USE_CHARACTERBELL
	#define NUM_NODES  84
#else
	#define NUM_NODES  83
#endif//#ifdef WAP_USE_CHARACTERBELL

typedef struct node_s {
  char *s;
  unsigned char len;
  signed char sibling;
  signed char child;
  signed char parent;
  signed char idx;
} node_t;

const node_t treeNodes[NUM_NODES] = {
  {"*/*", 3, 1, -1, -1, 0},
  {"text/", 5, 15, 2, -1, -1},
  {"*", 1, 3, -1, 1, 1},
  {"html", 4, 4, -1, 1, 2},
  {"plain", 5, 5, -1, 1, 3},
  {"x", 1, 11, 55, 1, -1},
  {"hdml", 4, 7, -1, 55, 4},
  {"ttml", 4, 8, -1, 55, 5},
  {"vca", 3, 80, 9, 55, -1},
  {"lendar", 6, 10, -1, 8, 6},
  {"rd", 2, -1, -1, 8, 7},
  {"vnd.wap.", 8, -1, 13, 1, -1},
  {"script", 6, -1, -1, 13, 9},
  {"wml", 3, 14, 12, 11, 8},
  {"c", 1, 64, 70, 11, -1},
  {"multipart/", 10, 21, 16, -1, -1},
  {"*", 1, 17, -1, 15, 11},
  {"mixed", 5, 18, -1, 15, 12},
  {"form-data", 9, 19, -1, 15, 13},
  {"byteranges", 10, 20, -1, 15, 14},
  {"alternative", 11, -1, -1, 15, 15},
  {"application/", 12, 40, 22, -1, -1},//21
  {"*", 1, 23, -1, 21, 16},
  {"java-vm", 7, 24, -1, 21, 17},
  {"x", 1, 27, 53, 21, -1},//24
  {"w", 1, 26, 81, 53, -1},//25
  {"hdmlc", 5, 37, -1, 53, 19},//26
  {"vnd.wap.", 8, -1, 30, 21, -1},
  {"c", 1, 29, -1, 33, 20},
  {"scriptc", 7, -1, -1, 33, 21},
  {"w", 1, 31, 33, 27, -1},
  {"c", 1, 32, 72, 27, -1},
  {"uaprof", 6, 47, -1, 27, 23},
  {"ml", 2, 34, 28, 30, -1},
  {"tls-", 4, 57, 35, 30, -1},
  {"ca-certificate", 14, 36, -1, 34, 24},
  {"user-certificate", 16, -1, -1, 34, 25},
#ifdef WAP_USE_CHARACTERBELL
  {"x", 1, 83, 58, 53, -1},//37
#else
  {"x", 1, -1, 58, 53, -1},//37
#endif//#ifdef WAP_USE_CHARACTERBELL
  {"ca-cert", 7, 39, -1, 58, 26},
  {"user-cert", 9, -1, -1, 58, 27},
  {"image/", 6, -1, 41, -1, -1},
  {"*", 1, 42, -1, 40, 28},
  {"gif", 3, 43, -1, 40, 29},
  {"jpeg", 4, 44, -1, 40, 30},
  {"tiff", 4, 45, -1, 40, 31},
  {"png", 3, 46, -1, 40, 32},
  {"vnd.wap.wbmp", 12, -1, -1, 40, 33},
  {"multipart.", 10, 65, 48, 27, -1},
  {"*", 1, 49, -1, 47, 34},
  {"mixed", 5, 50, -1, 47, 35},
  {"form-data", 9, 51, -1, 47, 36},
  {"byteranges", 10, 52, -1, 47, 37},
  {"alternative", 11, 74, -1, 47, 38},
  {"-", 1, 54, 25, 24, -1},//53
  {"ml", 2, -1, -1, 24, 39},
  {"-", 1, 56, 6, 5, -1},
  {"ml", 2, -1, -1, 5, 40},
  {"bxml", 4, -1, -1, 30, 41},
  {"509-", 4, 59, 38, 37, -1},
  {"968-", 4, -1, 62, 37, -1},
  {"ross-cert", 9, 61, -1, 62, 42},//60
  {"a-cert", 6, -1, -1, 62, 43},
  {"c", 1, 63, 60, 59, -1},
  {"user-cert", 9, -1, -1, 59, 44},
  {"s", 1, -1, 66, 11, -1},
  {"s", 1, -1, 68, 27, -1},
  {"i", 1, 67, -1, 64, 45},
  {"l", 1, -1, -1, 64, 47},
  {"i", 1, 69, 75, 65, -1},
  {"lc", 2, -1, -1, 65, 48},
  {"hannel", 6, 71, -1, 14, 10},//70
  {"o", 1, -1, 77, 14, 49},
  {"hannelc", 7, 73, -1, 31, 22},
  {"o", 1, -1, 78, 31, -1},
  {"related", 7, -1, -1, 47, 51},
  {"c", 1, 76, -1, 68, 46},
  {"a", 1, -1, -1, 68, 52},
  {"nnectivity-xml", 14, -1, -1, 71, 53},
  {"c", 1, 79, -1, 73, 50},
  {"nnectivity-wbxml", 16, -1, -1, 73, 54},
  {"wap-wta-wml", 11, -1, -1, 55, 55},//80
  {"ww-form-urlencoded", 18, 82, -1, 25, 18},
  {"ap-wta-wmlc", 11, -1, -1, 25, 56}
#ifdef WAP_USE_CHARACTERBELL
  ,{"cmf",3,-1,-1, 53, 106}//83
#endif//#ifdef WAP_USE_CHARACTERBELL 

};

#endif
