/*
 * Copyright (C) Ericsson Mobile Communications AB, 2001.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */


#ifndef XX_WSPWTP_WTLS_H
#define XX_WSPWTP_WTLS_H

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif
/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

extern void yInit_WSPWTP_WTLS XPP((void));

/*****
* SIGNAL EstablishWTLSSession
* <<PACKAGE WSPWTP_WTLS>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wspwtp_wtls.sun(1),161(30,40),2)
******/
#define z_WSPWTP_WTLS_0_EstablishWTLSSession 221
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    AddressType  Param2;
    AddressType  Param3;
    SDL_Integer  Param4;
    z_ctypes_4_VoidStar  Param5;
    SDL_Boolean  Param6;
} yPDef_z_WSPWTP_WTLS_0_EstablishWTLSSession;

/*****
* SIGNAL EstablishWTLSSessionDone
* <<PACKAGE WSPWTP_WTLS>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\wspwtp_wtls.sun(1),161(30,40),4)
******/
#define z_WSPWTP_WTLS_1_EstablishWTLSSessionDone 222
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Octet  Param2;
} yPDef_z_WSPWTP_WTLS_1_EstablishWTLSSessionDone;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
