/*
 * Copyright (C) Ericsson Mobile Communications AB, 2001.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */


#ifndef XX_StackMgr_H
#define XX_StackMgr_H

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif
/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SIGNAL StartWAPStack
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),2)
******/
#define z_StackMgr_0_StartWAPStack 164

/*****
* SIGNAL StartResult
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),3)
******/
#define z_StackMgr_1_StartResult 165
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_StackMgr_1_StartResult;

/*****
* SIGNAL CRYPTcInitialiseResponse
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),4)
******/
#define z_StackMgr_2_CRYPTcInitialiseResponse 166
typedef struct {
    SIGNAL_VARS
    SDL_PId  Param1;
    SDL_Integer  Param2;
} yPDef_z_StackMgr_2_CRYPTcInitialiseResponse;

/*****
* SIGNAL StartWAE
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),5)
******/
#define z_StackMgr_3_StartWAE 167

/*****
* SIGNAL StartWSP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),6)
******/
#define z_StackMgr_4_StartWSP 168

/*****
* SIGNAL StartWTP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),7)
******/
#define z_StackMgr_5_StartWTP 169

/*****
* SIGNAL StartWTLS
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),8)
******/
#define z_StackMgr_6_StartWTLS 170

/*****
* SIGNAL StartWDP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),9)
******/
#define z_StackMgr_7_StartWDP 171

/*****
* SIGNAL StartUDCP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),10)
******/
#define z_StackMgr_8_StartUDCP 172

/*****
* SIGNAL Ready
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),11)
******/
#define z_StackMgr_9_Ready 173
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_StackMgr_9_Ready;

/*****
* SIGNAL TerminateWAPStack
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),12)
******/
#define z_StackMgr_A_TerminateWAPStack 174

/*****
* SIGNAL TerminateWAE
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),13)
******/
#define z_StackMgr_B_TerminateWAE 175

/*****
* SIGNAL TerminateWSP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),14)
******/
#define z_StackMgr_C_TerminateWSP 176

/*****
* SIGNAL TerminateWTP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),15)
******/
#define z_StackMgr_D_TerminateWTP 177

/*****
* SIGNAL TerminateWTLS
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),16)
******/
#define z_StackMgr_E_TerminateWTLS 178

/*****
* SIGNAL TerminateWDP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),17)
******/
#define z_StackMgr_F_TerminateWDP 179

/*****
* SIGNAL TerminateUDCP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\stackmgr.sun(1),119(20,40),18)
******/
#define z_StackMgr_G_TerminateUDCP 180

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
