/*
 * Copyright (C) Ericsson Mobile Communications AB, 2001.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */


#ifndef XX_WAEPackage_H
#define XX_WAEPackage_H

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif
/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

extern void yInit_WAEPackage XPP((void));

/*****
* SYNONYM MAXNUMBEROFWMLUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),302(30,90),3)
******/
#define z_WAEPackage_3R_MAXNUMBEROFWMLUA SDL_INTEGER_LIT(5)

/*****
* NEWTYPE RequestType  (TYPE section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),1)
******/
typedef struct z_WAEPackage_32_RequestType_s {
    SDL_Integer  ViewID;
    SDL_Integer  UA_Type;
    SDL_Integer  Scheme;
    SDL_Integer  TID;
    z_ctypes_4_VoidStar  RequestStruct;
    SDL_Octet  Options;
    SDL_Integer  Prio;
} z_WAEPackage_32_RequestType;

/*****
* NEWTYPE ResponseType  (TYPE section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),11)
******/
typedef struct z_WAEPackage_33_ResponseType_s {
    SDL_Integer  Scheme;
    SDL_Integer  TID;
    z_ctypes_4_VoidStar  HeaderHandle;
    z_ctypes_4_VoidStar  ContentType;
    z_ctypes_4_VoidStar  BodyData;
    SDL_Integer  BodyDataLength;
    SDL_Octet  Status;
    z_ctypes_4_VoidStar  ExtParameters;
    SDL_Boolean  MoreData;
    SDL_Natural  TotalSize;
} z_WAEPackage_33_ResponseType;

/*****
* NEWTYPE RequestType  (HEADING section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),1)
******/

#define yAssF_z_WAEPackage_32_RequestType(V,E,A)  V = E
extern void yDef_z_WAEPackage_32_RequestType
  XPP(( z_WAEPackage_32_RequestType * ));
extern SDL_Boolean yEq_z_WAEPackage_32_RequestType
  XPP(( z_WAEPackage_32_RequestType, z_WAEPackage_32_RequestType ));
#define yEqF_z_WAEPackage_32_RequestType(Expr1,Expr2)  yEq_z_WAEPackage_32_RequestType(Expr1,Expr2)
#define yNEqF_z_WAEPackage_32_RequestType(Expr1,Expr2)  ( ! yEq_z_WAEPackage_32_RequestType(Expr1,Expr2) )
extern z_WAEPackage_32_RequestType yMake_z_WAEPackage_32_RequestType
  XPP(( SDL_Integer, SDL_Integer, SDL_Integer, SDL_Integer,
  z_ctypes_4_VoidStar, SDL_Octet, SDL_Integer ));
#ifndef ANY_z_WAEPackage_32_RequestType
#define ANY_z_WAEPackage_32_RequestType  yMake_z_WAEPackage_32_RequestType(ANY_SDL_Integer, \
  ANY_SDL_Integer, ANY_SDL_Integer, ANY_SDL_Integer, ANY_z_ctypes_4_VoidStar, \
  ANY_SDL_Octet, ANY_SDL_Integer)
#endif
#define z_WAEPackage_323_copy(P)  P

/*****
* NEWTYPE ResponseType  (HEADING section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),530(20,40),11)
******/

#define yAssF_z_WAEPackage_33_ResponseType(V,E,A)  V = E
extern void yDef_z_WAEPackage_33_ResponseType
  XPP(( z_WAEPackage_33_ResponseType * ));
extern SDL_Boolean yEq_z_WAEPackage_33_ResponseType
  XPP(( z_WAEPackage_33_ResponseType, z_WAEPackage_33_ResponseType ));
#define yEqF_z_WAEPackage_33_ResponseType(Expr1,Expr2)  yEq_z_WAEPackage_33_ResponseType(Expr1,Expr2)
#define yNEqF_z_WAEPackage_33_ResponseType(Expr1,Expr2)  ( ! yEq_z_WAEPackage_33_ResponseType(Expr1,Expr2) )
extern z_WAEPackage_33_ResponseType yMake_z_WAEPackage_33_ResponseType
  XPP(( SDL_Integer, SDL_Integer, z_ctypes_4_VoidStar, z_ctypes_4_VoidStar,
  z_ctypes_4_VoidStar, SDL_Integer, SDL_Octet, z_ctypes_4_VoidStar,
  SDL_Boolean, SDL_Natural ));
#ifndef ANY_z_WAEPackage_33_ResponseType
#define ANY_z_WAEPackage_33_ResponseType  yMake_z_WAEPackage_33_ResponseType(ANY_SDL_Integer, \
  ANY_SDL_Integer, ANY_z_ctypes_4_VoidStar, ANY_z_ctypes_4_VoidStar, \
  ANY_z_ctypes_4_VoidStar, ANY_SDL_Integer, ANY_SDL_Octet, \
  ANY_z_ctypes_4_VoidStar, ANY_SDL_Boolean, ANY_SDL_Natural)
#endif
#define z_WAEPackage_333_copy(P)  P

/*****
* SYNONYM Get
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),287(30,55),13)
******/
extern SDL_Octet  z_WAEPackage_34_Get;

/*****
* SYNONYM Post
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),287(30,55),14)
******/
extern SDL_Octet  z_WAEPackage_35_Post;

/*****
* SYNONYM application_vnd_wap.wmlc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),23)
******/
extern SDL_Octet  z_WAEPackage_36_application_vnd_wapwmlc;

/*****
* SYNONYM application_vnd_wap.wbxml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),24)
******/
extern SDL_Octet  z_WAEPackage_37_application_vnd_wapwbxml;

/*****
* SYNONYM application_vnd_wap.wmlscriptc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),25)
******/
extern SDL_Octet  z_WAEPackage_38_application_vnd_wapwmlscriptc;

/*****
* SYNONYM application_vnd_wap.channelc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),26)
******/
extern SDL_Octet  z_WAEPackage_39_application_vnd_wapchannelc;

/*****
* SYNONYM application_x_wap_wta.wmlc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),32)
******/
extern SDL_Octet  z_WAEPackage_3A_application_x_wap_wtawmlc;

/*****
* SYNONYM application_vnd_wap_connectivity.wbxml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),290(55,55),45)
******/
extern SDL_Octet  z_WAEPackage_3B_application_vnd_wap_connectivitywbxml;

/*****
* SYNONYM Continued
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),3)
******/
extern SDL_Octet  z_WAEPackage_3C_Continued;

/*****
* SYNONYM SwitchingProtocols
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),4)
******/
extern SDL_Octet  z_WAEPackage_3D_SwitchingProtocols;

/*****
* SYNONYM RequestOK
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),6)
******/
extern SDL_Octet  z_WAEPackage_3E_RequestOK;

/*****
* SYNONYM Created
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),9)
******/
extern SDL_Octet  z_WAEPackage_3F_Created;

/*****
* SYNONYM MultipleChoices
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),18)
******/
extern SDL_Octet  z_WAEPackage_3G_MultipleChoices;

/*****
* SYNONYM MovedPermanently
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),19)
******/
extern SDL_Octet  z_WAEPackage_3H_MovedPermanently;

/*****
* SYNONYM MovedTemporarily
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),20)
******/
extern SDL_Octet  z_WAEPackage_3I_MovedTemporarily;

/*****
* SYNONYM SeeOther
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),21)
******/
extern SDL_Octet  z_WAEPackage_3J_SeeOther;

/*****
* SYNONYM NotModified
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),22)
******/
extern SDL_Octet  z_WAEPackage_3K_NotModified;

/*****
* SYNONYM UseProxy
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),23)
******/
extern SDL_Octet  z_WAEPackage_3L_UseProxy;

/*****
* SYNONYM TemporaryRedirect
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),24)
******/
extern SDL_Octet  z_WAEPackage_3M_TemporaryRedirect;

/*****
* SYNONYM Unauthorized
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),30)
******/
extern SDL_Octet  z_WAEPackage_3N_Unauthorized;

/*****
* SYNONYM Forbidden
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),33)
******/
extern SDL_Octet  z_WAEPackage_3O_Forbidden;

/*****
* SYNONYM NotFound
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),35)
******/
extern SDL_Octet  z_WAEPackage_3P_NotFound;

/*****
* SYNONYM ProxyAuthenticationRequired
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WAEDeclarations),296(55,70),41)
******/
extern SDL_Octet  z_WAEPackage_3Q_ProxyAuthenticationRequired;

/*****
* SIGNAL GetContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(150,30),8)
******/
#define z_WAEPackage_00_GetContent 34
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_00_GetContent;

/*****
* SIGNAL PostContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(150,30),9)
******/
#define z_WAEPackage_01_PostContent 35
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
    SDL_Integer  Param6;
    SDL_Boolean  Param7;
    z_ctypes_4_VoidStar  Param8;
    SDL_Integer  Param9;
    z_ctypes_4_VoidStar  Param10;
    SDL_Natural  Param11;
} yPDef_z_WAEPackage_01_PostContent;

/*****
* SIGNAL AcknowledgeContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(150,30),11)
******/
#define z_WAEPackage_02_AcknowledgeContent 36
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_02_AcknowledgeContent;

/*****
* SIGNAL CancelContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(150,30),12)
******/
#define z_WAEPackage_03_CancelContent 37
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_03_CancelContent;

/*****
* SIGNAL PostMoreContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),197(150,30),13)
******/
#define z_WAEPackage_04_PostMoreContent 38
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    SDL_Boolean  Param4;
} yPDef_z_WAEPackage_04_PostMoreContent;

/*****
* SIGNAL InputString
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),3)
******/
#define z_WAEPackage_05_InputString 39
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_05_InputString;

/*****
* SIGNAL LoadURL
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),4)
******/
#define z_WAEPackage_06_LoadURL 40
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Boolean  Param3;
} yPDef_z_WAEPackage_06_LoadURL;

/*****
* SIGNAL ReloadCard
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),5)
******/
#define z_WAEPackage_07_ReloadCard 41
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_07_ReloadCard;

/*****
* SIGNAL OpenView
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),6)
******/
#define z_WAEPackage_08_OpenView 42
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_08_OpenView;

/*****
* SIGNAL CloseView
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),7)
******/
#define z_WAEPackage_09_CloseView 43
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_09_CloseView;

/*****
* SIGNAL DiscardAllContext
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),8)
******/
#define z_WAEPackage_0A_DiscardAllContext 44

/*****
* SIGNAL Abort
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),9)
******/
#define z_WAEPackage_0B_Abort 45
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_0B_Abort;

/*****
* SIGNAL GoBack
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),10)
******/
#define z_WAEPackage_0C_GoBack 46
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_0C_GoBack;

/*****
* SIGNAL WTAResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),11)
******/
#define z_WAEPackage_0D_WTAResponse 47
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_0D_WTAResponse;

/*****
* SIGNAL InputStringProvE2Esec
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),12)
******/
#define z_WAEPackage_0E_InputStringProvE2Esec 48
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_Integer  Param4;
    z_ctypes_A_UnsignedLongInt  Param5;
    SDL_Integer  Param6;
    z_ctypes_4_VoidStar  Param7;
} yPDef_z_WAEPackage_0E_InputStringProvE2Esec;

/*****
* SIGNAL ProvSharedSecret
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),191(5,40),14)
******/
#define z_WAEPackage_0F_ProvSharedSecret 49
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    SDL_Boolean  Param4;
} yPDef_z_WAEPackage_0F_ProvSharedSecret;

/*****
* SIGNAL InitCache
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(150,80),11)
******/
#define z_WAEPackage_0G_InitCache 50
typedef struct {
    SIGNAL_VARS
    z_ctypes_7_LongInt  Param1;
} yPDef_z_WAEPackage_0G_InitCache;

/*****
* SIGNAL PrepareCache
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(150,80),12)
******/
#define z_WAEPackage_0H_PrepareCache 51
typedef struct {
    SIGNAL_VARS
    z_ctypes_7_LongInt  Param1;
} yPDef_z_WAEPackage_0H_PrepareCache;

/*****
* SIGNAL PasswordDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(150,80),13)
******/
#define z_WAEPackage_0I_PasswordDialogResponse 52
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_0I_PasswordDialogResponse;

/*****
* SIGNAL SetupConnectionDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(150,80),15)
******/
#define z_WAEPackage_0J_SetupConnectionDone 53
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Boolean  Param3;
} yPDef_z_WAEPackage_0J_SetupConnectionDone;

/*****
* SIGNAL CloseConnection
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(150,80),16)
******/
#define z_WAEPackage_0K_CloseConnection 54
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Boolean  Param3;
} yPDef_z_WAEPackage_0K_CloseConnection;

/*****
* SIGNAL RequestConnectionDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(150,80),17)
******/
#define z_WAEPackage_0L_RequestConnectionDone 55
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Boolean  Param2;
} yPDef_z_WAEPackage_0L_RequestConnectionDone;

/*****
* SIGNAL E2ESecurityConfigured
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),200(150,80),18)
******/
#define z_WAEPackage_0M_E2ESecurityConfigured 56
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Boolean  Param2;
} yPDef_z_WAEPackage_0M_E2ESecurityConfigured;

/*****
* SIGNAL KeySelected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(165,160),3)
******/
#define z_WAEPackage_0N_KeySelected 57
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0N_KeySelected;

/*****
* SIGNAL TextSelected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(165,160),4)
******/
#define z_WAEPackage_0O_TextSelected 58
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0O_TextSelected;

/*****
* SIGNAL ImageSelected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(165,160),5)
******/
#define z_WAEPackage_0P_ImageSelected 59
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0P_ImageSelected;

/*****
* SIGNAL ChangeOptionState
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(165,160),6)
******/
#define z_WAEPackage_0Q_ChangeOptionState 60
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0Q_ChangeOptionState;

/*****
* SIGNAL LinkInfo
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),356(165,160),7)
******/
#define z_WAEPackage_0R_LinkInfo 61
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_0R_LinkInfo;

/*****
* SIGNAL PromptDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(5,165),3)
******/
#define z_WAEPackage_0S_PromptDialogResponse 62
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_0S_PromptDialogResponse;

/*****
* SIGNAL ConfirmDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(5,165),4)
******/
#define z_WAEPackage_0T_ConfirmDialogResponse 63
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_0T_ConfirmDialogResponse;

/*****
* SIGNAL AlertDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(5,165),5)
******/
#define z_WAEPackage_0U_AlertDialogResponse 64
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0U_AlertDialogResponse;

/*****
* SIGNAL TextSigned
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(5,165),6)
******/
#define z_WAEPackage_0V_TextSigned 65
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_Integer  Param4;
    z_ctypes_4_VoidStar  Param5;
    z_ctypes_4_VoidStar  Param6;
    SDL_Integer  Param7;
    z_ctypes_4_VoidStar  Param8;
    SDL_Integer  Param9;
    SDL_Integer  Param10;
    SDL_Integer  Param11;
} yPDef_z_WAEPackage_0V_TextSigned;

/*****
* SIGNAL WMLSLibFuncResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(EnvironmentSignals),179(5,165),7)
******/
#define z_WAEPackage_0W_WMLSLibFuncResponse 66
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z_WAEPackage_0W_WMLSLibFuncResponse;

/*****
* SIGNAL StartUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),5)
******/
#define z_WAEPackage_0X_StartUA 67
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z_WAEPackage_0X_StartUA;

/*****
* SIGNAL TerminateUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),6)
******/
#define z_WAEPackage_0Y_TerminateUA 68

/*****
* SIGNAL TerminateUACnf
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),11)
******/
#define z_WAEPackage_0Z_TerminateUACnf 69

/*****
* SIGNAL StartWMLS
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),17)
******/
#define z_WAEPackage_10_StartWMLS 70

/*****
* SIGNAL TerminateWMLS
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),18)
******/
#define z_WAEPackage_11_TerminateWMLS 71

/*****
* SIGNAL TerminateWMLSCnf
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(InitSignals),266(30,40),23)
******/
#define z_WAEPackage_12_TerminateWMLSCnf 72

/*****
* SIGNAL AbortScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),13)
******/
#define z_WAEPackage_13_AbortScript 73
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_13_AbortScript;

/*****
* SIGNAL InvokeScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),14)
******/
#define z_WAEPackage_14_InvokeScript 74
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
    SDL_Integer  Param6;
} yPDef_z_WAEPackage_14_InvokeScript;

/*****
* SIGNAL LoadDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),17)
******/
#define z_WAEPackage_15_LoadDone 75
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    SDL_Integer  Param4;
} yPDef_z_WAEPackage_15_LoadDone;

/*****
* SIGNAL LoadStringDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),20)
******/
#define z_WAEPackage_16_LoadStringDone 76
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    z_ctypes_9_UnsignedInt  Param4;
} yPDef_z_WAEPackage_16_LoadStringDone;

/*****
* SIGNAL LoadStringError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),23)
******/
#define z_WAEPackage_17_LoadStringError 77
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_17_LoadStringError;

/*****
* SIGNAL LoadError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),24)
******/
#define z_WAEPackage_18_LoadError 78
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_18_LoadError;

/*****
* SIGNAL InvokeWTAIFromScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),25)
******/
#define z_WAEPackage_19_InvokeWTAIFromScript 79
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_19_InvokeWTAIFromScript;

/*****
* SIGNAL WTAIResultInfoScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),26)
******/
#define z_WAEPackage_1A_WTAIResultInfoScript 80
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_1A_WTAIResultInfoScript;

/*****
* SIGNAL RefreshDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),27)
******/
#define z_WAEPackage_1B_RefreshDone 81
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1B_RefreshDone;

/*****
* SIGNAL InvokeDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),40)
******/
#define z_WAEPackage_1C_InvokeDone 82
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    SDL_Integer  Param4;
    z_ctypes_4_VoidStar  Param5;
} yPDef_z_WAEPackage_1C_InvokeDone;

/*****
* SIGNAL InvokeStatus
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),41)
******/
#define z_WAEPackage_1D_InvokeStatus 83
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1D_InvokeStatus;

/*****
* SIGNAL LoadBP
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),42)
******/
#define z_WAEPackage_1E_LoadBP 84
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z_WAEPackage_1E_LoadBP;

/*****
* SIGNAL LoadString
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),43)
******/
#define z_WAEPackage_1F_LoadString 85
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_1F_LoadString;

/*****
* SIGNAL RefreshReqFromWmls
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WMLSSignals),218(25,45),44)
******/
#define z_WAEPackage_1G_RefreshReqFromWmls 86
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1G_RefreshReqFromWmls;

/*****
* SIGNAL GetFileResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(FILESignals),338(60,50),4)
******/
#define z_WAEPackage_1H_GetFileResponse 87
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_1H_GetFileResponse;

/*****
* SIGNAL CallFunctionResult
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(FILESignals),338(60,50),5)
******/
#define z_WAEPackage_1I_CallFunctionResult 88
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
} yPDef_z_WAEPackage_1I_CallFunctionResult;

/*****
* SIGNAL FileFunctionTimer
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(FILESignals),338(60,50),6)
******/
#define z_WAEPackage_1J_FileFunctionTimer 89
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_WAEPackage_1J_FileFunctionTimer;

/*****
* SIGNAL WSPRequest
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),4)
******/
#define z_WAEPackage_1K_WSPRequest 90
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_32_RequestType  Param1;
} yPDef_z_WAEPackage_1K_WSPRequest;

/*****
* SIGNAL WSPAbortRequest
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),5)
******/
#define z_WAEPackage_1L_WSPAbortRequest 91
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1L_WSPAbortRequest;

/*****
* SIGNAL WSPAckGetContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),7)
******/
#define z_WAEPackage_1M_WSPAckGetContent 92
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1M_WSPAckGetContent;

/*****
* SIGNAL StartWSPIFDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),20)
******/
#define z_WAEPackage_1N_StartWSPIFDone 93

/*****
* SIGNAL TerminateWSPIFDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),21)
******/
#define z_WAEPackage_1O_TerminateWSPIFDone 94

/*****
* SIGNAL StartWSPIF
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),29)
******/
#define z_WAEPackage_1P_StartWSPIF 95
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z_WAEPackage_1P_StartWSPIF;

/*****
* SIGNAL TerminateWSPIF
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),533(105,40),30)
******/
#define z_WAEPackage_1Q_TerminateWSPIF 96

/*****
* SIGNAL WSPResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),536(20,130),4)
******/
#define z_WAEPackage_1R_WSPResponse 97
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_33_ResponseType  Param1;
} yPDef_z_WAEPackage_1R_WSPResponse;

/*****
* SIGNAL WSPError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),536(20,130),5)
******/
#define z_WAEPackage_1S_WSPError 98
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_1S_WSPError;

/*****
* SIGNAL WSPAckPostContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(WSPIFSignals),536(20,130),7)
******/
#define z_WAEPackage_1T_WSPAckPostContent 99
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1T_WSPAckPostContent;

/*****
* SIGNAL StartDI
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),18)
******/
#define z_WAEPackage_1U_StartDI 100

/*****
* SIGNAL TerminateDI
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),19)
******/
#define z_WAEPackage_1V_TerminateDI 101

/*****
* SIGNAL SMNewSession
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),20)
******/
#define z_WAEPackage_1W_SMNewSession 102
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
    SDL_PId  Param6;
} yPDef_z_WAEPackage_1W_SMNewSession;

/*****
* SIGNAL SMTerminateSession
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),21)
******/
#define z_WAEPackage_1X_SMTerminateSession 103

/*****
* SIGNAL SMNewTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),22)
******/
#define z_WAEPackage_1Y_SMNewTransaction 104
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_32_RequestType  Param1;
    SDL_PId  Param2;
} yPDef_z_WAEPackage_1Y_SMNewTransaction;

/*****
* SIGNAL SMAbortTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),23)
******/
#define z_WAEPackage_1Z_SMAbortTransaction 105
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1Z_SMAbortTransaction;

/*****
* SIGNAL SMBasicAuth
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),25)
******/
#define z_WAEPackage_20_SMBasicAuth 106
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_20_SMBasicAuth;

/*****
* SIGNAL SMReConnect
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),27)
******/
#define z_WAEPackage_21_SMReConnect 107

/*****
* SIGNAL SMTerminateBearer
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),28)
******/
#define z_WAEPackage_22_SMTerminateBearer 108
typedef struct {
    SIGNAL_VARS
    SDL_Octet  Param1;
} yPDef_z_WAEPackage_22_SMTerminateBearer;

/*****
* SIGNAL SMPushIndicationResp
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),30)
******/
#define z_WAEPackage_23_SMPushIndicationResp 109
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_23_SMPushIndicationResp;

/*****
* SIGNAL SMSetupConnectionDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),32)
******/
#define z_WAEPackage_24_SMSetupConnectionDone 110
typedef struct {
    SIGNAL_VARS
    SDL_Boolean  Param1;
} yPDef_z_WAEPackage_24_SMSetupConnectionDone;

/*****
* SIGNAL SMCloseConnection
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),34)
******/
#define z_WAEPackage_25_SMCloseConnection 111
typedef struct {
    SIGNAL_VARS
    SDL_Boolean  Param1;
} yPDef_z_WAEPackage_25_SMCloseConnection;

/*****
* SIGNAL WSPIFAckRes
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),36)
******/
#define z_WAEPackage_26_WSPIFAckRes 112
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_26_WSPIFAckRes;

/*****
* SIGNAL SessionProcInstalled
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),53)
******/
#define z_WAEPackage_27_SessionProcInstalled 113
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_PId  Param3;
} yPDef_z_WAEPackage_27_SessionProcInstalled;

/*****
* SIGNAL StartDIDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),54)
******/
#define z_WAEPackage_28_StartDIDone 114

/*****
* SIGNAL TerminateDIDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),55)
******/
#define z_WAEPackage_29_TerminateDIDone 115

/*****
* SIGNAL SMTerminateSessionDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),56)
******/
#define z_WAEPackage_2A_SMTerminateSessionDone 116

/*****
* SIGNAL GetNextTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),57)
******/
#define z_WAEPackage_2B_GetNextTransaction 117

/*****
* SIGNAL Connected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),58)
******/
#define z_WAEPackage_2C_Connected 118
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_2C_Connected;

/*****
* SIGNAL StoreTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),60)
******/
#define z_WAEPackage_2D_StoreTransaction 119
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_32_RequestType  Param1;
    SDL_PId  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_2D_StoreTransaction;

/*****
* SIGNAL WSPIFResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),61)
******/
#define z_WAEPackage_2E_WSPIFResponse 120
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_33_ResponseType  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    SDL_PId  Param4;
    SDL_Integer  Param5;
    SDL_Integer  Param6;
    z_WAEPackage_32_RequestType  Param7;
    SDL_Integer  Param8;
} yPDef_z_WAEPackage_2E_WSPIFResponse;

/*****
* SIGNAL WSPIFError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),63)
******/
#define z_WAEPackage_2F_WSPIFError 121
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_PId  Param3;
} yPDef_z_WAEPackage_2F_WSPIFError;

/*****
* SIGNAL WSPIFPushIndication
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),65)
******/
#define z_WAEPackage_2G_WSPIFPushIndication 122
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_Boolean  Param4;
    SDL_Integer  Param5;
    SDL_Integer  Param6;
    z_ctypes_4_VoidStar  Param7;
    z_ctypes_4_VoidStar  Param8;
    SDL_Integer  Param9;
} yPDef_z_WAEPackage_2G_WSPIFPushIndication;

/*****
* SIGNAL WSPIFAckCnf
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\packages\waepackage.sun(ResourceHandler),524(25,25),67)
******/
#define z_WAEPackage_2H_WSPIFAckCnf 123
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_PId  Param2;
} yPDef_z_WAEPackage_2H_WSPIFAckCnf;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
