/*
 * Copyright (C) Ericsson Mobile Communications AB, 2001.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#define C_MICRO_1_3
#include "ml_typw.h"
#include "ctypes.h"
#include "buffmgt.h"
#include "glbldecl.h"
#include "wdp_ul.h"
#include "wtlspckg.h"
#include "wtls_wdp.h"
#include "wdppckg.h"
#include "wdp_udp.h"
#include "wspcmwtp.h"
#include "wtppckg.h"
#include "wtp_wdp.h"
#include "sptp_tls.h"
#include "wspclwdp.h"
#include "waepckg.h"
#include "wtapckg.h"
#include "pushpckg.h"
#include "wae_wsp.h"
#include "stackmgr.h"
#include "wap.h"

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PROCESS WDPhandler
* <<SYSTEM WAP/BLOCK WDP>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z58_WDPhandler)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),872(30,20),2) */
    z_ctypes_4_VoidStar  z587_UDPData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),872(30,20),3) */
    DeviceAddress  z588_dstAddr;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),872(30,20),3) */
    DeviceAddress  z589_srcAddr;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),872(30,20),4) */
    pdubuf_ptr  z58A_tmpBuf;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),2) */
    SDL_Integer  z58B_srcPort;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),2) */
    SDL_Integer  z58C_dstPort;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),3) */
    SDL_Natural  z58D_DataLen;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),3) */
    SDL_Natural  z58E_FaultCode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),4) */
    SDL_Boolean  z58F_ok;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),239(30,65),2) */
    TDUnitdataReqType  z58G_dataReq;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),239(30,65),3) */
    TDUnitdataIndType  z58H_dataInd;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),2) */
    SDL_Integer  z58I_port;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),3) */
    SDL_PId  z58J_upperlayerPId;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),4) */
    SDL_Natural  z58K_stackconfig;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),5) */
    SDL_Octet  z58L_bearer;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),6) */
    SDL_Octet  z58M_viewID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),7) */
    SDL_Octet  z58N_channelID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),3143(30,85),8) */
    SDL_Octet  z58O_newChannelID;
    SDL_Octet  yDcn_SDL_Octet;
} yVDef_z58_WDPhandler;
#define z585_AwaitStart  1
#define z586_IDLE  2

/*****
* PROCESS WDPmanagement
* <<SYSTEM WAP/BLOCK WDP>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z59_WDPmanagement)
typedef struct {
    PROCESS_VARS
} yVDef_z59_WDPmanagement;
#define z590_AwaitStartWDP  1
#define z591_AwaitReady  2
#define z592_AwaitWDPhReady  3
#define z593_AwaitReassembleReady  4
#define z594_idle  5
#define z595_AwaitTerminated  6
#define z596_AwaitWDPhTerminated  7
#define z597_AwaitReassembleTerminated  8

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
                /* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(Definitions),287(30,45),4) */
#include "wdpsuppt.h"
#include "capiclnt.h"
#include "dbfunct.h"
#include "wipdb.h"


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PROCESS WDPhandler
* <<SYSTEM WAP/BLOCK WDP>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr,4,1)
******/

/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
** Tables for process WDPhandler
** #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr,4,1)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

/*--------------Instance Data---------------*/
#define X_MAX_INST_z58_WDPhandler 1
static yVDef_z58_WDPhandler *yINSTD_z58_WDPhandler[X_MAX_INST_z58_WDPhandler];

/*--------------Process State---------------*/
static xSTATE yPSTATETBL_z58_WDPhandler[X_MAX_INST_z58_WDPhandler] = {
  XSTARTUP
};

/*---------------State Index----------------*/
static XCONST xSITBL xSTATE_INDEX_z58_WDPhandler[3] = {0, 3, 9};

/*---------------Transition-----------------*/
#define XMAX_TRANS_z58_WDPhandler 9
static XCONST xTR_TABLE_ENTRY yTRTBL_z58_WDPhandler[XMAX_TRANS_z58_WDPhandler] = {

    /* AwaitStart */
  XMK_B z_WDP_UpperLayer_1_OpenPort, XSAVEID XMK_E,
  XMK_B z_WDPPckg_0_StartWDPh, 1 XMK_E,
  XMK_B z_WDPPckg_3_TerminateWDPh, 2 XMK_E

    /* IDLE */,
  XMK_B z_WDP_UpperLayer_0_TDUnitdataReq, 3 XMK_E,
  XMK_B z_Global_Declarations_0_ClosePort, 4 XMK_E,
  XMK_B z_WDP_UpperLayer_1_OpenPort, 5 XMK_E,
  XMK_B z_WDPPckg_3_TerminateWDPh, 6 XMK_E,
  XMK_B z_WDP_UDP_0_RecUDPDatagram, 8 XMK_E,
  XMK_B z_WDP_UDP_1_UDPErrorInd, 7 XMK_E
};

/*-----------Process-PID-Values-------------*/
#ifdef XMK_USE_PID_ADDRESSING
static xPIDTable yPID_TBL_z58_WDPhandler[X_MAX_INST_z58_WDPhandler];
#endif

/*-----------Process Description------------*/
#define X_PRIO_z58_WDPhandler  xDefaultPrioProcess
XCONST XPDTBL yPDTBL_z58_WDPhandler = {
#ifdef XMK_USE_PID_ADDRESSING
  yPID_TBL_z58_WDPhandler,
#endif
  (xINSTD *)yINSTD_z58_WDPhandler,
  sizeof(yVDef_z58_WDPhandler),
  X_MAX_INST_z58_WDPhandler,
#ifdef XMK_USE_TIMESLICE
  X_TIMESLICE_z58_WDPhandler,
#endif
#ifdef XMK_USE_PREEMPTIVE
  X_PRIO_z58_WDPhandler,
#endif
  (xmk_T_TRANS_ADDRESS) yPAD_z58_WDPhandler,
  yTRTBL_z58_WDPhandler,
  xSTATE_INDEX_z58_WDPhandler,
  yPSTATETBL_z58_WDPhandler
};

/*+++++
* Function for process WDPhandler
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr,4,1)
++++++*/
YPAD_FUNCTION(yPAD_z58_WDPhandler)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z58_WDPhandler)
  YPAD_TEMP_VARS
  /* INTEGRATION: commented out statement */
  /* SDL_Integer  yDcn_SDL_Integer; */
  /* INTEGRATION: commented out statement */
  /* SDL_Boolean  yDcn_SDL_Boolean; */
  YPRSNAME_VAR("WDPhandler")

  BEGIN_PAD
  switch (XSYMBOLNUMBER) {

/*-----
* START
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1763(55,25),1)
------*/
  case 0:
    BEGIN_START_TRANSITION
    XAT_FIRST_SYMBOL(0, 7990)
    yDef_z_ctypes_4_VoidStar(&yVarP->z587_UDPData);
    yDef_DeviceAddress(&yVarP->z588_dstAddr);
    yDef_DeviceAddress(&yVarP->z589_srcAddr);
    yDef_pdubuf_ptr(&yVarP->z58A_tmpBuf);
    xDef_SDL_Integer(&yVarP->z58B_srcPort);
    xDef_SDL_Integer(&yVarP->z58C_dstPort);
    xDef_SDL_Natural(&yVarP->z58D_DataLen);
    xDef_SDL_Natural(&yVarP->z58E_FaultCode);
    xDef_SDL_Boolean(&yVarP->z58F_ok);
    yDef_TDUnitdataReqType(&yVarP->z58G_dataReq);
    yDef_TDUnitdataIndType(&yVarP->z58H_dataInd);
    xDef_SDL_Integer(&yVarP->z58I_port);
    xDef_SDL_PId(&yVarP->z58J_upperlayerPId);
    xDef_SDL_Natural(&yVarP->z58K_stackconfig);
    xDef_SDL_Octet(&yVarP->z58L_bearer);
    xDef_SDL_Octet(&yVarP->z58M_viewID);
    xDef_SDL_Octet(&yVarP->z58N_channelID);
    xDef_SDL_Octet(&yVarP->z58O_newChannelID);
    XBETWEEN_SYMBOLS(9, 7999, 227)

/*-----
* NEXTSTATE AwaitStart
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1766(55,40),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitStart, z585_AwaitStart, "AwaitStart")

/*-----
* INPUT StartWDPh
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1772(55,80),1)
------*/
  case 1:
    XDEBUG_LABEL(AwaitStart_StartWDPh)
    XAT_FIRST_SYMBOL(1, 7991)
    XOS_TRACE_INPUT("StartWDPh")
    XBETWEEN_SYMBOLS(10, 8000, 244)
    {

/*-----
* CALL wdp_porttbl_init
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),3815(55,95),1)
------*/
#ifdef XTRACE
      xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_init");
#endif
#ifdef XMSCE
      xMSCETask("CALL EXTERNAL wdp_porttbl_init");
#endif
      wdp_porttbl_init();
    }
    XBETWEEN_SYMBOLS(11, 8001, 259)

/*-----
* TASK address_init
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),4010(55,110),1)
------*/
#ifdef XTRACE
    xTraceTask("address_init");
#endif
 #if defined CONFIG_SMS

 wdp_address_init ();

 #endif

    XBETWEEN_SYMBOLS(12, 8002, 274)

/*-----
* OUTPUT WDPhReady
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\startanswer.smc(1),281(80,40),1)
------*/
    ALLOC_SIGNAL_NPAR(WDPhReady, z_WDPPckg_9_WDPhReady, XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, WDPhReady, z_WDPPckg_9_WDPhReady,
      TO_PROCESS(WDPmanagement, z59_WDPmanagement), 0, "WDPhReady")
    XBETWEEN_SYMBOLS(13, 8003, 283)

/*-----
* OUTPUT SegmentationReady
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\startanswer.smc(1),287(80,55),1)
------*/
    ALLOC_SIGNAL_NPAR(SegmentationReady, z_WDPPckg_A_SegmentationReady,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, SegmentationReady,
      z_WDPPckg_A_SegmentationReady, TO_PROCESS(WDPmanagement,
      z59_WDPmanagement), 0, "SegmentationReady")
    XBETWEEN_SYMBOLS(14, 8004, 294)

/*-----
* OUTPUT ReassembleReady
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\startanswer.smc(1),293(80,70),1)
------*/
    ALLOC_SIGNAL_NPAR(ReassembleReady, z_WDPPckg_B_ReassembleReady,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, ReassembleReady,
      z_WDPPckg_B_ReassembleReady, TO_PROCESS(WDPmanagement,
      z59_WDPmanagement), 0, "ReassembleReady")
    XBETWEEN_SYMBOLS(15, 8005, 305)

/*-----
* NEXTSTATE IDLE
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1793(55,140),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(IDLE, z586_IDLE, "IDLE")

/*-----
* INPUT TerminateWDPh
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1796(120,85),1)
------*/
  case 2:
    XDEBUG_LABEL(AwaitStart_TerminateWDPh)
    XAT_FIRST_SYMBOL(2, 7992)
    XOS_TRACE_INPUT("TerminateWDPh")
    XBETWEEN_SYMBOLS(16, 8006, 322)
    {

/*-----
* CALL wdp_porttbl_clear
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),3821(120,100),1)
------*/
#ifdef XTRACE
      xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_clear");
#endif
#ifdef XMSCE
      xMSCETask("CALL EXTERNAL wdp_porttbl_clear");
#endif
      wdp_porttbl_clear();
    }
    XBETWEEN_SYMBOLS(17, 8007, 337)

/*-----
* OUTPUT WDPhTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),305(80,40),1)
------*/
    ALLOC_SIGNAL_NPAR(WDPhTerminated, z_WDPPckg_6_WDPhTerminated,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, WDPhTerminated,
      z_WDPPckg_6_WDPhTerminated, TO_PROCESS(WDPmanagement, z59_WDPmanagement),
      0, "WDPhTerminated")
    XBETWEEN_SYMBOLS(18, 8008, 348)

/*-----
* OUTPUT SegmentationTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),287(80,55),1)
------*/
    ALLOC_SIGNAL_NPAR(SegmentationTerminated,
      z_WDPPckg_8_SegmentationTerminated, XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, SegmentationTerminated,
      z_WDPPckg_8_SegmentationTerminated, TO_PROCESS(WDPmanagement,
      z59_WDPmanagement), 0, "SegmentationTerminated")
    XBETWEEN_SYMBOLS(19, 8009, 359)

/*-----
* OUTPUT ReassembleTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),293(80,70),1)
------*/
    ALLOC_SIGNAL_NPAR(ReassembleTerminated, z_WDPPckg_7_ReassembleTerminated,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, ReassembleTerminated,
      z_WDPPckg_7_ReassembleTerminated, TO_PROCESS(WDPmanagement,
      z59_WDPmanagement), 0, "ReassembleTerminated")
    XBETWEEN_SYMBOLS(20, 8010, 370)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(1),1799(120,130),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT TDUnitdataReq
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),128(75,60),1)
------*/
  case 3:
    XDEBUG_LABEL(IDLE_TDUnitdataReq)
    XAT_FIRST_SYMBOL(3, 7993)
    XOS_TRACE_INPUT("TDUnitdataReq")
    yAssF_TDUnitdataReqType(yVarP->z58G_dataReq,
      ((yPDef_z_WDP_UpperLayer_0_TDUnitdataReq *)ySVarP)->Param1, XASS);
    yAssF_SDL_PId(yVarP->z58J_upperlayerPId,
      ((yPDef_z_WDP_UpperLayer_0_TDUnitdataReq *)ySVarP)->Param2, XASS);
    yAssF_SDL_Natural(yVarP->z58K_stackconfig, yTstA_SDL_Natural(
      ((yPDef_z_WDP_UpperLayer_0_TDUnitdataReq *)ySVarP)->Param3), XASS);
    XBETWEEN_SYMBOLS(21, 8011, 393)

/*-----
* TASK log internal
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),3191(75,75),1)
------*/
#ifdef XTRACE
    xTraceTask("log internal");
#endif
#if defined LOG_INTERNAL
{
char *logstr;
char *strPDU;
char *strparam1;

logstr = OctetString2HexString((char*)yVarP->
  z58G_dataReq.SourceAddress.Address.data, yVarP->
  z58G_dataReq.SourceAddress.Address.length);
CLNTa_log(0, 0, "WDP Receive TDUnitDataReq: Source Address = %s\n", logstr);
OSConnectorFree(logstr);

logstr = OctetString2HexString((char*)yVarP->
  z58G_dataReq.SourceAddress.SecondAddress.data, yVarP->
  z58G_dataReq.SourceAddress.SecondAddress.length);
CLNTa_log(0, 0, "WDP Receive TDUnitDataReq: Source SecondAddress = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: Source Bearer = %d\n", yVarP->
  z58G_dataReq.SourceAddress.Bearer);

CLNTa_log(0, 0, "WDP: Source SecondAddressFormat= %d\n", yVarP->
  z58G_dataReq.SourceAddress.SecondAddressFormat);

CLNTa_log(0, 0, "WDP: Source PortNumber = %d\n", yVarP->
  z58G_dataReq.SourceAddress.PortNumber);

logstr = OctetString2HexString((char*)yVarP->
  z58G_dataReq. DestinationAddress.Address.data, yVarP->
  z58G_dataReq. DestinationAddress.Address.length);
CLNTa_log(0, 0, "WDP Receive TDUnitDataReq: Destination Address = %s\n", logstr);
OSConnectorFree(logstr);

logstr = OctetString2HexString((char*)yVarP->
  z58G_dataReq. DestinationAddress.SecondAddress.data, yVarP->
  z58G_dataReq. DestinationAddress.SecondAddress.length);
CLNTa_log(0, 0, "WDP Receive TDUnitDataReq: Destination SecondAddress = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: DesinationBearer = %d\n", yVarP->
  z58G_dataReq.DestinationAddress.Bearer);

CLNTa_log(0, 0, "WDP: DesinationSecondAddressFormat= %d\n", yVarP->
  z58G_dataReq.DestinationAddress.SecondAddressFormat);

CLNTa_log(0, 0, "WDP: DesinationPortNumber = %d\n", yVarP->
  z58G_dataReq.DestinationAddress.PortNumber);

CLNTa_log(0, 0, "WDP: StackConfig = %d\n", yVarP->z58K_stackconfig);

strPDU = (char*)pdubuf_getStart( (pdubuf *)yVarP->z58G_dataReq.UserData );
strparam1 = OctetString2HexString((CHAR*)strPDU,pdubuf_getLength(yVarP->
  z58G_dataReq.UserData));

CLNTa_log(0,0, "WDP data %s\n", strparam1?strparam1:"");
DEALLOC(&strparam1);
}
#endif

    XBETWEEN_SYMBOLS(22, 8012, 461)

/*-----
* ASSIGNMENT srcAddr := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),2525(75,90),1)
------*/
    yAssF_DeviceAddress(yVarP->z589_srcAddr, yVarP->z58G_dataReq.SourceAddress.
      Address, XASS);
#ifdef XTRACE
    xTraceAssign("srcAddr := ");
#endif
    XBETWEEN_SYMBOLS(23, 8013, 472)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),599(75,105),1)
------*/
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean,
      xAnd_SDL_Boolean((xLT_SDL_Integer(z_WDPPckg_N_MinDestPortNo, yVarP->
      z58G_dataReq.DestinationAddress.PortNumber)), (xLT_SDL_Integer(yVarP->
      z58G_dataReq.DestinationAddress.PortNumber, z_WDPPckg_O_MaxDestPortNo))),
      XASS);
    if (yDcn_SDL_Boolean) {
#else
    if (xAnd_SDL_Boolean((xLT_SDL_Integer(z_WDPPckg_N_MinDestPortNo, yVarP->
      z58G_dataReq.DestinationAddress.PortNumber)), (xLT_SDL_Integer(yVarP->
      z58G_dataReq.DestinationAddress.PortNumber,
      z_WDPPckg_O_MaxDestPortNo)))) {
#endif
#ifdef XTRACE
    xTraceDecision("TRUE");
#endif
      XBETWEEN_SYMBOLS(24, 8014, 494)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),617(75,125),1)
------*/
#ifdef XTRACE
      yAssF_SDL_Boolean(yDcn_SDL_Boolean,
        xAnd_SDL_Boolean((xLE_SDL_Integer(z_WDPPckg_L_MinSourcePortNo, yVarP->
        z58G_dataReq.SourceAddress.PortNumber)), (xLT_SDL_Integer(yVarP->
        z58G_dataReq.SourceAddress.PortNumber, z_WDPPckg_M_MaxSourcePortNo))),
        XASS);
      if (yDcn_SDL_Boolean) {
#else
      if (xAnd_SDL_Boolean((xLE_SDL_Integer(z_WDPPckg_L_MinSourcePortNo, yVarP->
        z58G_dataReq.SourceAddress.PortNumber)), (xLT_SDL_Integer(yVarP->
        z58G_dataReq.SourceAddress.PortNumber, z_WDPPckg_M_MaxSourcePortNo)))) {
#endif
#ifdef XTRACE
      xTraceDecision("TRUE");
#endif
        XBETWEEN_SYMBOLS(25, 8015, 515)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),635(75,145),1)
------*/
#ifdef XTRACE
        yAssF_SDL_Integer(yDcn_SDL_Integer, devaddr_getlen(&(yVarP->
          z58G_dataReq.DestinationAddress.Address)), XASS);
        if (yEqF_SDL_Integer(yDcn_SDL_Integer, SDL_INTEGER_LIT(0))) {
#else
        if (yEqF_SDL_Integer(devaddr_getlen(&(yVarP->z58G_dataReq.
          DestinationAddress.Address)), SDL_INTEGER_LIT(0))) {
#endif
#ifdef XTRACE
        xTraceDecision("PATH: Integer");
#endif
            /* Null transition */
        } else {
#ifdef XTRACE
        xTraceDecision("ELSE");
#endif
          XBETWEEN_SYMBOLS(26, 8016, 537)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),788(75,165),1)
------*/
#ifdef XTRACE
          yAssF_SDL_Integer(yDcn_SDL_Integer, PDU_getLen(yVarP->z58G_dataReq.
            UserData), XASS);
          if (yEqF_SDL_Integer(yDcn_SDL_Integer, SDL_INTEGER_LIT(0))) {
#else
          if (yEqF_SDL_Integer(PDU_getLen(yVarP->z58G_dataReq.UserData),
            SDL_INTEGER_LIT(0))) {
#endif
#ifdef XTRACE
          xTraceDecision("PATH: Integer");
#endif
              /* Null transition */
          } else {
#ifdef XTRACE
          xTraceDecision("ELSE");
#endif
            XBETWEEN_SYMBOLS(27, 8017, 559)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),137(75,185),1)
------*/
            yAssF_SDL_Octet(yVarP->yDcn_SDL_Octet, yVarP->z58G_dataReq.
              DestinationAddress.Bearer, XASS);
            if (yEqF_SDL_Octet(yVarP->yDcn_SDL_Octet, xI2O_SDL_Octet(
                  BEARER_ANY_UDP)) ||
                yEqF_SDL_Octet(yVarP->yDcn_SDL_Octet, xI2O_SDL_Octet(
                  BEARER_GSM_CSD)) ||
                yEqF_SDL_Octet(yVarP->yDcn_SDL_Octet, xI2O_SDL_Octet(
                  BEARER_GSM_GPRS)) ||
                yEqF_SDL_Octet(yVarP->yDcn_SDL_Octet, xI2O_SDL_Octet(
              BEARER_BT))) {
#ifdef XTRACE
            xTraceDecision("PATH: I2O");
#endif
              XBETWEEN_SYMBOLS(28, 8018, 578)

/*-----
* ASSIGNMENT srcPort := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),2)
------*/
              yAssF_SDL_Integer(yVarP->z58B_srcPort, yVarP->z58G_dataReq.
                SourceAddress.PortNumber, XASS);
#ifdef XTRACE
              xTraceAssign("srcPort := ");
#endif
              XBETWEEN_STMTS(29, 8019, 589)

/*-----
* ASSIGNMENT dstPort := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),3)
------*/
              yAssF_SDL_Integer(yVarP->z58C_dstPort, yVarP->z58G_dataReq.
                DestinationAddress.PortNumber, XASS);
#ifdef XTRACE
              xTraceAssign("dstPort := ");
#endif
              XBETWEEN_STMTS(30, 8020, 600)

/*-----
* ASSIGNMENT dstAddr := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),4)
------*/
              yAssF_DeviceAddress(yVarP->z588_dstAddr, yVarP->z58G_dataReq.
                DestinationAddress.Address, XASS);
#ifdef XTRACE
              xTraceAssign("dstAddr := ");
#endif
              XBETWEEN_STMTS(31, 8021, 611)

/*-----
* ASSIGNMENT viewID := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),5)
------*/
              yAssF_SDL_Octet(yVarP->z58M_viewID, yVarP->z58G_dataReq.
                DestinationAddress.ViewID, XASS);
#ifdef XTRACE
              xTraceAssign("viewID := ");
#endif
              XBETWEEN_STMTS(32, 8022, 622)

/*-----
* ASSIGNMENT channelID := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1151(75,225),6)
------*/
              yAssF_SDL_Octet(yVarP->z58N_channelID, yVarP->z58G_dataReq.
                DestinationAddress.ChannelID, XASS);
#ifdef XTRACE
              xTraceAssign("channelID := ");
#endif
              XBETWEEN_SYMBOLS(33, 8023, 633)
              {

/*-----
* CALL wdp_porttbl_update
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),3254(75,240),1)
------*/
#ifdef XTRACE
                xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_update");
#endif
#ifdef XMSCE
                xMSCETask("CALL EXTERNAL wdp_porttbl_update");
#endif
                wdp_porttbl_update(yVarP->z58B_srcPort, yVarP->
                  z58J_upperlayerPId, yTstA_SDL_Natural(yVarP->
                  z58K_stackconfig), yVarP->z58G_dataReq.DestinationAddress.
                  Bearer, yVarP->z58M_viewID, yVarP->z58N_channelID);
              }
              XBETWEEN_SYMBOLS(34, 8024, 651)

/*-----
* TASK sendRequest
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1463(75,255),1)
------*/
#ifdef XTRACE
              xTraceTask("sendRequest");
#endif
#ifdef FEATURE_WAP
  UDPa_sendRequest ((const CHAR *)(pdubuf_getStart (yVarP->z58G_dataReq.UserData)),
                    pdubuf_getLength (yVarP->z58G_dataReq.UserData),
                    (const CHAR *)(yVarP->z588_dstAddr.data), (INT8)yVarP->z588_dstAddr.length,
                    (const CHAR *)(yVarP->z589_srcAddr.data), (INT8)yVarP->z589_srcAddr.length,
                    (UINT16)yVarP->z58C_dstPort, (UINT16)yVarP->z58B_srcPort,
                    yVarP->z58M_viewID, yVarP->z58N_channelID);
#else
  UDPa_sendRequest (pdubuf_getStart (yVarP->z58G_dataReq.UserData),
                    pdubuf_getLength (yVarP->z58G_dataReq.UserData),
                    yVarP->z588_dstAddr.data, (INT8)yVarP->z588_dstAddr.length,
                    yVarP->z589_srcAddr.data, (INT8)yVarP->z589_srcAddr.length,
                    (UINT16)yVarP->z58C_dstPort, (UINT16)yVarP->z58B_srcPort,
                    yVarP->z58M_viewID, yVarP->z58N_channelID);
#endif //#ifdef FEATURE_WAP

              XBETWEEN_SYMBOLS(35, 8025, 667)

/*-----
* TASK log external
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),2180(75,270),1)
------*/
#ifdef XTRACE
              xTraceTask("log external");
#endif
#if defined LOG_EXTERNAL
  CLNTa_log (0, log_wdp_sendUDP, "UDPa_sendRequest");
#endif

              XBETWEEN_SYMBOLS(36, 8026, 680)

/*-----
* TASK log internal
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),3233(75,285),1)
------*/
#ifdef XTRACE
              xTraceTask("log internal");
#endif
#if defined LOG_INTERNAL
{
char *logstr;

logstr = OctetString2HexString((char*)yVarP->z589_srcAddr.data, yVarP->
  z589_srcAddr.length);
CLNTa_log(0, 0, "WDP UDPsendReq Source Address = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: Source PortNumber = %d\n", yVarP->z58B_srcPort);

logstr = OctetString2HexString((char*)yVarP->z588_dstAddr.data, yVarP->
  z588_dstAddr.length);
CLNTa_log(0, 0, "WDP: Destination Address = %s\n", logstr);
OSConnectorFree(logstr);

CLNTa_log(0, 0, "WDP: DesinationPortNumber = %d\n", yVarP->z58C_dstPort);

logstr = OctetString2HexString ((char*)pdubuf_getStart (yVarP->z58G_dataReq.UserData),
                                pdubuf_getLength (yVarP->
  z58G_dataReq.UserData));
CLNTa_log(0,0, "WDP data %s\n", logstr);
OSConnectorFree(logstr);
}
#endif

              XBETWEEN_SYMBOLS(37, 8027, 715)

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1157(75,300),1)
------*/
              yAssF_SDL_Boolean(yVarP->z58F_ok, PDU_rel(&(yVarP->z58G_dataReq.
                UserData)), XASS);
#ifdef XTRACE
              xTraceAssign("ok := ");
#endif
              XBETWEEN_SYMBOLS(38, 8028, 726)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1184(75,315),1)
------*/
              XAT_LAST_SYMBOL
              SDL_DASH_NEXTSTATE
            } else {
#ifdef XTRACE
            xTraceDecision("ELSE");
#endif
              XBETWEEN_SYMBOLS(39, 8029, 738)

/*-----
* TASK
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\bearerchoice.smc(1),158(80,55),1)
------*/
#ifdef XTRACE
              xTraceTask(" ");
#endif
  CLNTa_error (0, ERR_WDP_ErrorBearerNotSupported, ERRTYPE_INFORMATION);

              XBETWEEN_SYMBOLS(40, 8030, 749)

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\bearerchoice.smc(1),176(80,100),1)
------*/
              yAssF_SDL_Boolean(yVarP->z58F_ok, PDU_rel(&(yVarP->z58G_dataReq.
                UserData)), XASS);
#ifdef XTRACE
              xTraceAssign("ok := ");
#endif
              XBETWEEN_SYMBOLS(41, 8031, 760)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\bearerchoice.smc(1),179(80,145),1)
------*/
              XAT_LAST_SYMBOL
              SDL_DASH_NEXTSTATE
            }
          }
        }
      } else {
#ifdef XTRACE
      xTraceDecision("FALSE");
#endif
          /* Null transition */
      }
    } else {
#ifdef XTRACE
    xTraceDecision("FALSE");
#endif
        /* Null transition */
    }
    XBETWEEN_SYMBOLS(42, 8032, 783)

/*-----
* TASK error
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),2699(10,190),1)
------*/
#ifdef XTRACE
    xTraceTask("error");
#endif
  CLNTa_error (0, ERR_WDP_ErrorInDatafromWSP, ERRTYPE_INFORMATION);

    XBETWEEN_SYMBOLS(43, 8033, 794)

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1430(10,205),1)
------*/
    yAssF_SDL_Boolean(yVarP->z58F_ok, PDU_rel(&(yVarP->z58G_dataReq.UserData)),
      XASS);
#ifdef XTRACE
    xTraceAssign("ok := ");
#endif
    XBETWEEN_SYMBOLS(44, 8034, 805)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(2),1277(10,220),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT ClosePort
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3443(35,45),1)
------*/
  case 4:
    XDEBUG_LABEL(IDLE_ClosePort)
    XAT_FIRST_SYMBOL(4, 7994)
    XOS_TRACE_INPUT("ClosePort")
    yAssF_SDL_Integer(yVarP->z58I_port,
      ((yPDef_z_Global_Declarations_0_ClosePort *)ySVarP)->Param1, XASS);
    yAssF_SDL_Natural(yVarP->z58K_stackconfig, yTstA_SDL_Natural(
      ((yPDef_z_Global_Declarations_0_ClosePort *)ySVarP)->Param2), XASS);
    XBETWEEN_SYMBOLS(45, 8035, 826)
    {

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3797(35,80),1)
------*/
      yAssF_SDL_Boolean(yVarP->z58F_ok, wdp_porttbl_lookup(yVarP->z58I_port,
        &(yVarP->z58J_upperlayerPId), &(yVarP->z58K_stackconfig), &(yVarP->
        z58L_bearer), &(yVarP->z58M_viewID), &(yVarP->z58N_channelID)), XASS);
#ifdef XTRACE
      xTraceAssign("ok := ");
#endif
    }
    XBETWEEN_SYMBOLS(46, 8036, 840)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3800(35,95),1)
------*/
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z58F_ok, XASS);
    if (yDcn_SDL_Boolean) {
#else
    if (yVarP->z58F_ok) {
#endif
#ifdef XTRACE
    xTraceDecision("TRUE");
#endif
      XBETWEEN_SYMBOLS(47, 8037, 855)
      {

/*-----
* CALL wdp_porttbl_delete
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3791(35,110),1)
------*/
#ifdef XTRACE
        xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_delete");
#endif
#ifdef XMSCE
        xMSCETask("CALL EXTERNAL wdp_porttbl_delete");
#endif
        wdp_porttbl_delete(yVarP->z58I_port);
      }
      XBETWEEN_SYMBOLS(48, 8038, 870)

/*-----
* TASK close connection
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3779(35,125),1)
------*/
#ifdef LOG_EXTERNAL
      CLNTa_log(1,0,"close connection");
#endif
  {
    UINT8  errorCode;
    DB_ref ref;
    INT32  online;

    if ((yVarP->z58L_bearer == BEARER_ANY_UDP) ||
        (yVarP->z58L_bearer == BEARER_GSM_CSD) ||
        (yVarP->z58L_bearer == BEARER_GSM_GPRS) ||
        (yVarP->z58L_bearer == BEARER_BT)) {
      do {
        ref = getChannelRef (yVarP->z58M_viewID, yVarP->z58N_channelID);
        if (ref != DB_null) {
#ifdef FEATURE_WAP
          online = db_getInt (ref, (const BYTE *)ONLINE, FALSE, &errorCode);
#else
          online = db_getInt (ref, ONLINE, FALSE, &errorCode);
#endif //#ifdef FEATURE_WAP
#ifdef LOG_EXTERNAL
		  CLNTa_log(1,0,"errorCode [%d] online [%d]",errorCode, online);
#endif
          if ((errorCode == DB_err_success) && online)
		  {
#ifdef LOG_EXTERNAL
			CLNTa_log(1,0,"close connection error");
#endif
			break;
		  }
        }
        CLNTa_closeConnection (yVarP->z58M_viewID, yVarP->z58N_channelID);
      } while (0);
    }
  }

    } else {
#ifdef LOG_EXTERNAL
      CLNTa_log(1,0,"close connection false");
#endif
        /* Null transition */
    }
    XBETWEEN_SYMBOLS(49, 8039, 906)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3449(35,145),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT OpenPort
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3482(115,45),1)
------*/
  case 5:
    XDEBUG_LABEL(IDLE_OpenPort)
    XAT_FIRST_SYMBOL(5, 7995)
    XOS_TRACE_INPUT("OpenPort")
    yAssF_SDL_Integer(yVarP->z58I_port, ((yPDef_z_WDP_UpperLayer_1_OpenPort *)
      ySVarP)->Param1, XASS);
    yAssF_SDL_PId(yVarP->z58J_upperlayerPId,
      ((yPDef_z_WDP_UpperLayer_1_OpenPort *)ySVarP)->Param2, XASS);
    yAssF_SDL_Natural(yVarP->z58K_stackconfig, yTstA_SDL_Natural(
      ((yPDef_z_WDP_UpperLayer_1_OpenPort *)ySVarP)->Param3), XASS);
    XBETWEEN_SYMBOLS(50, 8040, 929)
    {

/*-----
* CALL wdp_porttbl_update
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3488(115,65),1)
------*/
#ifdef XTRACE
      xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_update");
#endif
#ifdef XMSCE
      xMSCETask("CALL EXTERNAL wdp_porttbl_update");
#endif
      wdp_porttbl_update(yVarP->z58I_port, yVarP->z58J_upperlayerPId,
        yTstA_SDL_Natural(yVarP->z58K_stackconfig), xI2O_SDL_Octet(
        SDL_INTEGER_LIT(0)), xI2O_SDL_Octet(SDL_INTEGER_LIT(0)), xI2O_SDL_Octet(
        SDL_INTEGER_LIT(0)));
    }
    XBETWEEN_SYMBOLS(51, 8041, 947)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(3),3491(115,85),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT TerminateWDPh
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3884(40,55),1)
------*/
  case 6:
    XDEBUG_LABEL(IDLE_TerminateWDPh)
    XAT_FIRST_SYMBOL(6, 7996)
    XOS_TRACE_INPUT("TerminateWDPh")
    XBETWEEN_SYMBOLS(52, 8042, 964)
    {

/*-----
* CALL wdp_porttbl_clear
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3887(40,70),1)
------*/
#ifdef XTRACE
      xTraceAlg("CALL EXTERNAL PROCEDURE wdp_porttbl_clear");
#endif
#ifdef XMSCE
      xMSCETask("CALL EXTERNAL wdp_porttbl_clear");
#endif
      wdp_porttbl_clear();
    }
    XBETWEEN_SYMBOLS(53, 8043, 979)

/*-----
* OUTPUT WDPhTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),305(80,40),1)
------*/
    ALLOC_SIGNAL_NPAR(WDPhTerminated, z_WDPPckg_6_WDPhTerminated,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, WDPhTerminated,
      z_WDPPckg_6_WDPhTerminated, TO_PROCESS(WDPmanagement, z59_WDPmanagement),
      0, "WDPhTerminated")
    XBETWEEN_SYMBOLS(54, 8044, 990)

/*-----
* OUTPUT SegmentationTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),287(80,55),1)
------*/
    ALLOC_SIGNAL_NPAR(SegmentationTerminated,
      z_WDPPckg_8_SegmentationTerminated, XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, SegmentationTerminated,
      z_WDPPckg_8_SegmentationTerminated, TO_PROCESS(WDPmanagement,
      z59_WDPmanagement), 0, "SegmentationTerminated")
    XBETWEEN_SYMBOLS(55, 8045, 1001)

/*-----
* OUTPUT ReassembleTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\terminateanswer.smc(1),293(80,70),1)
------*/
    ALLOC_SIGNAL_NPAR(ReassembleTerminated, z_WDPPckg_7_ReassembleTerminated,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, ReassembleTerminated,
      z_WDPPckg_7_ReassembleTerminated, TO_PROCESS(WDPmanagement,
      z59_WDPmanagement), 0, "ReassembleTerminated")
    XBETWEEN_SYMBOLS(56, 8046, 1012)

/*-----
* NEXTSTATE AwaitStart
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3893(40,105),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitStart, z585_AwaitStart, "AwaitStart")

/*-----
* INPUT UDPErrorInd
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3908(110,55),1)
------*/
  case 7:
    XDEBUG_LABEL(IDLE_UDPErrorInd)
    XAT_FIRST_SYMBOL(7, 7997)
    XOS_TRACE_INPUT("UDPErrorInd")
    yAssF_SDL_Integer(yVarP->z58C_dstPort, ((yPDef_z_WDP_UDP_1_UDPErrorInd *)
      ySVarP)->Param1, XASS);
    yAssF_SDL_Natural(yVarP->z58E_FaultCode, yTstA_SDL_Natural(
      ((yPDef_z_WDP_UDP_1_UDPErrorInd *)ySVarP)->Param2), XASS);
    XBETWEEN_SYMBOLS(57, 8047, 1033)

/*-----
* TASK log external
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3914(110,75),1)
------*/
#ifdef XTRACE
    xTraceTask("log external");
#endif
#if defined LOG_EXTERNAL
  CLNTa_log (0, log_wdp_UDPErrorInd, "\n");
#endif

    XBETWEEN_SYMBOLS(58, 8048, 1046)

/*-----
* TASK error
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3920(110,90),1)
------*/
#ifdef XTRACE
    xTraceTask("error");
#endif
  CLNTa_error (0, (INT16)yVarP->z58E_FaultCode, ERRTYPE_BEARER);

    XBETWEEN_SYMBOLS(59, 8049, 1057)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(4),3926(110,105),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT RecUDPDatagram
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3347(55,45),1)
------*/
  case 8:
    XDEBUG_LABEL(IDLE_RecUDPDatagram)
    XAT_FIRST_SYMBOL(8, 7998)
    XOS_TRACE_INPUT("RecUDPDatagram")
    yAssF_z_ctypes_4_VoidStar(yVarP->z587_UDPData,
      ((yPDef_z_WDP_UDP_0_RecUDPDatagram *)ySVarP)->Param1, XASS);
    yAssF_SDL_Natural(yVarP->z58D_DataLen, yTstA_SDL_Natural(
      ((yPDef_z_WDP_UDP_0_RecUDPDatagram *)ySVarP)->Param2), XASS);
    yAssF_DeviceAddress(yVarP->z588_dstAddr,
      ((yPDef_z_WDP_UDP_0_RecUDPDatagram *)ySVarP)->Param3, XASS);
    yAssF_DeviceAddress(yVarP->z589_srcAddr,
      ((yPDef_z_WDP_UDP_0_RecUDPDatagram *)ySVarP)->Param4, XASS);
    yAssF_SDL_Integer(yVarP->z58C_dstPort, ((yPDef_z_WDP_UDP_0_RecUDPDatagram *)
      ySVarP)->Param5, XASS);
    yAssF_SDL_Integer(yVarP->z58B_srcPort, ((yPDef_z_WDP_UDP_0_RecUDPDatagram *)
      ySVarP)->Param6, XASS);
    yAssF_SDL_Octet(yVarP->z58O_newChannelID,
      ((yPDef_z_WDP_UDP_0_RecUDPDatagram *)ySVarP)->Param7, XASS);
    XBETWEEN_SYMBOLS(60, 8050, 1088)

/*-----
* TASK log external
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3353(55,60),1)
------*/
#ifdef XTRACE
    xTraceTask("log external");
#endif
#if defined LOG_EXTERNAL
  CLNTa_log (0, log_wdp_RecUDPDatagram, "\n");
#endif

    XBETWEEN_SYMBOLS(61, 8051, 1101)

/*-----
* TASK log internal
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3359(55,75),1)
------*/
#ifdef XTRACE
    xTraceTask("log internal");
#endif
#if defined LOG_INTERNAL
{
  char *logstr1, *logstr2;
  char *strparam1;

  logstr1 = OctetString2HexString ((char*)yVarP->z589_srcAddr.data, yVarP->
  z589_srcAddr.length);
  logstr2 = OctetString2HexString ((char*)yVarP->z588_dstAddr.data, yVarP->
  z588_dstAddr.length);

  CLNTa_log (0, 0, "WDP: Received UDP Datagram\n"
                   "\tSource Address = %s\n"
                   "\tSource PortNumber = %d\n"
                   "\tDestination Address = %s\n"
                   "\tDestination PortNumber = %d\n"
                   "\tNew Channel ID = %d\n",
                   logstr1, yVarP->z58B_srcPort, logstr2, yVarP->
  z58C_dstPort, yVarP->z58O_newChannelID);

  OSConnectorFree(logstr1);
  OSConnectorFree(logstr2);

  strparam1 = OctetString2HexString ((char*)yVarP->z587_UDPData, yVarP->z58D_DataLen);
  CLNTa_log (0, 0, "WDP data %s\n", strparam1 ? strparam1 : "");
  DEALLOC (&strparam1);
}
#endif

    XBETWEEN_SYMBOLS(62, 8052, 1138)
    {

/*-----
* ASSIGNMENT ok := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3389(55,90),1)
------*/
      yAssF_SDL_Boolean(yVarP->z58F_ok, wdp_porttbl_lookup(yVarP->z58C_dstPort,
        &(yVarP->z58J_upperlayerPId), &(yVarP->z58K_stackconfig), &(yVarP->
        z58L_bearer), &(yVarP->z58M_viewID), &(yVarP->z58N_channelID)), XASS);
#ifdef XTRACE
      xTraceAssign("ok := ");
#endif
    }
    XBETWEEN_SYMBOLS(63, 8053, 1152)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3398(55,105),1)
------*/
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yVarP->z58F_ok, XASS);
    if (yDcn_SDL_Boolean) {
#else
    if (yVarP->z58F_ok) {
#endif
#ifdef XTRACE
    xTraceDecision("TRUE");
#endif
      XBETWEEN_SYMBOLS(66, 8056, 1167)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2537(55,125),1)
------*/
#ifdef XTRACE
      yAssF_SDL_Boolean(yDcn_SDL_Boolean, xLE_SDL_Integer(yVarP->z58D_DataLen,
        MaxPDUsize), XASS);
      if (yDcn_SDL_Boolean) {
#else
      if (xLE_SDL_Integer(yVarP->z58D_DataLen, MaxPDUsize)) {
#endif
#ifdef XTRACE
      xTraceDecision("TRUE");
#endif
        XBETWEEN_SYMBOLS(67, 8057, 1183)

/*-----
* ASSIGNMENT tmpBuf := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2498(55,140),1)
------*/
        yAssF_pdubuf_ptr(yVarP->z58A_tmpBuf, PDU_getFromData(yVarP->
          z587_UDPData, yTstA_SDL_Natural(yVarP->z58D_DataLen)), XASS);
#ifdef XTRACE
        xTraceAssign("tmpBuf := ");
#endif
        XBETWEEN_SYMBOLS(68, 8058, 1194)

/*-----
* DECISION
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2504(55,155),1)
------*/
#ifdef XTRACE
        yAssF_SDL_Boolean(yDcn_SDL_Boolean, PDU_isNull(yVarP->z58A_tmpBuf),
          XASS);
        if (yDcn_SDL_Boolean) {
#else
        if (PDU_isNull(yVarP->z58A_tmpBuf)) {
#endif
#ifdef XTRACE
        xTraceDecision("TRUE");
#endif
            /* Null transition */
        } else {
#ifdef XTRACE
        xTraceDecision("FALSE");
#endif
          XBETWEEN_SYMBOLS(69, 8059, 1215)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),923(55,175),1)
------*/
          yAssF_pdubuf_ptr(yVarP->z58H_dataInd.UserData, yVarP->z58A_tmpBuf,
            XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_SYMBOLS(70, 8060, 1226)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2264(55,195),1)
------*/
          yAssF_SDL_Integer(yVarP->z58H_dataInd.SourceAddress.PortNumber,
            yVarP->z58B_srcPort, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(71, 8061, 1237)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2264(55,195),2)
------*/
          yAssF_SDL_Integer(yVarP->z58H_dataInd.DestinationAddress.PortNumber,
            yVarP->z58C_dstPort, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_SYMBOLS(72, 8062, 1248)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2267(55,225),1)
------*/
          yAssF_DeviceAddress(yVarP->z58H_dataInd.SourceAddress.Address, yVarP->
            z589_srcAddr, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(73, 8063, 1259)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2267(55,225),2)
------*/
          yAssF_SDL_Octet(yVarP->z58H_dataInd.SourceAddress.
            SecondAddressFormat, xI2O_SDL_Octet(SDL_INTEGER_LIT(255)), XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(74, 8064, 1270)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2267(55,225),3)
------*/
          yAssF_DeviceAddress(yVarP->z58H_dataInd.DestinationAddress.Address,
            yVarP->z588_dstAddr, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(75, 8065, 1281)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2267(55,225),4)
------*/
          yAssF_SDL_Octet(yVarP->z58H_dataInd.DestinationAddress.
            SecondAddressFormat, xI2O_SDL_Octet(SDL_INTEGER_LIT(255)), XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_SYMBOLS(76, 8066, 1292)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),1)
------*/
          yAssF_SDL_Octet(yVarP->z58H_dataInd.SourceAddress.Bearer, yVarP->
            z58L_bearer, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(77, 8067, 1303)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),2)
------*/
          yAssF_SDL_Octet(yVarP->z58H_dataInd.DestinationAddress.Bearer, yVarP->
            z58L_bearer, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(78, 8068, 1314)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),3)
------*/
          yAssF_SDL_Octet(yVarP->z58H_dataInd.SourceAddress.ViewID, yVarP->
            z58M_viewID, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(79, 8069, 1325)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),4)
------*/
          yAssF_SDL_Octet(yVarP->z58H_dataInd.DestinationAddress.ViewID, yVarP->
            z58M_viewID, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(80, 8070, 1336)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),5)
------*/
          yAssF_SDL_Octet(yVarP->z58H_dataInd.SourceAddress.ChannelID, yVarP->
            z58N_channelID, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_STMTS(81, 8071, 1347)

/*-----
* ASSIGNMENT dataInd... := ...
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3146(55,245),6)
------*/
          yAssF_SDL_Octet(yVarP->z58H_dataInd.DestinationAddress.ChannelID,
            yVarP->z58O_newChannelID, XASS);
#ifdef XTRACE
          xTraceAssign("dataInd... := ");
#endif
          XBETWEEN_SYMBOLS(82, 8072, 1358)

/*-----
* TASK log internal
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3170(55,275),1)
------*/
#ifdef XTRACE
          xTraceTask("log internal");
#endif
#if defined LOG_INTERNAL
{
  char *logstr1, *logstr2, *logstr3;
  char *strPDU;
  char *strparam1;

  logstr1 = OctetString2HexString ((char*)yVarP->
  z58H_dataInd.SourceAddress.Address.data, yVarP->
  z58H_dataInd.SourceAddress.Address.length);
  logstr2 = OctetString2HexString ((char*)yVarP->
  z58H_dataInd.SourceAddress. SecondAddress.data, yVarP->
  z58H_dataInd.SourceAddress. SecondAddress.length);
  logstr3 = OctetString2HexString ((char*)yVarP->
  z58H_dataInd.DestinationAddress.Address.data, yVarP->
  z58H_dataInd.DestinationAddress.Address.length);
  CLNTa_log(0, 0, "WDP Send TDUnitDataInd:\n"
                  "\tSource Address = %s\n"
                  "\tSource SecondAddress = %s\n"
                  "\tSource SecondAddressFormat = %d\n"
                  "\tSource Bearer = %d\n"
                  "\tSource PortNumber = %d\n"
                  "\tDestination Address = %s\n"
                  "\tDestination Bearer = %d\n"
                  "\tDestination PortNumber = %d\n"
                  "\tDestination View ID = %d\n"
                  "\tDestination Channel ID = %d\n"
                  "\tStackConfig = %d\n",
                  logstr1, logstr2, yVarP->
  z58H_dataInd.SourceAddress.SecondAddressFormat,
                  yVarP->z58H_dataInd.SourceAddress.Bearer, yVarP->
  z58H_dataInd.SourceAddress.PortNumber,
                  logstr3, yVarP->z58H_dataInd.DestinationAddress.Bearer,
                  yVarP->z58H_dataInd.DestinationAddress.PortNumber,
                  yVarP->z58H_dataInd.DestinationAddress.ViewID,
                  yVarP->z58H_dataInd.DestinationAddress.ChannelID,
                  yVarP->z58K_stackconfig);

  OSConnectorFree (logstr1);
  OSConnectorFree (logstr2);
  OSConnectorFree (logstr3);

  strPDU = (char*)pdubuf_getStart ((pdubuf*)yVarP->z58H_dataInd.UserData);
  strparam1 = OctetString2HexString ((CHAR*)strPDU, pdubuf_getLength (yVarP->
  z58H_dataInd.UserData));

  CLNTa_log (0, 0, "WDP data %s\n", strparam1 ? strparam1 : "");
  DEALLOC (&strparam1);
}
#endif

          XBETWEEN_SYMBOLS(83, 8073, 1417)

/*-----
* OUTPUT TDUnitDataInd
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2285(55,290),1)
------*/
          ALLOC_SIGNAL_PAR(TDUnitDataInd, z_WDP_UpperLayer_2_TDUnitDataInd,
            yPDef_z_WDP_UpperLayer_2_TDUnitDataInd)
          yAssF_TDUnitdataIndType(((yPDef_z_WDP_UpperLayer_2_TDUnitDataInd *)OUTSIGNAL_DATA_PTR)->Param1,
            yVarP->z58H_dataInd, XASSPARA);
          yAssF_SDL_Natural(((yPDef_z_WDP_UpperLayer_2_TDUnitDataInd *)OUTSIGNAL_DATA_PTR)->Param2,
            yTstA_SDL_Natural(yVarP->z58K_stackconfig), XASSPARA);
          SDL_OUTP_PAR(xDefaultPrioSignal, TDUnitDataInd,
            z_WDP_UpperLayer_2_TDUnitDataInd, yVarP->z58J_upperlayerPId,
            yPDef_z_WDP_UpperLayer_2_TDUnitDataInd, "TDUnitDataInd")
          XBETWEEN_SYMBOLS(84, 8074, 1432)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2288(55,305),1)
------*/
          XAT_LAST_SYMBOL
          SDL_DASH_NEXTSTATE
        }
      } else {
#ifdef XTRACE
      xTraceDecision("FALSE");
#endif
          /* Null transition */
      }
      XBETWEEN_SYMBOLS(85, 8075, 1447)

/*-----
* TASK error
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2780(115,175),1)
------*/
#ifdef XTRACE
      xTraceTask("error");
#endif
  CLNTa_error (0, ERR_WDP_UDPBigBuffer, ERRTYPE_INFORMATION);

      XBETWEEN_SYMBOLS(86, 8076, 1458)

/*-----
* TASK Free buffer
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),2408(115,190),1)
------*/
#ifdef XTRACE
      xTraceTask("Free buffer");
#endif
  OSConnectorFree (yVarP->z587_UDPData);

      XBETWEEN_SYMBOLS(87, 8077, 1469)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),1358(115,210),1)
------*/
      XAT_LAST_SYMBOL
      SDL_DASH_NEXTSTATE
    } else {
#ifdef XTRACE
    xTraceDecision("FALSE");
#endif
      XBETWEEN_SYMBOLS(64, 8054, 1481)

/*-----
* TASK Free buffer
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3404(135,120),1)
------*/
#ifdef XTRACE
      xTraceTask("Free buffer");
#endif
  OSConnectorFree (yVarP->z587_UDPData);

      XBETWEEN_SYMBOLS(65, 8055, 1492)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdphandler.spr(5),3416(135,135),1)
------*/
      XAT_LAST_SYMBOL
      SDL_DASH_NEXTSTATE
    }
  }
  END_PAD(yPAD_z58_WDPhandler)
}

/*****
* PROCESS WDPmanagement
* <<SYSTEM WAP/BLOCK WDP>>
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr,4,1)
******/

/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
** Tables for process WDPmanagement
** #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr,4,1)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

/*--------------Instance Data---------------*/
#define X_MAX_INST_z59_WDPmanagement 1
static yVDef_z59_WDPmanagement *yINSTD_z59_WDPmanagement[X_MAX_INST_z59_WDPmanagement];

/*--------------Process State---------------*/
static xSTATE yPSTATETBL_z59_WDPmanagement[X_MAX_INST_z59_WDPmanagement] = {
  XSTARTUP
};

/*---------------State Index----------------*/
static XCONST xSITBL xSTATE_INDEX_z59_WDPmanagement[9] = {0, 2, 5, 7, 8, 9, 12,
    14, 15};

/*---------------Transition-----------------*/
#define XMAX_TRANS_z59_WDPmanagement 15
static XCONST xTR_TABLE_ENTRY yTRTBL_z59_WDPmanagement[XMAX_TRANS_z59_WDPmanagement] = {

    /* AwaitStartWDP */
  XMK_B z_StackMgr_7_StartWDP, 2 XMK_E,
  XMK_B z_StackMgr_F_TerminateWDP, 1 XMK_E

    /* AwaitReady */,
  XMK_B z_WDPPckg_9_WDPhReady, XSAVEID XMK_E,
  XMK_B z_WDPPckg_A_SegmentationReady, 3 XMK_E,
  XMK_B z_WDPPckg_B_ReassembleReady, XSAVEID XMK_E

    /* AwaitWDPhReady */,
  XMK_B z_WDPPckg_9_WDPhReady, 4 XMK_E,
  XMK_B z_WDPPckg_B_ReassembleReady, XSAVEID XMK_E

    /* AwaitReassembleReady */,
  XMK_B z_WDPPckg_B_ReassembleReady, 5 XMK_E

    /* idle */,
  XMK_B z_StackMgr_F_TerminateWDP, 6 XMK_E

    /* AwaitTerminated */,
  XMK_B z_WDPPckg_6_WDPhTerminated, XSAVEID XMK_E,
  XMK_B z_WDPPckg_7_ReassembleTerminated, XSAVEID XMK_E,
  XMK_B z_WDPPckg_8_SegmentationTerminated, 7 XMK_E

    /* AwaitWDPhTerminated */,
  XMK_B z_WDPPckg_6_WDPhTerminated, 8 XMK_E,
  XMK_B z_WDPPckg_7_ReassembleTerminated, XSAVEID XMK_E

    /* AwaitReassembleTerminated */,
  XMK_B z_WDPPckg_7_ReassembleTerminated, 9 XMK_E
};

/*-----------Process-PID-Values-------------*/
#ifdef XMK_USE_PID_ADDRESSING
static xPIDTable yPID_TBL_z59_WDPmanagement[X_MAX_INST_z59_WDPmanagement];
#endif

/*-----------Process Description------------*/
#define X_PRIO_z59_WDPmanagement  xDefaultPrioProcess
XCONST XPDTBL yPDTBL_z59_WDPmanagement = {
#ifdef XMK_USE_PID_ADDRESSING
  yPID_TBL_z59_WDPmanagement,
#endif
  (xINSTD *)yINSTD_z59_WDPmanagement,
  sizeof(yVDef_z59_WDPmanagement),
  X_MAX_INST_z59_WDPmanagement,
#ifdef XMK_USE_TIMESLICE
  X_TIMESLICE_z59_WDPmanagement,
#endif
#ifdef XMK_USE_PREEMPTIVE
  X_PRIO_z59_WDPmanagement,
#endif
  (xmk_T_TRANS_ADDRESS) yPAD_z59_WDPmanagement,
  yTRTBL_z59_WDPmanagement,
  xSTATE_INDEX_z59_WDPmanagement,
  yPSTATETBL_z59_WDPmanagement
};

/*+++++
* Function for process WDPmanagement
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr,4,1)
++++++*/
YPAD_FUNCTION(yPAD_z59_WDPmanagement)
{
  YPAD_YSVARP
  /* INTEGRATION: commented out statement */
  /* YPAD_YVARP(yVDef_z59_WDPmanagement) */
  YPAD_TEMP_VARS
  YPRSNAME_VAR("WDPmanagement")

  BEGIN_PAD
  switch (XSYMBOLNUMBER) {

/*-----
* START
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),197(30,25),1)
------*/
  case 0:
    BEGIN_START_TRANSITION
    XAT_FIRST_SYMBOL(0, 8078)
    XBETWEEN_SYMBOLS(10, 8088, 1612)

/*-----
* NEXTSTATE AwaitStartWDP
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),611(30,40),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitStartWDP, z590_AwaitStartWDP, "AwaitStartWDP")

/*-----
* INPUT TerminateWDP
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1652(105,40),1)
------*/
  case 1:
    XDEBUG_LABEL(AwaitStartWDP_TerminateWDP)
    XAT_FIRST_SYMBOL(1, 8079)
    XOS_TRACE_INPUT("TerminateWDP")
    XBETWEEN_SYMBOLS(11, 8089, 1629)

/*-----
* OUTPUT Ready
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1655(105,55),1)
------*/
    ALLOC_SIGNAL_PAR(Ready, z_StackMgr_9_Ready, yPDef_z_StackMgr_9_Ready)
    yAssF_SDL_Natural(((yPDef_z_StackMgr_9_Ready *)OUTSIGNAL_DATA_PTR)->Param1,
      yTstA_SDL_Natural(SDL_INTEGER_LIT(5)), XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, Ready, z_StackMgr_9_Ready,
      TO_PROCESS(StackCtrl, z17_StackCtrl), yPDef_z_StackMgr_9_Ready, "Ready")
    XBETWEEN_SYMBOLS(12, 8090, 1640)

/*-----
* NEXTSTATE -
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1658(105,70),1)
------*/
    XAT_LAST_SYMBOL
    SDL_DASH_NEXTSTATE

/*-----
* INPUT StartWDP
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\managementstart.smc(1),251(80,25),1)
------*/
  case 2:
    XDEBUG_LABEL(AwaitStartWDP_StartWDP)
    XAT_FIRST_SYMBOL(2, 8080)
    XOS_TRACE_INPUT("StartWDP")
    XBETWEEN_SYMBOLS(13, 8091, 1657)

/*-----
* OUTPUT StartWDPh
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\managementstart.smc(1),254(80,40),1)
------*/
    ALLOC_SIGNAL_NPAR(StartWDPh, z_WDPPckg_0_StartWDPh, XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, StartWDPh, z_WDPPckg_0_StartWDPh,
      TO_PROCESS(WDPhandler, z58_WDPhandler), 0, "StartWDPh")
    XBETWEEN_SYMBOLS(14, 8092, 1666)

/*-----
* NEXTSTATE AwaitReady
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\managementstart.smc(1),263(80,85),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitReady, z591_AwaitReady, "AwaitReady")

/*-----
* INPUT SegmentationReady
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1859(30,100),1)
------*/
  case 3:
    XDEBUG_LABEL(AwaitReady_SegmentationReady)
    XAT_FIRST_SYMBOL(3, 8081)
    XOS_TRACE_INPUT("SegmentationReady")
    XBETWEEN_SYMBOLS(15, 8093, 1683)

/*-----
* NEXTSTATE AwaitWDPhReady
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1865(30,115),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitWDPhReady, z592_AwaitWDPhReady, "AwaitWDPhReady")

/*-----
* INPUT WDPhReady
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1691(130,100),1)
------*/
  case 4:
    XDEBUG_LABEL(AwaitWDPhReady_WDPhReady)
    XAT_FIRST_SYMBOL(4, 8082)
    XOS_TRACE_INPUT("WDPhReady")
    XBETWEEN_SYMBOLS(16, 8094, 1700)

/*-----
* NEXTSTATE AwaitReassembleReady
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1694(130,115),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitReassembleReady, z593_AwaitReassembleReady,
      "AwaitReassembleReady")

/*-----
* INPUT ReassembleReady
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1715(30,145),1)
------*/
  case 5:
    XDEBUG_LABEL(AwaitReassembleReady_ReassembleReady)
    XAT_FIRST_SYMBOL(5, 8083)
    XOS_TRACE_INPUT("ReassembleReady")
    XBETWEEN_SYMBOLS(17, 8095, 1718)

/*-----
* OUTPUT Ready
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1724(30,160),1)
------*/
    ALLOC_SIGNAL_PAR(Ready, z_StackMgr_9_Ready, yPDef_z_StackMgr_9_Ready)
    yAssF_SDL_Natural(((yPDef_z_StackMgr_9_Ready *)OUTSIGNAL_DATA_PTR)->Param1,
      yTstA_SDL_Natural(SDL_INTEGER_LIT(5)), XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, Ready, z_StackMgr_9_Ready,
      TO_PROCESS(StackCtrl, z17_StackCtrl), yPDef_z_StackMgr_9_Ready, "Ready")
    XBETWEEN_SYMBOLS(18, 8096, 1729)

/*-----
* NEXTSTATE idle
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Startup),1727(30,175),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(idle, z594_idle, "idle")

/*-----
* INPUT TerminateWDP
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),818(30,40),1)
------*/
  case 6:
    XDEBUG_LABEL(idle_TerminateWDP)
    XAT_FIRST_SYMBOL(6, 8084)
    XOS_TRACE_INPUT("TerminateWDP")
    XBETWEEN_SYMBOLS(19, 8097, 1746)

/*-----
* OUTPUT TerminateWDPh
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\managementterminate.smc(1),302(80,55),1)
------*/
    ALLOC_SIGNAL_NPAR(TerminateWDPh, z_WDPPckg_3_TerminateWDPh,
      XSIGNALHEADERTYPE)
    SDL_OUTP_NPAR(xDefaultPrioSignal, TerminateWDPh, z_WDPPckg_3_TerminateWDPh,
      TO_PROCESS(WDPhandler, z58_WDPhandler), 0, "TerminateWDPh")
    XBETWEEN_SYMBOLS(20, 8098, 1756)

/*-----
* NEXTSTATE AwaitTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),830(30,70),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitTerminated, z595_AwaitTerminated, "AwaitTerminated")

/*-----
* INPUT SegmentationTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2006(80,40),1)
------*/
  case 7:
    XDEBUG_LABEL(AwaitTerminated_SegmentationTerminated)
    XAT_FIRST_SYMBOL(7, 8085)
    XOS_TRACE_INPUT("SegmentationTerminated")
    XBETWEEN_SYMBOLS(21, 8099, 1773)

/*-----
* NEXTSTATE AwaitWDPhTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2009(80,55),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitWDPhTerminated, z596_AwaitWDPhTerminated,
      "AwaitWDPhTerminated")

/*-----
* INPUT WDPhTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2018(30,115),1)
------*/
  case 8:
    XDEBUG_LABEL(AwaitWDPhTerminated_WDPhTerminated)
    XAT_FIRST_SYMBOL(8, 8086)
    XOS_TRACE_INPUT("WDPhTerminated")
    XBETWEEN_SYMBOLS(22, 8100, 1791)

/*-----
* NEXTSTATE AwaitReassembleTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2021(30,130),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitReassembleTerminated, z597_AwaitReassembleTerminated,
      "AwaitReassembleTerminated")

/*-----
* INPUT ReassembleTerminated
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2030(130,115),1)
------*/
  case 9:
    XDEBUG_LABEL(AwaitReassembleTerminated_ReassembleTerminated)
    XAT_FIRST_SYMBOL(9, 8087)
    XOS_TRACE_INPUT("ReassembleTerminated")
    XBETWEEN_SYMBOLS(23, 8101, 1809)

/*-----
* OUTPUT Ready
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2039(130,130),1)
------*/
    ALLOC_SIGNAL_PAR(Ready, z_StackMgr_9_Ready, yPDef_z_StackMgr_9_Ready)
    yAssF_SDL_Natural(((yPDef_z_StackMgr_9_Ready *)OUTSIGNAL_DATA_PTR)->Param1,
      yTstA_SDL_Natural(SDL_INTEGER_LIT(5)), XASSPARA);
    SDL_OUTP_PAR(xDefaultPrioSignal, Ready, z_StackMgr_9_Ready,
      TO_PROCESS(StackCtrl, z17_StackCtrl), yPDef_z_StackMgr_9_Ready, "Ready")
    XBETWEEN_SYMBOLS(24, 8102, 1820)

/*-----
* NEXTSTATE AwaitStartWDP
* #SDTREF(SDL,D:\WIP\Maintenance\4.x\System\SystemConfigurations\base_push_wta_wtls_co_korea\sdl\wdp\wdpmanagement.spr(Termination),2042(130,145),1)
------*/
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(AwaitStartWDP, z590_AwaitStartWDP, "AwaitStartWDP")
  }
  END_PAD(yPAD_z59_WDPmanagement)
}
