/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_StackMgr_H
#define XX_StackMgr_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SIGNAL StartWAPStack
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),2)
******/
#define z_StackMgr_0_StartWAPStack 28

/*****
* SIGNAL StartResult
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),3)
******/
#define z_StackMgr_1_StartResult 29
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_StackMgr_1_StartResult;

/*****
* SIGNAL StartWAE
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),4)
******/
#define z_StackMgr_2_StartWAE 30

/*****
* SIGNAL StartWSP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),5)
******/
#define z_StackMgr_3_StartWSP 31

/*****
* SIGNAL StartWTP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),6)
******/
#define z_StackMgr_4_StartWTP 32

/*****
* SIGNAL StartWTLS
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),7)
******/
#define z_StackMgr_5_StartWTLS 33

/*****
* SIGNAL StartWDP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),8)
******/
#define z_StackMgr_6_StartWDP 34

/*****
* SIGNAL StartUDCP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),9)
******/
#define z_StackMgr_7_StartUDCP 35

/*****
* SIGNAL Ready
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),10)
******/
#define z_StackMgr_8_Ready 36
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_StackMgr_8_Ready;

/*****
* SIGNAL TerminateWAPStack
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),11)
******/
#define z_StackMgr_9_TerminateWAPStack 37

/*****
* SIGNAL TerminateWAE
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),12)
******/
#define z_StackMgr_A_TerminateWAE 38

/*****
* SIGNAL TerminateWSP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),13)
******/
#define z_StackMgr_B_TerminateWSP 39

/*****
* SIGNAL TerminateWTP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),14)
******/
#define z_StackMgr_C_TerminateWTP 40

/*****
* SIGNAL TerminateWTLS
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),15)
******/
#define z_StackMgr_D_TerminateWTLS 41

/*****
* SIGNAL TerminateWDP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),16)
******/
#define z_StackMgr_E_TerminateWDP 42

/*****
* SIGNAL TerminateUDCP
* <<PACKAGE StackMgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\StackMgr.sun(1),119(20,45),17)
******/
#define z_StackMgr_F_TerminateUDCP 43

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
