/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif


/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PROCESS WAE_ME
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WAE_ME>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\WAE_ME.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z0005_WAE_ME)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\WAE_ME.spr(Init),254(5,25),2) */
    z_ctypes_4_VoidStar  z0005L_WAEManagementObject;
} yVDef_z0005_WAE_ME;
#define z0005C_StandBy  1
#define z0005D_StartingURL  2
#define z0005E_Initializing  3
#define z0005F_WaitForStartupInitUA  4
#define z0005G_Idle  5
#define z0005H_WaitForRuntimeInitUA  6
#define z0005I_TerminatingURL  7
#define z0005J_TerminatingWMLS  8
#define z0005K_TerminatingUA  9

/*****
* SYNONYM wmls_more
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),4)
******/
#define z00140D_wmls_more SDL_INTEGER_LIT(1)

/*****
* SYNONYM wmls_done
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),5)
******/
#define z00140E_wmls_done SDL_INTEGER_LIT(2)

/*****
* SYNONYM wmls_donePrev
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),6)
******/
#define z00140F_wmls_donePrev SDL_INTEGER_LIT(3)

/*****
* SYNONYM wmls_doneGo
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),7)
******/
#define z00140G_wmls_doneGo SDL_INTEGER_LIT(4)

/*****
* SYNONYM wmls_error
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),8)
******/
#define z00140H_wmls_error SDL_INTEGER_LIT(5)

/*****
* SYNONYM wmls_external
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),9)
******/
#define z00140I_wmls_external SDL_INTEGER_LIT(6)

/*****
* SYNONYM wmls_lib
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),10)
******/
#define z00140J_wmls_lib SDL_INTEGER_LIT(7)

/*****
* SYNONYM lib_dialogs
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),13)
******/
#define z00140K_lib_dialogs SDL_INTEGER_LIT(5)

/*****
* SYNONYM libFunc_prompt
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),14)
******/
#define z00140L_libFunc_prompt SDL_INTEGER_LIT(0)

/*****
* SYNONYM libFunc_confirm
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),15)
******/
#define z00140M_libFunc_confirm SDL_INTEGER_LIT(1)

/*****
* SYNONYM libFunc_alert
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),16)
******/
#define z00140N_libFunc_alert SDL_INTEGER_LIT(2)

/*****
* SYNONYM libFunc_refresh
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),17)
******/
#define z00140O_libFunc_refresh SDL_INTEGER_LIT(6)

/*****
* SYNONYM libFunc_loadString
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),18)
******/
#define z00140P_libFunc_loadString SDL_INTEGER_LIT(13)

/*****
* SYNONYM lib_browser
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),19)
******/
#define z00140Q_lib_browser SDL_INTEGER_LIT(4)

/*****
* SYNONYM lib_url
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),20)
******/
#define z00140R_lib_url SDL_INTEGER_LIT(3)

/*****
* SYNONYM lib_wta_vcc
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),23)
******/
#define z00140S_lib_wta_vcc SDL_INTEGER_LIT(513)

/*****
* SYNONYM lib_wta_nt
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),24)
******/
#define z00140T_lib_wta_nt SDL_INTEGER_LIT(514)

/*****
* SYNONYM lib_wta_pb
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),25)
******/
#define z00140U_lib_wta_pb SDL_INTEGER_LIT(515)

/*****
* SYNONYM lib_wta_misc
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),26)
******/
#define z00140V_lib_wta_misc SDL_INTEGER_LIT(516)

/*****
* SYNONYM lib_wta_cl
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),27)
******/
#define z00140W_lib_wta_cl SDL_INTEGER_LIT(519)

/*****
* SYNONYM lib_wta_gsm_nf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),28)
******/
#define z00140X_lib_wta_gsm_nf SDL_INTEGER_LIT(518)

/*****
* SYNONYM lib_wta_pdc_nf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),29)
******/
#define z00140Y_lib_wta_pdc_nf SDL_INTEGER_LIT(520)

/*****
* SYNONYM lib_wta_is_136_nf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),770(80,55),30)
******/
#define z00140Z_lib_wta_is_136_nf SDL_INTEGER_LIT(517)

/*****
* PROCESS WMLS_SM
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr,1,1)
******/
YPAD_PROTOTYPE(yPAD_z0014_WMLS_SM)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),6) */
    SDL_Integer  z001410_tmp;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),7) */
    SDL_Natural  z001411_UApidAsInt;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),8) */
    SDL_PId  z001412_UApid;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),9) */
    SDL_Integer  z001413_invokeId;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),10) */
    z_ctypes_4_VoidStar  z001414_resultStr;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),11) */
    SDL_Integer  z001415_resultBool;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),12) */
    SDL_Integer  z001416_scriptStatus;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),14) */
    SDL_Integer  z001417_wmlPrev;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),15) */
    z_ctypes_4_VoidStar  z001418_wmlGoUrl;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),17) */
    SDL_Integer  z001419_errorCode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),19) */
    SDL_Integer  z00141A_IANAcharset;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),20) */
    SDL_Natural  z00141B_strLen;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),22) */
    z_ctypes_4_VoidStar  z00141C_extUrl;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),24) */
    SDL_Natural  z00141D_libIndex;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),25) */
    SDL_Integer  z00141E_libFuncIndex;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),26) */
    z_ctypes_4_VoidStar  z00141F_libArgOpS;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),28) */
    z_ctypes_4_VoidStar  z00141G_incomingBP;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),29) */
    SDL_Natural  z00141H_incomingBPlen;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),30) */
    z_ctypes_4_VoidStar  z00141I_incomingUrl;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),31) */
    z_ctypes_4_VoidStar  z00141J_UAstruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),32) */
    SDL_Integer  z00141K_isTopPrio;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),34) */
    z_ctypes_4_VoidStar  z00141L_theSQ;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),36) */
    z_ctypes_4_VoidStar  z00141M_strMessage;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),37) */
    z_ctypes_4_VoidStar  z00141N_strDefaultInput;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),38) */
    z_ctypes_4_VoidStar  z00141O_strOk;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),39) */
    z_ctypes_4_VoidStar  z00141P_strCancel;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),40) */
    z_ctypes_4_VoidStar  z00141Q_strUrl;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),41) */
    z_ctypes_4_VoidStar  z00141R_strContentType;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),203(5,25),43) */
    SDL_Integer  z00141S_viewId;
} yVDef_z0014_WMLS_SM;

/*****
* SIGNAL Exec
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK WMLS/PROCESS WMLS_SM>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wmls\WMLS_SM.spr(1),1127(30,10),2)
******/
#define z00140A_Exec 183
#define z00140B_Idle  1
#define z00140C_Normal  2

/*****
* NEWTYPE DisplayInfoType  (TYPE section)
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2288(20,170),1)
******/
typedef struct z00222_DisplayInfoType_s {
    z_ctypes_4_VoidStar  CardURL;
    z_ctypes_4_VoidStar  Card;
    SDL_Integer  Refresh;
    SDL_Integer  Reload;
    SDL_Integer  ImagesEnabled;
    SDL_Integer  CompleteImagesDynamically;
    z_ctypes_4_VoidStar  Network;
    SDL_Integer  NewContext;
} z00222_DisplayInfoType;

/*****
* NEWTYPE DisplayInfoType  (HEADING section)
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2288(20,170),1)
******/

#define yAssF_z00222_DisplayInfoType(V,E,A)  V = E
extern void yDef_z00222_DisplayInfoType XPP(( z00222_DisplayInfoType * ));
extern SDL_Boolean yEq_z00222_DisplayInfoType XPP(( z00222_DisplayInfoType,
  z00222_DisplayInfoType ));
#define yEqF_z00222_DisplayInfoType(Expr1,Expr2)  yEq_z00222_DisplayInfoType(Expr1,Expr2)
#define yNEqF_z00222_DisplayInfoType(Expr1,Expr2)  ( ! yEq_z00222_DisplayInfoType(Expr1,Expr2) )
extern z00222_DisplayInfoType yMake_z00222_DisplayInfoType
  XPP(( z_ctypes_4_VoidStar, z_ctypes_4_VoidStar, SDL_Integer, SDL_Integer,
  SDL_Integer, SDL_Integer, z_ctypes_4_VoidStar, SDL_Integer ));
#ifndef ANY_z00222_DisplayInfoType
#define ANY_z00222_DisplayInfoType  yMake_z00222_DisplayInfoType(ANY_z_ctypes_4_VoidStar, \
  ANY_z_ctypes_4_VoidStar, ANY_SDL_Integer, ANY_SDL_Integer, ANY_SDL_Integer, \
  ANY_SDL_Integer, ANY_z_ctypes_4_VoidStar, ANY_SDL_Integer)
#endif
#define z002223_copy(P)  P

/*****
* PROCESS UA_ME
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z0020E_UA_ME)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),2) */
    z_ctypes_4_VoidStar  z0020E0H_CurrentUA;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),3) */
    z_ctypes_4_VoidStar  z0020E0I_ActiveAgentsList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),4) */
    SDL_Integer  z0020E0J_NbrOfActiveAgents;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),5) */
    SDL_Integer  z0020E0K_TempIdx;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),6) */
    SDL_Integer  z0020E0L_TempInt;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),7) */
    z_ctypes_4_VoidStar  z0020E0M_WAEManagementObject;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),8) */
    SDL_PId  z0020E0N_DestinationUA;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),9) */
    SDL_PId  z0020E0O_ThePid;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),10) */
    SDL_Integer  z0020E0P_ViewID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),11) */
    SDL_Integer  z0020E0Q_InputID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),12) */
    z_ctypes_4_VoidStar  z0020E0R_RequestURL;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),13) */
    z_ctypes_4_VoidStar  z0020E0S_Username;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),14) */
    z_ctypes_4_VoidStar  z0020E0T_Password;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),15) */
    SDL_Integer  z0020E0U_DialogID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),16) */
    SDL_Boolean  z0020E0V_Reload;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),17) */
    z_ctypes_4_VoidStar  z0020E0W_TheArgument;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),18) */
    SDL_Integer  z0020E0X_UAMode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA_ME.spr(InitVar),263(5,25),19) */
    SDL_Integer  z0020E0Y_WTAViewID;
    z_ctypes_4_VoidStar  yDcn_z_ctypes_4_VoidStar;
} yVDef_z0020E_UA_ME;

/*****
* PROCEDURE WML_GetA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS UA_ME>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_GetA.spd,1,1)
******/
extern SDL_Boolean z0020E0A_WML_GetA XPP((SDL_Boolean z0020E0A0_fPrintError));

/*****
* PROCEDURE WML_UnRA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS UA_ME>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UnRA.spd,1,1)
******/
extern void z0020E0B_WML_UnRA XPP((SDL_PId z0020E0B0_UnregPid));
#define z0020E0C_WaitForStart  1
#define z0020E0D_Idle  2
#define z0020E0F_TerminatingUserAgents  3
#define z0020E0G_TerminatingContentHandler  4

/*****
* PROCESS MMI_DISP
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_DISP.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z0020F_MMI_DISP)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_DISP.spr(VariableDecl),152(55,25),2) */
    z_ctypes_4_VoidStar  z0020F4_ActiveMMIAgents;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_DISP.spr(VariableDecl),152(55,25),3) */
    SDL_Integer  z0020F5_TempInt;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_DISP.spr(VariableDecl),152(55,25),4) */
    SDL_Integer  z0020F6_ViewID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_DISP.spr(VariableDecl),152(55,25),5) */
    SDL_Integer  z0020F7_WidgetID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_DISP.spr(VariableDecl),152(55,25),6) */
    SDL_PId  z0020F8_ThePid;
} yVDef_z0020F_MMI_DISP;

/*****
* PROCEDURE MMI_GetA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_DISP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_GetA.spd,1,1)
******/
extern SDL_PId z0020F1_MMI_GetA XPP((SDL_Integer z0020F10_Dummy));
#define z0020F2_WaitForStart  1
#define z0020F3_Idle  2

/*****
* SYNONYM CLR_NOTHING
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),2)
******/
extern SDL_Octet  z0020G1X_CLR_NOTHING;

/*****
* SYNONYM CLR_RESPONSE
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),3)
******/
extern SDL_Octet  z0020G1Y_CLR_RESPONSE;

/*****
* SYNONYM CLR_ACTIONS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),4)
******/
extern SDL_Octet  z0020G1Z_CLR_ACTIONS;

/*****
* SYNONYM CLR_REQUESTS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),5)
******/
extern SDL_Octet  z0020G20_CLR_REQUESTS;

/*****
* SYNONYM CLR_CONTEXT
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),6)
******/
extern SDL_Octet  z0020G21_CLR_CONTEXT;

/*****
* SYNONYM WTA_ERROR_CLR
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),7)
******/
extern SDL_Octet  z0020G22_WTA_ERROR_CLR;

/*****
* SYNONYM CLR_ALL
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),8)
******/
extern SDL_Octet  z0020G23_CLR_ALL;

/*****
* SYNONYM NoCache
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),10)
******/
extern SDL_Octet  z0020G24_NoCache;

/*****
* SYNONYM NoStore
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),11)
******/
extern SDL_Octet  z0020G25_NoStore;

/*****
* SYNONYM Private
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20903(105,100),12)
******/
extern SDL_Octet  z0020G26_Private;

/*****
* PROCESS WML_UA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr,1,1)
******/
YPAD_PROTOTYPE(yPAD_z0020G_WML_UA)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),2) */
    z_ctypes_4_VoidStar  z0020G28_WAEObject;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),3) */
    SDL_PId  z0020G29_PidMMI_Agent;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),4) */
    SDL_Integer  z0020G2A_ViewID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),5) */
    z_ctypes_6_ShortInt  z0020G2B_UA_Mode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),6) */
    SDL_Integer  z0020G2C_UASessionID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),10) */
    SDL_Integer  z0020G2D_iTotalNonCnfRequests;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),11) */
    SDL_Integer  z0020G2E_RequestTID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),12) */
    z_WAEPackage_2U_RequestType  z0020G2F_RequestData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),13) */
    z_ctypes_4_VoidStar  z0020G2G_RequestStruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),14) */
    z_ctypes_4_VoidStar  z0020G2H_LoadRequestURL;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),15) */
    z_ctypes_4_VoidStar  z0020G2I_RequestURL;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),16) */
    z_ctypes_6_ShortInt  z0020G2J_Reload;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),17) */
    z_ctypes_6_ShortInt  z0020G2K_RefreshSignal;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),18) */
    z_WAEPackage_2W_SessionType  z0020G2L_SessionInfo;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),21) */
    z_WAEPackage_2V_ResponseType  z0020G2M_ResponseData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),22) */
    z_ctypes_4_VoidStar  z0020G2N_ResponseURL;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),23) */
    SDL_Integer  z0020G2O_ContentTypeAsInt;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),24) */
    SDL_Integer  z0020G2P_IANACharID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),26) */
    z_ctypes_4_VoidStar  z0020G2Q_RequestedAccept;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),27) */
    z_ctypes_4_VoidStar  z0020G2R_ResponseInfo;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),28) */
    SDL_Integer  z0020G2S_ResponseTID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),29) */
    SDL_Integer  z0020G2T_ResponseSID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),30) */
    SDL_Integer  z0020G2U_ErrorCode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),31) */
    SDL_Boolean  z0020G2V_LookupCredentials;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),32) */
    z_ctypes_7_LongInt  z0020G2W_TimerStartValue;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),35) */
    SDL_Boolean  z0020G2X_IsRefreshed;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),36) */
    z_ctypes_6_ShortInt  z0020G2Y_CacheControl;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),37) */
    z_ctypes_4_VoidStar  z0020G2Z_CurrentCard;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),38) */
    z_ctypes_4_VoidStar  z0020G30_TaskElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),39) */
    z_ctypes_4_VoidStar  z0020G31_TimerElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),40) */
    z_ctypes_4_VoidStar  z0020G32_UA;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),41) */
    z_ctypes_4_VoidStar  z0020G33_Password;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),42) */
    z_ctypes_4_VoidStar  z0020G34_UserName;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),43) */
    z_ctypes_4_VoidStar  z0020G35_InputElementList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),44) */
    SDL_Integer  z0020G36_NbrOfInputElements;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),45) */
    SDL_Integer  z0020G37_ActiveScriptId;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),46) */
    SDL_Integer  z0020G38_DialogID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),47) */
    SDL_Integer  z0020G39_AuthIndex;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),48) */
    SDL_Integer  z0020G3A_IndexCounter;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),49) */
    SDL_Integer  z0020G3B_AuthType;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),50) */
    SDL_Integer  z0020G3C_NewContext;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),51) */
    z_ctypes_4_VoidStar  z0020G3D_Realm;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),52) */
    SDL_Boolean  z0020G3E_MMICleared;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),53) */
    z_ctypes_6_ShortInt  z0020G3F_Reparsing;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),55) */
    z00222_DisplayInfoType  z0020G3G_DisplayData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),56) */
    SDL_Integer  z0020G3H_EventType;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),58) */
    z_ctypes_6_ShortInt  z0020G3I_cmicro;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3941(30,40),59) */
    SDL_Integer  z0020G3J_TimerElementValue;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),15752(105,40),2) */
    SDL_Integer  z0020G3K_ScriptErrorCode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),15752(105,40),3) */
    z_ctypes_4_VoidStar  z0020G3L_ScriptResultString;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),15752(105,40),4) */
    SDL_Integer  z0020G3M_ScriptGoPrev;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),15752(105,40),5) */
    z_ctypes_4_VoidStar  z0020G3N_ScriptRequestURL;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),15752(105,40),6) */
    SDL_Boolean  z0020G3O_LoadBPMode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),13160(180,40),4) */
    z_ctypes_4_VoidStar  z0020G3P_VoidStarDummy;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),13160(180,40),5) */
    SDL_Integer  z0020G3Q_IntegerDummy;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),13160(180,40),6) */
    SDL_Integer  z0020G3R_TempInt;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3704(105,70),2) */
    SDL_Boolean  z0020G3S_ScriptActive;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3704(105,70),3) */
    SDL_Integer  z0020G3T_GoRef;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),25337(205,70),2) */
    z_ctypes_4_VoidStar  z0020G3U_WTAEventType;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),25337(205,70),3) */
    SDL_Integer  z0020G3V_WTAILibId;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),25337(205,70),4) */
    SDL_Integer  z0020G3W_WTAIFuncId;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),20828(105,85),2) */
    z_ctypes_4_VoidStar  z0020G3X_TheInputString;
    z_ctypes_4_VoidStar  yDcn_z_ctypes_4_VoidStar;
    SDL_Octet  yDcn_SDL_Octet;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3701(30,25),2) */
    DEF_TIMER_VAR(yTim_TimerEvent)
} yVDef_z0020G_WML_UA;

/*****
* PROCEDURE WML_SRQ
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_SRQ.spd,1,1)
******/
extern SDL_Integer z0020G1H_WML_SRQ XPP((SDL_Integer z0020G1H0_SID,
    z_ctypes_4_VoidStar z0020G1H1_SendURL,
    z_ctypes_4_VoidStar z0020G1H2_SendAccept,
    z_ctypes_4_VoidStar z0020G1H3_SendElement));

/*****
* PROCEDURE WML_CLR
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_CLR.spd,1,1)
******/
extern void z0020G1I_WML_CLR XPP((SDL_Octet z0020G1I0_ClearFlags));

/*****
* SIGNAL ParsingSignal
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),4721(80,25),2)
******/
#define z0020G1J_ParsingSignal 184

/*****
* SIGNAL IntrinsicEventSignal
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),4721(80,25),3)
******/
#define z0020G1K_IntrinsicEventSignal 185
#define z0020G1L_WaitForInit  1
#define z0020G1M_WaitForNewUASession  2
#define z0020G1N_WaitForMMIAgentCnf  3
#define z0020G1O_Idle  4
#define z0020G1P_Config  5
#define z0020G1R_ShuttingDown  6
#define z0020G1S_WaitForScriptCnf  7
#define z0020G1T_Parsing  8
#define z0020G1U_WaitDisplayMMI  9
#define z0020G1V_WaitForVariableInputResponse  10
#define z0020G1W_ScriptRunning  11

/*****
* TIMER TimerEvent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS WML_UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr(InitVars),3701(30,25),2)
******/
#define z0020G27_TimerEvent 1

/*****
* SYNONYM CLR_NOTHING
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),5798(130,25),2)
******/
extern SDL_Octet  z0020H1P_CLR_NOTHING;

/*****
* SYNONYM CLR_RESPONSE
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),5798(130,25),3)
******/
extern SDL_Octet  z0020H1Q_CLR_RESPONSE;

/*****
* SYNONYM CLR_MMI_LISTS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),5798(130,25),4)
******/
extern SDL_Octet  z0020H1R_CLR_MMI_LISTS;

/*****
* SYNONYM CLR_REQUESTS
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),5798(130,25),5)
******/
extern SDL_Octet  z0020H1S_CLR_REQUESTS;

/*****
* PROCESS MMI_AGNT
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr,1,1)
******/
YPAD_PROTOTYPE(yPAD_z0020H_MMI_AGNT)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),2) */
    SDL_Integer  z0020H1T_ViewID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),3) */
    z_ctypes_4_VoidStar  z0020H1U_WAEObject;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),4) */
    z_ctypes_4_VoidStar  z0020H1V_UA;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),5) */
    SDL_Integer  z0020H1W_UASessionID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),8) */
    SDL_Integer  z0020H1X_iTotalNonCnfRequests;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),9) */
    SDL_Integer  z0020H1Y_TID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),10) */
    z_WAEPackage_2U_RequestType  z0020H1Z_RequestData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),11) */
    z_ctypes_4_VoidStar  z0020H20_RequestStruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),12) */
    z_ctypes_4_VoidStar  z0020H21_RequestURL;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),15) */
    z_WAEPackage_2V_ResponseType  z0020H22_ResponseData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),16) */
    z_ctypes_4_VoidStar  z0020H23_ResponseURL;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),17) */
    z_ctypes_4_VoidStar  z0020H24_ResponseInfo;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),18) */
    SDL_Integer  z0020H25_ResponseTID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),19) */
    SDL_Integer  z0020H26_ResponseSID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),20) */
    SDL_Integer  z0020H27_ErrorCode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),22) */
    z_ctypes_4_VoidStar  z0020H28_CurrentElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),23) */
    z_ctypes_4_VoidStar  z0020H29_ContainerElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),24) */
    z_ctypes_4_VoidStar  z0020H2A_UATimerElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),25) */
    z_ctypes_4_VoidStar  z0020H2B_TaskElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),26) */
    z_ctypes_4_VoidStar  z0020H2C_RequestImageElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),27) */
    z00222_DisplayInfoType  z0020H2D_DisplayData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),29) */
    z_ctypes_4_VoidStar  z0020H2E_ListElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),30) */
    z_ctypes_4_VoidStar  z0020H2F_InputElementList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),31) */
    z_ctypes_4_VoidStar  z0020H2G_ATextElementList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),32) */
    z_ctypes_4_VoidStar  z0020H2H_AImageElementList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),33) */
    z_ctypes_4_VoidStar  z0020H2I_OptionElementList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),34) */
    z_ctypes_4_VoidStar  z0020H2J_DoElementList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),35) */
    z_ctypes_4_VoidStar  z0020H2K_ImageRequestQueue;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),37) */
    z_ctypes_4_VoidStar  z0020H2L_ElementStack;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),39) */
    z_ctypes_4_VoidStar  z0020H2M_LinkTitle;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),40) */
    SDL_Boolean  z0020H2N_InTableElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),41) */
    z_ctypes_6_ShortInt  z0020H2O_WhiteSpace;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),42) */
    z_ctypes_6_ShortInt  z0020H2P_TableWhiteSpace;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),43) */
    SDL_Integer  z0020H2Q_TableColumns;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),44) */
    SDL_Integer  z0020H2R_TempInt;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),45) */
    SDL_Integer  z0020H2S_EmphMode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),46) */
    SDL_Integer  z0020H2T_ImageNr;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),47) */
    SDL_Integer  z0020H2U_InputNr;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),48) */
    SDL_Integer  z0020H2V_TextNr;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),49) */
    SDL_Integer  z0020H2W_OptionNr;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),50) */
    SDL_Integer  z0020H2X_DoElementNr;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),737(5,25),51) */
    SDL_Integer  z0020H2Y_WidgetID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),5669(80,85),2) */
    z_ctypes_4_VoidStar  z0020H2Z_TempText;
    z_ctypes_4_VoidStar  yDcn_z_ctypes_4_VoidStar;
} yVDef_z0020H_MMI_AGNT;

/*****
* PROCEDURE MMI_CLR
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_CLR.spd,1,1)
******/
extern void z0020H1H_MMI_CLR XPP((SDL_Octet z0020H1H0_ClearFlags));

/*****
* PROCEDURE MMI_SRQ
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_SRQ.spd,1,1)
******/
extern SDL_Integer z0020H1I_MMI_SRQ XPP((SDL_Integer z0020H1I0_SID,
    z_ctypes_4_VoidStar z0020H1I1_SendURL,
    z_ctypes_4_VoidStar z0020H1I2_SendAccept,
    z_ctypes_4_VoidStar z0020H1I3_SendElement));

/*****
* SIGNAL ScheduleElement
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA/PROCESS MMI_AGNT>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\MMI_AGNT.spr(VariableDecl),5663(80,70),2)
******/
#define z0020H1J_ScheduleElement 186
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z0020H1J_ScheduleElement;
#define z0020H1K_WaitForID  1
#define z0020H1M_ShuttingDown  2
#define z0020H1N_Idle  3
#define z0020H1O_ProcessingCard  4

/*****
* PROCESS CONT_UA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z0020I_CONT_UA)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),2) */
    z_ctypes_4_VoidStar  z0020I0C_WAEObject;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),3) */
    SDL_Integer  z0020I0D_UserAgentID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),6) */
    SDL_Integer  z0020I0E_TID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),7) */
    z_WAEPackage_2U_RequestType  z0020I0F_RequestData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),8) */
    z_ctypes_4_VoidStar  z0020I0G_RequestStruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),9) */
    z_ctypes_4_VoidStar  z0020I0H_RequestURL;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),10) */
    z_WAEPackage_2W_SessionType  z0020I0I_SessionInfo;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),13) */
    z_WAEPackage_2V_ResponseType  z0020I0J_ResponseData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),14) */
    z_ctypes_4_VoidStar  z0020I0K_ResponseURL;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),15) */
    z_ctypes_4_VoidStar  z0020I0L_TempText;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),16) */
    SDL_Integer  z0020I0M_ResponseTID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),17) */
    SDL_Integer  z0020I0N_ResponseSID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),18) */
    z_ctypes_4_VoidStar  z0020I0O_ResponseInfo;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),19) */
    SDL_Integer  z0020I0P_ErrorCode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),20) */
    z_ctypes_4_VoidStar  z0020I0Q_RequestElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),21) */
    SDL_Integer  z0020I0R_TempInt;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),22) */
    SDL_Integer  z0020I0S_UrlID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),23) */
    SDL_Boolean  z0020I0T_IsOTAAllowed;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),24) */
    z_ctypes_4_VoidStar  z0020I0U_ListElement;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),25) */
    z_ctypes_4_VoidStar  z0020I0V_ContentRequestList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),26) */
    SDL_Integer  z0020I0W_UASessionID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(InitVars),707(30,25),27) */
    z_ctypes_4_VoidStar  z0020I0X_UAParam;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\CONT_UA.spr(Send),422(130,25),2) */
    SDL_Integer  z0020I0Y_RequestScheme;
    z_ctypes_4_VoidStar  yDcn_z_ctypes_4_VoidStar;
    SDL_Octet  yDcn_SDL_Octet;
} yVDef_z0020I_CONT_UA;
#define z0020I07_StandBy  1
#define z0020I08_WaitForNewUASession  2
#define z0020I09_Config  3
#define z0020I0A_Idle  4

/*****
* SIGNAL DisplayCardCnf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),8)
******/
#define z0020J_DisplayCardCnf 187
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z0020J_DisplayCardCnf;

/*****
* SIGNAL RegisterUAWithMMICnf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),9)
******/
#define z0020K_RegisterUAWithMMICnf 188

/*****
* SIGNAL TerminateMMIAgentCnf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),10)
******/
#define z0020L_TerminateMMIAgentCnf 189

/*****
* SIGNAL HandleMMIEvent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),11)
******/
#define z0020M_HandleMMIEvent 190
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z0020M_HandleMMIEvent;

/*****
* SIGNAL DisplayAbout
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),24)
******/
#define z0020N_DisplayAbout 191
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z0020N_DisplayAbout;

/*****
* SIGNAL RegisterUAWithMMI
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),25)
******/
#define z0020O_RegisterUAWithMMI 192
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z0020O_RegisterUAWithMMI;

/*****
* SIGNAL ClearMMI
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),26)
******/
#define z0020P_ClearMMI 193

/*****
* SIGNAL StopDisplay
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),27)
******/
#define z0020Q_StopDisplay 194

/*****
* SIGNAL CloseMMIAgent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),28)
******/
#define z0020R_CloseMMIAgent 195

/*****
* SIGNAL TerminateMMIAgent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),29)
******/
#define z0020S_TerminateMMIAgent 196

/*****
* SIGNAL DisplayCard
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),1937(95,25),30)
******/
#define z0020T_DisplayCard 197
typedef struct {
    SIGNAL_VARS
    z00222_DisplayInfoType  Param1;
} yPDef_z0020T_DisplayCard;

/*****
* SIGNAL TerminateWMLUACnf
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),4)
******/
#define z0020U_TerminateWMLUACnf 198

/*****
* SIGNAL StartWMLUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),19)
******/
#define z0020V_StartWMLUA 199
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z0020V_StartWMLUA;

/*****
* SIGNAL TerminateWMLUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),20)
******/
#define z0020W_TerminateWMLUA 200

/*****
* SIGNAL DiscardContext
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),21)
******/
#define z0020X_DiscardContext 201

/*****
* SIGNAL CloseWMLUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),22)
******/
#define z0020Y_CloseWMLUA 202

/*****
* SIGNAL LoadNewDeck
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),23)
******/
#define z0020Z_LoadNewDeck 203
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    z_ctypes_6_ShortInt  Param2;
    z_ctypes_6_ShortInt  Param3;
} yPDef_z0020Z_LoadNewDeck;

/*****
* SIGNAL StopAction
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),24)
******/
#define z00210_StopAction 204

/*****
* SIGNAL GoBackAction
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),25)
******/
#define z00211_GoBackAction 205

/*****
* SIGNAL BasicAuth
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),26)
******/
#define z00212_BasicAuth 206
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z00212_BasicAuth;

/*****
* SIGNAL SetExternalInputField
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),27)
******/
#define z00213_SetExternalInputField 207
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z00213_SetExternalInputField;

/*****
* SIGNAL InitializeWMLUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),28)
******/
#define z00214_InitializeWMLUA 208
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z00214_InitializeWMLUA;

/*****
* SIGNAL InitializeContentUA
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),29)
******/
#define z00215_InitializeContentUA 209
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z00215_InitializeContentUA;

/*****
* SIGNAL StartContentHandler
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),32)
******/
#define z00216_StartContentHandler 210
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z00216_StartContentHandler;

/*****
* SIGNAL TerminateContentHandler
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),33)
******/
#define z00217_TerminateContentHandler 211

/*****
* SIGNAL TerminateContentHandlerDone
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),34)
******/
#define z00218_TerminateContentHandlerDone 212

/*****
* SIGNAL StartMMiDisp
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),35)
******/
#define z00219_StartMMiDisp 213

/*****
* SIGNAL TerminateMMiDisp
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),227(25,40),36)
******/
#define z0021A_TerminateMMiDisp 214

/*****
* SIGNAL MMIKeySelect
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2177(95,135),9)
******/
#define z0021B_MMIKeySelect 215
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z0021B_MMIKeySelect;

/*****
* SIGNAL MMILinkSelectText
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2177(95,135),10)
******/
#define z0021C_MMILinkSelectText 216
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z0021C_MMILinkSelectText;

/*****
* SIGNAL MMILinkSelectImage
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2177(95,135),11)
******/
#define z0021D_MMILinkSelectImage 217
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z0021D_MMILinkSelectImage;

/*****
* SIGNAL MMIChangeOption
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2177(95,135),12)
******/
#define z0021E_MMIChangeOption 218
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z0021E_MMIChangeOption;

/*****
* SIGNAL MMILinkInfo
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2177(95,135),13)
******/
#define z0021F_MMILinkInfo 219
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z0021F_MMILinkInfo;

/*****
* SIGNAL RegisterMMIAgent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2177(95,135),21)
******/
#define z0021G_RegisterMMIAgent 220
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z0021G_RegisterMMIAgent;

/*****
* SIGNAL UnregisterMMIAgent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK UA>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2177(95,135),22)
******/
#define z0021H_UnregisterMMIAgent 221

/*****
* SYNONYM NoCache
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),413(25,140),1)
******/
extern SDL_Octet  z003R_NoCache;

/*****
* SYNONYM NoStore
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),413(25,140),2)
******/
extern SDL_Octet  z003S_NoStore;

/*****
* SYNONYM Private
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),413(25,140),3)
******/
extern SDL_Octet  z003T_Private;

/*****
* PROCESS RES_ME
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z0034_RES_ME)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),3) */
    z_WAEPackage_2U_RequestType  z00340P_stRequestStruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),4) */
    z_WAEPackage_2W_SessionType  z00340Q_stNewSessionStruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),5) */
    SDL_PId  z00340R_pidWmlUa;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),5) */
    SDL_PId  z00340S_pidSessionProc;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),6) */
    z_ctypes_4_VoidStar  z00340T_vsWAEMainObject;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),6) */
    z_ctypes_4_VoidStar  z00340U_vsPidIndexList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),6) */
    z_ctypes_4_VoidStar  z00340V_vsTransList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),6) */
    z_ctypes_4_VoidStar  z00340W_vsSessionList;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),6) */
    z_ctypes_4_VoidStar  z00340X_vsDummy;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),7) */
    z_ctypes_A_UnsignedLongInt  z00340Y_uliLastModified;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),7) */
    z_ctypes_A_UnsignedLongInt  z00340Z_uiPidIndex;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),8) */
    SDL_Integer  z003410_iErrorCode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),8) */
    SDL_Integer  z003411_iSID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),8) */
    SDL_Integer  z003412_iTID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),8) */
    SDL_Integer  z003413_iSIDCounter;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),8) */
    SDL_Integer  z003414_iDummy;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),8) */
    SDL_Integer  z003415_iDummy2;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),9) */
    SDL_Boolean  z003416_bDummy;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),3848(5,25),10) */
    SDL_Octet  z003417_oBearer;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_ME.spr(Declarations_7),4598(5,70),2) */
    z_WAEPackage_2V_ResponseType  z003418_stResponseStruct;
} yVDef_z0034_RES_ME;
#define z00340I_WaitStart  1
#define z00340J_WaitCCStarted  2
#define z00340K_WaitDIStarted  3
#define z00340L_Idle  4
#define z00340M_WaitForTerminateSessionDone  5
#define z00340N_WaitForCCTerminateAck  6
#define z00340O_WaitForDITerminateAck  7

/*****
* PROCESS RES_CC
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z0035_RES_CC)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),3) */
    z_WAEPackage_2U_RequestType  z00355_stRequestStruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),4) */
    z_WAEPackage_2V_ResponseType  z00356_stResponseStruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),5) */
    SDL_PId  z00357_pidWmlUa;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),6) */
    z_ctypes_4_VoidStar  z00358_vsWAEMainObject;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),6) */
    z_ctypes_4_VoidStar  z00359_vsHeader;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),6) */
    z_ctypes_4_VoidStar  z0035A_vsBody;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),7) */
    z_ctypes_A_UnsignedLongInt  z0035B_uliLastModified;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),8) */
    z_ctypes_7_LongInt  z0035C_liCacheSize;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),8) */
    z_ctypes_7_LongInt  z0035D_liDummy;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),9) */
    SDL_Integer  z0035E_iDummy;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),9) */
    SDL_Integer  z0035F_iHeaderLength;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),9) */
    SDL_Integer  z0035G_iCacheInIdle;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),10) */
    SDL_Integer  z0035H_iFirstInit;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),10) */
    SDL_Integer  z0035I_iErrorCode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),10) */
    SDL_Integer  z0035J_iCacheDirective;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),10) */
    SDL_Integer  z0035K_iRedirected;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),239(5,175),11) */
    SDL_Octet  z0035L_oCacheValue;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),2648(105,190),2) */
    SDL_Integer  z0035M_iSID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),2648(105,190),2) */
    SDL_Integer  z0035N_iTID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),2648(105,190),2) */
    SDL_Integer  z0035O_iBodyLen;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr(Start_1),2648(105,190),3) */
    SDL_Boolean  z0035P_bDummy1;
    SDL_Octet  yDcn_SDL_Octet;
} yVDef_z0035_RES_CC;
#define z00352_WaitStart  1
#define z00353_WaitInitCache  2
#define z00354_Idle  3

/*****
* PROCESS RES_FC
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z0036_RES_FC)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),2) */
    z_WAEPackage_2U_RequestType  z00365_stRequestStruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),3) */
    z_WAEPackage_2V_ResponseType  z00366_stResponseStruct;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),4) */
    z_ctypes_4_VoidStar  z00367_vsData;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),4) */
    z_ctypes_4_VoidStar  z00368_vsContentType;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),4) */
    z_ctypes_4_VoidStar  z00369_vsParameters;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),5) */
    SDL_PId  z0036A_pidWmlUa;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),6) */
    SDL_Integer  z0036B_iTID;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),6) */
    SDL_Integer  z0036C_iErrorCode;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),6) */
    SDL_Integer  z0036D_iDataLength;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),215(5,205),6) */
    SDL_Integer  z0036E_iDummy;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),224(5,190),2) */
    DEF_TIMER_VAR(yTim_FileTimeOut)
} yVDef_z0036_RES_FC;
#define z00362_Idle  1
#define z00363_WaitForFileResponse  2

/*****
* TIMER FileTimeOut
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler/PROCESS RES_FC>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_FC.spr(Idle_1),224(5,190),2)
******/
#define z00364_FileTimeOut 2

/*****
* SIGNAL StartCC
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),251(25,45),7)
******/
#define z0037_StartCC 222
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z0037_StartCC;

/*****
* SIGNAL TerminateCC
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),251(25,45),8)
******/
#define z0038_TerminateCC 223

/*****
* SIGNAL ME_UrlInCache
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),251(25,45),9)
******/
#define z0039_ME_UrlInCache 224
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2U_RequestType  Param1;
    SDL_PId  Param2;
} yPDef_z0039_ME_UrlInCache;

/*****
* SIGNAL StartCCDone
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),251(25,45),17)
******/
#define z003A_StartCCDone 225

/*****
* SIGNAL TerminateCCDone
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),251(25,45),18)
******/
#define z003B_TerminateCCDone 226

/*****
* SIGNAL ME_ReqToWSP
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),251(25,45),19)
******/
#define z003C_ME_ReqToWSP 227
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2U_RequestType  Param1;
    SDL_PId  Param2;
    z_ctypes_A_UnsignedLongInt  Param3;
} yPDef_z003C_ME_ReqToWSP;

/*****
* SIGNAL GetFileContent
* <<SYSTEM WAP/BLOCK WAE/SUBSTRUCTURE WAE/BLOCK ResourceHandler>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_HAND.sbk(2),251(25,45),23)
******/
#define z003D_GetFileContent 228
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2U_RequestType  Param1;
    SDL_PId  Param2;
} yPDef_z003D_GetFileContent;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\WAE.sbk,4,1) */
#include "errcodes.h"
#include "waedef.h"
#include "wae_cmmn.h"
#include "cache.h"
#include "header.h"
#include "capiclnt.h"
#include "si_sdl.h"
#include "aapimmi.h"
#include "aapiclnt.h"
#include "logcodes.h"
#include "URL.h"

                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\UA.sbk(2),2288(20,170),10) */
#include "wmldef.h"
#include "wml_uafn.h"
#include "wml_mmi.h"
#include "wmlif.h"
#include "wmltoken.h"

                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wml\WML_UA.spr,1,1) */
#include "wmlelm.h"

                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\wae\wspif\RES_CC.spr,4,1) */
#include "aapimem.h"

