/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#define C_MICRO_1_3
#include "ml_typ.h"
#include "ctypes.h"
#include "GlblDecl.h"
#include "WAE_WSP.h"


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* NEWTYPE SUnitMethodInvokeReqType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionLess),212(25,45),3)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SUnitMethodInvokeReqType( SUnitMethodInvokeReqType *yVar )
#else
extern void yDef_SUnitMethodInvokeReqType( yVar )
  SUnitMethodInvokeReqType *yVar;
#endif
{
  yDef_AddressType(&((*yVar).ServerAddress));
  yDef_AddressType(&((*yVar).ClientAddress));
  xDef_SDL_Octet(&((*yVar).TransactionId));
  xDef_SDL_Octet(&((*yVar).Method));
  xDef_SDL_Integer(&((*yVar).URILen));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  xDef_SDL_Integer(&((*yVar).BodyLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RequestURI));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RequestHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RequestBody));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SUnitMethodInvokeReqType(
  SUnitMethodInvokeReqType yExpr1,
  SUnitMethodInvokeReqType yExpr2 )
#else
extern SDL_Boolean yEq_SUnitMethodInvokeReqType( yExpr1, yExpr2 )
  SUnitMethodInvokeReqType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_AddressType(yExpr1.ServerAddress, yExpr2.ServerAddress) )
  return SDL_False;
  if ( yNEqF_AddressType(yExpr1.ClientAddress, yExpr2.ClientAddress) )
  return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.TransactionId, yExpr2.TransactionId) )
  return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.Method, yExpr2.Method) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.URILen, yExpr2.URILen) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyLen, yExpr2.BodyLen) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RequestURI, yExpr2.RequestURI) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RequestHeaders,
  yExpr2.RequestHeaders) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RequestBody, yExpr2.RequestBody) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SUnitMethodInvokeReqType yMake_SUnitMethodInvokeReqType(
  AddressType yServerAddress,
  AddressType yClientAddress,
  SDL_Octet yTransactionId,
  SDL_Octet yMethod,
  SDL_Integer yURILen,
  SDL_Integer yHeadersLen,
  SDL_Integer yBodyLen,
  z_ctypes_4_VoidStar yRequestURI,
  z_ctypes_4_VoidStar yRequestHeaders,
  z_ctypes_4_VoidStar yRequestBody )
#else
extern SUnitMethodInvokeReqType  yMake_SUnitMethodInvokeReqType
  ( yServerAddress, yClientAddress, yTransactionId, yMethod, yURILen,
  yHeadersLen, yBodyLen, yRequestURI, yRequestHeaders, yRequestBody )
  AddressType yServerAddress;
  AddressType yClientAddress;
  SDL_Octet yTransactionId;
  SDL_Octet yMethod;
  SDL_Integer yURILen;
  SDL_Integer yHeadersLen;
  SDL_Integer yBodyLen;
  z_ctypes_4_VoidStar yRequestURI;
  z_ctypes_4_VoidStar yRequestHeaders;
  z_ctypes_4_VoidStar yRequestBody;
#endif
{
  SUnitMethodInvokeReqType  yVar;
  memset((void *)(&yVar), 0, sizeof(SUnitMethodInvokeReqType));
  yAssF_AddressType(yVar.ServerAddress, yServerAddress, XASSMAKE);
  yAssF_AddressType(yVar.ClientAddress, yClientAddress, XASSMAKE);
  yAssF_SDL_Octet(yVar.TransactionId, yTransactionId, XASSMAKE);
  yAssF_SDL_Octet(yVar.Method, yMethod, XASSMAKE);
  yAssF_SDL_Integer(yVar.URILen, yURILen, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyLen, yBodyLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RequestURI, yRequestURI, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RequestHeaders, yRequestHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RequestBody, yRequestBody, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SUnitMethodResultIndType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionLess),212(25,45),16)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SUnitMethodResultIndType( SUnitMethodResultIndType *yVar )
#else
extern void yDef_SUnitMethodResultIndType( yVar )
  SUnitMethodResultIndType *yVar;
#endif
{
  yDef_AddressType(&((*yVar).ClientAddress));
  yDef_AddressType(&((*yVar).ServerAddress));
  xDef_SDL_Octet(&((*yVar).TransactionId));
  xDef_SDL_Octet(&((*yVar).Status));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  xDef_SDL_Integer(&((*yVar).BodyLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ResponseHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ResponseBody));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SUnitMethodResultIndType(
  SUnitMethodResultIndType yExpr1,
  SUnitMethodResultIndType yExpr2 )
#else
extern SDL_Boolean yEq_SUnitMethodResultIndType( yExpr1, yExpr2 )
  SUnitMethodResultIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_AddressType(yExpr1.ClientAddress, yExpr2.ClientAddress) )
  return SDL_False;
  if ( yNEqF_AddressType(yExpr1.ServerAddress, yExpr2.ServerAddress) )
  return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.TransactionId, yExpr2.TransactionId) )
  return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.Status, yExpr2.Status) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyLen, yExpr2.BodyLen) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ResponseHeaders,
  yExpr2.ResponseHeaders) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ResponseBody, yExpr2.ResponseBody) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SUnitMethodResultIndType yMake_SUnitMethodResultIndType(
  AddressType yClientAddress,
  AddressType yServerAddress,
  SDL_Octet yTransactionId,
  SDL_Octet yStatus,
  SDL_Integer yHeadersLen,
  SDL_Integer yBodyLen,
  z_ctypes_4_VoidStar yResponseHeaders,
  z_ctypes_4_VoidStar yResponseBody )
#else
extern SUnitMethodResultIndType  yMake_SUnitMethodResultIndType
  ( yClientAddress, yServerAddress, yTransactionId, yStatus, yHeadersLen,
  yBodyLen, yResponseHeaders, yResponseBody )
  AddressType yClientAddress;
  AddressType yServerAddress;
  SDL_Octet yTransactionId;
  SDL_Octet yStatus;
  SDL_Integer yHeadersLen;
  SDL_Integer yBodyLen;
  z_ctypes_4_VoidStar yResponseHeaders;
  z_ctypes_4_VoidStar yResponseBody;
#endif
{
  SUnitMethodResultIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(SUnitMethodResultIndType));
  yAssF_AddressType(yVar.ClientAddress, yClientAddress, XASSMAKE);
  yAssF_AddressType(yVar.ServerAddress, yServerAddress, XASSMAKE);
  yAssF_SDL_Octet(yVar.TransactionId, yTransactionId, XASSMAKE);
  yAssF_SDL_Octet(yVar.Status, yStatus, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyLen, yBodyLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ResponseHeaders, yResponseHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ResponseBody, yResponseBody, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SUnitPushIndType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionLess),212(25,45),27)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SUnitPushIndType( SUnitPushIndType *yVar )
#else
extern void yDef_SUnitPushIndType( yVar )
  SUnitPushIndType *yVar;
#endif
{
  yDef_AddressType(&((*yVar).ClientAddress));
  yDef_AddressType(&((*yVar).ServerAddress));
  xDef_SDL_Octet(&((*yVar).PushId));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  xDef_SDL_Integer(&((*yVar).BodyLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).PushHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).PushBody));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SUnitPushIndType(
  SUnitPushIndType yExpr1,
  SUnitPushIndType yExpr2 )
#else
extern SDL_Boolean yEq_SUnitPushIndType( yExpr1, yExpr2 )
  SUnitPushIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_AddressType(yExpr1.ClientAddress, yExpr2.ClientAddress) )
  return SDL_False;
  if ( yNEqF_AddressType(yExpr1.ServerAddress, yExpr2.ServerAddress) )
  return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.PushId, yExpr2.PushId) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyLen, yExpr2.BodyLen) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.PushHeaders, yExpr2.PushHeaders) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.PushBody, yExpr2.PushBody) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SUnitPushIndType yMake_SUnitPushIndType(
  AddressType yClientAddress,
  AddressType yServerAddress,
  SDL_Octet yPushId,
  SDL_Integer yHeadersLen,
  SDL_Integer yBodyLen,
  z_ctypes_4_VoidStar yPushHeaders,
  z_ctypes_4_VoidStar yPushBody )
#else
extern SUnitPushIndType  yMake_SUnitPushIndType( yClientAddress,
  yServerAddress, yPushId, yHeadersLen, yBodyLen, yPushHeaders, yPushBody )
  AddressType yClientAddress;
  AddressType yServerAddress;
  SDL_Octet yPushId;
  SDL_Integer yHeadersLen;
  SDL_Integer yBodyLen;
  z_ctypes_4_VoidStar yPushHeaders;
  z_ctypes_4_VoidStar yPushBody;
#endif
{
  SUnitPushIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(SUnitPushIndType));
  yAssF_AddressType(yVar.ClientAddress, yClientAddress, XASSMAKE);
  yAssF_AddressType(yVar.ServerAddress, yServerAddress, XASSMAKE);
  yAssF_SDL_Octet(yVar.PushId, yPushId, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyLen, yBodyLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.PushHeaders, yPushHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.PushBody, yPushBody, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SConnectReqType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode1),119(25,40),1)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SConnectReqType( SConnectReqType *yVar )
#else
extern void yDef_SConnectReqType( yVar )
  SConnectReqType *yVar;
#endif
{
  yDef_AddressType(&((*yVar).ServerAddress));
  yDef_AddressType(&((*yVar).ClientAddress));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  xDef_SDL_Integer(&((*yVar).CapabilitiesLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ClientHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RequestedCapabilities));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SConnectReqType(
  SConnectReqType yExpr1,
  SConnectReqType yExpr2 )
#else
extern SDL_Boolean yEq_SConnectReqType( yExpr1, yExpr2 )
  SConnectReqType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_AddressType(yExpr1.ServerAddress, yExpr2.ServerAddress) )
  return SDL_False;
  if ( yNEqF_AddressType(yExpr1.ClientAddress, yExpr2.ClientAddress) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.CapabilitiesLen, yExpr2.CapabilitiesLen) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ClientHeaders, yExpr2.ClientHeaders) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RequestedCapabilities,
  yExpr2.RequestedCapabilities) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SConnectReqType yMake_SConnectReqType(
  AddressType yServerAddress,
  AddressType yClientAddress,
  SDL_Integer yHeadersLen,
  SDL_Integer yCapabilitiesLen,
  z_ctypes_4_VoidStar yClientHeaders,
  z_ctypes_4_VoidStar yRequestedCapabilities )
#else
extern SConnectReqType  yMake_SConnectReqType( yServerAddress, yClientAddress,
  yHeadersLen, yCapabilitiesLen, yClientHeaders, yRequestedCapabilities )
  AddressType yServerAddress;
  AddressType yClientAddress;
  SDL_Integer yHeadersLen;
  SDL_Integer yCapabilitiesLen;
  z_ctypes_4_VoidStar yClientHeaders;
  z_ctypes_4_VoidStar yRequestedCapabilities;
#endif
{
  SConnectReqType  yVar;
  memset((void *)(&yVar), 0, sizeof(SConnectReqType));
  yAssF_AddressType(yVar.ServerAddress, yServerAddress, XASSMAKE);
  yAssF_AddressType(yVar.ClientAddress, yClientAddress, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.CapabilitiesLen, yCapabilitiesLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ClientHeaders, yClientHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RequestedCapabilities, yRequestedCapabilities,
    XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SConnectCnfType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode1),119(25,40),10)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SConnectCnfType( SConnectCnfType *yVar )
#else
extern void yDef_SConnectCnfType( yVar )
  SConnectCnfType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Natural(&((*yVar).HeadersLen));
  xDef_SDL_Natural(&((*yVar).CapabilitiesLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ServerHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).NegotiatedCapabilities));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SConnectCnfType(
  SConnectCnfType yExpr1,
  SConnectCnfType yExpr2 )
#else
extern SDL_Boolean yEq_SConnectCnfType( yExpr1, yExpr2 )
  SConnectCnfType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Natural(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Natural(yExpr1.CapabilitiesLen, yExpr2.CapabilitiesLen) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ServerHeaders, yExpr2.ServerHeaders) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.NegotiatedCapabilities,
  yExpr2.NegotiatedCapabilities) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SConnectCnfType yMake_SConnectCnfType(
  SDL_Integer ySourcePort,
  SDL_Natural yHeadersLen,
  SDL_Natural yCapabilitiesLen,
  z_ctypes_4_VoidStar yServerHeaders,
  z_ctypes_4_VoidStar yNegotiatedCapabilities )
#else
extern SConnectCnfType  yMake_SConnectCnfType( ySourcePort, yHeadersLen,
  yCapabilitiesLen, yServerHeaders, yNegotiatedCapabilities )
  SDL_Integer ySourcePort;
  SDL_Natural yHeadersLen;
  SDL_Natural yCapabilitiesLen;
  z_ctypes_4_VoidStar yServerHeaders;
  z_ctypes_4_VoidStar yNegotiatedCapabilities;
#endif
{
  SConnectCnfType  yVar;
  memset((void *)(&yVar), 0, sizeof(SConnectCnfType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Natural(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Natural(yVar.CapabilitiesLen, yCapabilitiesLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ServerHeaders, yServerHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.NegotiatedCapabilities,
    yNegotiatedCapabilities, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SDisconnectType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode1),122(25,120),1)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SDisconnectType( SDisconnectType *yVar )
#else
extern void yDef_SDisconnectType( yVar )
  SDisconnectType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Natural(&((*yVar).ReasonCode));
  xDef_SDL_Boolean(&((*yVar).RedirectSecurity));
  xDef_SDL_Integer(&((*yVar).AddressesLen));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  xDef_SDL_Integer(&((*yVar).BodyLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RedirectAddresses));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ErrorHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ErrorBody));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SDisconnectType(
  SDisconnectType yExpr1,
  SDisconnectType yExpr2 )
#else
extern SDL_Boolean yEq_SDisconnectType( yExpr1, yExpr2 )
  SDisconnectType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Natural(yExpr1.ReasonCode, yExpr2.ReasonCode) )
  return SDL_False;
  if ( yNEqF_SDL_Boolean(yExpr1.RedirectSecurity, yExpr2.RedirectSecurity) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.AddressesLen, yExpr2.AddressesLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyLen, yExpr2.BodyLen) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RedirectAddresses,
  yExpr2.RedirectAddresses) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ErrorHeaders, yExpr2.ErrorHeaders) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ErrorBody, yExpr2.ErrorBody) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SDisconnectType yMake_SDisconnectType(
  SDL_Integer ySourcePort,
  SDL_Natural yReasonCode,
  SDL_Boolean yRedirectSecurity,
  SDL_Integer yAddressesLen,
  SDL_Integer yHeadersLen,
  SDL_Integer yBodyLen,
  z_ctypes_4_VoidStar yRedirectAddresses,
  z_ctypes_4_VoidStar yErrorHeaders,
  z_ctypes_4_VoidStar yErrorBody )
#else
extern SDisconnectType  yMake_SDisconnectType( ySourcePort, yReasonCode,
  yRedirectSecurity, yAddressesLen, yHeadersLen, yBodyLen, yRedirectAddresses,
  yErrorHeaders, yErrorBody )
  SDL_Integer ySourcePort;
  SDL_Natural yReasonCode;
  SDL_Boolean yRedirectSecurity;
  SDL_Integer yAddressesLen;
  SDL_Integer yHeadersLen;
  SDL_Integer yBodyLen;
  z_ctypes_4_VoidStar yRedirectAddresses;
  z_ctypes_4_VoidStar yErrorHeaders;
  z_ctypes_4_VoidStar yErrorBody;
#endif
{
  SDisconnectType  yVar;
  memset((void *)(&yVar), 0, sizeof(SDisconnectType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Natural(yVar.ReasonCode, yReasonCode, XASSMAKE);
  yAssF_SDL_Boolean(yVar.RedirectSecurity, yRedirectSecurity, XASSMAKE);
  yAssF_SDL_Integer(yVar.AddressesLen, yAddressesLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyLen, yBodyLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RedirectAddresses, yRedirectAddresses,
    XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ErrorHeaders, yErrorHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ErrorBody, yErrorBody, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SMethodInvokeReqType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode2),140(20,40),1)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SMethodInvokeReqType( SMethodInvokeReqType *yVar )
#else
extern void yDef_SMethodInvokeReqType( yVar )
  SMethodInvokeReqType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).ClientTransactionId));
  xDef_SDL_Octet(&((*yVar).Method));
  xDef_SDL_Integer(&((*yVar).URILen));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  xDef_SDL_Integer(&((*yVar).BodyLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RequestURI));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RequestHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RequestBody));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SMethodInvokeReqType(
  SMethodInvokeReqType yExpr1,
  SMethodInvokeReqType yExpr2 )
#else
extern SDL_Boolean yEq_SMethodInvokeReqType( yExpr1, yExpr2 )
  SMethodInvokeReqType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.ClientTransactionId,
  yExpr2.ClientTransactionId) ) return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.Method, yExpr2.Method) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.URILen, yExpr2.URILen) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyLen, yExpr2.BodyLen) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RequestURI, yExpr2.RequestURI) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RequestHeaders,
  yExpr2.RequestHeaders) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RequestBody, yExpr2.RequestBody) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SMethodInvokeReqType yMake_SMethodInvokeReqType(
  SDL_Integer ySourcePort,
  SDL_Integer yClientTransactionId,
  SDL_Octet yMethod,
  SDL_Integer yURILen,
  SDL_Integer yHeadersLen,
  SDL_Integer yBodyLen,
  z_ctypes_4_VoidStar yRequestURI,
  z_ctypes_4_VoidStar yRequestHeaders,
  z_ctypes_4_VoidStar yRequestBody )
#else
extern SMethodInvokeReqType  yMake_SMethodInvokeReqType( ySourcePort,
  yClientTransactionId, yMethod, yURILen, yHeadersLen, yBodyLen, yRequestURI,
  yRequestHeaders, yRequestBody )
  SDL_Integer ySourcePort;
  SDL_Integer yClientTransactionId;
  SDL_Octet yMethod;
  SDL_Integer yURILen;
  SDL_Integer yHeadersLen;
  SDL_Integer yBodyLen;
  z_ctypes_4_VoidStar yRequestURI;
  z_ctypes_4_VoidStar yRequestHeaders;
  z_ctypes_4_VoidStar yRequestBody;
#endif
{
  SMethodInvokeReqType  yVar;
  memset((void *)(&yVar), 0, sizeof(SMethodInvokeReqType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.ClientTransactionId, yClientTransactionId, XASSMAKE);
  yAssF_SDL_Octet(yVar.Method, yMethod, XASSMAKE);
  yAssF_SDL_Integer(yVar.URILen, yURILen, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyLen, yBodyLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RequestURI, yRequestURI, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RequestHeaders, yRequestHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RequestBody, yRequestBody, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SMethodInvokeCnfType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode2),140(20,40),13)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SMethodInvokeCnfType( SMethodInvokeCnfType *yVar )
#else
extern void yDef_SMethodInvokeCnfType( yVar )
  SMethodInvokeCnfType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).ClientTransactionId));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SMethodInvokeCnfType(
  SMethodInvokeCnfType yExpr1,
  SMethodInvokeCnfType yExpr2 )
#else
extern SDL_Boolean yEq_SMethodInvokeCnfType( yExpr1, yExpr2 )
  SMethodInvokeCnfType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.ClientTransactionId,
  yExpr2.ClientTransactionId) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SMethodInvokeCnfType yMake_SMethodInvokeCnfType(
  SDL_Integer ySourcePort,
  SDL_Integer yClientTransactionId )
#else
extern SMethodInvokeCnfType  yMake_SMethodInvokeCnfType( ySourcePort,
  yClientTransactionId )
  SDL_Integer ySourcePort;
  SDL_Integer yClientTransactionId;
#endif
{
  SMethodInvokeCnfType  yVar;
  memset((void *)(&yVar), 0, sizeof(SMethodInvokeCnfType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.ClientTransactionId, yClientTransactionId, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SMethodResultIndType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode2),143(20,100),1)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SMethodResultIndType( SMethodResultIndType *yVar )
#else
extern void yDef_SMethodResultIndType( yVar )
  SMethodResultIndType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).ClientTransactionId));
  xDef_SDL_Octet(&((*yVar).Status));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  xDef_SDL_Integer(&((*yVar).BodyLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ResponseHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ResponseBody));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SMethodResultIndType(
  SMethodResultIndType yExpr1,
  SMethodResultIndType yExpr2 )
#else
extern SDL_Boolean yEq_SMethodResultIndType( yExpr1, yExpr2 )
  SMethodResultIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.ClientTransactionId,
  yExpr2.ClientTransactionId) ) return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.Status, yExpr2.Status) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyLen, yExpr2.BodyLen) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ResponseHeaders,
  yExpr2.ResponseHeaders) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ResponseBody, yExpr2.ResponseBody) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SMethodResultIndType yMake_SMethodResultIndType(
  SDL_Integer ySourcePort,
  SDL_Integer yClientTransactionId,
  SDL_Octet yStatus,
  SDL_Integer yHeadersLen,
  SDL_Integer yBodyLen,
  z_ctypes_4_VoidStar yResponseHeaders,
  z_ctypes_4_VoidStar yResponseBody )
#else
extern SMethodResultIndType  yMake_SMethodResultIndType( ySourcePort,
  yClientTransactionId, yStatus, yHeadersLen, yBodyLen, yResponseHeaders,
  yResponseBody )
  SDL_Integer ySourcePort;
  SDL_Integer yClientTransactionId;
  SDL_Octet yStatus;
  SDL_Integer yHeadersLen;
  SDL_Integer yBodyLen;
  z_ctypes_4_VoidStar yResponseHeaders;
  z_ctypes_4_VoidStar yResponseBody;
#endif
{
  SMethodResultIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(SMethodResultIndType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.ClientTransactionId, yClientTransactionId, XASSMAKE);
  yAssF_SDL_Octet(yVar.Status, yStatus, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyLen, yBodyLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ResponseHeaders, yResponseHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ResponseBody, yResponseBody, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SMethodResultResType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode2),143(20,100),11)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SMethodResultResType( SMethodResultResType *yVar )
#else
extern void yDef_SMethodResultResType( yVar )
  SMethodResultResType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).ClientTransactionId));
  yDef_z_ctypes_4_VoidStar(&((*yVar).AcknowledgementHeaders));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SMethodResultResType(
  SMethodResultResType yExpr1,
  SMethodResultResType yExpr2 )
#else
extern SDL_Boolean yEq_SMethodResultResType( yExpr1, yExpr2 )
  SMethodResultResType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.ClientTransactionId,
  yExpr2.ClientTransactionId) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.AcknowledgementHeaders,
  yExpr2.AcknowledgementHeaders) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SMethodResultResType yMake_SMethodResultResType(
  SDL_Integer ySourcePort,
  SDL_Integer yClientTransactionId,
  z_ctypes_4_VoidStar yAcknowledgementHeaders )
#else
extern SMethodResultResType  yMake_SMethodResultResType( ySourcePort,
  yClientTransactionId, yAcknowledgementHeaders )
  SDL_Integer ySourcePort;
  SDL_Integer yClientTransactionId;
  z_ctypes_4_VoidStar yAcknowledgementHeaders;
#endif
{
  SMethodResultResType  yVar;
  memset((void *)(&yVar), 0, sizeof(SMethodResultResType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.ClientTransactionId, yClientTransactionId, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.AcknowledgementHeaders,
    yAcknowledgementHeaders, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SMethodAbortReqType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode2),146(20,165),1)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_10_SMethodAbortReqType(
   z_WAE_WSP_10_SMethodAbortReqType *yVar )
#else
extern void yDef_z_WAE_WSP_10_SMethodAbortReqType( yVar )
  z_WAE_WSP_10_SMethodAbortReqType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).TransactionId));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_10_SMethodAbortReqType(
  z_WAE_WSP_10_SMethodAbortReqType yExpr1,
  z_WAE_WSP_10_SMethodAbortReqType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_10_SMethodAbortReqType( yExpr1, yExpr2 )
  z_WAE_WSP_10_SMethodAbortReqType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.TransactionId, yExpr2.TransactionId) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_10_SMethodAbortReqType yMake_z_WAE_WSP_10_SMethodAbortReqType(
  SDL_Integer ySourcePort,
  SDL_Integer yTransactionId )
#else
extern z_WAE_WSP_10_SMethodAbortReqType  yMake_z_WAE_WSP_10_SMethodAbortReqType
  ( ySourcePort, yTransactionId )
  SDL_Integer ySourcePort;
  SDL_Integer yTransactionId;
#endif
{
  z_WAE_WSP_10_SMethodAbortReqType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_10_SMethodAbortReqType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.TransactionId, yTransactionId, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SMethodAbortIndType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode2),146(20,165),6)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_11_SMethodAbortIndType(
   z_WAE_WSP_11_SMethodAbortIndType *yVar )
#else
extern void yDef_z_WAE_WSP_11_SMethodAbortIndType( yVar )
  z_WAE_WSP_11_SMethodAbortIndType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).TransactionId));
  xDef_SDL_Natural(&((*yVar).Reason));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_11_SMethodAbortIndType(
  z_WAE_WSP_11_SMethodAbortIndType yExpr1,
  z_WAE_WSP_11_SMethodAbortIndType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_11_SMethodAbortIndType( yExpr1, yExpr2 )
  z_WAE_WSP_11_SMethodAbortIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.TransactionId, yExpr2.TransactionId) )
  return SDL_False;
  if ( yNEqF_SDL_Natural(yExpr1.Reason, yExpr2.Reason) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_11_SMethodAbortIndType yMake_z_WAE_WSP_11_SMethodAbortIndType(
  SDL_Integer ySourcePort,
  SDL_Integer yTransactionId,
  SDL_Natural yReason )
#else
extern z_WAE_WSP_11_SMethodAbortIndType  yMake_z_WAE_WSP_11_SMethodAbortIndType
  ( ySourcePort, yTransactionId, yReason )
  SDL_Integer ySourcePort;
  SDL_Integer yTransactionId;
  SDL_Natural yReason;
#endif
{
  z_WAE_WSP_11_SMethodAbortIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_11_SMethodAbortIndType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.TransactionId, yTransactionId, XASSMAKE);
  yAssF_SDL_Natural(yVar.Reason, yReason, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SPushIndType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),167(20,40),1)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_12_SPushIndType( z_WAE_WSP_12_SPushIndType *yVar )
#else
extern void yDef_z_WAE_WSP_12_SPushIndType( yVar )
  z_WAE_WSP_12_SPushIndType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  xDef_SDL_Integer(&((*yVar).BodyLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).PushHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).PushBody));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_12_SPushIndType(
  z_WAE_WSP_12_SPushIndType yExpr1,
  z_WAE_WSP_12_SPushIndType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_12_SPushIndType( yExpr1, yExpr2 )
  z_WAE_WSP_12_SPushIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyLen, yExpr2.BodyLen) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.PushHeaders, yExpr2.PushHeaders) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.PushBody, yExpr2.PushBody) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_12_SPushIndType yMake_z_WAE_WSP_12_SPushIndType(
  SDL_Integer ySourcePort,
  SDL_Integer yHeadersLen,
  SDL_Integer yBodyLen,
  z_ctypes_4_VoidStar yPushHeaders,
  z_ctypes_4_VoidStar yPushBody )
#else
extern z_WAE_WSP_12_SPushIndType  yMake_z_WAE_WSP_12_SPushIndType( ySourcePort,
  yHeadersLen, yBodyLen, yPushHeaders, yPushBody )
  SDL_Integer ySourcePort;
  SDL_Integer yHeadersLen;
  SDL_Integer yBodyLen;
  z_ctypes_4_VoidStar yPushHeaders;
  z_ctypes_4_VoidStar yPushBody;
#endif
{
  z_WAE_WSP_12_SPushIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_12_SPushIndType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyLen, yBodyLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.PushHeaders, yPushHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.PushBody, yPushBody, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SConfirmedPushIndType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),167(20,40),9)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_13_SConfirmedPushIndType(
   z_WAE_WSP_13_SConfirmedPushIndType *yVar )
#else
extern void yDef_z_WAE_WSP_13_SConfirmedPushIndType( yVar )
  z_WAE_WSP_13_SConfirmedPushIndType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).ClientPushId));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  xDef_SDL_Integer(&((*yVar).BodyLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).PushHeaders));
  yDef_z_ctypes_4_VoidStar(&((*yVar).PushBody));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_13_SConfirmedPushIndType(
  z_WAE_WSP_13_SConfirmedPushIndType yExpr1,
  z_WAE_WSP_13_SConfirmedPushIndType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_13_SConfirmedPushIndType( yExpr1, yExpr2 )
  z_WAE_WSP_13_SConfirmedPushIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.ClientPushId, yExpr2.ClientPushId) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyLen, yExpr2.BodyLen) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.PushHeaders, yExpr2.PushHeaders) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.PushBody, yExpr2.PushBody) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_13_SConfirmedPushIndType yMake_z_WAE_WSP_13_SConfirmedPushIndType(
  SDL_Integer ySourcePort,
  SDL_Integer yClientPushId,
  SDL_Integer yHeadersLen,
  SDL_Integer yBodyLen,
  z_ctypes_4_VoidStar yPushHeaders,
  z_ctypes_4_VoidStar yPushBody )
#else
extern z_WAE_WSP_13_SConfirmedPushIndType  yMake_z_WAE_WSP_13_SConfirmedPushIndType
  ( ySourcePort, yClientPushId, yHeadersLen, yBodyLen, yPushHeaders, yPushBody )
  SDL_Integer ySourcePort;
  SDL_Integer yClientPushId;
  SDL_Integer yHeadersLen;
  SDL_Integer yBodyLen;
  z_ctypes_4_VoidStar yPushHeaders;
  z_ctypes_4_VoidStar yPushBody;
#endif
{
  z_WAE_WSP_13_SConfirmedPushIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_13_SConfirmedPushIndType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.ClientPushId, yClientPushId, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyLen, yBodyLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.PushHeaders, yPushHeaders, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.PushBody, yPushBody, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SConfirmedPushResType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),167(20,40),18)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_14_SConfirmedPushResType(
   z_WAE_WSP_14_SConfirmedPushResType *yVar )
#else
extern void yDef_z_WAE_WSP_14_SConfirmedPushResType( yVar )
  z_WAE_WSP_14_SConfirmedPushResType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).ClientPushId));
  yDef_z_ctypes_4_VoidStar(&((*yVar).AcknowledgementHeaders));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_14_SConfirmedPushResType(
  z_WAE_WSP_14_SConfirmedPushResType yExpr1,
  z_WAE_WSP_14_SConfirmedPushResType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_14_SConfirmedPushResType( yExpr1, yExpr2 )
  z_WAE_WSP_14_SConfirmedPushResType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.ClientPushId, yExpr2.ClientPushId) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.AcknowledgementHeaders,
  yExpr2.AcknowledgementHeaders) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_14_SConfirmedPushResType yMake_z_WAE_WSP_14_SConfirmedPushResType(
  SDL_Integer ySourcePort,
  SDL_Integer yClientPushId,
  z_ctypes_4_VoidStar yAcknowledgementHeaders )
#else
extern z_WAE_WSP_14_SConfirmedPushResType  yMake_z_WAE_WSP_14_SConfirmedPushResType
  ( ySourcePort, yClientPushId, yAcknowledgementHeaders )
  SDL_Integer ySourcePort;
  SDL_Integer yClientPushId;
  z_ctypes_4_VoidStar yAcknowledgementHeaders;
#endif
{
  z_WAE_WSP_14_SConfirmedPushResType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_14_SConfirmedPushResType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.ClientPushId, yClientPushId, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.AcknowledgementHeaders,
    yAcknowledgementHeaders, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SPushAbortReqType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),167(20,40),28)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_15_SPushAbortReqType(
   z_WAE_WSP_15_SPushAbortReqType *yVar )
#else
extern void yDef_z_WAE_WSP_15_SPushAbortReqType( yVar )
  z_WAE_WSP_15_SPushAbortReqType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).ClientPushId));
  xDef_SDL_Natural(&((*yVar).Reason));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_15_SPushAbortReqType(
  z_WAE_WSP_15_SPushAbortReqType yExpr1,
  z_WAE_WSP_15_SPushAbortReqType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_15_SPushAbortReqType( yExpr1, yExpr2 )
  z_WAE_WSP_15_SPushAbortReqType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.ClientPushId, yExpr2.ClientPushId) )
  return SDL_False;
  if ( yNEqF_SDL_Natural(yExpr1.Reason, yExpr2.Reason) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_15_SPushAbortReqType yMake_z_WAE_WSP_15_SPushAbortReqType(
  SDL_Integer ySourcePort,
  SDL_Integer yClientPushId,
  SDL_Natural yReason )
#else
extern z_WAE_WSP_15_SPushAbortReqType  yMake_z_WAE_WSP_15_SPushAbortReqType
  ( ySourcePort, yClientPushId, yReason )
  SDL_Integer ySourcePort;
  SDL_Integer yClientPushId;
  SDL_Natural yReason;
#endif
{
  z_WAE_WSP_15_SPushAbortReqType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_15_SPushAbortReqType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.ClientPushId, yClientPushId, XASSMAKE);
  yAssF_SDL_Natural(yVar.Reason, yReason, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SPushAbortIndType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),167(20,40),34)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_16_SPushAbortIndType(
   z_WAE_WSP_16_SPushAbortIndType *yVar )
#else
extern void yDef_z_WAE_WSP_16_SPushAbortIndType( yVar )
  z_WAE_WSP_16_SPushAbortIndType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Integer(&((*yVar).ClientPushId));
  xDef_SDL_Natural(&((*yVar).Reason));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_16_SPushAbortIndType(
  z_WAE_WSP_16_SPushAbortIndType yExpr1,
  z_WAE_WSP_16_SPushAbortIndType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_16_SPushAbortIndType( yExpr1, yExpr2 )
  z_WAE_WSP_16_SPushAbortIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.ClientPushId, yExpr2.ClientPushId) )
  return SDL_False;
  if ( yNEqF_SDL_Natural(yExpr1.Reason, yExpr2.Reason) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_16_SPushAbortIndType yMake_z_WAE_WSP_16_SPushAbortIndType(
  SDL_Integer ySourcePort,
  SDL_Integer yClientPushId,
  SDL_Natural yReason )
#else
extern z_WAE_WSP_16_SPushAbortIndType  yMake_z_WAE_WSP_16_SPushAbortIndType
  ( ySourcePort, yClientPushId, yReason )
  SDL_Integer ySourcePort;
  SDL_Integer yClientPushId;
  SDL_Natural yReason;
#endif
{
  z_WAE_WSP_16_SPushAbortIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_16_SPushAbortIndType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Integer(yVar.ClientPushId, yClientPushId, XASSMAKE);
  yAssF_SDL_Natural(yVar.Reason, yReason, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SSuspendReqType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),164(100,40),1)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_17_SSuspendReqType(
   z_WAE_WSP_17_SSuspendReqType *yVar )
#else
extern void yDef_z_WAE_WSP_17_SSuspendReqType( yVar )
  z_WAE_WSP_17_SSuspendReqType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_17_SSuspendReqType(
  z_WAE_WSP_17_SSuspendReqType yExpr1,
  z_WAE_WSP_17_SSuspendReqType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_17_SSuspendReqType( yExpr1, yExpr2 )
  z_WAE_WSP_17_SSuspendReqType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_17_SSuspendReqType yMake_z_WAE_WSP_17_SSuspendReqType(
  SDL_Integer ySourcePort )
#else
extern z_WAE_WSP_17_SSuspendReqType  yMake_z_WAE_WSP_17_SSuspendReqType
  ( ySourcePort )
  SDL_Integer ySourcePort;
#endif
{
  z_WAE_WSP_17_SSuspendReqType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_17_SSuspendReqType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SSuspendIndType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),164(100,40),5)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_18_SSuspendIndType(
   z_WAE_WSP_18_SSuspendIndType *yVar )
#else
extern void yDef_z_WAE_WSP_18_SSuspendIndType( yVar )
  z_WAE_WSP_18_SSuspendIndType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
  xDef_SDL_Natural(&((*yVar).Reason));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_18_SSuspendIndType(
  z_WAE_WSP_18_SSuspendIndType yExpr1,
  z_WAE_WSP_18_SSuspendIndType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_18_SSuspendIndType( yExpr1, yExpr2 )
  z_WAE_WSP_18_SSuspendIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  if ( yNEqF_SDL_Natural(yExpr1.Reason, yExpr2.Reason) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_18_SSuspendIndType yMake_z_WAE_WSP_18_SSuspendIndType(
  SDL_Integer ySourcePort,
  SDL_Natural yReason )
#else
extern z_WAE_WSP_18_SSuspendIndType  yMake_z_WAE_WSP_18_SSuspendIndType
  ( ySourcePort, yReason )
  SDL_Integer ySourcePort;
  SDL_Natural yReason;
#endif
{
  z_WAE_WSP_18_SSuspendIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_18_SSuspendIndType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  yAssF_SDL_Natural(yVar.Reason, yReason, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SResumeCnfType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),164(100,40),10)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_19_SResumeCnfType(
   z_WAE_WSP_19_SResumeCnfType *yVar )
#else
extern void yDef_z_WAE_WSP_19_SResumeCnfType( yVar )
  z_WAE_WSP_19_SResumeCnfType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).SourcePort));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_19_SResumeCnfType(
  z_WAE_WSP_19_SResumeCnfType yExpr1,
  z_WAE_WSP_19_SResumeCnfType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_19_SResumeCnfType( yExpr1, yExpr2 )
  z_WAE_WSP_19_SResumeCnfType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.SourcePort, yExpr2.SourcePort) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_19_SResumeCnfType yMake_z_WAE_WSP_19_SResumeCnfType(
  SDL_Integer ySourcePort )
#else
extern z_WAE_WSP_19_SResumeCnfType  yMake_z_WAE_WSP_19_SResumeCnfType
  ( ySourcePort )
  SDL_Integer ySourcePort;
#endif
{
  z_WAE_WSP_19_SResumeCnfType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_19_SResumeCnfType));
  yAssF_SDL_Integer(yVar.SourcePort, ySourcePort, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SResumeReqType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),164(100,40),14)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_SResumeReqType( SResumeReqType *yVar )
#else
extern void yDef_SResumeReqType( yVar )
  SResumeReqType *yVar;
#endif
{
  yDef_AddressType(&((*yVar).ServerAddress));
  yDef_AddressType(&((*yVar).ClientAddress));
  xDef_SDL_Integer(&((*yVar).HeadersLen));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ClientHeaders));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_SResumeReqType(
  SResumeReqType yExpr1,
  SResumeReqType yExpr2 )
#else
extern SDL_Boolean yEq_SResumeReqType( yExpr1, yExpr2 )
  SResumeReqType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_AddressType(yExpr1.ServerAddress, yExpr2.ServerAddress) )
  return SDL_False;
  if ( yNEqF_AddressType(yExpr1.ClientAddress, yExpr2.ClientAddress) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.HeadersLen, yExpr2.HeadersLen) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ClientHeaders, yExpr2.ClientHeaders) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern SResumeReqType yMake_SResumeReqType(
  AddressType yServerAddress,
  AddressType yClientAddress,
  SDL_Integer yHeadersLen,
  z_ctypes_4_VoidStar yClientHeaders )
#else
extern SResumeReqType  yMake_SResumeReqType( yServerAddress, yClientAddress,
  yHeadersLen, yClientHeaders )
  AddressType yServerAddress;
  AddressType yClientAddress;
  SDL_Integer yHeadersLen;
  z_ctypes_4_VoidStar yClientHeaders;
#endif
{
  SResumeReqType  yVar;
  memset((void *)(&yVar), 0, sizeof(SResumeReqType));
  yAssF_AddressType(yVar.ServerAddress, yServerAddress, XASSMAKE);
  yAssF_AddressType(yVar.ClientAddress, yClientAddress, XASSMAKE);
  yAssF_SDL_Integer(yVar.HeadersLen, yHeadersLen, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ClientHeaders, yClientHeaders, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SExceptionIndType  (BODY section)
* <<PACKAGE WAE_WSP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\CNF_CO_CL__WAE_WSP.sun(ConnectionMode3),170(100,115),1)
******/

/*------------------ASSIGN------------------*/
#ifndef XNOPROTO
extern void yAss_z_WAE_WSP_1B_SExceptionIndType(
  z_WAE_WSP_1B_SExceptionIndType *yVar,
  z_WAE_WSP_1B_SExceptionIndType  yExpr,
  int AssType )
#else
extern void yAss_z_WAE_WSP_1B_SExceptionIndType( yVar, yExpr, AssType )
  z_WAE_WSP_1B_SExceptionIndType *yVar;
  z_WAE_WSP_1B_SExceptionIndType  yExpr;
  int AssType;
#endif
{
  yAssF_SDL_Octet_String((*yVar).ExceptionData, yExpr.ExceptionData, AssType);
}

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAE_WSP_1B_SExceptionIndType(
   z_WAE_WSP_1B_SExceptionIndType *yVar )
#else
extern void yDef_z_WAE_WSP_1B_SExceptionIndType( yVar )
  z_WAE_WSP_1B_SExceptionIndType *yVar;
#endif
{
  xDef_SDL_Octet_String(&((*yVar).ExceptionData));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAE_WSP_1B_SExceptionIndType(
  z_WAE_WSP_1B_SExceptionIndType yExpr1,
  z_WAE_WSP_1B_SExceptionIndType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAE_WSP_1B_SExceptionIndType( yExpr1, yExpr2 )
  z_WAE_WSP_1B_SExceptionIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Octet_String(yExpr1.ExceptionData, yExpr2.ExceptionData) )
  return SDL_False;
  return SDL_True;
}

/*-------------------FREE-------------------*/
#ifndef XNOPROTO
extern void yFree_z_WAE_WSP_1B_SExceptionIndType( void **yVar )
#else
extern void yFree_z_WAE_WSP_1B_SExceptionIndType( yVar )
  void **yVar;
#endif
{
  xFree_SDL_Bit_String
  ((void **)&(*(z_WAE_WSP_1B_SExceptionIndType *)yVar).ExceptionData);
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAE_WSP_1B_SExceptionIndType yMake_z_WAE_WSP_1B_SExceptionIndType(
  SDL_Octet_String yExceptionData )
#else
extern z_WAE_WSP_1B_SExceptionIndType  yMake_z_WAE_WSP_1B_SExceptionIndType
  ( yExceptionData )
  SDL_Octet_String yExceptionData;
#endif
{
  z_WAE_WSP_1B_SExceptionIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAE_WSP_1B_SExceptionIndType));
  yAssF_SDL_Octet_String(yVar.ExceptionData, yExceptionData, XASSMAKE);
  return yVar;
}
