/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#define C_MICRO_1_3
#include "ml_typ.h"
#include "ctypes.h"
#include "WAEPckg.h"


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* SYNONYM Get
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),287(30,55),13)
******/
SDL_Octet  z_WAEPackage_2X_Get;

/*****
* SYNONYM Post
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),287(30,55),14)
******/
SDL_Octet  z_WAEPackage_2Y_Post;

/*****
* SYNONYM anything
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),3)
******/
SDL_Octet  z_WAEPackage_2Z_anything;

/*****
* SYNONYM text
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),4)
******/
SDL_Octet  z_WAEPackage_30_text;

/*****
* SYNONYM text_html
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),5)
******/
SDL_Octet  z_WAEPackage_31_text_html;

/*****
* SYNONYM text_plain
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),6)
******/
SDL_Octet  z_WAEPackage_32_text_plain;

/*****
* SYNONYM text_x_hdml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),7)
******/
SDL_Octet  z_WAEPackage_33_text_x_hdml;

/*****
* SYNONYM text_x_ttml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),8)
******/
SDL_Octet  z_WAEPackage_34_text_x_ttml;

/*****
* SYNONYM text_x_vCalendar
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),9)
******/
SDL_Octet  z_WAEPackage_35_text_x_vCalendar;

/*****
* SYNONYM text_x_vCard
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),10)
******/
SDL_Octet  z_WAEPackage_36_text_x_vCard;

/*****
* SYNONYM text_x_wap.wml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),11)
******/
SDL_Octet  z_WAEPackage_37_text_x_wapwml;

/*****
* SYNONYM text_x_wap.wmlscript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),12)
******/
SDL_Octet  z_WAEPackage_38_text_x_wapwmlscript;

/*****
* SYNONYM text_x_wap.wta_event
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),13)
******/
SDL_Octet  z_WAEPackage_39_text_x_wapwta_event;

/*****
* SYNONYM multipart
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),14)
******/
SDL_Octet  z_WAEPackage_3A_multipart;

/*****
* SYNONYM multipart_mixed
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),15)
******/
SDL_Octet  z_WAEPackage_3B_multipart_mixed;

/*****
* SYNONYM multipart_form_data
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),16)
******/
SDL_Octet  z_WAEPackage_3C_multipart_form_data;

/*****
* SYNONYM multipart_byteranges
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),17)
******/
SDL_Octet  z_WAEPackage_3D_multipart_byteranges;

/*****
* SYNONYM multipart_alternative
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),18)
******/
SDL_Octet  z_WAEPackage_3E_multipart_alternative;

/*****
* SYNONYM application
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),19)
******/
SDL_Octet  z_WAEPackage_3F_application;

/*****
* SYNONYM application_java_vm
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),20)
******/
SDL_Octet  z_WAEPackage_3G_application_java_vm;

/*****
* SYNONYM application_x_www_form_urlencoded
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),21)
******/
SDL_Octet  z_WAEPackage_3H_application_x_www_form_urlencoded;

/*****
* SYNONYM application_x_hdmlc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),22)
******/
SDL_Octet  z_WAEPackage_3I_application_x_hdmlc;

/*****
* SYNONYM application_vnd_wap.wmlc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),23)
******/
SDL_Octet  z_WAEPackage_3J_application_vnd_wapwmlc;

/*****
* SYNONYM application_vnd_wap.wbxml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),24)
******/
SDL_Octet  z_WAEPackage_3K_application_vnd_wapwbxml;

/*****
* SYNONYM application_vnd_wap.wmlscriptc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),25)
******/
SDL_Octet  z_WAEPackage_3L_application_vnd_wapwmlscriptc;

/*****
* SYNONYM application_x_wap.wta_eventc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),26)
******/
SDL_Octet  z_WAEPackage_3M_application_x_wapwta_eventc;

/*****
* SYNONYM application_x_wap.uaprof
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),27)
******/
SDL_Octet  z_WAEPackage_3N_application_x_wapuaprof;

/*****
* SYNONYM application_x_wap.wtls_ca_certificate
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),28)
******/
SDL_Octet  z_WAEPackage_3O_application_x_wapwtls_ca_certificate;

/*****
* SYNONYM application_x_wap.wtls_user_certificate
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),29)
******/
SDL_Octet  z_WAEPackage_3P_application_x_wapwtls_user_certificate;

/*****
* SYNONYM application_x_x509_ca_cert
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),30)
******/
SDL_Octet  z_WAEPackage_3Q_application_x_x509_ca_cert;

/*****
* SYNONYM application_x_x509_user_cert
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),31)
******/
SDL_Octet  z_WAEPackage_3R_application_x_x509_user_cert;

/*****
* SYNONYM image
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),32)
******/
SDL_Octet  z_WAEPackage_3S_image;

/*****
* SYNONYM image_gif
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),33)
******/
SDL_Octet  z_WAEPackage_3T_image_gif;

/*****
* SYNONYM image_jpeg
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),34)
******/
SDL_Octet  z_WAEPackage_3U_image_jpeg;

/*****
* SYNONYM image_tiff
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),35)
******/
SDL_Octet  z_WAEPackage_3V_image_tiff;

/*****
* SYNONYM image_png
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),36)
******/
SDL_Octet  z_WAEPackage_3W_image_png;

/*****
* SYNONYM image_x_wap.wbmp
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),37)
******/
SDL_Octet  z_WAEPackage_3X_image_x_wapwbmp;

/*****
* SYNONYM x_wap.multipart
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),38)
******/
SDL_Octet  z_WAEPackage_3Y_x_wapmultipart;

/*****
* SYNONYM x_wap.multipart_mixed
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),39)
******/
SDL_Octet  z_WAEPackage_3Z_x_wapmultipart_mixed;

/*****
* SYNONYM x_wap.multipart_form_data
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),40)
******/
SDL_Octet  z_WAEPackage_40_x_wapmultipart_form_data;

/*****
* SYNONYM x_wap.multipart_byteranges
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),41)
******/
SDL_Octet  z_WAEPackage_41_x_wapmultipart_byteranges;

/*****
* SYNONYM x_wap.multipart_alternative
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),42)
******/
SDL_Octet  z_WAEPackage_42_x_wapmultipart_alternative;

/*****
* SYNONYM application_vnd_wap.channelc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),43)
******/
SDL_Octet  z_WAEPackage_43_application_vnd_wapchannelc;

/*****
* SYNONYM hex128
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),284(85,55),1)
******/
SDL_Octet  z_WAEPackage_44_hex128;

/*****
* SYNONYM Continued
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),3)
******/
SDL_Octet  z_WAEPackage_45_Continued;

/*****
* SYNONYM SwitchingProtocols
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),4)
******/
SDL_Octet  z_WAEPackage_46_SwitchingProtocols;

/*****
* SYNONYM RequestOK
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),6)
******/
SDL_Octet  z_WAEPackage_47_RequestOK;

/*****
* SYNONYM Created
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),9)
******/
SDL_Octet  z_WAEPackage_48_Created;

/*****
* SYNONYM Accepted
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),10)
******/
SDL_Octet  z_WAEPackage_49_Accepted;

/*****
* SYNONYM NonAuthoritativeInformation
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),11)
******/
SDL_Octet  z_WAEPackage_4A_NonAuthoritativeInformation;

/*****
* SYNONYM NoContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),12)
******/
SDL_Octet  z_WAEPackage_4B_NoContent;

/*****
* SYNONYM ResetContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),13)
******/
SDL_Octet  z_WAEPackage_4C_ResetContent;

/*****
* SYNONYM PartialContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),14)
******/
SDL_Octet  z_WAEPackage_4D_PartialContent;

/*****
* SYNONYM MultipleChoices
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),15)
******/
SDL_Octet  z_WAEPackage_4E_MultipleChoices;

/*****
* SYNONYM MovedPermanently
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),16)
******/
SDL_Octet  z_WAEPackage_4F_MovedPermanently;

/*****
* SYNONYM MovedTemporarily
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),17)
******/
SDL_Octet  z_WAEPackage_4G_MovedTemporarily;

/*****
* SYNONYM SeeOther
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),19)
******/
SDL_Octet  z_WAEPackage_4H_SeeOther;

/*****
* SYNONYM NotModified
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),20)
******/
SDL_Octet  z_WAEPackage_4I_NotModified;

/*****
* SYNONYM UseProxy
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),21)
******/
SDL_Octet  z_WAEPackage_4J_UseProxy;

/*****
* SYNONYM BadRequest
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),23)
******/
SDL_Octet  z_WAEPackage_4K_BadRequest;

/*****
* SYNONYM Unauthorized
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),24)
******/
SDL_Octet  z_WAEPackage_4L_Unauthorized;

/*****
* SYNONYM PaymentRequired
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),25)
******/
SDL_Octet  z_WAEPackage_4M_PaymentRequired;

/*****
* SYNONYM Forbidden
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),26)
******/
SDL_Octet  z_WAEPackage_4N_Forbidden;

/*****
* SYNONYM NotFound
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),27)
******/
SDL_Octet  z_WAEPackage_4O_NotFound;

/*****
* SYNONYM MethodNotAllowed
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),28)
******/
SDL_Octet  z_WAEPackage_4P_MethodNotAllowed;

/*****
* SYNONYM NotAcceptable
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),29)
******/
SDL_Octet  z_WAEPackage_4Q_NotAcceptable;

/*****
* SYNONYM ProxyAuthenticationRequired
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),30)
******/
SDL_Octet  z_WAEPackage_4R_ProxyAuthenticationRequired;

/*****
* SYNONYM RequestTimeout
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),31)
******/
SDL_Octet  z_WAEPackage_4S_RequestTimeout;

/*****
* SYNONYM Conflict
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),32)
******/
SDL_Octet  z_WAEPackage_4T_Conflict;

/*****
* SYNONYM Gone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),33)
******/
SDL_Octet  z_WAEPackage_4U_Gone;

/*****
* SYNONYM LengthRequired
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),34)
******/
SDL_Octet  z_WAEPackage_4V_LengthRequired;

/*****
* SYNONYM PreconditionFailed
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),35)
******/
SDL_Octet  z_WAEPackage_4W_PreconditionFailed;

/*****
* SYNONYM RequestedEntityTooLarge
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),36)
******/
SDL_Octet  z_WAEPackage_4X_RequestedEntityTooLarge;

/*****
* SYNONYM RequestURITooLarge
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),37)
******/
SDL_Octet  z_WAEPackage_4Y_RequestURITooLarge;

/*****
* SYNONYM UnsupportedMediaType
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),38)
******/
SDL_Octet  z_WAEPackage_4Z_UnsupportedMediaType;

/*****
* SYNONYM InternalServerError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),40)
******/
SDL_Octet  z_WAEPackage_50_InternalServerError;

/*****
* SYNONYM NotImplemented
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),41)
******/
SDL_Octet  z_WAEPackage_51_NotImplemented;

/*****
* SYNONYM BadGateway
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),42)
******/
SDL_Octet  z_WAEPackage_52_BadGateway;

/*****
* SYNONYM ServiceUnavailable
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),43)
******/
SDL_Octet  z_WAEPackage_53_ServiceUnavailable;

/*****
* SYNONYM GatewayTimeout
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),44)
******/
SDL_Octet  z_WAEPackage_54_GatewayTimeout;

/*****
* SYNONYM HTTPverNotSupported
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),45)
******/
SDL_Octet  z_WAEPackage_55_HTTPverNotSupported;

/*****
* SYNONYM SendOK
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),1)
******/
SDL_Octet  z_WAEPackage_57_SendOK;

/*****
* SYNONYM NoTIDAvailable
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),2)
******/
SDL_Octet  z_WAEPackage_58_NoTIDAvailable;

/*****
* SYNONYM NonSupportedScheme
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),3)
******/
SDL_Octet  z_WAEPackage_59_NonSupportedScheme;

/*****
* SYNONYM PublicWTAIAction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),4)
******/
SDL_Octet  z_WAEPackage_5A_PublicWTAIAction;

/*****
* SYNONYM AboutScheme
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),5)
******/
SDL_Octet  z_WAEPackage_5B_AboutScheme;

/*****
* NEWTYPE RequestType  (BODY section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),530(20,40),1)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAEPackage_2U_RequestType(
   z_WAEPackage_2U_RequestType *yVar )
#else
extern void yDef_z_WAEPackage_2U_RequestType( yVar )
  z_WAEPackage_2U_RequestType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).UA_Type));
  xDef_SDL_Integer(&((*yVar).Scheme));
  xDef_SDL_Integer(&((*yVar).SID));
  xDef_SDL_Integer(&((*yVar).TID));
  yDef_z_ctypes_4_VoidStar(&((*yVar).RequestStruct));
  xDef_SDL_Integer(&((*yVar).Reload));
  xDef_SDL_Integer(&((*yVar).Prio));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAEPackage_2U_RequestType(
  z_WAEPackage_2U_RequestType yExpr1,
  z_WAEPackage_2U_RequestType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAEPackage_2U_RequestType( yExpr1, yExpr2 )
  z_WAEPackage_2U_RequestType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.UA_Type, yExpr2.UA_Type) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.Scheme, yExpr2.Scheme) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.SID, yExpr2.SID) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.TID, yExpr2.TID) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.RequestStruct, yExpr2.RequestStruct) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.Reload, yExpr2.Reload) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.Prio, yExpr2.Prio) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAEPackage_2U_RequestType yMake_z_WAEPackage_2U_RequestType(
  SDL_Integer yUA_Type,
  SDL_Integer yScheme,
  SDL_Integer ySID,
  SDL_Integer yTID,
  z_ctypes_4_VoidStar yRequestStruct,
  SDL_Integer yReload,
  SDL_Integer yPrio )
#else
extern z_WAEPackage_2U_RequestType  yMake_z_WAEPackage_2U_RequestType
  ( yUA_Type, yScheme, ySID, yTID, yRequestStruct, yReload, yPrio )
  SDL_Integer yUA_Type;
  SDL_Integer yScheme;
  SDL_Integer ySID;
  SDL_Integer yTID;
  z_ctypes_4_VoidStar yRequestStruct;
  SDL_Integer yReload;
  SDL_Integer yPrio;
#endif
{
  z_WAEPackage_2U_RequestType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAEPackage_2U_RequestType));
  yAssF_SDL_Integer(yVar.UA_Type, yUA_Type, XASSMAKE);
  yAssF_SDL_Integer(yVar.Scheme, yScheme, XASSMAKE);
  yAssF_SDL_Integer(yVar.SID, ySID, XASSMAKE);
  yAssF_SDL_Integer(yVar.TID, yTID, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.RequestStruct, yRequestStruct, XASSMAKE);
  yAssF_SDL_Integer(yVar.Reload, yReload, XASSMAKE);
  yAssF_SDL_Integer(yVar.Prio, yPrio, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE ResponseType  (BODY section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),530(20,40),11)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAEPackage_2V_ResponseType(
   z_WAEPackage_2V_ResponseType *yVar )
#else
extern void yDef_z_WAEPackage_2V_ResponseType( yVar )
  z_WAEPackage_2V_ResponseType *yVar;
#endif
{
  xDef_SDL_Integer(&((*yVar).Scheme));
  xDef_SDL_Integer(&((*yVar).SID));
  xDef_SDL_Integer(&((*yVar).TID));
  yDef_z_ctypes_4_VoidStar(&((*yVar).HeaderHandle));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ContentType));
  yDef_z_ctypes_4_VoidStar(&((*yVar).BodyData));
  xDef_SDL_Integer(&((*yVar).BodyDataLength));
  xDef_SDL_Octet(&((*yVar).Status));
  yDef_z_ctypes_4_VoidStar(&((*yVar).ExtParameters));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAEPackage_2V_ResponseType(
  z_WAEPackage_2V_ResponseType yExpr1,
  z_WAEPackage_2V_ResponseType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAEPackage_2V_ResponseType( yExpr1, yExpr2 )
  z_WAEPackage_2V_ResponseType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_SDL_Integer(yExpr1.Scheme, yExpr2.Scheme) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.SID, yExpr2.SID) ) return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.TID, yExpr2.TID) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.HeaderHandle, yExpr2.HeaderHandle) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ContentType, yExpr2.ContentType) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.BodyData, yExpr2.BodyData) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.BodyDataLength, yExpr2.BodyDataLength) )
  return SDL_False;
  if ( yNEqF_SDL_Octet(yExpr1.Status, yExpr2.Status) ) return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.ExtParameters, yExpr2.ExtParameters) )
  return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAEPackage_2V_ResponseType yMake_z_WAEPackage_2V_ResponseType(
  SDL_Integer yScheme,
  SDL_Integer ySID,
  SDL_Integer yTID,
  z_ctypes_4_VoidStar yHeaderHandle,
  z_ctypes_4_VoidStar yContentType,
  z_ctypes_4_VoidStar yBodyData,
  SDL_Integer yBodyDataLength,
  SDL_Octet yStatus,
  z_ctypes_4_VoidStar yExtParameters )
#else
extern z_WAEPackage_2V_ResponseType  yMake_z_WAEPackage_2V_ResponseType
  ( yScheme, ySID, yTID, yHeaderHandle, yContentType, yBodyData,
  yBodyDataLength, yStatus, yExtParameters )
  SDL_Integer yScheme;
  SDL_Integer ySID;
  SDL_Integer yTID;
  z_ctypes_4_VoidStar yHeaderHandle;
  z_ctypes_4_VoidStar yContentType;
  z_ctypes_4_VoidStar yBodyData;
  SDL_Integer yBodyDataLength;
  SDL_Octet yStatus;
  z_ctypes_4_VoidStar yExtParameters;
#endif
{
  z_WAEPackage_2V_ResponseType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAEPackage_2V_ResponseType));
  yAssF_SDL_Integer(yVar.Scheme, yScheme, XASSMAKE);
  yAssF_SDL_Integer(yVar.SID, ySID, XASSMAKE);
  yAssF_SDL_Integer(yVar.TID, yTID, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.HeaderHandle, yHeaderHandle, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ContentType, yContentType, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.BodyData, yBodyData, XASSMAKE);
  yAssF_SDL_Integer(yVar.BodyDataLength, yBodyDataLength, XASSMAKE);
  yAssF_SDL_Octet(yVar.Status, yStatus, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.ExtParameters, yExtParameters, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE SessionType  (BODY section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),530(20,40),23)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_z_WAEPackage_2W_SessionType(
   z_WAEPackage_2W_SessionType *yVar )
#else
extern void yDef_z_WAEPackage_2W_SessionType( yVar )
  z_WAEPackage_2W_SessionType *yVar;
#endif
{
  yDef_z_ctypes_4_VoidStar(&((*yVar).Network));
  yDef_z_ctypes_4_VoidStar(&((*yVar).UaSettings));
  xDef_SDL_Integer(&((*yVar).ViewID));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_z_WAEPackage_2W_SessionType(
  z_WAEPackage_2W_SessionType yExpr1,
  z_WAEPackage_2W_SessionType yExpr2 )
#else
extern SDL_Boolean yEq_z_WAEPackage_2W_SessionType( yExpr1, yExpr2 )
  z_WAEPackage_2W_SessionType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.Network, yExpr2.Network) )
  return SDL_False;
  if ( yNEqF_z_ctypes_4_VoidStar(yExpr1.UaSettings, yExpr2.UaSettings) )
  return SDL_False;
  if ( yNEqF_SDL_Integer(yExpr1.ViewID, yExpr2.ViewID) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern z_WAEPackage_2W_SessionType yMake_z_WAEPackage_2W_SessionType(
  z_ctypes_4_VoidStar yNetwork,
  z_ctypes_4_VoidStar yUaSettings,
  SDL_Integer yViewID )
#else
extern z_WAEPackage_2W_SessionType  yMake_z_WAEPackage_2W_SessionType
  ( yNetwork, yUaSettings, yViewID )
  z_ctypes_4_VoidStar yNetwork;
  z_ctypes_4_VoidStar yUaSettings;
  SDL_Integer yViewID;
#endif
{
  z_WAEPackage_2W_SessionType  yVar;
  memset((void *)(&yVar), 0, sizeof(z_WAEPackage_2W_SessionType));
  yAssF_z_ctypes_4_VoidStar(yVar.Network, yNetwork, XASSMAKE);
  yAssF_z_ctypes_4_VoidStar(yVar.UaSettings, yUaSettings, XASSMAKE);
  yAssF_SDL_Integer(yVar.ViewID, yViewID, XASSMAKE);
  return yVar;
}

extern void yInit_WAEPackage XPP((void))
{
  static int IsCalled = 0;
  if (IsCalled) return;
  IsCalled = 1;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),287(30,55),13) */
  yAssF_SDL_Octet(z_WAEPackage_2X_Get, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L40", "40")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),287(30,55),14) */
  yAssF_SDL_Octet(z_WAEPackage_2Y_Post, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L60", "60")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),3) */
  yAssF_SDL_Octet(z_WAEPackage_2Z_anything, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L00", "00")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),4) */
  yAssF_SDL_Octet(z_WAEPackage_30_text, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L01", "01")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),5) */
  yAssF_SDL_Octet(z_WAEPackage_31_text_html, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L02", "02")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),6) */
  yAssF_SDL_Octet(z_WAEPackage_32_text_plain, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L03", "03")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),7) */
  yAssF_SDL_Octet(z_WAEPackage_33_text_x_hdml, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L04", "04")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),8) */
  yAssF_SDL_Octet(z_WAEPackage_34_text_x_ttml, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L05", "05")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),9) */
  yAssF_SDL_Octet(z_WAEPackage_35_text_x_vCalendar, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L06", "06")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),10) */
  yAssF_SDL_Octet(z_WAEPackage_36_text_x_vCard, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L07", "07")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),11) */
  yAssF_SDL_Octet(z_WAEPackage_37_text_x_wapwml, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L08", "08")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),12) */
  yAssF_SDL_Octet(z_WAEPackage_38_text_x_wapwmlscript, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L09", "09")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),13) */
  yAssF_SDL_Octet(z_WAEPackage_39_text_x_wapwta_event, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L0A", "0A")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),14) */
  yAssF_SDL_Octet(z_WAEPackage_3A_multipart, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L0B", "0B")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),15) */
  yAssF_SDL_Octet(z_WAEPackage_3B_multipart_mixed, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L0C", "0C")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),16) */
  yAssF_SDL_Octet(z_WAEPackage_3C_multipart_form_data, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L0D", "0D")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),17) */
  yAssF_SDL_Octet(z_WAEPackage_3D_multipart_byteranges, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L0E", "0E")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),18) */
  yAssF_SDL_Octet(z_WAEPackage_3E_multipart_alternative, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L0F", "0F")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),19) */
  yAssF_SDL_Octet(z_WAEPackage_3F_application, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L10", "10")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),20) */
  yAssF_SDL_Octet(z_WAEPackage_3G_application_java_vm, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L11", "11")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),21) */
  yAssF_SDL_Octet(z_WAEPackage_3H_application_x_www_form_urlencoded,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L12", "12")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),22) */
  yAssF_SDL_Octet(z_WAEPackage_3I_application_x_hdmlc, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L13", "13")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),23) */
  yAssF_SDL_Octet(z_WAEPackage_3J_application_vnd_wapwmlc, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L14", "14")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),24) */
  yAssF_SDL_Octet(z_WAEPackage_3K_application_vnd_wapwbxml, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L14", "14")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),25) */
  yAssF_SDL_Octet(z_WAEPackage_3L_application_vnd_wapwmlscriptc,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L15", "15")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),26) */
  yAssF_SDL_Octet(z_WAEPackage_3M_application_x_wapwta_eventc,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L16", "16")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),27) */
  yAssF_SDL_Octet(z_WAEPackage_3N_application_x_wapuaprof, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L17", "17")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),28) */
  yAssF_SDL_Octet(z_WAEPackage_3O_application_x_wapwtls_ca_certificate,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L18", "18")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),29) */
  yAssF_SDL_Octet(z_WAEPackage_3P_application_x_wapwtls_user_certificate,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L19", "19")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),30) */
  yAssF_SDL_Octet(z_WAEPackage_3Q_application_x_x509_ca_cert, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L1A", "1A")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),31) */
  yAssF_SDL_Octet(z_WAEPackage_3R_application_x_x509_user_cert,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L1B", "1B")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),32) */
  yAssF_SDL_Octet(z_WAEPackage_3S_image, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L1C", "1C")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),33) */
  yAssF_SDL_Octet(z_WAEPackage_3T_image_gif, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L1D", "1D")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),34) */
  yAssF_SDL_Octet(z_WAEPackage_3U_image_jpeg, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L1E", "1E")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),35) */
  yAssF_SDL_Octet(z_WAEPackage_3V_image_tiff, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L1F", "1F")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),36) */
  yAssF_SDL_Octet(z_WAEPackage_3W_image_png, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L20", "20")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),37) */
  yAssF_SDL_Octet(z_WAEPackage_3X_image_x_wapwbmp, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L21", "21")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),38) */
  yAssF_SDL_Octet(z_WAEPackage_3Y_x_wapmultipart, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L22", "22")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),39) */
  yAssF_SDL_Octet(z_WAEPackage_3Z_x_wapmultipart_mixed, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L23", "23")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),40) */
  yAssF_SDL_Octet(z_WAEPackage_40_x_wapmultipart_form_data, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L24", "24")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),41) */
  yAssF_SDL_Octet(z_WAEPackage_41_x_wapmultipart_byteranges, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L25", "25")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),42) */
  yAssF_SDL_Octet(z_WAEPackage_42_x_wapmultipart_alternative, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L26", "26")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),43) */
  yAssF_SDL_Octet(z_WAEPackage_43_application_vnd_wapchannelc,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L0A", "0A")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),284(85,55),1) */
  yAssF_SDL_Octet(z_WAEPackage_44_hex128, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L80", "80")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),3) */
  yAssF_SDL_Octet(z_WAEPackage_45_Continued, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L10", "10")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),4) */
  yAssF_SDL_Octet(z_WAEPackage_46_SwitchingProtocols, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L11", "11")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),6) */
  yAssF_SDL_Octet(z_WAEPackage_47_RequestOK, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L20", "20")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),9) */
  yAssF_SDL_Octet(z_WAEPackage_48_Created, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L21", "21")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),10) */
  yAssF_SDL_Octet(z_WAEPackage_49_Accepted, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L22", "22")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),11) */
  yAssF_SDL_Octet(z_WAEPackage_4A_NonAuthoritativeInformation,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L23", "23")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),12) */
  yAssF_SDL_Octet(z_WAEPackage_4B_NoContent, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L24", "24")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),13) */
  yAssF_SDL_Octet(z_WAEPackage_4C_ResetContent, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L25", "25")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),14) */
  yAssF_SDL_Octet(z_WAEPackage_4D_PartialContent, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L26", "26")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),15) */
  yAssF_SDL_Octet(z_WAEPackage_4E_MultipleChoices, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L30", "30")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),16) */
  yAssF_SDL_Octet(z_WAEPackage_4F_MovedPermanently, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L31", "31")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),17) */
  yAssF_SDL_Octet(z_WAEPackage_4G_MovedTemporarily, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L32", "32")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),19) */
  yAssF_SDL_Octet(z_WAEPackage_4H_SeeOther, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L33", "33")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),20) */
  yAssF_SDL_Octet(z_WAEPackage_4I_NotModified, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L34", "34")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),21) */
  yAssF_SDL_Octet(z_WAEPackage_4J_UseProxy, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L35", "35")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),23) */
  yAssF_SDL_Octet(z_WAEPackage_4K_BadRequest, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L40", "40")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),24) */
  yAssF_SDL_Octet(z_WAEPackage_4L_Unauthorized, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L41", "41")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),25) */
  yAssF_SDL_Octet(z_WAEPackage_4M_PaymentRequired, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L42", "42")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),26) */
  yAssF_SDL_Octet(z_WAEPackage_4N_Forbidden, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L43", "43")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),27) */
  yAssF_SDL_Octet(z_WAEPackage_4O_NotFound, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L44", "44")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),28) */
  yAssF_SDL_Octet(z_WAEPackage_4P_MethodNotAllowed, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L45", "45")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),29) */
  yAssF_SDL_Octet(z_WAEPackage_4Q_NotAcceptable, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L46", "46")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),30) */
  yAssF_SDL_Octet(z_WAEPackage_4R_ProxyAuthenticationRequired,
    xHexStr_SDL_Octet(SDL_CHARSTRING_LIT("L47", "47")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),31) */
  yAssF_SDL_Octet(z_WAEPackage_4S_RequestTimeout, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L48", "48")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),32) */
  yAssF_SDL_Octet(z_WAEPackage_4T_Conflict, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L49", "49")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),33) */
  yAssF_SDL_Octet(z_WAEPackage_4U_Gone, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L4A", "4A")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),34) */
  yAssF_SDL_Octet(z_WAEPackage_4V_LengthRequired, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L4B", "4B")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),35) */
  yAssF_SDL_Octet(z_WAEPackage_4W_PreconditionFailed, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L4C", "4C")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),36) */
  yAssF_SDL_Octet(z_WAEPackage_4X_RequestedEntityTooLarge, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L4D", "4D")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),37) */
  yAssF_SDL_Octet(z_WAEPackage_4Y_RequestURITooLarge, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L4E", "4E")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),38) */
  yAssF_SDL_Octet(z_WAEPackage_4Z_UnsupportedMediaType, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L4F", "4F")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),40) */
  yAssF_SDL_Octet(z_WAEPackage_50_InternalServerError, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L60", "60")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),41) */
  yAssF_SDL_Octet(z_WAEPackage_51_NotImplemented, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L61", "61")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),42) */
  yAssF_SDL_Octet(z_WAEPackage_52_BadGateway, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L62", "62")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),43) */
  yAssF_SDL_Octet(z_WAEPackage_53_ServiceUnavailable, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L63", "63")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),44) */
  yAssF_SDL_Octet(z_WAEPackage_54_GatewayTimeout, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L64", "64")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),45) */
  yAssF_SDL_Octet(z_WAEPackage_55_HTTPverNotSupported, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L65", "65")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),1) */
  yAssF_SDL_Octet(z_WAEPackage_57_SendOK, xHexStr_SDL_Octet(SDL_CHARSTRING_LIT(
    "L00", "00")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),2) */
  yAssF_SDL_Octet(z_WAEPackage_58_NoTIDAvailable, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L01", "01")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),3) */
  yAssF_SDL_Octet(z_WAEPackage_59_NonSupportedScheme, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L02", "02")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),4) */
  yAssF_SDL_Octet(z_WAEPackage_5A_PublicWTAIAction, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L03", "03")), XASS);
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),5) */
  yAssF_SDL_Octet(z_WAEPackage_5B_AboutScheme, xHexStr_SDL_Octet(
    SDL_CHARSTRING_LIT("L03", "03")), XASS);
}
