/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_WAEPackage_H
#define XX_WAEPackage_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

extern void yInit_WAEPackage XPP((void));

/*****
* SYNONYM MAXNUMBEROFWMLUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),302(30,90),3)
******/
#define z_WAEPackage_56_MAXNUMBEROFWMLUA SDL_INTEGER_LIT(1)

/*****
* SYNONYM nCache
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),539(25,190),1)
******/
#define z_WAEPackage_5C_nCache SDL_INTEGER_LIT(0)

/*****
* SYNONYM nUpdateCache
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),539(25,190),2)
******/
#define z_WAEPackage_5D_nUpdateCache SDL_INTEGER_LIT(1)

/*****
* SYNONYM nNoCache
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),539(25,190),3)
******/
#define z_WAEPackage_5E_nNoCache SDL_INTEGER_LIT(2)

/*****
* NEWTYPE RequestType  (TYPE section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),530(20,40),1)
******/
typedef struct z_WAEPackage_2U_RequestType_s {
    SDL_Integer  UA_Type;
    SDL_Integer  Scheme;
    SDL_Integer  SID;
    SDL_Integer  TID;
    z_ctypes_4_VoidStar  RequestStruct;
    SDL_Integer  Reload;
    SDL_Integer  Prio;
} z_WAEPackage_2U_RequestType;

/*****
* NEWTYPE ResponseType  (TYPE section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),530(20,40),11)
******/
typedef struct z_WAEPackage_2V_ResponseType_s {
    SDL_Integer  Scheme;
    SDL_Integer  SID;
    SDL_Integer  TID;
    z_ctypes_4_VoidStar  HeaderHandle;
    z_ctypes_4_VoidStar  ContentType;
    z_ctypes_4_VoidStar  BodyData;
    SDL_Integer  BodyDataLength;
    SDL_Octet  Status;
    z_ctypes_4_VoidStar  ExtParameters;
} z_WAEPackage_2V_ResponseType;

/*****
* NEWTYPE SessionType  (TYPE section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),530(20,40),23)
******/
typedef struct z_WAEPackage_2W_SessionType_s {
    z_ctypes_4_VoidStar  Network;
    z_ctypes_4_VoidStar  UaSettings;
    SDL_Integer  ViewID;
} z_WAEPackage_2W_SessionType;

/*****
* NEWTYPE RequestType  (HEADING section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),530(20,40),1)
******/

#define yAssF_z_WAEPackage_2U_RequestType(V,E,A)  V = E
extern void yDef_z_WAEPackage_2U_RequestType
  XPP(( z_WAEPackage_2U_RequestType * ));
extern SDL_Boolean yEq_z_WAEPackage_2U_RequestType
  XPP(( z_WAEPackage_2U_RequestType, z_WAEPackage_2U_RequestType ));
#define yEqF_z_WAEPackage_2U_RequestType(Expr1,Expr2)  yEq_z_WAEPackage_2U_RequestType(Expr1,Expr2)
#define yNEqF_z_WAEPackage_2U_RequestType(Expr1,Expr2)  ( ! yEq_z_WAEPackage_2U_RequestType(Expr1,Expr2) )
extern z_WAEPackage_2U_RequestType yMake_z_WAEPackage_2U_RequestType
  XPP(( SDL_Integer, SDL_Integer, SDL_Integer, SDL_Integer,
  z_ctypes_4_VoidStar, SDL_Integer, SDL_Integer ));
#ifndef ANY_z_WAEPackage_2U_RequestType
#define ANY_z_WAEPackage_2U_RequestType  yMake_z_WAEPackage_2U_RequestType(ANY_SDL_Integer, \
  ANY_SDL_Integer, ANY_SDL_Integer, ANY_SDL_Integer, ANY_z_ctypes_4_VoidStar, \
  ANY_SDL_Integer, ANY_SDL_Integer)
#endif
#define z_WAEPackage_2U3_copy(P)  P

/*****
* NEWTYPE ResponseType  (HEADING section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),530(20,40),11)
******/

#define yAssF_z_WAEPackage_2V_ResponseType(V,E,A)  V = E
extern void yDef_z_WAEPackage_2V_ResponseType
  XPP(( z_WAEPackage_2V_ResponseType * ));
extern SDL_Boolean yEq_z_WAEPackage_2V_ResponseType
  XPP(( z_WAEPackage_2V_ResponseType, z_WAEPackage_2V_ResponseType ));
#define yEqF_z_WAEPackage_2V_ResponseType(Expr1,Expr2)  yEq_z_WAEPackage_2V_ResponseType(Expr1,Expr2)
#define yNEqF_z_WAEPackage_2V_ResponseType(Expr1,Expr2)  ( ! yEq_z_WAEPackage_2V_ResponseType(Expr1,Expr2) )
extern z_WAEPackage_2V_ResponseType yMake_z_WAEPackage_2V_ResponseType
  XPP(( SDL_Integer, SDL_Integer, SDL_Integer, z_ctypes_4_VoidStar,
  z_ctypes_4_VoidStar, z_ctypes_4_VoidStar, SDL_Integer, SDL_Octet,
  z_ctypes_4_VoidStar ));
#ifndef ANY_z_WAEPackage_2V_ResponseType
#define ANY_z_WAEPackage_2V_ResponseType  yMake_z_WAEPackage_2V_ResponseType(ANY_SDL_Integer, \
  ANY_SDL_Integer, ANY_SDL_Integer, ANY_z_ctypes_4_VoidStar, \
  ANY_z_ctypes_4_VoidStar, ANY_z_ctypes_4_VoidStar, ANY_SDL_Integer, \
  ANY_SDL_Octet, ANY_z_ctypes_4_VoidStar)
#endif
#define z_WAEPackage_2V3_copy(P)  P

/*****
* NEWTYPE SessionType  (HEADING section)
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),530(20,40),23)
******/

#define yAssF_z_WAEPackage_2W_SessionType(V,E,A)  V = E
extern void yDef_z_WAEPackage_2W_SessionType
  XPP(( z_WAEPackage_2W_SessionType * ));
extern SDL_Boolean yEq_z_WAEPackage_2W_SessionType
  XPP(( z_WAEPackage_2W_SessionType, z_WAEPackage_2W_SessionType ));
#define yEqF_z_WAEPackage_2W_SessionType(Expr1,Expr2)  yEq_z_WAEPackage_2W_SessionType(Expr1,Expr2)
#define yNEqF_z_WAEPackage_2W_SessionType(Expr1,Expr2)  ( ! yEq_z_WAEPackage_2W_SessionType(Expr1,Expr2) )
extern z_WAEPackage_2W_SessionType yMake_z_WAEPackage_2W_SessionType
  XPP(( z_ctypes_4_VoidStar, z_ctypes_4_VoidStar, SDL_Integer ));
#ifndef ANY_z_WAEPackage_2W_SessionType
#define ANY_z_WAEPackage_2W_SessionType  yMake_z_WAEPackage_2W_SessionType(ANY_z_ctypes_4_VoidStar, \
  ANY_z_ctypes_4_VoidStar, ANY_SDL_Integer)
#endif
#define z_WAEPackage_2W3_copy(P)  P

/*****
* SYNONYM Get
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),287(30,55),13)
******/
extern SDL_Octet  z_WAEPackage_2X_Get;

/*****
* SYNONYM Post
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),287(30,55),14)
******/
extern SDL_Octet  z_WAEPackage_2Y_Post;

/*****
* SYNONYM anything
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),3)
******/
extern SDL_Octet  z_WAEPackage_2Z_anything;

/*****
* SYNONYM text
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),4)
******/
extern SDL_Octet  z_WAEPackage_30_text;

/*****
* SYNONYM text_html
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),5)
******/
extern SDL_Octet  z_WAEPackage_31_text_html;

/*****
* SYNONYM text_plain
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),6)
******/
extern SDL_Octet  z_WAEPackage_32_text_plain;

/*****
* SYNONYM text_x_hdml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),7)
******/
extern SDL_Octet  z_WAEPackage_33_text_x_hdml;

/*****
* SYNONYM text_x_ttml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),8)
******/
extern SDL_Octet  z_WAEPackage_34_text_x_ttml;

/*****
* SYNONYM text_x_vCalendar
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),9)
******/
extern SDL_Octet  z_WAEPackage_35_text_x_vCalendar;

/*****
* SYNONYM text_x_vCard
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),10)
******/
extern SDL_Octet  z_WAEPackage_36_text_x_vCard;

/*****
* SYNONYM text_x_wap.wml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),11)
******/
extern SDL_Octet  z_WAEPackage_37_text_x_wapwml;

/*****
* SYNONYM text_x_wap.wmlscript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),12)
******/
extern SDL_Octet  z_WAEPackage_38_text_x_wapwmlscript;

/*****
* SYNONYM text_x_wap.wta_event
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),13)
******/
extern SDL_Octet  z_WAEPackage_39_text_x_wapwta_event;

/*****
* SYNONYM multipart
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),14)
******/
extern SDL_Octet  z_WAEPackage_3A_multipart;

/*****
* SYNONYM multipart_mixed
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),15)
******/
extern SDL_Octet  z_WAEPackage_3B_multipart_mixed;

/*****
* SYNONYM multipart_form_data
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),16)
******/
extern SDL_Octet  z_WAEPackage_3C_multipart_form_data;

/*****
* SYNONYM multipart_byteranges
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),17)
******/
extern SDL_Octet  z_WAEPackage_3D_multipart_byteranges;

/*****
* SYNONYM multipart_alternative
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),18)
******/
extern SDL_Octet  z_WAEPackage_3E_multipart_alternative;

/*****
* SYNONYM application
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),19)
******/
extern SDL_Octet  z_WAEPackage_3F_application;

/*****
* SYNONYM application_java_vm
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),20)
******/
extern SDL_Octet  z_WAEPackage_3G_application_java_vm;

/*****
* SYNONYM application_x_www_form_urlencoded
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),21)
******/
extern SDL_Octet  z_WAEPackage_3H_application_x_www_form_urlencoded;

/*****
* SYNONYM application_x_hdmlc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),22)
******/
extern SDL_Octet  z_WAEPackage_3I_application_x_hdmlc;

/*****
* SYNONYM application_vnd_wap.wmlc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),23)
******/
extern SDL_Octet  z_WAEPackage_3J_application_vnd_wapwmlc;

/*****
* SYNONYM application_vnd_wap.wbxml
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),24)
******/
extern SDL_Octet  z_WAEPackage_3K_application_vnd_wapwbxml;

/*****
* SYNONYM application_vnd_wap.wmlscriptc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),25)
******/
extern SDL_Octet  z_WAEPackage_3L_application_vnd_wapwmlscriptc;

/*****
* SYNONYM application_x_wap.wta_eventc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),26)
******/
extern SDL_Octet  z_WAEPackage_3M_application_x_wapwta_eventc;

/*****
* SYNONYM application_x_wap.uaprof
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),27)
******/
extern SDL_Octet  z_WAEPackage_3N_application_x_wapuaprof;

/*****
* SYNONYM application_x_wap.wtls_ca_certificate
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),28)
******/
extern SDL_Octet  z_WAEPackage_3O_application_x_wapwtls_ca_certificate;

/*****
* SYNONYM application_x_wap.wtls_user_certificate
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),29)
******/
extern SDL_Octet  z_WAEPackage_3P_application_x_wapwtls_user_certificate;

/*****
* SYNONYM application_x_x509_ca_cert
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),30)
******/
extern SDL_Octet  z_WAEPackage_3Q_application_x_x509_ca_cert;

/*****
* SYNONYM application_x_x509_user_cert
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),31)
******/
extern SDL_Octet  z_WAEPackage_3R_application_x_x509_user_cert;

/*****
* SYNONYM image
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),32)
******/
extern SDL_Octet  z_WAEPackage_3S_image;

/*****
* SYNONYM image_gif
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),33)
******/
extern SDL_Octet  z_WAEPackage_3T_image_gif;

/*****
* SYNONYM image_jpeg
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),34)
******/
extern SDL_Octet  z_WAEPackage_3U_image_jpeg;

/*****
* SYNONYM image_tiff
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),35)
******/
extern SDL_Octet  z_WAEPackage_3V_image_tiff;

/*****
* SYNONYM image_png
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),36)
******/
extern SDL_Octet  z_WAEPackage_3W_image_png;

/*****
* SYNONYM image_x_wap.wbmp
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),37)
******/
extern SDL_Octet  z_WAEPackage_3X_image_x_wapwbmp;

/*****
* SYNONYM x_wap.multipart
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),38)
******/
extern SDL_Octet  z_WAEPackage_3Y_x_wapmultipart;

/*****
* SYNONYM x_wap.multipart_mixed
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),39)
******/
extern SDL_Octet  z_WAEPackage_3Z_x_wapmultipart_mixed;

/*****
* SYNONYM x_wap.multipart_form_data
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),40)
******/
extern SDL_Octet  z_WAEPackage_40_x_wapmultipart_form_data;

/*****
* SYNONYM x_wap.multipart_byteranges
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),41)
******/
extern SDL_Octet  z_WAEPackage_41_x_wapmultipart_byteranges;

/*****
* SYNONYM x_wap.multipart_alternative
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),42)
******/
extern SDL_Octet  z_WAEPackage_42_x_wapmultipart_alternative;

/*****
* SYNONYM application_vnd_wap.channelc
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),290(55,55),43)
******/
extern SDL_Octet  z_WAEPackage_43_application_vnd_wapchannelc;

/*****
* SYNONYM hex128
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),284(85,55),1)
******/
extern SDL_Octet  z_WAEPackage_44_hex128;

/*****
* SYNONYM Continued
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),3)
******/
extern SDL_Octet  z_WAEPackage_45_Continued;

/*****
* SYNONYM SwitchingProtocols
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),4)
******/
extern SDL_Octet  z_WAEPackage_46_SwitchingProtocols;

/*****
* SYNONYM RequestOK
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),6)
******/
extern SDL_Octet  z_WAEPackage_47_RequestOK;

/*****
* SYNONYM Created
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),9)
******/
extern SDL_Octet  z_WAEPackage_48_Created;

/*****
* SYNONYM Accepted
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),10)
******/
extern SDL_Octet  z_WAEPackage_49_Accepted;

/*****
* SYNONYM NonAuthoritativeInformation
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),11)
******/
extern SDL_Octet  z_WAEPackage_4A_NonAuthoritativeInformation;

/*****
* SYNONYM NoContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),12)
******/
extern SDL_Octet  z_WAEPackage_4B_NoContent;

/*****
* SYNONYM ResetContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),13)
******/
extern SDL_Octet  z_WAEPackage_4C_ResetContent;

/*****
* SYNONYM PartialContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),14)
******/
extern SDL_Octet  z_WAEPackage_4D_PartialContent;

/*****
* SYNONYM MultipleChoices
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),15)
******/
extern SDL_Octet  z_WAEPackage_4E_MultipleChoices;

/*****
* SYNONYM MovedPermanently
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),16)
******/
extern SDL_Octet  z_WAEPackage_4F_MovedPermanently;

/*****
* SYNONYM MovedTemporarily
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),17)
******/
extern SDL_Octet  z_WAEPackage_4G_MovedTemporarily;

/*****
* SYNONYM SeeOther
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),19)
******/
extern SDL_Octet  z_WAEPackage_4H_SeeOther;

/*****
* SYNONYM NotModified
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),20)
******/
extern SDL_Octet  z_WAEPackage_4I_NotModified;

/*****
* SYNONYM UseProxy
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),21)
******/
extern SDL_Octet  z_WAEPackage_4J_UseProxy;

/*****
* SYNONYM BadRequest
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),23)
******/
extern SDL_Octet  z_WAEPackage_4K_BadRequest;

/*****
* SYNONYM Unauthorized
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),24)
******/
extern SDL_Octet  z_WAEPackage_4L_Unauthorized;

/*****
* SYNONYM PaymentRequired
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),25)
******/
extern SDL_Octet  z_WAEPackage_4M_PaymentRequired;

/*****
* SYNONYM Forbidden
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),26)
******/
extern SDL_Octet  z_WAEPackage_4N_Forbidden;

/*****
* SYNONYM NotFound
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),27)
******/
extern SDL_Octet  z_WAEPackage_4O_NotFound;

/*****
* SYNONYM MethodNotAllowed
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),28)
******/
extern SDL_Octet  z_WAEPackage_4P_MethodNotAllowed;

/*****
* SYNONYM NotAcceptable
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),29)
******/
extern SDL_Octet  z_WAEPackage_4Q_NotAcceptable;

/*****
* SYNONYM ProxyAuthenticationRequired
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),30)
******/
extern SDL_Octet  z_WAEPackage_4R_ProxyAuthenticationRequired;

/*****
* SYNONYM RequestTimeout
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),31)
******/
extern SDL_Octet  z_WAEPackage_4S_RequestTimeout;

/*****
* SYNONYM Conflict
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),32)
******/
extern SDL_Octet  z_WAEPackage_4T_Conflict;

/*****
* SYNONYM Gone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),33)
******/
extern SDL_Octet  z_WAEPackage_4U_Gone;

/*****
* SYNONYM LengthRequired
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),34)
******/
extern SDL_Octet  z_WAEPackage_4V_LengthRequired;

/*****
* SYNONYM PreconditionFailed
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),35)
******/
extern SDL_Octet  z_WAEPackage_4W_PreconditionFailed;

/*****
* SYNONYM RequestedEntityTooLarge
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),36)
******/
extern SDL_Octet  z_WAEPackage_4X_RequestedEntityTooLarge;

/*****
* SYNONYM RequestURITooLarge
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),37)
******/
extern SDL_Octet  z_WAEPackage_4Y_RequestURITooLarge;

/*****
* SYNONYM UnsupportedMediaType
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),38)
******/
extern SDL_Octet  z_WAEPackage_4Z_UnsupportedMediaType;

/*****
* SYNONYM InternalServerError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),40)
******/
extern SDL_Octet  z_WAEPackage_50_InternalServerError;

/*****
* SYNONYM NotImplemented
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),41)
******/
extern SDL_Octet  z_WAEPackage_51_NotImplemented;

/*****
* SYNONYM BadGateway
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),42)
******/
extern SDL_Octet  z_WAEPackage_52_BadGateway;

/*****
* SYNONYM ServiceUnavailable
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),43)
******/
extern SDL_Octet  z_WAEPackage_53_ServiceUnavailable;

/*****
* SYNONYM GatewayTimeout
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),44)
******/
extern SDL_Octet  z_WAEPackage_54_GatewayTimeout;

/*****
* SYNONYM HTTPverNotSupported
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),296(55,70),45)
******/
extern SDL_Octet  z_WAEPackage_55_HTTPverNotSupported;

/*****
* SYNONYM SendOK
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),1)
******/
extern SDL_Octet  z_WAEPackage_57_SendOK;

/*****
* SYNONYM NoTIDAvailable
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),2)
******/
extern SDL_Octet  z_WAEPackage_58_NoTIDAvailable;

/*****
* SYNONYM NonSupportedScheme
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),3)
******/
extern SDL_Octet  z_WAEPackage_59_NonSupportedScheme;

/*****
* SYNONYM PublicWTAIAction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),4)
******/
extern SDL_Octet  z_WAEPackage_5A_PublicWTAIAction;

/*****
* SYNONYM AboutScheme
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WAEDeclarations),341(90,110),5)
******/
extern SDL_Octet  z_WAEPackage_5B_AboutScheme;

/*****
* SIGNAL InputString
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),191(20,40),3)
******/
#define z_WAEPackage_01_InputString 44
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_01_InputString;

/*****
* SIGNAL LoadURL
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),191(20,40),4)
******/
#define z_WAEPackage_02_LoadURL 45
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Boolean  Param3;
    SDL_Integer  Param4;
} yPDef_z_WAEPackage_02_LoadURL;

/*****
* SIGNAL ReloadCard
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),191(20,40),5)
******/
#define z_WAEPackage_03_ReloadCard 46
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_03_ReloadCard;

/*****
* SIGNAL OpenView
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),191(20,40),6)
******/
#define z_WAEPackage_04_OpenView 47
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_04_OpenView;

/*****
* SIGNAL CloseView
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),191(20,40),7)
******/
#define z_WAEPackage_05_CloseView 48
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_05_CloseView;

/*****
* SIGNAL DiscardAllContext
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),191(20,40),8)
******/
#define z_WAEPackage_06_DiscardAllContext 49

/*****
* SIGNAL Abort
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),191(20,40),9)
******/
#define z_WAEPackage_07_Abort 50
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_07_Abort;

/*****
* SIGNAL GoBack
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),191(20,40),10)
******/
#define z_WAEPackage_08_GoBack 51
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_08_GoBack;

/*****
* SIGNAL PasswordDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),191(20,40),11)
******/
#define z_WAEPackage_09_PasswordDialogResponse 52
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_09_PasswordDialogResponse;

/*****
* SIGNAL GetContent
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),197(110,40),4)
******/
#define z_WAEPackage_0A_GetContent 53
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Boolean  Param3;
} yPDef_z_WAEPackage_0A_GetContent;

/*****
* SIGNAL DownloadConfirm
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),200(110,60),9)
******/
#define z_WAEPackage_0B_DownloadConfirm 54
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Boolean  Param2;
} yPDef_z_WAEPackage_0B_DownloadConfirm;

/*****
* SIGNAL InitCache
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),200(110,60),10)
******/
#define z_WAEPackage_0C_InitCache 55
typedef struct {
    SIGNAL_VARS
    z_ctypes_7_LongInt  Param1;
    z_ctypes_7_LongInt  Param2;
} yPDef_z_WAEPackage_0C_InitCache;

/*****
* SIGNAL PrepareCache
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),200(110,60),11)
******/
#define z_WAEPackage_0D_PrepareCache 56
typedef struct {
    SIGNAL_VARS
    z_ctypes_7_LongInt  Param1;
} yPDef_z_WAEPackage_0D_PrepareCache;

/*****
* SIGNAL ClntUsePort
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),200(110,60),12)
******/
#define z_WAEPackage_0E_ClntUsePort 57
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_Boolean  Param4;
} yPDef_z_WAEPackage_0E_ClntUsePort;

/*****
* SIGNAL ClntClosePort
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),200(110,60),13)
******/
#define z_WAEPackage_0F_ClntClosePort 58
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_0F_ClntClosePort;

/*****
* SIGNAL KeySelected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),356(110,110),3)
******/
#define z_WAEPackage_0G_KeySelected 59
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0G_KeySelected;

/*****
* SIGNAL TextSelected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),356(110,110),4)
******/
#define z_WAEPackage_0H_TextSelected 60
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0H_TextSelected;

/*****
* SIGNAL ImageSelected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),356(110,110),5)
******/
#define z_WAEPackage_0I_ImageSelected 61
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0I_ImageSelected;

/*****
* SIGNAL ChangeOptionState
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),356(110,110),6)
******/
#define z_WAEPackage_0J_ChangeOptionState 62
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0J_ChangeOptionState;

/*****
* SIGNAL LinkInfo
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),356(110,110),7)
******/
#define z_WAEPackage_0K_LinkInfo 63
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_0K_LinkInfo;

/*****
* SIGNAL Initialized
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),188(20,120),3)
******/
#define z_WAEPackage_0L_Initialized 64

/*****
* SIGNAL PromptDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),179(85,170),3)
******/
#define z_WAEPackage_0M_PromptDialogResponse 65
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_0M_PromptDialogResponse;

/*****
* SIGNAL ConfirmDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),179(85,170),4)
******/
#define z_WAEPackage_0N_ConfirmDialogResponse 66
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_0N_ConfirmDialogResponse;

/*****
* SIGNAL AlertDialogResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),179(85,170),5)
******/
#define z_WAEPackage_0O_AlertDialogResponse 67
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_0O_AlertDialogResponse;

/*****
* SIGNAL WMLSLibFuncResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(EnvironmentSignals),179(85,170),6)
******/
#define z_WAEPackage_0P_WMLSLibFuncResponse 68
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z_WAEPackage_0P_WMLSLibFuncResponse;

/*****
* SIGNAL StartUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(InitSignals),266(30,40),6)
******/
#define z_WAEPackage_0Q_StartUA 69
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z_WAEPackage_0Q_StartUA;

/*****
* SIGNAL TerminateUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(InitSignals),266(30,40),7)
******/
#define z_WAEPackage_0R_TerminateUA 70

/*****
* SIGNAL InitializeUA
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(InitSignals),266(30,40),8)
******/
#define z_WAEPackage_0S_InitializeUA 71

/*****
* SIGNAL InitializeUADone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(InitSignals),266(30,40),14)
******/
#define z_WAEPackage_0T_InitializeUADone 72

/*****
* SIGNAL TerminateUACnf
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(InitSignals),266(30,40),15)
******/
#define z_WAEPackage_0U_TerminateUACnf 73

/*****
* SIGNAL StartWMLS
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(InitSignals),266(30,40),21)
******/
#define z_WAEPackage_0V_StartWMLS 74

/*****
* SIGNAL TerminateWMLS
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(InitSignals),266(30,40),22)
******/
#define z_WAEPackage_0W_TerminateWMLS 75

/*****
* SIGNAL TerminateWMLSCnf
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(InitSignals),266(30,40),27)
******/
#define z_WAEPackage_0X_TerminateWMLSCnf 76

/*****
* SIGNAL AbortScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),12)
******/
#define z_WAEPackage_0Y_AbortScript 77
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_0Y_AbortScript;

/*****
* SIGNAL InvokeScript
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),13)
******/
#define z_WAEPackage_0Z_InvokeScript 78
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
    SDL_Integer  Param6;
} yPDef_z_WAEPackage_0Z_InvokeScript;

/*****
* SIGNAL LoadDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),16)
******/
#define z_WAEPackage_10_LoadDone 79
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    SDL_Integer  Param4;
} yPDef_z_WAEPackage_10_LoadDone;

/*****
* SIGNAL LoadStringDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),19)
******/
#define z_WAEPackage_11_LoadStringDone 80
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    z_ctypes_9_UnsignedInt  Param4;
} yPDef_z_WAEPackage_11_LoadStringDone;

/*****
* SIGNAL LoadStringError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),22)
******/
#define z_WAEPackage_12_LoadStringError 81
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_12_LoadStringError;

/*****
* SIGNAL LoadError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),23)
******/
#define z_WAEPackage_13_LoadError 82
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_13_LoadError;

/*****
* SIGNAL RefreshDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),24)
******/
#define z_WAEPackage_14_RefreshDone 83
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_14_RefreshDone;

/*****
* SIGNAL InvokeDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),36)
******/
#define z_WAEPackage_15_InvokeDone 84
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    z_ctypes_4_VoidStar  Param3;
    SDL_Integer  Param4;
    z_ctypes_4_VoidStar  Param5;
} yPDef_z_WAEPackage_15_InvokeDone;

/*****
* SIGNAL InvokeStatus
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),37)
******/
#define z_WAEPackage_16_InvokeStatus 85
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_16_InvokeStatus;

/*****
* SIGNAL LoadBP
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),38)
******/
#define z_WAEPackage_17_LoadBP 86
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
} yPDef_z_WAEPackage_17_LoadBP;

/*****
* SIGNAL LoadString
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),39)
******/
#define z_WAEPackage_18_LoadString 87
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    z_ctypes_4_VoidStar  Param3;
} yPDef_z_WAEPackage_18_LoadString;

/*****
* SIGNAL RefreshReqFromWmls
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WMLSSignals),218(25,45),40)
******/
#define z_WAEPackage_19_RefreshReqFromWmls 88
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_19_RefreshReqFromWmls;

/*****
* SIGNAL GetFileResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(FILESignals),338(60,50),4)
******/
#define z_WAEPackage_1A_GetFileResponse 89
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_1A_GetFileResponse;

/*****
* SIGNAL CallFunctionResult
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(FILESignals),338(60,50),5)
******/
#define z_WAEPackage_1B_CallFunctionResult 90
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
    z_ctypes_4_VoidStar  Param5;
} yPDef_z_WAEPackage_1B_CallFunctionResult;

/*****
* SIGNAL WSPRequest
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),4)
******/
#define z_WAEPackage_1C_WSPRequest 91
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2U_RequestType  Param1;
} yPDef_z_WAEPackage_1C_WSPRequest;

/*****
* SIGNAL WSPAbortRequest
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),5)
******/
#define z_WAEPackage_1D_WSPAbortRequest 92
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
} yPDef_z_WAEPackage_1D_WSPAbortRequest;

/*****
* SIGNAL WSPNewSession
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),7)
******/
#define z_WAEPackage_1E_WSPNewSession 93
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2W_SessionType  Param1;
} yPDef_z_WAEPackage_1E_WSPNewSession;

/*****
* SIGNAL WSPTerminateSession
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),8)
******/
#define z_WAEPackage_1F_WSPTerminateSession 94
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1F_WSPTerminateSession;

/*****
* SIGNAL WSPChangeSessionParam
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),10)
******/
#define z_WAEPackage_1G_WSPChangeSessionParam 95
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    z_WAEPackage_2W_SessionType  Param2;
} yPDef_z_WAEPackage_1G_WSPChangeSessionParam;

/*****
* SIGNAL StartWSPIFDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),26)
******/
#define z_WAEPackage_1H_StartWSPIFDone 96

/*****
* SIGNAL TerminateWSPIFDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),27)
******/
#define z_WAEPackage_1I_TerminateWSPIFDone 97

/*****
* SIGNAL StartWSPIF
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),36)
******/
#define z_WAEPackage_1J_StartWSPIF 98
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
} yPDef_z_WAEPackage_1J_StartWSPIF;

/*****
* SIGNAL TerminateWSPIF
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),37)
******/
#define z_WAEPackage_1K_TerminateWSPIF 99

/*****
* SIGNAL WSPTerminateBearer
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),533(105,40),38)
******/
#define z_WAEPackage_1L_WSPTerminateBearer 100
typedef struct {
    SIGNAL_VARS
    SDL_Octet  Param1;
} yPDef_z_WAEPackage_1L_WSPTerminateBearer;

/*****
* SIGNAL WSPSessionAck
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),536(20,130),4)
******/
#define z_WAEPackage_1M_WSPSessionAck 101
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1M_WSPSessionAck;

/*****
* SIGNAL WSPResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),536(20,130),5)
******/
#define z_WAEPackage_1N_WSPResponse 102
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2V_ResponseType  Param1;
} yPDef_z_WAEPackage_1N_WSPResponse;

/*****
* SIGNAL WSPError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(WSPIFSignals),536(20,130),6)
******/
#define z_WAEPackage_1O_WSPError 103
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
} yPDef_z_WAEPackage_1O_WSPError;

/*****
* SIGNAL StartDI
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),18)
******/
#define z_WAEPackage_1P_StartDI 104

/*****
* SIGNAL TerminateDI
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),19)
******/
#define z_WAEPackage_1Q_TerminateDI 105

/*****
* SIGNAL SMNewSession
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),20)
******/
#define z_WAEPackage_1R_SMNewSession 106
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2W_SessionType  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    z_ctypes_4_VoidStar  Param4;
} yPDef_z_WAEPackage_1R_SMNewSession;

/*****
* SIGNAL SMChangeSessionParam
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),21)
******/
#define z_WAEPackage_1S_SMChangeSessionParam 107
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2W_SessionType  Param1;
} yPDef_z_WAEPackage_1S_SMChangeSessionParam;

/*****
* SIGNAL SMTerminateSession
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),22)
******/
#define z_WAEPackage_1T_SMTerminateSession 108

/*****
* SIGNAL SMNewTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),23)
******/
#define z_WAEPackage_1U_SMNewTransaction 109
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2U_RequestType  Param1;
    SDL_PId  Param2;
    z_ctypes_A_UnsignedLongInt  Param3;
} yPDef_z_WAEPackage_1U_SMNewTransaction;

/*****
* SIGNAL SMAbortTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),25)
******/
#define z_WAEPackage_1V_SMAbortTransaction 110
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1V_SMAbortTransaction;

/*****
* SIGNAL SMDownLoadConfirm
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),27)
******/
#define z_WAEPackage_1W_SMDownLoadConfirm 111
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Boolean  Param2;
} yPDef_z_WAEPackage_1W_SMDownLoadConfirm;

/*****
* SIGNAL SMReConnect
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),29)
******/
#define z_WAEPackage_1X_SMReConnect 112

/*****
* SIGNAL SMTerminateBearer
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),30)
******/
#define z_WAEPackage_1Y_SMTerminateBearer 113
typedef struct {
    SIGNAL_VARS
    SDL_Octet  Param1;
} yPDef_z_WAEPackage_1Y_SMTerminateBearer;

/*****
* SIGNAL SMPushIndicationResp
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),32)
******/
#define z_WAEPackage_1Z_SMPushIndicationResp 114
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_1Z_SMPushIndicationResp;

/*****
* SIGNAL SMUsePort
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),34)
******/
#define z_WAEPackage_20_SMUsePort 115
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Boolean  Param2;
} yPDef_z_WAEPackage_20_SMUsePort;

/*****
* SIGNAL SMClosePort
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),36)
******/
#define z_WAEPackage_21_SMClosePort 116
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
} yPDef_z_WAEPackage_21_SMClosePort;

/*****
* SIGNAL SessionProcInstalled
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),52)
******/
#define z_WAEPackage_22_SessionProcInstalled 117

/*****
* SIGNAL StartDIDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),53)
******/
#define z_WAEPackage_23_StartDIDone 118

/*****
* SIGNAL TerminateDIDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),54)
******/
#define z_WAEPackage_24_TerminateDIDone 119

/*****
* SIGNAL SMTerminateSessionDone
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),55)
******/
#define z_WAEPackage_25_SMTerminateSessionDone 120

/*****
* SIGNAL GetNextTransaction
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),56)
******/
#define z_WAEPackage_26_GetNextTransaction 121

/*****
* SIGNAL Connected
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),57)
******/
#define z_WAEPackage_27_Connected 122
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Boolean  Param2;
} yPDef_z_WAEPackage_27_Connected;

/*****
* SIGNAL WSPIFResponse
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),58)
******/
#define z_WAEPackage_28_WSPIFResponse 123
typedef struct {
    SIGNAL_VARS
    z_WAEPackage_2V_ResponseType  Param1;
    z_ctypes_4_VoidStar  Param2;
    SDL_Integer  Param3;
    SDL_PId  Param4;
    SDL_Integer  Param5;
    SDL_Integer  Param6;
    z_WAEPackage_2U_RequestType  Param7;
} yPDef_z_WAEPackage_28_WSPIFResponse;

/*****
* SIGNAL WSPIFError
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),60)
******/
#define z_WAEPackage_29_WSPIFError 124
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_PId  Param4;
} yPDef_z_WAEPackage_29_WSPIFError;

/*****
* SIGNAL WSPIFPushIndication
* <<PACKAGE WAEPackage>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WAEPackage.sun(ResourceHandler),524(25,25),62)
******/
#define z_WAEPackage_2A_WSPIFPushIndication 125
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Integer  Param2;
    SDL_Integer  Param3;
    SDL_Boolean  Param4;
    SDL_Integer  Param5;
    SDL_Integer  Param6;
    z_ctypes_4_VoidStar  Param7;
    z_ctypes_4_VoidStar  Param8;
} yPDef_z_WAEPackage_2A_WSPIFPushIndication;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
