/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif


/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/
#define XPTID_z0005_WAE_ME 0
extern XCONST XPDTBL yPDTBL_z0005_WAE_ME;
#define XPTID_z0014_WMLS_SM 1
extern XCONST XPDTBL yPDTBL_z0014_WMLS_SM;
#define XPTID_z0020E_UA_ME 2
extern XCONST XPDTBL yPDTBL_z0020E_UA_ME;
#define XPTID_z0020F_MMI_DISP 3
extern XCONST XPDTBL yPDTBL_z0020F_MMI_DISP;
#define XPTID_z0020G_WML_UA 4
extern XCONST XPDTBL yPDTBL_z0020G_WML_UA;
#define XPTID_z0020H_MMI_AGNT 5
extern XCONST XPDTBL yPDTBL_z0020H_MMI_AGNT;
#define XPTID_z0020I_CONT_UA 6
extern XCONST XPDTBL yPDTBL_z0020I_CONT_UA;
#define XPTID_z0034_RES_ME 7
extern XCONST XPDTBL yPDTBL_z0034_RES_ME;
#define XPTID_z0035_RES_CC 8
extern XCONST XPDTBL yPDTBL_z0035_RES_CC;
#define XPTID_z0036_RES_FC 9
extern XCONST XPDTBL yPDTBL_z0036_RES_FC;
#define XPTID_z00403_WSPIF_SM 10
extern XCONST XPDTBL yPDTBL_z00403_WSPIF_SM;
#define XPTID_z00404_WSPIF_TR 11
extern XCONST XPDTBL yPDTBL_z00404_WSPIF_TR;
#define XPTID_z00405_WSPIF_DI 12
extern XCONST XPDTBL yPDTBL_z00405_WSPIF_DI;
#define XPTID_z17_StackCtrl 13
extern XCONST XPDTBL yPDTBL_z17_StackCtrl;
#define XPTID_z209_ClientSession 14
extern XCONST XPDTBL yPDTBL_z209_ClientSession;
#define XPTID_z20A_ClientMethod 15
extern XCONST XPDTBL yPDTBL_z20A_ClientMethod;
#define XPTID_z20B_ClientDispatcher 16
extern XCONST XPDTBL yPDTBL_z20B_ClientDispatcher;
#define XPTID_z20C_ClientPush 17
extern XCONST XPDTBL yPDTBL_z20C_ClientPush;
#define XPTID_z20D_WSP_ME 18
extern XCONST XPDTBL yPDTBL_z20D_WSP_ME;
#define XPTID_z20E_ConnectionLess 19
extern XCONST XPDTBL yPDTBL_z20E_ConnectionLess;
#define XPTID_z3000F_TransactionManager 20
extern XCONST XPDTBL yPDTBL_z3000F_TransactionManager;
#define XPTID_z3000G_Initiator 21
extern XCONST XPDTBL yPDTBL_z3000G_Initiator;
#define XPTID_z3000H_Responder 22
extern XCONST XPDTBL yPDTBL_z3000H_Responder;
#define XPTID_z3014_MEProcess 23
extern XCONST XPDTBL yPDTBL_z3014_MEProcess;
#define XPTID_z40C_WDPhandler 24
extern XCONST XPDTBL yPDTBL_z40C_WDPhandler;
#define XPTID_z40D_WDPmanagement 25
extern XCONST XPDTBL yPDTBL_z40D_WDPmanagement;
#define XPTID_z40E_Segmentation 26
extern XCONST XPDTBL yPDTBL_z40E_Segmentation;
#define XPTID_z40F_Reassemble 27
extern XCONST XPDTBL yPDTBL_z40F_Reassemble;
#define XPTID_z505_UDCPDialogueHandler 28
extern XCONST XPDTBL yPDTBL_z505_UDCPDialogueHandler;
#define XPTID_z506_UDCP_ME 29
extern XCONST XPDTBL yPDTBL_z506_UDCP_ME;

/*****
* PROCESS StackCtrl
* <<SYSTEM WAP/BLOCK Stack_Mgr>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\stackmgr\StackCtrl.spr,4,1)
******/
YPAD_PROTOTYPE(yPAD_z17_StackCtrl)
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\stackmgr\StackCtrl.spr(1),182(105,10),2) */
    SDL_Natural  z178_n;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\stackmgr\StackCtrl.spr(1),182(105,10),3) */
    SDL_Natural  z179_NbrOfLayers;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\stackmgr\StackCtrl.spr(1),182(105,10),4) */
    SDL_Natural  z17A_Wait;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\stackmgr\StackCtrl.spr(1),182(105,10),5) */
    SDL_Real  z17B_R;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\stackmgr\StackCtrl.spr(1),182(105,10),6) */
    SDL_Duration  z17C_Diff;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\stackmgr\StackCtrl.spr(1),182(105,10),7) */
    SDL_Natural  z17D_Layer;
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\stackmgr\StackCtrl.spr(1),239(155,10),2) */
    DEF_TIMER_VAR(yTim_MaxWait)
} yVDef_z17_StackCtrl;
#define z170_IDLE  1
#define z171_AwaitWAEReadySignal  2
#define z172_AwaitWSPReadySignal  3
#define z173_AwaitWTPReadySignal  4
#define z174_AwaitWDPReadySignal  5
#define z175_AwaitUDCPReadySignal  6
#define z176_AwaitReadySignals  7

/*****
* TIMER MaxWait
* <<SYSTEM WAP/BLOCK Stack_Mgr/PROCESS StackCtrl>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\stackmgr\StackCtrl.spr(1),239(155,10),2)
******/
#define z177_MaxWait 6

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
                /* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\WAP.ssy,4,2) */
#include "confvars.h"
#include "logcodes.h"
#include "errcodes.h"
#include "aapisms.h"
#include "aapiudp.h"
#include "aapiclnt.h"
#include "capiclnt.h"

