/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_WDP_UDP_H
#define XX_WDP_UDP_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SIGNAL UDPsendReq
* <<PACKAGE WDP_UDP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDP.sun(1),122(30,85),5)
******/
#define z_WDP_UDP_0_UDPsendReq 159
typedef struct {
    SIGNAL_VARS
    SDL_Octet_String  Param1;
    DeviceAddress  Param2;
    DeviceAddress  Param3;
    SDL_Natural  Param4;
    SDL_Natural  Param5;
} yPDef_z_WDP_UDP_0_UDPsendReq;

/*****
* SIGNAL RecUDPDatagram
* <<PACKAGE WDP_UDP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDP.sun(1),125(30,110),3)
******/
#define z_WDP_UDP_1_RecUDPDatagram 160
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Natural  Param2;
    DeviceAddress  Param3;
    DeviceAddress  Param4;
    SDL_Natural  Param5;
    SDL_Natural  Param6;
} yPDef_z_WDP_UDP_1_RecUDPDatagram;

/*****
* SIGNAL UDPErrorInd
* <<PACKAGE WDP_UDP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDP.sun(1),125(30,110),6)
******/
#define z_WDP_UDP_2_UDPErrorInd 161
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Natural  Param2;
} yPDef_z_WDP_UDP_2_UDPErrorInd;

/*****
* SIGNAL RecWDDatagram
* <<PACKAGE WDP_UDP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDP.sun(1),125(30,110),8)
******/
#define z_WDP_UDP_3_RecWDDatagram 162
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Natural  Param2;
    DeviceAddress  Param3;
    DeviceAddress  Param4;
    SDL_Natural  Param5;
    SDL_Natural  Param6;
} yPDef_z_WDP_UDP_3_RecWDDatagram;

/*****
* SIGNAL WDErrorInd
* <<PACKAGE WDP_UDP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDP.sun(1),125(30,110),11)
******/
#define z_WDP_UDP_4_WDErrorInd 163
typedef struct {
    SIGNAL_VARS
    SDL_Integer  Param1;
    SDL_Natural  Param2;
} yPDef_z_WDP_UDP_4_WDErrorInd;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
