/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#define C_MICRO_1_3
#include "ml_typ.h"
#include "ctypes.h"
#include "BuffMgt.h"
#include "GlblDecl.h"
#include "WDP_UL.h"


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* NEWTYPE TDUnitdataReqType  (BODY section)
* <<PACKAGE WDP_UpperLayer>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UpperLayer.sun(1),173(55,25),3)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_TDUnitdataReqType( TDUnitdataReqType *yVar )
#else
extern void yDef_TDUnitdataReqType( yVar )
  TDUnitdataReqType *yVar;
#endif
{
  yDef_AddressType(&((*yVar).SourceAddress));
  yDef_AddressType(&((*yVar).DestinationAddress));
  yDef_pdubuf_ptr(&((*yVar).UserData));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_TDUnitdataReqType(
  TDUnitdataReqType yExpr1,
  TDUnitdataReqType yExpr2 )
#else
extern SDL_Boolean yEq_TDUnitdataReqType( yExpr1, yExpr2 )
  TDUnitdataReqType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_AddressType(yExpr1.SourceAddress, yExpr2.SourceAddress) )
  return SDL_False;
  if ( yNEqF_AddressType(yExpr1.DestinationAddress,
  yExpr2.DestinationAddress) ) return SDL_False;
  if ( yNEqF_pdubuf_ptr(yExpr1.UserData, yExpr2.UserData) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern TDUnitdataReqType yMake_TDUnitdataReqType(
  AddressType ySourceAddress,
  AddressType yDestinationAddress,
  pdubuf_ptr yUserData )
#else
extern TDUnitdataReqType  yMake_TDUnitdataReqType( ySourceAddress,
  yDestinationAddress, yUserData )
  AddressType ySourceAddress;
  AddressType yDestinationAddress;
  pdubuf_ptr yUserData;
#endif
{
  TDUnitdataReqType  yVar;
  memset((void *)(&yVar), 0, sizeof(TDUnitdataReqType));
  yAssF_AddressType(yVar.SourceAddress, ySourceAddress, XASSMAKE);
  yAssF_AddressType(yVar.DestinationAddress, yDestinationAddress, XASSMAKE);
  yAssF_pdubuf_ptr(yVar.UserData, yUserData, XASSMAKE);
  return yVar;
}

/*****
* NEWTYPE TDUnitDataIndType  (BODY section)
* <<PACKAGE WDP_UpperLayer>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UpperLayer.sun(1),164(20,60),3)
******/

/*------------------DEFAULT-----------------*/
#ifndef XNOPROTO
extern void yDef_TDUnitdataIndType( TDUnitdataIndType *yVar )
#else
extern void yDef_TDUnitdataIndType( yVar )
  TDUnitdataIndType *yVar;
#endif
{
  yDef_AddressType(&((*yVar).SourceAddress));
  yDef_AddressType(&((*yVar).DestinationAddress));
  yDef_pdubuf_ptr(&((*yVar).UserData));
}

/*------------------EQUAL-------------------*/
#ifndef XNOPROTO
extern SDL_Boolean yEq_TDUnitdataIndType(
  TDUnitdataIndType yExpr1,
  TDUnitdataIndType yExpr2 )
#else
extern SDL_Boolean yEq_TDUnitdataIndType( yExpr1, yExpr2 )
  TDUnitdataIndType yExpr1, yExpr2;
#endif
{
  if ( yNEqF_AddressType(yExpr1.SourceAddress, yExpr2.SourceAddress) )
  return SDL_False;
  if ( yNEqF_AddressType(yExpr1.DestinationAddress,
  yExpr2.DestinationAddress) ) return SDL_False;
  if ( yNEqF_pdubuf_ptr(yExpr1.UserData, yExpr2.UserData) ) return SDL_False;
  return SDL_True;
}

/*-------------------MAKE-------------------*/
#ifndef XNOPROTO
extern TDUnitdataIndType yMake_TDUnitdataIndType(
  AddressType ySourceAddress,
  AddressType yDestinationAddress,
  pdubuf_ptr yUserData )
#else
extern TDUnitdataIndType  yMake_TDUnitdataIndType( ySourceAddress,
  yDestinationAddress, yUserData )
  AddressType ySourceAddress;
  AddressType yDestinationAddress;
  pdubuf_ptr yUserData;
#endif
{
  TDUnitdataIndType  yVar;
  memset((void *)(&yVar), 0, sizeof(TDUnitdataIndType));
  yAssF_AddressType(yVar.SourceAddress, ySourceAddress, XASSMAKE);
  yAssF_AddressType(yVar.DestinationAddress, yDestinationAddress, XASSMAKE);
  yAssF_pdubuf_ptr(yVar.UserData, yUserData, XASSMAKE);
  return yVar;
}
