/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_WDP_SMS_H
#define XX_WDP_SMS_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SIGNAL SMSout
* <<PACKAGE WDP_SMS>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_SMS.sun(1),119(35,55),5)
******/
#define z_WDP_SMS_0_SMSout 150
typedef struct {
    SIGNAL_VARS
    SDL_Octet_String  Param1;
    AuxiliaryAddress  Param2;
    DeviceAddress  Param3;
} yPDef_z_WDP_SMS_0_SMSout;

/*****
* SIGNAL RecSMSDatagram
* <<PACKAGE WDP_SMS>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_SMS.sun(1),122(55,90),3)
******/
#define z_WDP_SMS_1_RecSMSDatagram 151
typedef struct {
    SIGNAL_VARS
    z_ctypes_4_VoidStar  Param1;
    SDL_Natural  Param2;
    DeviceAddress  Param3;
} yPDef_z_WDP_SMS_1_RecSMSDatagram;

/*****
* SIGNAL SMSsentInd
* <<PACKAGE WDP_SMS>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_SMS.sun(1),122(55,90),5)
******/
#define z_WDP_SMS_2_SMSsentInd 152

/*****
* SIGNAL SMSErrorInd
* <<PACKAGE WDP_SMS>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_SMS.sun(1),122(55,90),6)
******/
#define z_WDP_SMS_3_SMSErrorInd 153
typedef struct {
    SIGNAL_VARS
    SDL_Natural  Param1;
} yPDef_z_WDP_SMS_3_SMSErrorInd;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
