/*
 * Copyright (C) Ericsson Mobile Communications AB, 2000.
 * Licensed to AU-System AB.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and AU-System AB, and may be used and copied
 * only in accordance with the terms of the said agreement.
 *
 * Neither Ericsson Mobile Communications AB nor AU-System AB
 * assumes any responsibility or liability for any errors or inaccuracies in
 * this software, or any consequential, incidental or indirect damage arising
 * out of the use of the Generic WAP Client software.
 */

/* Program generated by SDT Cmicro, version 1.33 */

#ifndef XSCT_CMICRO
#define XSCT_CMICRO
#endif

#ifndef XX_WDP_UDCP_H
#define XX_WDP_UDCP_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SIGNAL UDCPDataReq
* <<PACKAGE WDP_UDCP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDCP.sun(1),173(30,70),5)
******/
#define z_WDP_UDCP_0_UDCPDataReq 154
typedef struct {
    SIGNAL_VARS
    SDL_Octet_String  Param1;
    DeviceAddress  Param2;
    SDL_Octet  Param3;
    AuxiliaryAddress  Param4;
    SDL_Boolean  Param5;
} yPDef_z_WDP_UDCP_0_UDCPDataReq;

/*****
* SIGNAL UDCPReleaseReq
* <<PACKAGE WDP_UDCP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDCP.sun(1),173(30,70),12)
******/
#define z_WDP_UDCP_1_UDCPReleaseReq 155
typedef struct {
    SIGNAL_VARS
    SDL_Octet  Param1;
} yPDef_z_WDP_UDCP_1_UDCPReleaseReq;

/*****
* SIGNAL UDCPDataInd
* <<PACKAGE WDP_UDCP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDCP.sun(1),179(25,135),5)
******/
#define z_WDP_UDCP_2_UDCPDataInd 156
typedef struct {
    SIGNAL_VARS
    SDL_Octet_String  Param1;
    DeviceAddress  Param2;
    SDL_Octet  Param3;
} yPDef_z_WDP_UDCP_2_UDCPDataInd;

/*****
* SIGNAL UDCPErrorind
* <<PACKAGE WDP_UDCP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDCP.sun(1),179(25,135),14)
******/
#define z_WDP_UDCP_3_UDCPErrorind 157
typedef struct {
    SIGNAL_VARS
    SDL_Octet  Param1;
} yPDef_z_WDP_UDCP_3_UDCPErrorind;

/*****
* SIGNAL UDCPReleaseInd
* <<PACKAGE WDP_UDCP>>
* #SDTREF(SDL,D:\WIP\Maintenance\WAP_1.1\System\base_co\sdl\packages\WDP_UDCP.sun(1),179(25,135),17)
******/
#define z_WDP_UDCP_4_UDCPReleaseInd 158
typedef struct {
    SIGNAL_VARS
    SDL_Octet  Param1;
} yPDef_z_WDP_UDCP_4_UDCPReleaseInd;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
